### ISSUE TITLE
Disabling all fields using form.disable() ->After loading data

### ISSUE THREAD

**Issue by thorgod** [formly-js/ngx-formly#1000]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
Form loads fine, I am to use a button to disable all fields; however, I would like to be able to disable all fields right after the NGX-FORMLY loads

**Expected behavior**
I would like to be able to disable all fields right after the NGX-FORMLY loads

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-jfdvxj?file=src/app/app.component.ts

**What I need**
What I think I need is to use lifecycle hooks to bind to the event when NGX-Formly is done loading so I can call disable.

**Comment by aitboudad** [comment]
until adding an event for that you can use`expressionProperties`:
```ts
      expressionProperties: {
        'templateOptions.disabled': () => true,
      },
```

I think it should be triggered throughout `options.fieldChanges`

**Comment by thorgod** [comment]
Thank you, I will give it a try.

Does the Angular form have any life cycle events I can use to trigger after NGX-Formly is done loading (FYI I looked and tried a few things didn't work, just asking)

**Comment by aitboudad** [comment]
just tried `lifecycle.onInit` and it seems working as expected:
see https://stackblitz.com/edit/angular-jfdvxj-it6diu,

```ts
      lifecycle: {
        onInit: () => {
          this.form.disable();
        }
      },
```

**Comment by NitsanBaleli** [comment]
@aitboudad is therer any way to achieve what you show in your example, without grouping all the controls under a `fieldGroup` ?

from what I understand here, if you call `form.disable()` at the right time (onInit - after all controls initiated), all the form controls will be disabled without any more code needed, is that correct ?

**Comment by aitboudad** [comment]
@NitsanBaleli correct, I see two methods to disable the form:

1. using `expressionProperties`: https://ngx-formly.github.io/ngx-formly/examples/form-options/form-state
2. build the form using `FormlyFormBuilder` service:

```ts
  constructor(builder: FormlyFormBuilder) {
    builder.buildForm(this.form, this.fields, this.model, this.options);
    this.form.disable();
  }
```

**Comment by NitsanBaleli** [comment]
@aitboudad thank you for your answer,
although it's not very clear to me about the first part,
is there a way to achieve the onInit hook without grouping all the controls under a `fieldGroup`?

**Comment by aitboudad** [comment]
@NitsanBaleli the first part allows controlling the disability of the form through form state.

> is there a way to achieve the onInit hook without grouping all the controls under a fieldGroup?

the question is generic so the answer is `yes`, use `FormlyFormBuilder` (part 2 above).
Usually, I would prefer to describe the use-case, why grouping all the controls under a `fieldGroup` is not suitable for you?

**Comment by NitsanBaleli** [comment]
@aitboudad I get it now. Thank you I appreciate your time.

**Comment by GovardhanGitHub** [comment]
how to disable whole form fields

**Comment by aitboudad** [comment]
> how to disable whole form fields

form.disable()
