### ISSUE TITLE
JSON powered Stackblitz sample broken

### ISSUE THREAD

**Issue by htrex** [formly-js/ngx-formly#1005]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

The Stackblitz sample https://stackblitz.com/angular/yoeeoymnyxy linked in the "JSON powered" section of the documentation is broken.

**Expected behavior**

It should show a form, but it only shows a submit button.

**Minimal reproduction of the problem with instructions**

Open https://formly-js.github.io/ngx-formly/examples/other/json-powered and click the "Edit in StackBlitz"
button on the top right

I've created a fork and fixed the issue on a personal StackBlitz here https://angular-8arnjw.stackblitz.io

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

N/A

* **Angular version:** 2.0.X

All

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all
* **Node (for AoT issues):** `node --version` =

**Comment by jdpnielsen** [comment]
I'm not sure how the stackblitz samples are built, but you could make a pull request for: https://github.com/formly-js/ngx-formly/blob/master/demo/src/app/examples/other/json-powered/user.service.ts

**Comment by htrex** [comment]
have you seen my working fork? https://stackblitz.com/edit/angular-8arnjw?file=src%2Fapp%2Fuser.service.ts 
it loads a json file from the assets folder and StackBlitz seems to serve it without problems:
https://angular-8arnjw.stackblitz.io/assets/json-powered/user-form.json
https://angular-8arnjw.stackblitz.io/assets/json-powered/user.json

An issue with the original version linked on the documentation is that the json files are in the src/app folder while angular.json declares 
```
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
```

**Comment by johnpapa** [comment]
I'm trying to do something similar: use http with angular to access a local json file. I'm getting back `index.html` when the request is made to my json file. How do I get around this?

It works locally.

**Comment by aitboudad** [comment]
@johnpapa normally requesting a file in assets should work, the following example https://stackblitz.com/angular/jnndkxxmjvy work as expected
