### ISSUE TITLE
Bind observable to select for JSON loaded form from server

### ISSUE THREAD

**Issue by darlontrofy** [formly-js/ngx-formly#1010]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

I am not able to bind an observable to a select when loading a form via json, because JSON expects a string instead of the current way of passing a function as a property as seen in the example. When I wrap the service call in a string, it throws exceptions and blows up the application. Also, I would also like  to dynamically update the options in the select. 

**Expected behavior**

Be able to bind an observable to a select when using JSON powered form from server and update options in select as needed.
**Minimal reproduction of the problem with instructions**

Bootstrap
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Angular 5
* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript
* **Node (for AoT issues):** `node --version` =

**Comment by james-poulose** [comment]
Looks like this is already implemented.
https://github.com/formly-js/ngx-formly/issues/693

**Comment by aitboudad** [comment]
see https://formly-js.github.io/ngx-formly/examples/other/observable-select
