### ISSUE TITLE
Updating the Json in the Json powered forms with an Api request to add more Input fields in the UI without reloading the Angular component

### ISSUE THREAD

**Issue by thetinshusasi** [formly-js/ngx-formly#1011]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
I would  like to incrementally update the Json ( Retrieved using API request)  in the Json powered Forms, so that it should reflect the new UI based on the update  without the need to reload the UI.
Update to the Json ( also retrieved using API call) should be easily appended to the FormlyFieldsConfig[]. 

However when trying to add a new input object to the FormlyFieldsConfig [ ]. it is throwing an error 
"Cannot find control with unspecified name attribute"

**Expected behavior**
New input object should be reflected in the UI.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows
* **Angular version:** 2.0.X
Yes
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Yes
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescripe

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
hi, can you provide a reproduction example.
Thanks!

**Comment by thetinshusasi** [comment]
Thanks for quick response.
It is fixed
UI will be only updated when "fields" is reassigned with  immutable object. If we mutate the "fields" variable  UI won't be updated

**Comment by darlontrofy** [comment]
@thetinshusasi Can you please tell me how you were able to add more input fields to form created via JSON. I need to do the same exact thing, but when I update the FormlyFieldsConfig [], not all the input fields are added and the validation does not kick in too. Thanks.

**Comment by aitboudad** [comment]
override fields input to let angular detect change:
```ts
this.fields = [
  ...this.fields,
 ...jsonFields
];
```

**Comment by darlontrofy** [comment]
@aitboudad thanks so much. And to remove the fields again, I assume I can use the spread operator to remove by key or something.

**Comment by aitboudad** [comment]
@darlontrofy yes, use filter:
```ts
this.fields = [
  ...this.fields.filter(f => f.key !=== 'name')
];
```

**Comment by darlontrofy** [comment]
@aitboudad  Thanks so much!

**Comment by aitboudad** [comment]
can you show me an example of what you've done using stackblitz.

**Comment by darlontrofy** [comment]
@aitboudad It's adding it in the stackblitz below. 

https://stackblitz.com/edit/angular-msj3ka 

but in my full application, it doesn't and the code is almost identical. thanks

**Comment by aitboudad** [comment]
> but in my full application, it doesn't and the code is almost identical. thanks

you mean the provided example work as expected but on your app not?

**Comment by darlontrofy** [comment]
yes, the provided example works as expected, but not in my app. .

**Comment by aitboudad** [comment]
then can you try updating to v5 beta version

**Comment by darlontrofy** [comment]
Ok, I will try that and see if it resolves the issue. do you have any idea what the issue could be? thanks.

**Comment by aitboudad** [comment]
nop, without a reproduction I can't guess!

**Comment by darlontrofy** [comment]
Ok, thank you! Much appreciated as always.
