### ISSUE TITLE
Unable to use with Material

### ISSUE THREAD

**Issue by ShahanaFarooqui** [formly-js/ngx-formly#1012]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

FormlyFiledInput is not available to import from the same location for Material. I am getting below compile time error after upgrading Formly  to 4.5.0.
error TS2305: Module './@ngx-formly/material/ngx-formly-material' has no exported member 'FormlyFieldInput'.

**Expected behavior**
I should be able to build my app successfully.

**Minimal reproduction of the problem with instructions**
STEPS TO REPRODUCE: import 'FormlyFieldInput' to any demo application.
import { FormlyFieldInput } from '@ngx-formly/material';

**What is the motivation / use case for changing the behavior?**
Upgrading to 4.5.0

**Please tell us about your environment:**
Windows 7, Visual Studio Code, npm, Node, webpack.

* **Angular version:** 2.0.X
Angular ^5.2.10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
NA (Compile time error)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Type Script

* **Node (for AoT issues):** `node --version` =
Node Version 8.11.2. No AOT compilation.

**Comment by aitboudad** [comment]
instead of relying on `FormlyFieldInput` I suggest extending `FieldType` instead, see https://github.com/formly-js/ngx-formly/blob/master/src/material/input/src/input.type.ts
