### ISSUE TITLE
Custom template throws error on form rendring

### ISSUE THREAD

**Issue by ravikumarmistry** [formly-js/ngx-formly#1019]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
I have created a demo on [https://stackblitz.com/edit/angular-riwlny-3hkdm3](stackblitz).
I have created the grid-form component and registered the template in the root module. Grid-form template internally uses the formly-form component. But on rendring it throws error on console. 
error message is
 Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at FormGroup._forEachChild (model.js:2411)
    at FormGroup._setUpControls (model.js:2427)
    at new FormGroup (model.js:1940)
    at FormlyFormBuilder.addFormControl (formly.form.builder.ts:252)
    at eval (formly.form.builder.ts:59)
    at Array.forEach (<anonymous>)
    at eval (formly.form.builder.ts:54)
    at Array.forEach (<anonymous>)
    at FormlyFormBuilder.registerFormControls (formly.form.builder.ts:44) 

**Expected behavior**
It should not throw the error in console

**Minimal reproduction of the problem with instructions**
Example is on [https://stackblitz.com/edit/angular-riwlny-3hkdm3](stackblitz). Second tab is using my custom template 'grid-form'

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
fixed in `4.6.0`
