### ISSUE TITLE
Dynamically update (add/remove) options in select dropdown after loading

### ISSUE THREAD

**Issue by darlontrofy** [formly-js/ngx-formly#1022]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ X] support request
```

**Current behavior**

I am currently using the library ngx-formly to create Angular forms dynamically from JSON. Select dropdowns can already be created by binding to an observable, which gets the options (Order types in my case) from a service and create the options. This is working fine.

The issue is that in my case, I have added a popup to allow user create and save new order types BUT I don't know how to force an Angular form control (dropdown) to recreate itself, or reload the options from the service, or if possible, just append a new option to the existing dropdown. I am able to get the information for the new item added from the DB, but I don't know if (or how) it's possible to add it manually, or force the dropdown on the form to reload. I have searched online and couldn't find anything. Any help is much appreciated.

**Expected behavior**

Be able to trigger update on the select control
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I would like to update the dropdown with more options or trigger a reload.
**Please tell us about your environment:**

* **Angular version:** 2.0.X

Angular 5
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

ALL
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
just check the passed observable instance is not completed, see the following example which use `Subject` to emit the new options value:
https://stackblitz.com/edit/angular-dqcsy5

**Comment by darlontrofy** [comment]
Thank you so much. This worked so well.
