### ISSUE TITLE
Using the native select in the mobile context 

### ISSUE THREAD

**Issue by Bretto** [formly-js/ngx-formly#1024]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**

The mat-select doesn't work properly in the mobile context is there a way to use the native select experience in the mobile context ?

**Expected behavior**

Being able to set the native select in mobile context

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

The default select in the mobile context in a superior UX

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
in that you case can create you own select type (named `native-select`) see https://formly-js.github.io/ngx-formly/guide/custom-formly-field (check the bootstrap select type which use the native one https://github.com/formly-js/ngx-formly/blob/master/src/bootstrap/src/lib/types/select.ts and how to create custom type for material ui https://github.com/formly-js/ngx-formly/tree/master/src/material/select/src)
then in your formly config you may check which type to use:```ts
{
  type: 'city',
  type: isMobile ? 'select':'native-select'
  ...
}
```
