### ISSUE TITLE
dynamic steps in a multi-step form

### ISSUE THREAD

**Issue by Bretto** [formly-js/ngx-formly#1026]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**

In a multi-step form I would like to customize step 2 based on the selection of step 1 is this possible with ngx-formly ? How would you go about it ?

**Expected behavior**

Enable a way to pick ngx-formly configuration fragment based on prior selection.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
that's depend :), for me I mainly rely on `hideExpression` (https://formly-js.github.io/ngx-formly/examples/field-options/hide-fields) and `expressionProperties` (https://formly-js.github.io/ngx-formly/examples/field-options/expression-properties

**Comment by eng-dibo** [comment]
how to totally build step2 only when the user clicks the next button?

for clarification:
when the page initially rendered, the step1 form is displayed to the user.
when he click `next` to go to step2 at the first time, an http request is performed to update `model` and create the step2 based on the retrieved data.

**Comment by aitboudad** [comment]
> how to totally build step2 only when the user clicks the next button?

Just attach the extra config to the parent field once loaded, then call build form.

```ts
next(step) {
  if (not_loaded) {
    // attach the loaded config to the current field
    this.field.fieldGroup[step] = [{ key: 'name', type: 'input' }];

    // build (V6)
    // this.options.build();

    // build (V5)
    // (<any> this.options)._buildForm(true);
  }
  
  ....
}
```

You may also check our Multi-Step Form example: https://formly.dev/examples/advanced/multi-step-form
