### ISSUE TITLE
Issue with 100% width on Material form-field wrapper

### ISSUE THREAD

**Issue by bancroftway** [formly-js/ngx-formly#1027]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
All Material form fields are currently being rendered with style="width:100%" 

**Expected behavior**

Material fields should behave the same way as for Bootstrap template i.e. width should not be hard-coded to 100%.

Also, if a fix is not possible, could you suggest a workaround to override the 100% width style.

**Minimal reproduction of the problem with instructions**
The problem can be seen at https://formly-js.github.io/ngx-formly/ui/material. The mat-form-field has a width of 100%

**What is the motivation / use case for changing the behavior?**
100% width is on all form fields is ugly, especially when using repeating sections...it tends to produce really long forms. Sometimes when using repeatring sections, we would like to put the entire form group on a single line.

**Please tell us about your environment:**
Windows, Angular 6

* **Angular version:** 2.0.X
6.0.3. yes the issue is present in latest angular

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =
8.11.3

**Comment by aitboudad** [comment]
we will consider removing the width in the next major version since it'll introduce a breaking change.
for now just include the following code in your global style:

```css
.mat-form-field {
  width: initial !important;
}
