### ISSUE TITLE
Getting ERROR TypeError: Object(...) is not a function 

### ISSUE THREAD

**Issue by SudeshAK** [formly-js/ngx-formly#1028]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```
Angular CLI: 1.7.4
Node: 8.9.3
OS: win32 x64
Angular: 5.2.11

I have updated this
 @angular/forms@5.2.11
 @ngx-formly/core@3.1.0

Now when I try to execute https://stackblitz.com/angular/drepnyvxqex  example in my local machine then I am getting 
error FormlyFieldSelect.html:22 ERROR TypeError: Object(...) is not a function

![error](https://user-images.githubusercontent.com/36342286/42507016-557b4fb0-8461-11e8-9364-5daa78e77e43.png)

Its only coming for dropdowns every other controls work fine

**Comment by aitboudad** [comment]
the latest version (v4) of `ngx-formly` require `Angular >= 6` or at least you have to use `rxjs-compat` in order to work properly

**Comment by SudeshAK** [comment]
Yes I have installed @ngx-formly/core@3.x as I have angular 5

**Comment by aitboudad** [comment]
Ahh I see now the version `4.3.0` require the version 6 of `rxjs`:
update your rxjs to:
```
    "rxjs": "^6.2.1",
    "rxjs-compat": "^6.2.1",
```
to make it work https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md

**Comment by SudeshAK** [comment]
Yes after I updated rxjs.. Its working now .. thank you
