### ISSUE TITLE
how-to use ngx-formly with ngx-translate

### ISSUE THREAD

**Issue by fschell** [formly-js/ngx-formly#1030]
[x ] support request

just a question:

Is there a way to use ngx-translate with formly? Any samples available?

Formly seems to be awesome but we can not find any working example for translation or the usage of pipes

something like 
````    
       ....
	{
		key: 'readyTime',
		type: 'select',		
		templateOptions: {
			description:  '"from" | translate' ,
			required: true,
			options: fromTime
		},
		...
	},
        ...

````
did not work (translate not defined)

Thanks for a hint!

**Comment by aitboudad** [comment]
You can use one of the following methods:

1. `expressionProperties` https://stackblitz.com/edit/ngx-formly-translate-1
2. override the default wrappers for example label wrapper https://stackblitz.com/edit/ngx-formly-translate-2

for the first methods it may introduce some performance issues for a large form which I'm thinking to solve it by allowing observable in `expressionProperties`, in the future you can use something like:

```ts      
expressionProperties: {
  'templateOptions.label': this.translate.stream('HOME.SELECT'),
},
```

**Comment by aitboudad** [comment]
another method is to wait until translate is ready and use simply `this.translate.instant`:
https://stackblitz.com/edit/ngx-formly-translate-3

**Comment by fschell** [comment]
Thank you for the examples, which were very helpful. It works perfect! 
You saved my day!

**Comment by HangLoop** [comment]
@aitboudad What is the most recommend way to handle the select options of a custom select type? I am currently using a custom pipe in the template to handle.

**Comment by aitboudad** [comment]
@HangLoop that's depend but the most recommended way for me is to pass options as an observable which will give you more control.

**Comment by aitboudad** [comment]
an example of ngx-translate is now available through the demo website https://formly-js.github.io/ngx-formly/examples/advanced/i18n

**Comment by aitboudad** [comment]
@HangLoop seems to me a good option too, keep in mind that there are several ways to achieve the same goal :)

**Comment by AhmedBHameed** [comment]
@aitboudad Changing in label is perfectly detected. But it seems placeholder has no observable to detect changes. Is there  a way to make it as observable !

**Comment by aitboudad** [comment]
@AhmedBHameed `observable` is only available in `V5`  else use other [proposals](https://github.com/ngx-formly/ngx-formly/issues/1030#issuecomment-404487016)

```ts
expressionProperties: {
  'templateOptions.placeholder': this.translate.stream('HOME.SELECT'),
},
```

**Comment by AhmedBHameed** [comment]
@aitboudad Yes this is what i already done. Still label is updating but placeholder dose not detect changes.
formly `v3`.

**Comment by aitboudad** [comment]
just checked and it seems working for me, check `CONTACT.PLACEHOLDER` message is defined else 
fill an issue with a reproduction example.

**Comment by AhmedBHameed** [comment]
@aitboudad Tested with `v4` also. Placeholder changes not detected.
I will rise an issue hoping to be solved for the version `3` since we are use it in our company.

**Comment by aitboudad** [comment]
I see now the issue which is solved in `V5`,
`V3` is not maintained anymore you may create a custom input which overrides the default [input](https://github.com/ngx-formly/ngx-formly/blob/master/src/bootstrap/src/lib/types/input.ts)  and bind placeholder attr.

**Comment by AhmedBHameed** [comment]
@aitboudad Any docs to follow ?

**Comment by aitboudad** [comment]
@AhmedBHameed https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field,
if you want a quick solution (as a workaround), rerender fields when changing the placeholder which can be done using:

```ts
  changePlaceholder() {
   ...
    this.fields = [...this.fields];
  }
```

**Comment by johannesjo** [comment]
I think a nice and more performant option would be to provide alternative templates, which always use the translate pipe for things like labels. Like this for example:
```html
    <mat-checkbox
      [formControl]="formControl"
      [id]="id"
      [formlyAttributes]="field"
      [tabindex]="to.tabindex || 0"
      [indeterminate]="to.indeterminate && formControl.value === null"
      [color]="to.color"
      [labelPosition]="to.align || to.labelPosition">
      {{ isTranslatePipe ? (to.label|translate) : to.label }}
      <span *ngIf="to.required && to.hideRequiredMarker !== true" class="mat-form-field-required-marker">*</span>
    </mat-checkbox>
```

**Comment by aitboudad** [comment]
@johannesjo that requires adding `ngx-translate` as a dependency :(, I see another approach that would make the integration much easy (using a custom extension), I'll provide an example when time allows!

**Comment by aitboudad** [comment]
@johannesjo see https://stackblitz.com/edit/angular-k8dzcs

**Comment by johannesjo** [comment]
@aitboudad that's really awesome! Thank you very much! Works like a charm! Love it!

**Comment by sudharsan203** [comment]
> You can use one of the following methods:
> 
> 1. `expressionProperties` https://stackblitz.com/edit/ngx-formly-translate-1
> 2. override the default wrappers for example label wrapper https://stackblitz.com/edit/ngx-formly-translate-2
> 
> for the first method it may introduce some performance issues for a large form which I'm thinking to solve it by allowing observable in `expressionProperties`, in the future you can use something like:
> 
> ```ts
> expressionProperties: {
>   'templateOptions.label': this.translate.stream('HOME.SELECT'),
> },
> ```

I tried to implement the above process, But not work for me,Please give me some suggestions here.
FormlyModule.forRoot({
      types: [{
        name: 'autocomplete',
        component: AutocompleteTypeComponent,
        wrappers: ['form-field'],
      }, 
    ],
    wrappers: [
                { name: 'label', component: FormlyWrapperLabel }
              ],
    },),]

In component.ts
{
                            "key": "dwclanguage",
                            "type": "radio",
                            "defaultValue": "en",
                            "className": "col-lg-12 col-md-12 col-sm-12 col-xs-12 text_center",
                            "templateOptions": {
                                "translate": true,
                                'label':'dwclabels.Charts',
                                change: (field) => this.changeLang(field.formControl.value), 
                              "options": [
                                {
                                  "value": "en",
                                  "label": "English"
                                },
                                {
                                  "value": "es",
                                  "label": "ESPANOL"
                                }
                              ]
                            },

**Comment by Bukic** [comment]
@aitboudad  I am using this translate.extension.ts approach (it is same like your from stackblitz with plus code for placeholder) and works perfect. But i have one issue. When using bootstrap accordion formly fields that are inside collapsed accordion are not translated, for example change language from dropdown and expand accordion labels/placeholders are not translated. But if all accordions are expanded and change language everything works perfect.

  ``` 
{
            type: 'ac-accordion-field',
            templateOptions: {},
            fieldGroupClassName: 'row',
            fieldGroup: [
                {
                    key: 'accPeople',
                    templateOptions: { translate: true, label: 'caseFile.accordionPeople' },
                    fieldGroupClassName: 'row',
                    fieldGroup: [
                        {
                            className: 'col-sm-6 form-group',
                            key: 'personAssoc',
                            type: 'input',
                            templateOptions: {
                                translate: true,
                                label: 'caseFile.personType',
                                placeholder: 'caseFile.placeholderPersonType',
                            },
                        },
                    ],
                },
            ],
}
```

accordion-field html

```
<ngb-accordion>
    <ng-container #fieldComponent> </ng-container>
    <ng-container *ngFor="let tab of field.fieldGroup; let index = index; let last = last">
        <ngb-panel title="{{ tab.templateOptions.label }}" id="ngb-panel-{{ index }}">
            <ng-template ngbPanelContent> <formly-field [field]="tab"></formly-field> </ng-template>
        </ngb-panel>
    </ng-container>
</ngb-accordion>
```

**Comment by aitboudad** [comment]
@Bukic please fill a new issue with a reproduction stackblitz example.
Thanks!

**Comment by Bukic** [comment]
@aitboudad  here is link to the new issue i created:

https://github.com/ngx-formly/ngx-formly/issues/2214
