### ISSUE TITLE
Enrich formly's HTML with id property from FormlyFieldConfiguration

### ISSUE THREAD

**Issue by Etchelon** [formly-js/ngx-formly#1032]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```

**Current behavior**
Some field types (input) have id property exposed in their HTML, some others don't.

**Expected behavior**
I expect to be able to use jQuery to select the actual element of a form field.
For example, given this FormlyFieldConfig:
`const config = { id: "myDatePicker", type: "datepicker", .... }`
I expect to be able to write
`$("#myDatePicker").doSomething()`
I have been able to achieve this in a couple of control types that I've written, by adding
`@HostBinding("attr.id") get id() { return this.field.id; }`

Can you add something like this line to the FieldType base class? Since id is a property of FormlyFieldConfig, I think it should be ok and not have any impact. Maybe change the name of the attribute with something more specific...

**What is the motivation / use case for changing the behavior?**
I need to be able to execute an action (for example, notify the user with a toast notification) when a formly field is shown/hidden. Currently there are no events exposed by the library, and I cannot know when the hideExpression property changes, so I've come up with the idea to attach a MutationObserver to a field's parent formly-field and listen for changes to its style property, something like this:
`const el = $("#" + field_.id).closest("formly-field")[0];
									if (_.isNil(el)) {
										return;
									}
									const isVisibleSubject = new Subject<boolean>();
									const observer = new MutationObserver(mutationsList => {
										_.each(mutationsList, mutation => {
											if (mutation.attributeName === "style") {
												const isVisible = $(el).is(":visible");
												isVisibleSubject.next(isVisible);
											}
										});
									});`

Please note: I'm not using formly as is but I've written a whole framework that wraps it, and my expressionProperties are all functions that are generated from a JSON configuration file.

* **Angular version:** 2.0.X
Version@latest (6.0.7 today), formly @latest (4.6.3 today).

**Comment by aitboudad** [comment]
> Can you add something like this line to the FieldType base class? Since id is a property of FormlyFieldConfig, I think it should be ok and not have any impact. Maybe change the name of the attribute with something more specific...

just ensure that the field type has `[formlyAttributes]` directive which is responsible to set the `id` attr,

>  Currently there are no events exposed by the library, and I cannot know when the hideExpression property changes

use `options.fieldChanges`:
```ts
this.options.fieldChanges.subscribe(({field, type, value}) => {
  if (type === 'hidden') {
      // value === true -> show
      // value === false -> hide
  }
});
```

**Comment by Etchelon** [comment]
Oh wow... amazing.
Now, searching the repo's source code I found that only the "hidden" type is supported for now, correct?

**Comment by aitboudad** [comment]
> Now, searching the repo's source code I found that only the "hidden" type is supported for now, correct?

yep
