### ISSUE TITLE
Custom Template/Mat-Autocomplete - Display value from model object on page load

### ISSUE THREAD

**Issue by lagay** [formly-js/ngx-formly#1036]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x ] support request
```

**Current behavior**
I have a custom template with an matInput field connected by a mat-autocomplete that allows a user to search for users and groups. The data in the model is an object with four fields. I want to keep all four fields in the model (id, userGroupId, userGroupName, type), not just the display value (userGroupName).

The user must type at least 3 characters for the search to begin. In my code example, the data is hard coded but in real life, that search is going against a database. Once the user finds the record they want and selects it, the onSelectedChange function will set the userGroupName into the input field.

That all works great. The problem is when the page is loaded and data is coming from the model, the input field has `[object Object]` displayed instead of model.userGroupName. I have not been able to figure out how to hook into a method or lifecycle method and get the userGroupName from the model data to display in the input field upon the page loading.

**Expected behavior**
I would like to display model.userGroupName in the input field when the page loads. The input field currently displays `[object Object]`.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-mt3vvm-5wlcqf

* When the page loads, the input field displays `[object Object]` which comes from the model data which is being set in ngOnInit in app.component.ts.
* Place your cursor in the input field and clear the `[object Object]`.
* Start typing `Travel` and select the `Travel Department`, you will see the name displayed in the input field and what the model data looks like that will be saved.

**What is the motivation / use case for changing the behavior?**
I want to keep all the fields as an object in the model; but only need to display one field from that model.

**Please tell us about your environment:**
MacOS 10.13.6 and Windows 10
NPM 5.6.0

* **Angular version:** 2.0.X
Angular 5.2.9

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
ALL

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Probably ALL but I am using TypeScript 2.8.3

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
`displayWith` would solve your issue, check the solution https://stackblitz.com/edit/angular-mt3vvm-kyqbxf

so next time take a look at the autocomplete [documentation](https://material.angular.io/components/autocomplete/api) first :)

**Comment by lagay** [comment]
@aitboudad Thank you so much! Yes, I should have read the autocomplete documentation in more detail and really appreciate your help on this. 🥇
