### ISSUE TITLE
Select not working on Angular 5

### ISSUE THREAD

**Issue by adityaba** [formly-js/ngx-formly#1037]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

Select Type is not working on angular 5

**Expected behavior**
Select option should appear

**stackblitz example**
https://ngx-formly-ui-bootstrap-pbx3xd.stackblitz.io

**environment:**
Windows 10

* **Angular version:** 5.2.X

Issue is not reproducible on angular 6

* **Browser:** [Chrome]

**Comment by aitboudad** [comment]
Readme need to be updated, for angular 5 either use `@ngx-formly/core@2.x` version or update rxjs to v6 https://github.com/formly-js/ngx-formly/issues/1028#issuecomment-403915978

**Comment by aitboudad** [comment]
sorry, I didn't checked your example the `name` field should be replaced by `label`.
```ts
        {
          "label": "Iron Man",
          "value": "iron_man"
        },
```

**Comment by adityaba** [comment]
@aitboudad Thanks for your quick response.
