### ISSUE TITLE
[Material] textarea autosize

### ISSUE THREAD

**Issue by smile2014** [formly-js/ngx-formly#1039]
Hello, textarea set minRows, maxRows does not take effect

**Comment by aitboudad** [comment]
why not just using `rows` property instead ?
```ts
    {
      key: 'comment',
      type: 'textarea',
      templateOptions: {
        rows: 5,
      },
    },
```

**Comment by aitboudad** [comment]
you may use a custom type for that since `autosize` is not available by default and require an additional deps

**Comment by smile2014** [comment]
I am using the custom textarea now, but in the dynamic table but there is no way to use
  @HostListener('input')
   textAreaOnChange(): void {
     If (this.autosize) {
       this.resizeTextArea();
     }
   }

**Comment by smile2014** [comment]
https://stackblitz.com/edit/textarea-formly

**Comment by smile2014** [comment]
Online demo no problem, crash

**Comment by aitboudad** [comment]
added support of `autosize` in `v5.3`, it can be configured through the following options:
```ts
{
  ...
  type: 'textarea',
  templateOptions: {
    autosize: true,
    autosizeMinRows: 5,
    autosizeMaxRows: 10,
  },
},
```
