### ISSUE TITLE
Implementing custom template as group of fields

### ISSUE THREAD

**Issue by SpindlerS** [formly-js/ngx-formly#1045]
**Hey formlies, I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**My goal**
I need to implement multiple forms with repetive groups of controls (like contact or address information). So my goal is to implement custom templates that encapsulate these controls.

**Current approach**
Implementing a custom FieldType that contains a definition of fields (as you can see in the example app) and building the form based on these fields. In general that seems to work, except the model binding.

**Problem**
The model is not bound to the form or not updated correctly.
In 'simple' fields (like the custom date) models are updated correctly, I guess because it's bound to the formControl of the FieldType. Why isn't it updating in the case?

**Minimal reproduction of the problem with instructions**
Example app using address field.

https://stackblitz.com/edit/ngx-formly-demo

* **Angular version:** 6.0.X

* **Browser:** [all]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

In general I'm not sure whether this is the best approach to implement groups of fields. What's your opinion about this?

Any help is greatly appreciated.
Thanks,
Sören

**Comment by aitboudad** [comment]
*Note*: 
nested key with `fieldGroup` doesn't work properly so changed into the following code until fixed:
```ts
        {
          key: 'doctor',
          fieldGroup: [
            {
              key: 'address',
              type: 'address',
              fieldGroupClassName: 'row',
            },
          ]
        }
```

**Comment by SpindlerS** [comment]
Thank you very much, that's pretty nice.

Keep up the good work on formly :)

**Comment by eduardoleopoldino** [comment]
Sorry for commenting here, but this is the only example i've found about grouping fields as a type.
I'd like to know how I can make this group of fields required? I tried this:

             {
              key: 'address',
              type: 'address',
              lifecycle: {
                onInit: (form, field) => {
                  console.log(field);
                  field.fieldGroup.forEach(x => {
                    x.fieldGroup.forEach(f => {
                        f.templateOptions.required = true;
                    });
                  });
                },
              },

Somehow the '*' indicator is set, but the form.valid is true and there's no invalid class on the fields.

If its necessary, I can try to create a new example to reproduce the error.
Thanks for your help!

**Comment by instantgis** [comment]
> _Note_:
> nested key with `fieldGroup` doesn't work properly so changed into the following code until fixed:
> 
> ```ts
>         {
>           key: 'doctor',
>           fieldGroup: [
>             {
>               key: 'address',
>               type: 'address',
>               fieldGroupClassName: 'row',
>             },
>           ]
>         }
> ```

I tried this approach to create a "custom" control for a date range that has a select for
equals
greater or equal
greater
less
less than equal
...
not null
null
between
followed by two date pickers

This is amazing. It works like a charm and I did not even have to roll a component for it!
In my model the data comes out as...

<key> : {
  operator: number,
  start: Date,
  end: Date
}

I used hideExpression to hide the end datepicker when operator is not 'between'

Awesome
