### ISSUE TITLE
Options values not reseted when options are removed

### ISSUE THREAD

**Issue by Jiiieeef** [formly-js/ngx-formly#1050]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Hello,
I have two multiple selects, Team and Player. Player options depend of Team selection. 
I choose Team from Bayern Munich and Real Madrid and the followings players: Bayern Munich (Player 1), Real Madrid (Player 1). 
I deselect Bayern Munich and reselect it right away => Bayern Munich (Player 1) is still selected :(

Because my english is not perfect, see the attached gif :D

**Expected behavior**
Selected options which aren't in a select anymore should be removed from the array of selected id.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/ngx-formly-ui-material-ahve3g

![2018-07-19 18 27 33](https://user-images.githubusercontent.com/6318981/42957008-ae1f2c82-8b81-11e8-98b1-c19d023c2027.gif)

**Comment by aitboudad** [comment]
because you have commented the `setValue` in line `98`
```ts
// field.formControl.setValue('');
```

the following example show how it should be solved https://stackblitz.com/edit/ngx-formly-ui-material-oh3yc8
