### ISSUE TITLE
Setting a fields defaultValue in lifecycle onInit

### ISSUE THREAD

**Issue by SpindlerS** [formly-js/ngx-formly#1053]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

Hi, I'm not sure whether this is a bug or I'm doing something wrong. 
In general I want to pass options to a field in a custom field-group template. Like this:

```typescript
{
  'key': 'address',
  'type': 'address',
  'templateOptions': {
    'countryOptions': [
      { 'value': 'de', 'label': 'Germany' },
      { 'value': 'at', 'label': 'Austria' },
      { 'value': 'ch', 'label': 'Switzerland' },
    ],
    'defaultCountry': 'de',
    'disabledCountry': false,
  }
},
```

I found a solution by setting the options of a select field in `onInit` lifecycle of the custom template.

```typescript
{ 
  name: 'address',
  extends: 'formly-group',
  defaultOptions: {
    lifecycle: {
      onInit: (form, field) => {
        const countryField = field.fieldGroup[3].fieldGroup[2]; // TODO: grab by key
        
        if (field.templateOptions.countryOptions) {
          countryField.templateOptions.options = field.templateOptions.countryOptions;
        }

        if (field.templateOptions.defaultCountry) {
          // Why is this not working?
          countryField.defaultValue = field.templateOptions.defaultCountry;
          // This works in some way:
          // field.formControl.get('country').setValue(field.templateOptions.defaultCountry);
        }

        console.log(countryField);
      },
    },
    fieldGroup: [...]
  }
}
```

**Current behavior**

Setting the defaultValue of a select field in onInit lifecycle of a parent formly-group does not update the initial value. 

`countryField.defaultValue = field.templateOptions.defaultCountry;`

Options of the select field are updated correctly:

`countryField.templateOptions.options = field.templateOptions.countryOptions;`

**Expected behavior**

Setting the defaultValue in onInit updates the initial value of the select field correctly.

**Minimal reproduction of the problem with instructions**

Demo app: https://stackblitz.com/edit/ngx-formly-demo?file=src%2Fapp%2Fforms%2Fgroups%2Faddress.group.ts

**What is the motivation / use case for changing the behavior?**

Maybe there is another way to pass options to a child field of a custom template?

**Please tell us about your environment:**

* **Angular version:** 6.0.X

* **Browser:** [Chrome XX | Firefox XX]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by aitboudad** [comment]
defaultValue is assigned before that event, in your case use `formcontrol.setValue(..)` instead:
```ts
countryField.formControl.setValue(field.templateOptions.defaultCountry);
```

in the future we'll introduce `fieldTransform` property to allow you a such things.
