### ISSUE TITLE
Repeater with Asyncronous data loaded

### ISSUE THREAD

**Issue by Viddhiyartha** [formly-js/ngx-formly#1055]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report 
[ ] feature request
[ X] support request
```

**Current behavior**
Couldn't get the repeater working with asynchronous data. Couldn't decide on the number of items to repeat when data is returned asynchronously.

**Expected behavior**
With Async data load , the number of repeater section should be able to determine.

**Minimal reproduction of the problem with instructions**
We load the data from server using async data load inside success callback of a form init function.

**OnInit of function within which data loads** 
$scope.vm.options.formState.injector.get('Service').getPhoneNumbers({
            'email': email
        }).subscribe(phoenumber => {
            $scope.form.controls[0].patchValue({
                    'phone': phoneNumber
            });
        });
**phone** is a key for one of the formly fields 
**repeater HTML:**
Repeat component is a custom component.

_

- <div fxLayout="column" fxLayoutGap="20px" class="{{field.className}}">
-   <div *ngFor="let field of field.fieldGroup; let i = index;">
-      <formly-group [model]="model[i]" [field]="field" [options]="options" [form]="formControl">
-             <div fxFlexAlign="start">
-             <button type="button" class="icon-button"
-                 [disabled]="to.disable"
-                 (click)="remove(i)">
-                 <div class="icon-container">
-               </div>
-             </button>
-           </div>
-      </formly-group>
-    </div> 
-  </div>

_

**Repeater TS File:**

OnInit() { 
for (
        let index = 0;
        index < noOfFields
        index++
      ) {
        super.add();
      }
}

When we try to read the **this.model property** , it is having **length of 0**. So couldn't decide on **noOfFields** property above.

**What is the motivation / use case for changing the behavior?**
The repeater when used with static data and adding the UI fields before the data is available is working.
It is a part of requirement.

**Please tell us about your environment:**
OS - WIndows 10 , IDE - VS Code , Service - returns the data,

* **Angular version:** 5.2.0 ,  "@ngx-formly/core": "^3.1.0"

* **Browser:**  all 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by aitboudad** [comment]
your example isn't clear so I provide you a working example with async load https://stackblitz.com/edit/angular-rxlpp4
