### ISSUE TITLE
Materil Autocomplete StackBlitz demo does not work

### ISSUE THREAD

**Issue by m98** [formly-js/ngx-formly#1062]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search GitHub for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```
Material Autocomplete example on StackBlitz does not work.

Here is the link to Material Autocomplete: https://formly-js.github.io/ngx-formly/ui/material
StackBlitz demo:https://oaojqeryanb.angular.stackblitz.io

**Comment by aitboudad** [comment]
I think there is an issue on  new version of material anyway here a working example https://stackblitz.com/edit/angular-bf6g6m

**Comment by m98** [comment]
I also have a question about this; the documentation is not clear about custom inputs, and how to get data from `input` in Material Autocomplete. For example, where does the data we enter on input stores? And how to get it back?

**Comment by aitboudad** [comment]
we rely on angular reactive form to set/get data on input, so `formControl` input is required for custom field type.

for example to get data we enter you may rely on `modelChange` output or the passed `model` itself or subscribing on the `form` instance
