### ISSUE TITLE
Required a solution to Implement tag input field 

### ISSUE THREAD

**Issue by anupsarkar377** [formly-js/ngx-formly#1063]
**Problem Statement**
I am  designing the form using Angular Material.I am trying to implement the tag input field in the form, how I do that and what will be the type of the field in the fields array?

**Current behavior**
Now I have only the input type field in the fields array

**Expected Behavior**
I want tag input field in the following format

![screen shot 2018-07-25 at 11 47 48 am](https://user-images.githubusercontent.com/37542666/43184335-e2fc555a-9005-11e8-9005-ce8c3b025f93.png)

Following all are my dependencies

"dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/cdk": "^6.1.0",
    "@angular/common": "^6.0.2",
    "@angular/compiler": "^6.0.2",
    "@angular/core": "^6.0.2",
    "@angular/forms": "^6.0.7",
    "@angular/http": "^6.0.2",
    "@angular/material": "^6.1.0",
    "@angular/platform-browser": "^6.0.2",
    "@angular/platform-browser-dynamic": "^6.0.2",
    "@angular/router": "^6.0.2",
    "@ngx-formly/core": "^4.6.3",
    "@ngx-formly/material": "^4.6.3",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "rxjs": "^6.2.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.3",
    "@angular/cli": "^6.0.8",
    "@angular/compiler-cli": "^6.0.2",
    "@angular/language-service": "^6.0.2",
    "@ngx-formly/schematics": "0.0.1",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }

**Comment by juristr** [comment]
Hey, you can use `ng-select` for that which supports tagging and a series of other things as well: https://ng-select.github.io/ng-select#/tags

Here's an example of how to integrate ng-select with ngx-formly:
https://github.com/formly-js/ngx-formly/issues/708#issuecomment-364903803

**Comment by anupsarkar377** [comment]
**Problem Statement**
Hey thanks for the help .Now the input view is coming  but the data is not coming into the browser console.
**Current Behavior**
I am designing a form that has several fields within that one of the field is tag input field.Now the view is like this
![screen shot 2018-07-26 at 3 39 01 pm](https://user-images.githubusercontent.com/37542666/43256536-9cae6d5a-90ea-11e8-99b9-f5884e81889a.png)


**Expected Behavior**
Now the view and functionality is working fine but after submitting the from data is not coming into the browser console.

I tried with this code to get the custom type field and tag functionality
![screen shot 2018-07-26 at 3 45 23 pm](https://user-images.githubusercontent.com/37542666/43256637-f967131c-90ea-11e8-954f-fa0ef7a2fc15.png)

this is the code for the "app.module.ts" to create custom type.I mention this code into the @NgModule imports array.
![screen shot 2018-07-26 at 3 47 53 pm](https://user-images.githubusercontent.com/37542666/43256726-4dbe13ca-90eb-11e8-9c66-418189051e04.png)

I am using the custom type input field into the another component and I mentioned  the following code  in the component fields array declearation
 {
      key: 'tags',
      type: 'tags',
      templateOptions: {
        label: 'Enter Tags'
            }
    }
but still data is not coming into the browser console.Please help me out thanks in advance.

**Comment by aitboudad** [comment]
@anupsarkar377 if you've followed my example you may notice that `formControl` attr in missing in your field type:
```html
    <ng-select
      ...
      [formControl]="formControl">
    </ng-select>
```
