### ISSUE TITLE
Regarding the tag input field implement in the fields array

### ISSUE THREAD

**Issue by anupsarkar377** [formly-js/ngx-formly#1064]
**Problem Statement**
I tried  [https://stackblitz.com/edit/angular-ntysej?file=app%2Fapp.component.ts] this example  but it only supports  dropdown tag feature. But the view is not coming properly,I am only able to do the custom type field.

**Current behavior**
I tried following code to get the custom type
![screen shot 2018-07-25 at 6 04 38 pm](https://user-images.githubusercontent.com/37542666/43201149-51876760-9035-11e8-8d62-49f3520b6aa9.png)

I tried with this and I am able to get the custom field type.But I only get this view
![screen shot 2018-07-25 at 6 00 26 pm](https://user-images.githubusercontent.com/37542666/43200924-b0baeb36-9034-11e8-816b-62e62bcb8646.png)

label also not coming and I am not getting the proper view
**Expected Behavior**
I want tag input field in the following format
![screen shot 2018-07-25 at 11 57 06 am](https://user-images.githubusercontent.com/37542666/43200952-cd13f2be-9034-11e8-8649-9449732c8544.png)
I want as one line input not as an dropdown tags.When I press the enter it will automatically create the new tag.

I am using the following dependencies

"dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/cli": "^6.0.1",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "amazon-cognito-identity-js": "^2.0.3",
    "aws-sdk": "^2.211.1",
    "bootstrap": "^4.0.0",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "popper.js": "^1.14.3",
    "rxjs": "^6.1.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^6.0.0",
    "@angular/language-service": "^6.0.0",
    "@types/google.analytics": "0.0.39",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^6.0.102",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2",
    "@angular-devkit/build-angular": "~0.6.1"
  }

**Comment by aitboudad** [comment]
you have to import the `ng-select` style:
```
// styles.scss
@import "~@ng-select/ng-select/themes/default.theme.css";
```
