### ISSUE TITLE
Elements for Ionic 4

### ISSUE THREAD

**Issue by Devqon** [formly-js/ngx-formly#1073]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**

**Expected behavior**
With the relase of Ionic 4 the elements should be updated too.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
The release of Ionic 4 cannot use the existing elements

**Please tell us about your environment:**

* **Angular version:** 6.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

I would like to use your great library in my Ionic4 project. However, some elements have adjusted a bit. I tried to implement the changes myself ([here](https://github.com/Devqon/ngx-formly/tree/feature/ionic4) but I cannot get the Demo to work. What am I missing for the package to work?

After the working changes I would like to create a pull request to support your library with Ionic4.

**Comment by aitboudad** [comment]
@Devqon just open a PR and I'll take a look :)

**Comment by Devqon** [comment]
@aitboudad #1074
