### ISSUE TITLE
ngx-datatable stackblitz old lib version / enhancements / bugs

### ISSUE THREAD

**Issue by FritzHerbers** [formly-js/ngx-formly#1076]
```
[x] bug report
[x] enhancement
[x] support request
```

Thanks for your ngx-datatable implementation.

Opening ngx-datatable on Stackblitz shows on every row headers.
I think ngx-datatable support is only valid with ngx-formy/core 5.0.0 library.
On Stackblitz 4.6.6 is loaded. Changing it the 5.0.0-alpha library solved it.

I am mainly reporting this as I had a similar issue some months ago, which costs me a lot of time to identify a misbehaviour for the repeating section example and older libs.

Enhancement:
I adapted ngx-datatable example with an add and remove button, similar to repeating section example. Might be worth adding it to the example.
[https://stackblitz.com/edit/angular-wwqs8k?file=src%2Fapp%2Fdatatable.type.ts](https://stackblitz.com/edit/angular-wwqs8k?file=src%2Fapp%2Fdatatable.type.ts)
(FontAwesome buttons not showing correct and example needs some better layout)

Enhancement:
Repeating section and ngx-datatable formly type are derived from FieldArrayType. Similar to add/remove row method, is it possible to add a reset forms (model) method which can be called within the formly type component? 
Calling FormlyForms.resetModel() would reset the whole model and is not what I am looking for.

Bug:
Header should show an asterix on required fields.

Bug:
When adding a row in my above example new headers are created. Why? Bug?

**Comment by aitboudad** [comment]
> Enhancement:
Repeating section and ngx-datatable formly type are derived from FieldArrayType. Similar to add/remove row method, is it possible to add a reset forms (model) method which can be called within the formly type component?
Calling FormlyForms.resetModel() would reset the whole model and is not what I am looking for.

done by https://github.com/formly-js/ngx-formly/pull/1077

> Bug:
When adding a row in my above example new headers are created. Why? Bug?

see https://github.com/formly-js/ngx-formly/pull/1079

> Bug:
Header should show an asterix on required fields.

you may add it manually in the column name

**Comment by FritzHerbers** [comment]
I looked at the reset code and as I interpret it, it deletes the model content.

With reset I meant reset to the original model data, setting the values to their initial state.
Is this possible?

**Comment by aitboudad** [comment]
ahh I see, I'll take a look on it later!

**Comment by FritzHerbers** [comment]
You added the following which makes sense to me as the default formly input field configs change from fieldset/label to fieldset:
```
   this.field.fieldArray.fieldGroup.forEach(element => {
      element.wrappers = ['fieldset']
    });
```

But in my example why the first 3 rows didn't have labels and the added rows have labels?
The first 3 rows have a
`formly-field` > `formly-wrapper-description` > `formly-wrapper-validation-messages` > `formly-field-input` 
and newly added rows have
`formly-field` > `formly-wrapper-fieldset` > `formly-wrapper-label` > `formly-wrapper-description` > `formly-wrapper-validation-messages`> `formly-field-input`

In your example the existing rows and the added rows are also different constructed.
Therefor the `'rowHeight: 'auto'` does not work and has to be fixed (this would be the least issue).

Why are newly added rows different constructed ?

**Comment by enricooliva** [comment]
@FritzHerbers  I modified the provided example only to resolved the label problem. 
I see the layout problem in the https://stackblitz.com environment.

> Therefor the 'rowHeight: 'auto'
the rowHeight is a property of ngx-datatable https://swimlane.github.io/ngx-datatable/

This the result in my local environment.

```
"dependencies": {
    "@angular/animations": "^6.0.7",
    "@angular/common": "^6.0.7",
    "@angular/compiler": "^6.0.7",
    "@angular/core": "^6.0.7",
    "@angular/forms": "^6.0.9",
    "@angular/http": "^6.0.7",
    "@angular/platform-browser": "^6.0.7",
    "@angular/platform-browser-dynamic": "^6.0.7",
    "@angular/router": "^6.0.7",
    "@auth0/angular-jwt": "^2.0.0",
    "@ng-bootstrap/ng-bootstrap": "^2.2.0",
    "@ngx-formly/bootstrap": "^4.6.6",
    "@ngx-formly/core": "^4.6.6",
    "@swimlane/ngx-datatable": "^13.0.1",
    "bootstrap-italia": "^0.9.5",
    "core-js": "^2.5.4",
    "ngx-permissions": "^5.0.0",
    "rxjs": "^6.2.1",
    "zone.js": "^0.8.26"
  },
```

![table](https://user-images.githubusercontent.com/11843561/43456336-6d090fd8-94c3-11e8-918f-b78ad4025966.PNG)

**Comment by aitboudad** [comment]
reset feature reverted, for now adding a such feature would complicate the core part, I'll reconsider adding a such feature after moving away `field-array` feature from the core package.
