### ISSUE TITLE
Can bind events on addon

### ISSUE THREAD

**Issue by smile2014** [formly-js/ngx-formly#1090]
For example, I want to add a addon to the right of input, which binds a click event to query the data

**Comment by mateuslopes** [comment]
Did you solved the problem? And how did you do it? I didn´t found the solution, and the documentation does not mention it here: https://formly-js.github.io/ngx-formly/examples/bootstrap-specific/input-add-ons

**Comment by aitboudad** [comment]
use `onClick` callback https://github.com/formly-js/ngx-formly/blob/master/src/bootstrap/src/lib/wrappers/addons.ts#L41

**Comment by mateuslopes** [comment]
Thanks for your fast answer. I tried addonRight with onClick but it was not working. Now I see that I am trying to do it using material2 formly templates, and addons with onClick works just for bootstrap. Do you know if there is something similar for material2 templates?
Or is it better to do a custom field?

**Comment by aitboudad** [comment]
for material you can use `suffix` or `prefix` see the following example https://stackblitz.com/edit/angular-txutgw?file=src%2Fapp%2Fsuffix.wrapper.ts

**Comment by bhaidar** [comment]
Hi @aitboudad 
How can I apply mat-suffix and mat-prefix for any field in formly? More like having this feature as configurable instead of having to create a new FieldType per field?

**Comment by aitboudad** [comment]
in the above example we didn't create a new FieldType per field but instead, we declared a wrapper which allows us to use mat-suffix and mat-prefix for any field in formly.

**Comment by sakenerana** [comment]
How to generate wrapper using command??

**Comment by aitboudad** [comment]
@sakenerana not available yet, the source code of prefix/suffix can be extracted from https://formly.dev/examples/other/material-prefix-suffix

**Comment by immanuelrosal** [comment]
> for material you can use `suffix` or `prefix` see the following example

@aitboudad Is there a way for me to combine rendering an array and providing the "remove" functionality from it to the prefix/suffix? Idk if this is something easy but I come from a react background so I'm having a hard time understanding how. Hope you can help me! Love the library btw! :)

**Comment by aitboudad** [comment]
@immanuelrosal array type has a separate component where you can add the remove button https://formly.dev/examples/advanced/repeating-section.
