### ISSUE TITLE
Ionic Stacked Label

### ISSUE THREAD

**Issue by DrakeWitt** [formly-js/ngx-formly#1092]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**

Currently the only option for Ionic Labels (according to the documentation anyway) is the fixed label type by default, with the label on the left and the input on the right on the same line. 

**Expected behavior**

Ionic provides a "stacked" label component that puts the label above the input component. To make an input stacked you just add "stacked" inside the ion-label component. 

https://ionicframework.com/docs/api/components/input/Input/

Is there a way to do this by specifying template options?

**Comment by aitboudad** [comment]
we're working on the new ionic version (V4) which appear that the `stacked` input  has been changed into `position` that accept 'inline' | 'fixed' | 'stacked' | 'floating' value.

@DrakeWitt  are you interested to work on this feature ?

**Comment by DrakeWitt** [comment]
Ah, if Ionic 4 is changing the API I can wait until then.

**Comment by aitboudad** [comment]
the v4 is already supported (version `5.0.0-beta.0` of ngx-formly) and we can add this feature that's why I've asked you if you're willing to contribute on it, it shouldn't be difficult, just adding the following code on all [ionic label fields](https://github.com/formly-js/ngx-formly/tree/master/src/ionic/src/lib/types) would do the job:
```ts
<ion-label [position]="to.labelPosition">{{ to.label }}</ion-label>
```

**Comment by damsorian** [comment]
This is documented? how can I set the floating label for example? thanks.

**Comment by vicebtx** [comment]
> This is documented? how can I set the floating label for example? thanks.

+1

**Comment by aitboudad** [comment]
> This is documented? how can I set the floating label for example? thanks.

by passing `labelPosition` which accept the following value: `'inline' | 'fixed' | 'stacked' | 'floating'`
here is a working example: see https://stackblitz.com/edit/angular-tvcdsx

**Note**: we'll focus on a proper doc after `V6` (so not anytime soon), we've provided a bunch of examples that shows all major features that formly offers and for `UI` such as ionic I encourage you to check the source code for more advanced usage.

**Comment by mj6uc** [comment]
Does this work with version 3.1.0?  How to get it working? We have an app that still uses angular 5, so version 3.1 is the suggested version for formly.

**Comment by vicebtx** [comment]
Use *labelPosition* in the *templateOptions* of the desired field.

**Comment by mj6uc** [comment]
I tried

*labelPosition: 'stacked'*

like this:
{
fieldGroupClassName: 'display-flex',
fieldGroup: [
{
className: 'flex-2',
type: 'input',
key: 'street',
templateOptions: {
label: 'Street',
labelPosition:'stacked'
},
},

*It does not seem to have any impact when using angular 5 / ngx-formly
3.1.0 with Ionic.*

*Any thing that I am missing?*

**Comment by aitboudad** [comment]
@mj6uc this option not available in `v3`, instead create a custom wrapper which overrides the default [wrapper](https://github.com/ngx-formly/ngx-formly/blob/v3.1.0/src/ui-ionic/src/wrappers/form-field.ts) and adds the desired option.

1- custom wrapper

```ts
import { Component, ViewChild, ViewContainerRef } from '@angular/core';
import { FieldWrapper } from '@ngx-formly/core';

@Component({ ... })
export class IonicWrapperFormField extends FieldWrapper {
  @ViewChild('fieldComponent', { read: ViewContainerRef }) fieldComponent: ViewContainerRef;
}
```
2- declare the new wrapper through the NgModule declaration:

```ts
@NgModule({
  imports: [
    FormlyModule.forRoot({
      wrappers: [
        { name: 'form-field', component: IonicWrapperFormField },
      ],
    }),
  ],
})
export class FormlyIonicModule {
}
```
