### ISSUE TITLE
dropdown arrow in select field is not styled with CSS

### ISSUE THREAD

**Issue by MareoRaft** [formly-js/ngx-formly#1100]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

When creating a "select" field (dropdown) with Bootstrap css, the dropdown arrow on the far right of the field is not pretty and is different depending on the browser:

![screen shot 2018-08-07 at 6 10 05 pm](https://user-images.githubusercontent.com/860303/43805280-2f62ddda-9a6d-11e8-924f-548c62f4beeb.png)

**Expected behavior**

As seen on stackblitz, a double arrow should appear that is pretty:

![screen shot 2018-08-07 at 6 11 09 pm](https://user-images.githubusercontent.com/860303/43805312-4c065656-9a6d-11e8-9ff7-73892dd1467e.png)

**Minimal reproduction of the problem with instructions**

This is difficult because as far as I can tell, my project is set up the same way as stackblitz.  You can find my attempt at:
https://github.com/MareoRaft/dog-registration/tree/b923033d2c82a1f270159c857a289cba1214ec2b

You can see that all bootstrap things seem to work correctly with the exception of the dropdown styling.

I have spent a lot of time trying to solve this to no avail.  I believe the issue may be that I am not importing the bootstrap.js file.  Does this feature require JavaScript to work correctly?  I am using `import { FormlyBootstrapModule } from '@ngx-formly/bootstrap';` and `FormlyBootstrapModule` and `bootstrap: [ AppComponent ]` in my app.module.ts file to include bootstrap, nothing more.

I am happy to give more information about the issue, just let me know!  Thank you!!!

**Please tell us about your environment:**

macOS High Sierra, brew, Angular 6, ngx-formly

* **Angular version:** 6.1.1

* **Browser:** all

* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` = v10.6.0

**Comment by aitboudad** [comment]
fixed in `5.0.0-beta.1`, you have to pass `customSelect` prop as true:
```ts
key: 'Select',
type: 'select',
templateOptions: {
  customSelect: true,
}
```
