### ISSUE TITLE
[FEATURE / Support] Pre select an option for the select type

### ISSUE THREAD

**Issue by b-barry** [formly-js/ngx-formly#1101]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[x ] support request
```

**Current behavior**

For the select type in material, I would like to be able to pre-select an option in the list of option ( observable) based on some criteria such as if the length of the options arrays is equal to one, pre-select this element

**Expected behavior**

Be able to pre-select an option easily

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-cyko4o

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-cyko4o-eh5mjs
