### ISSUE TITLE
Bind observable to select for JSON loaded form from server 

### ISSUE THREAD

**Issue by albertthinc** [formly-js/ngx-formly#1102]
I am building an application with dynamic forms using ngxformly.
Shcema to be fetched from the DB. But how do I call a observable in the JSON.

For eg:
"Expression profiles" : { "templates prions.options" : "model.getSports()" }

Is it possible or is there any other way to do it.

Thanks in advance for your support.

**Comment by aitboudad** [comment]
you have to do it manually by processing the passed fields here is an example https://stackblitz.com/edit/angular-g1h2be

**Comment by technbuzz** [comment]
What if I just use `eval` to pass the down the string to be evaluated as (using stackblitz example)
```
"templateOptions": {
  "label": "Color Preference (try this out)",
  "options": [],
  "populate": "this.userService.getColors()"
}
```

```
if (f.key === 'color') {
  f.templateOptions.options = eval(f.templateOptions.populate)
  // f.templateOptions.options = this.userService.getColors();
}
```
It works, though, but is it safe?
