### ISSUE TITLE
Add button inside input (textfield) at the end

### ISSUE THREAD

**Issue by darlontrofy** [formly-js/ngx-formly#1108]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

**Current behavior**

I would like to add a button inside the input field that can be clicked by user to trigger an action, but button must be inside right of the text field.
**Expected behavior**

Add button inside text field.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

Angular 4
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
see https://formly-js.github.io/ngx-formly/examples/bootstrap-specific/input-add-ons
