### ISSUE TITLE
Feature: callback for field/model initialisation

### ISSUE THREAD

**Issue by FritzHerbers** [formly-js/ngx-formly#1109]
```
[x] feature request
```
It would be nice to have an initialisation callback before fields are populated. 
For example:

- In the Repeating Type, when model data exists, the FieldGroups are already populated, before the FieldArrayType implementation's ngOnit runs. Having a callback would simplify the code.
[https://stackblitz.com/edit/angular-abr1eg?file=src/app/datatable.type.ts
](https://stackblitz.com/edit/angular-abr1eg?file=src/app/datatable.type.ts
)

- In the Repeating Type to populate buttons.
- In the Repeating Type to populate a first row in the model when no model data exists.

Some of this can be done before it is handed over to formly, but I think it also makes sense to have the option to have it as near to the library as possible.

**Comment by aitboudad** [comment]
> In the Repeating Type, when model data exists, the FieldGroups are already populated, before the FieldArrayType implementation's ngOnit runs. Having a callback would simplify the code.

what would be the diff of using for example `onCreate` callback rather than `ngOnit`

> In the Repeating Type to populate buttons.

not clear, can you elaborate please.

> In the Repeating Type to populate a first row in the model when no model data exists.

you can use `defaultValue` property

**Comment by FritzHerbers** [comment]
>what would be the diff of using for example onCreate callback rather than ngOnit

I searched angular and formly for an onCreate hook, but couldn't find some information. Or is it something you would like to implement. Can you please elaborate.

>> In the Repeating Type to populate buttons.
> not clear, can you elaborate please.

Adding the remove/delete buttons as fields, instead of supplying them in html. Aligning a fieldgroup (container) and additional (outside container) buttons is somehow problematic. This is a minor issue.

>you can use defaultValue property

The defaultValue example explains to provide default values in the model is preferred. defaultValue is also OK.
[https://stackblitz.com/edit/angular-bh6dx1-grbh18?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-bh6dx1-grbh18?file=src%2Fapp%2Fapp.component.ts)
Tried it and added it at to two different places, but didn't work. 
Setting it at the 'repeat' level throws an exception in formly.

**Comment by aitboudad** [comment]
> Setting it at the 'repeat' level throws an exception in formly.

you've passed an object value instead of array for 'windowsDisks' try with:
```ts
    {
      key: 'windowsDisks',
      type: 'repeat',
      defaultValue: [undefined], // used undefined here in order to take the default value from fieldArray
    }
```

> I searched angular and formly for an onCreate hook, but couldn't find some information. Or is it something you would like to implement. Can you please elaborate.

`onCreate` not yet implemented, I'm just asking the benefit of having a such hook, now I clearly understand your request

**Comment by FritzHerbers** [comment]
[https://stackblitz.com/edit/angular-bh6dx1-79gru5?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-bh6dx1-79gru5?file=src/app/app.component.ts)
> defaultValue: [undefined], // used undefined here in order to take the default value from fieldArray

Tried your suggestion, but didn't work.

[https://stackblitz.com/edit/angular-bh6dx1-ukstmr?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-bh6dx1-ukstmr?file=src/app/app.component.ts)
Setting defaultValue at the type level works and solves the model initialisation for me. From this point I am in the need of a "callback" to update the select options to have the "simpler" code as mentioned in the inital issue description.

>onCreate not yet implemented, I'm just asking the benefit of having a such hook, now I clearly understand your request

How it is called or implemented is up to you. The code in the derived type should run before FieldType calls the template rendering. Model and field should be set. It should also to be called on every field/model change too.

**Comment by aitboudad** [comment]
Here is my proposal
* `prePopulate`: before touching the field.
* `onPopulate`:  defaultOptions, Model, formControl are set (which is suitable to update the child element).
* `postPopulate`: after populate children, if the field doesn't have children it should be the same as `onPopulate` event.

also please note that these events can be called whenever the field model change not matter the field was initialized or not.

**Comment by aitboudad** [comment]
defaultValue should be fixed by #1115

**Comment by aitboudad** [comment]
landed as an extension which will allow more extensibility, first you have to create a custom extension and register it in the main module:

```ts
export const lifecycleFormlyExtension: FormlyExtension = {
  prePopulate(field: FormlyFieldConfig) {
    if (field.lifecycle && field.lifecycle.prePopulate) {
      field.lifecycle.prePopulate(field);
    }
  },
  onPopulate(field: FormlyFieldConfig) {
    if (field.lifecycle && field.lifecycle.onPopulate) {
      field.lifecycle.onPopulate(field);
    }
  },
  postPopulate(field: FormlyFieldConfig) {
    if (field.lifecycle && field.lifecycle.postPopulate) {
      field.lifecycle.postPopulate(field);
    }
  },
};

@NgModule({
  imports: [
    ...,
    FormlyModule.forRoot({
      ...,
      extensions: [lifecycleFormlyExtension],
    }),
  ],
})
export class AppModule { }
```

**Comment by aitboudad** [comment]
**Note**: this feature is marked as experimental for now and it may change in the nearest future so play with it and provide us you feedback before it's too late :).

**Comment by aitboudad** [comment]
published in `v5.0.0-beta.2`.

**Update**: extension require a name:
```ts
@NgModule({
  imports: [
    ...,
    FormlyModule.forRoot({
      ...,
      extensions: [{ name: 'custom_name', extension: lifecycleFormlyExtension }],
    }),
  ],
})
export class AppModule { }
```

**Comment by FritzHerbers** [comment]
@aitboudad Great, your extension works as expected. It can solve to reduce complexities in the custom type's code. Thanks a lot.

To use a field config implementation is not my favored one. To use a custom type the app component (by field config) has to provide code which needs to interact with the behaviour of the custom type or even provide the full code for the custom type's intend.

To overcome this, before handing over the field config to formly an application can call a service which traverses through the field config, modifies the field config for a custom type and also provides the `populate` code.

The idea of a custom type is to have an interface (by an as simple as possible field config) and a behaviour/semantics. It interacts closely with the formly library and shields of the implementation for it's users (app component) (and even more the implementation of the formly library).

I was hoping more for a coded solution, extending a `populate` method in the derived custom type:
[TypeScript extending example](http://www.typescriptlang.org/play/#src=class%20FieldType%20%7B%0A%0A%20%20%20%20DoStuff()%20%7B%0A%20%20%20%20%20%20%20%20this.prePopulate()%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20prePopulate()%20%7B%0A%20%20%20%20%20%20%20console.log(%22prePopulate%20A%2C%20should%20not%20log%2C%20when%20extended%22)%3B%0A%20%20%20%20%7D%0A%7D%0A%0Aclass%20FieldArrayType%20extends%20FieldType%20%7B%0A%0A%20%20%20%20constructor()%7B%0A%20%20%20%20%20%20%20%20super()%3B%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%7D%0A%0Aclass%20MyFieldType%20extends%20FieldArrayType%20%7B%20%0A%0A%20%20%20%20constructor()%20%7B%0A%20%20%20%20%20%20%20%20super()%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%0A%20%20%20%20prePopulate()%20%7B%0A%20%20%20%20%20%20%20%20console.log(%22prePopulate%20C%22)%3B%0A%20%20%20%20%7D%0A%7D%0A%0Avar%20c%20%3D%20new%20MyFieldType()%3B%0Ac.DoStuff()%3B)

Are there any drawbacks or implications using such a solution?

The field config implementation can be valuable for specific situations. Would be great to have an additional "coded" solution.

For the time being I will go the above described "using a service" path.

**Comment by aitboudad** [comment]
not sure if possible since components are created after `postPopulate`, the only possible way is to use a static callback.
I'll look into it later

**Comment by aitboudad** [comment]
currently there is no easy way to have a such feature in the core, I hope the new ivy would allow more flexibility in angular.

**Comment by aitboudad** [comment]
good news, I figure-out that there is a way to create the field component instance too early so there a hope to have a such feature out of the box!

**Comment by FritzHerbers** [comment]
Just wanted to implement my "using a service" and noticed my issue is back open and to read your message, this would be great.
Looking forward for your solution (I will be on holiday till 19.09 and are delighted to test after).

**Comment by aitboudad** [comment]
done in `beta.5`.

**Comment by FritzHerbers** [comment]
@aitboudad thx, works great and reduces initialization code.
