### ISSUE TITLE
buildForm produces side effects on dynamically constructed fields

### ISSUE THREAD

**Issue by FritzHerbers** [formly-js/ngx-formly#1112]
```
[x] bug report
```

Having a FieldArrayType implementation, when pressing `remove()`, `buildForm()` rebuilds other fields, which can have side effects.

As `remove()` changes the model, which has to be addressed in other fields the behaviour is correct in my eyes.

However I have an implementation, which populates select options dynamically, these get lost, when another field's `remove()` is called and `buildForm()` repopulates this field, giving the implementation not the chance to act on the new repopulation.

[https://stackblitz.com/edit/angular-bh6dx1?file=src%2Fapp%2Frepeat-section.type.ts](https://stackblitz.com/edit/angular-bh6dx1?file=src%2Fapp%2Frepeat-section.type.ts)

The example has two repeating fields, the first repeating field has a column with a select, for which the options are populated dynamically. Press the remove button of one of the rows of the second repeating field. The first repeating field select options are empty.

Please read the comments in the source also.

Version: 5.0.0-beta.1

**Comment by aitboudad** [comment]
already fixed I think by #1110, to be checked!

**Comment by FritzHerbers** [comment]
Thanks for the quick fix. I will check as soon as your release a new version.

Or is there another way to test it (git cloning, going to samples and adapt one). I tried once, but it didn't work somehow, missing dependencies, etc. Are the libraries in samples taken relative or from npm?
Please explain how such testing can be accomplished.

**Comment by aitboudad** [comment]
tested on my side, it appear that is partially fixed but still there an issue which related to the select type

to test it locally:
```bash
git clone git@github.com:formly-js/ngx-formly.git
cd ngx-formly
npm install
npm run start
```

**Comment by aitboudad** [comment]
the remaining issue can be solved by yourself by adding `this.change()` after remove call similar to `add`:
```ts
  remove(i: number) {
     ...
    this.change();
  }
```

**Comment by FritzHerbers** [comment]
Tested your fix locally and is fine. thx.
