### ISSUE TITLE
change one value in form based on another value in form

### ISSUE THREAD

**Issue by MareoRaft** [formly-js/ngx-formly#1116]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Expected behavior**

I have some "price" fields that contain numbers, and a "total" field that I want to automatically populate the total of the other fields.

Ideally, the user changing any of the "price" fields would trigger some onChange event, which would run a custom function that adds up the prices and alters the "total" value shown in the form.

**Minimal reproduction of the problem with instructions**

I have tried many different approaches, each one not working for its own reason:
  * adding `onChange` event to "price" field and `this.model.total = val` as described [here](https://stackoverflow.com/questions/33823424/angular-formly-calculate-value-of-one-field-based-on-other-fields-input#36092284), but `this.model.total = val` does not alter form.
  * using `this.fields[8].fieldGroup[0].formControl.value = val` instead of `this.model.total = val`, but it still doesn't change the form
  * adding `parsers` list of functions, but they don't run.
  * using `'templateOptions.placeholder': (model, formState) => { return model.price }`, but this only updates the total on load and never again, despite the function running repeatedly.
  * mimicking the `lifecycle` thing used in this [example](https://formly-js.github.io/ngx-formly/examples/other/cascaded-select), but it's undocumented and emits errors for me.

**What is the motivation / use case for changing the behavior?**

I have some "price" fields that contain numbers, and a "total" field that I want to automatically populate the total of the other fields.

**Please tell us about your environment:**

MacOS High Sierra, brew, npm, formly

* **Angular version:** 6.1.1

* **Browser:** Chrome, but I think it's the same on all

* **Language:** TypeScript 2.7.2

* **Node (for AoT issues):** `node --version` = v10.6.0

**Comment by aitboudad** [comment]
can you replicate your example in stackblitz, here is a starter demo https://stackblitz.com/edit/angular-yg36va

**Comment by MareoRaft** [comment]
Yes, here's an [example](https://stackblitz.com/edit/angular-yg36va-grupbq) of what I think should work.

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-yg36va-2gmgz5

use `change` instead of `onChange` with `bind` or arrow function in order to access to the current component instance:
```patch
-- onChange: this.addTotal,
++ change: this.addTotal.bind(this),
++ change: () => this.addTotal(),
```

# method1
to change the model value you have to ovveride the hole model in order to trigger `ngOnChanges`:

```ts
    // method 1
    this.model = {
      ...this.model,
      total: 10,
    }
```
# method2
use `setValue`
```ts
    this.form.get('total').setValue(total);
```

# mehtod3
use lifecycle

**Comment by pedy711** [comment]
> see https://stackblitz.com/edit/angular-yg36va-2gmgz5
> 
> use `change` instead of `onChange` with `bind` or arrow function in order to access to the current component instance:
> 
> ```diff
> -- onChange: this.addTotal,
> ++ change: this.addTotal.bind(this),
> ++ change: () => this.addTotal(),
> ```
> 
> # method1
> to change the model value you have to ovveride the hole model in order to trigger `ngOnChanges`:
> 
> ```ts
>     // method 1
>     this.model = {
>       ...this.model,
>       total: 10,
>     }
> ```
> 
> # method2
> use `setValue`
> 
> ```ts
>     this.form.get('total').setValue(total);
> ```
> 
> # mehtod3
> use lifecycle

the example doesn't work as expected. Could you please update it?

**Comment by aitboudad** [comment]
@pedy711 see https://stackblitz.com/edit/angular-d9iptd?file=src%2Fapp%2Fapp.component.ts
