### ISSUE TITLE
Custom CSS styles in forly fields

### ISSUE THREAD

**Issue by AugustinChini** [formly-js/ngx-formly#1121]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```
Hi, first thanks for your work it's a very powerful tool :). I have a question about the fields styles.

**Current behavior**

If I use the "className" option in a field, the class attribut is correctly set in the DOM ( I see " <formly-field class="test" ng-reflect-ng-class="test" ng-refle ... " ) but no class are found in the component's CSS file. It's because there is no inheritance between a component and his father ... so how can we pass css style sheets to the formly component ? 
**Expected behavior**

I want that the formly component could reach the fathers components css class OR add in the FormlyFieldConfig a field to provide CSS class to the formly form.
**Minimal reproduction of the problem with instructions**

Create some fields, add "className" option in the description and the class are unreachable in the component (even if the father had them).
**What is the motivation / use case for changing the behavior?**

It would be great for customise fields style
**Please tell us about your environment:**

* **Angular version:** 5.2.9

* **Formly :** 3.0.0

* **Browser:** Chrome 68

* **Language:** TypeScript 2.9.2

* **Node (for AoT issues):** `node --version` = 8.11.0

**Comment by aitboudad** [comment]
> the class are unreachable in the component (even if the father had them).

if I clearly understood, you have to change the display type to `block` in order to make it working, see https://stackblitz.com/edit/angular-wj6g8s

**Comment by AugustinChini** [comment]
ok you put it in the global scss file, thanks a lot  👍
