### ISSUE TITLE
Overriding the type's component is not working.

### ISSUE THREAD

**Issue by ravikumarmistry** [formly-js/ngx-formly#1123]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

I am trying to override the default component of a type using component property in FormlyFieldConfig is not working.  

**Expected behavior**

It should render the component using new component as defined in the **FormlyFieldConfig**
**Minimal reproduction of the problem with instructions**

[Here](https://stackblitz.com/angular/pxgxkoboreej?file=src%2Fapp%2Fapp.component.ts) is the example of problem.
Following is the code that is not behaving the way it should have been.

added a type to the code
`@NgModule({
  imports: [
    BrowserModule,
    ReactiveFormsModule,
    FormlyBootstrapModule,
    FormlyModule.forRoot({
      types: [{component: PppComponent, name: "custom-component"}]
    }),
  ]`

and overridden in the fieldconfig
`fields: FormlyFieldConfig[] = [
    {
      component: BbbComponent,
      type: "custom-component",
      key: "abc"
    },`  

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
seems it wasn't supported which good :), I suggest to use a custom field (that extend 'custom-component') instead.
```ts
@NgModule({ 
  imports: [ 
    BrowserModule,
    ReactiveFormsModule,
    FormlyBootstrapModule,
    FormlyModule.forRoot({
      types: [
        { component: PppComponent, name: "custom-component" },
        { component: BbbComponent, name: "custom-bbb-component", extends: "custom-component" },
      ] 
    }), 
  ]
})
```

I'm thinking on a better way which will allow skip field declaration throughout ngModule.
