### ISSUE TITLE
custom validation and required fields

### ISSUE THREAD

**Issue by dpl10** [formly-js/ngx-formly#1126]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
When using custom validation on non-required fields (templateOptions.required=false) the form is invalid if the non-required fields are empty (i.e. the required property is ignored).

**Expected behavior**
The form should be valid if the required field(s) are valid and the non-required fields are either empty or filled with valid data.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-nh87qm [a fork of the custom validation example provided in the documentation (https://stackblitz.com/angular/oyybvjvpjgoq) with the field key properties set to unique values (as they would normally be) and the first two fields not required]

**What is the motivation / use case for changing the behavior?**
The required property of the field should be respected: although one could write a custom validation function at accepts either empty or valid data, this is annoying when it comes to reuse and more error prone (both the required property and the function name must be set in agreement).

**Please tell us about your environment:**

* **Angular version:** 2.0.X
6.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome, Firefox (others not tested)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
because the defined custom validators doesn't allow empty value which can be adjusted into the following code to ignore optional field:

```patch
-- return /(\d{1,3}\.){3}\d{1,3}/.test(control.value) ? null : { 'ip': true };
++ return !control.value || /(\d{1,3}\.){3}\d{1,3}/.test(control.value) ? null : { 'ip': true };

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-nh87qm-lff53t

**Comment by dpl10** [comment]
Yes, that is a workaround, but that doesn't actually fix the problem: **the required property is being ignored**. Thus, every validation function has to have two versions (required and optional) and expressionProperties must contain two entries to change a field from required to optional (one for required and one for the validator).

**Comment by aitboudad** [comment]
@dpl10 no it's up to you, if you want to rely on required for all your forms which is the suggested way then all custom validators should be defined as optional (it shouldn't take account of required version at all!)
I'm going to update the demo to not take account of required since it's already covered by `required` option.
