### ISSUE TITLE
Change color of input field and input tag, when tag is clicked.

### ISSUE THREAD

**Issue by darlontrofy** [formly-js/ngx-formly#1131]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

**Current behavior**

I would like to set the background color or apply a custom class of an input (textfield) when an attached input tag is clicked or alternatively change the background color of the input tag on click. Would this be possible?
**Expected behavior**

Change background color of field when attached input tag is clicked, or change color of input tag.

**Minimal reproduction of the problem with instructions**

Bootstrap
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

Angular 4
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript
* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
use `attributes` property, see the following example https://stackblitz.com/edit/angular-objr91
