### ISSUE TITLE
Angular interpolation in JSON powered forms

### ISSUE THREAD

**Issue by bmarchbank** [formly-js/ngx-formly#1135]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```
I'm looking for a way to display a model value as HTML (via JSON file):
```json
    {
      "template": "<h1>Name: {{model.name}}</h1>",
      "hideExpression": "!model.name",
    }
```

**Current behavior**
`Name: {{model.name}}`

**Expected behavior**
`Name: John`

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/ngx-formly-ui-material-s6wh1o?file=app/app.component.ts

**Comment by aitboudad** [comment]
not supported since angular doesn't allow it as it require to include angular compiler, an alternative solution is to use `expressionProperties` instead:

```ts
    {
      "hideExpression": "!model.name",
      expressionProperties: {
        'template': '"<h1>Name: " + model.name + "</h1>"'
      }
    }
```

**Comment by bmarchbank** [comment]
@aitboudad, is there a way I can use in-line styles? E.g.
```json
    {
      "expressionProperties": {
        "template": "'<h1 style=\"color: red\">Name: ' + model.name + '</h1>'",
      },
      "hideExpression": "!model.name",
    }
```

**Comment by aitboudad** [comment]
create a custom formly type and call `bypassSecurityTrustHtml` see the following example: https://stackblitz.com/edit/angular-jbrdls
