### ISSUE TITLE
Add support for angular/flex-layout with material component

### ISSUE THREAD

**Issue by mungpara** [formly-js/ngx-formly#1140]
**Current behavior**
can not add attributes to mat-form-field or wrapper like fxLayout="row"

**Expected behavior**
should support for attribute for allowing grid layout

**What is the motivation / use case for changing the behavior?**
Add dynamic attribute support or add attributed through json schema

* **Angular version:** 6.1.X

**Comment by juristr** [comment]
As far as I know, the current Angular version does not allow adding directives dynamically, which would be necessary to support this of flex-layout. That might change once the new Angular compiler Ivy gets released.
(Correct me if I'm wrong @aitboudad )

**Comment by aitboudad** [comment]
yep blocked by https://github.com/angular/angular/issues/11716 for now, I've some ideas to make it work by using custom wrapper but not implemented yet.

**Comment by aitboudad** [comment]
@mungpara you can use the following workaround https://stackblitz.com/edit/ngx-formly-flex-layout for now .

**Comment by aitboudad** [comment]
**Note**: the example has been updated which use a better way to manage the flex-layout by relying on a custom field type, here is an example https://stackblitz.com/edit/ngx-formly-flex-layout

**Comment by bluee** [comment]
@aitboudad Great example thanks. If you add fxFlex to your flex-layout.type.ts then fxFlexFill and stretch will work:
```
<formly-field fxFlex *ngFor="let f of field.fieldGroup" [field]="f">
</formly-field>
```
