### ISSUE TITLE
Using dotted keys not always working

### ISSUE THREAD

**Issue by FritzHerbers** [formly-js/ngx-formly#1143]
```
[x] bug report
[x] support request
```

The Introduction Example shows a textarea with a dotted key, but this is not working for some types.

[https://stackblitz.com/edit/angular-hpwcbv?file=src%2Fapp%2Fshow-type.component.ts](https://stackblitz.com/edit/angular-hpwcbv?file=src%2Fapp%2Fshow-type.component.ts)

It works for `input`, but not for `checkbox`.
How do I have to address my model in my custom `show` type when using dots ? Is there some helper get method to access the model?

**Comment by aitboudad** [comment]
> How do I have to address my model in my custom show type when using dots ? Is there some helper get method to access the model?

use `field.formControl.value`
