### ISSUE TITLE
Add Support for appearance for <mat-form-field> using JSON

### ISSUE THREAD

**Issue by mungpara** [formly-js/ngx-formly#1144]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**
Currently there are no option to select appearance for <mat-form-field>

**Expected behavior**
allow option to select appearance.

**Minimal reproduction of the problem with instructions**

https://material.angular.io/components/form-field/overview#form-field-appearance-variants

**What is the motivation / use case for changing the behavior?**
{
      key: 'text',
      type: 'input',
      templateOptions: {
        label: 'Text',
        placeholder: 'Placeholder',
        required: true,
        **appearance: 'legacy' | 'standard' | 'fill' | 'outline'**
      }
}

**Please tell us about your environment:**

* **Angular version:** 6.0.X

**Comment by aitboudad** [comment]
already supported check the following example https://stackblitz.com/edit/angular-dyxzi9

**Comment by mungpara** [comment]
Doesn not work for custom component while fetching JSON from server

**Comment by aitboudad** [comment]
this feature was introduced since `4.2.0`, either you use an old version or `form-field` wrapper is not used in your custom component.
providing a reproduction example is necessary here to see what's going wrong!

**Comment by intellix** [comment]
is it possible to declare stuff like this on a global level? I'd like to make the appearance and a couple of other `templateOptions` configurable on an app level. Either all of them are outlined or standard (for example)

**Comment by aitboudad** [comment]
@intellix pass the desired appearance through `MAT_FORM_FIELD_DEFAULT_OPTIONS` provider,
here is a working example https://stackblitz.com/edit/angular-xdtrcl
