### ISSUE TITLE
[SUPPORT] Dynamic custom fields

### ISSUE THREAD

**Issue by jogelin** [formly-js/ngx-formly#1147]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

Hello, since a long time I didn't play with formly but today I would like to refactor my code ;)

Today, to be able to reuse some field configurations, I am creating services to create them. Then, the form is generated by formly. 
But I have some troubles when I want to react dynamically on the "not yet generated form" in my services. I know it's not a good pratice so I started to put everything in field component.

But now, because the fields configuration is not specified from the top form, I have some troubles to modify a field on the fly.

Here a simple example to explain my issue : https://stackblitz.com/edit/dynamic-field-v4

The `select-requester-field` should be a field that can generate dynamically the fieldGroups that will contain the `select-user-field`.
The `select-user-field` is just an alias of a `select` with default internal configurations. There is two solutions, the `select-user-field` type could be overwrited by the `select` type OR the `select-user-field` could contains the `select` type and overwrite come configurations.

The goal is not to define a form from the top but be able re-use some "smart" fields that can generate dynamically sub form.

I think it's easy but I can't make it work with the formlyFormBuilder or formlyConfig.getMergedField and I would like the best way of doing.

For the moment I have the `ExpressionChangedAfterItHasBeenCheckedError` issue :)

I would be interested by a v4 solution and a v5 solution if there are different :)

**Comment by aitboudad** [comment]
for v5 check my answer https://github.com/formly-js/ngx-formly/issues/1091#issuecomment-411516592

**Comment by jogelin** [comment]
@aitboudad I adapted my example with the v5 : https://stackblitz.com/edit/dynamic-field-v5  

But `Error: Cannot find control with unspecified name attribute` :s

I don't really how the `getMergedField(field)` is working

**Comment by aitboudad** [comment]
`getMergedField` it assign the default option to the field if not set, the current solution doens't support nested form using fieldGroup which require to be built first.

for `select-requester-field` you can pass `fieldGroup` in defaultOptions or use `buildForm` see 
* using defaultOptions: https://stackblitz.com/edit/dynamic-field-v5-yrhqbi 
* using buildForm: https://stackblitz.com/edit/dynamic-field-v5-dgqn62 (not better since it use an internal function which I don't want to make public for now)

**Comment by jogelin** [comment]
Ok thank you, I'll have to use the second way then because the formGroup will not always contain my component `select-user-field`, sometimes it could be another one...so I cannot define default configurations

**Comment by aitboudad** [comment]
ok sound good, remind me later to make it public :)

**Comment by jogelin** [comment]
@aitboudad Hello, monday morning and I would like to refactor my code with your solution ;)

But I still have an issue when I put a default value... `ExpressionChangedAfterItHasBeenCheckedError`

See : https://stackblitz.com/edit/dynamic-field-v5-8fwrjl?file=src/app/select-requester-field.component.ts

**Comment by jogelin** [comment]
I am really stuck with that :( I don't know how could I update the model earlier...

**Comment by jogelin** [comment]
@aitboudad Something else, on your exmaple https://stackblitz.com/edit/dynamic-field-v5-yrhqbi?file=src%2Fapp%2Fselect-user-field.component.ts the `select-user-field` doesn't display the label and the description....but the properties are presents....

**Comment by jogelin** [comment]
- `ExpressionChangedAfterItHasBeenCheckedError` fixed by setTimeout, thx : https://stackblitz.com/edit/dynamic-field-v5-of7jt7?file=src/app/select-requester-field.component.ts 
I don't really know how to use the `lifecycleFormlyExtension` to solve this. I mean, I'll have to put my code oustide of my component...which is my concern for the next point

- The goal is to specialize the component then I have some questions because I am a bit lost with this `getMergedField`...:
  - What this `getMergedField` is used for ? Merge configurations + build de fields ?
  - Why did you add `wrapper: undefined` ?
  - I would like to specify the `expressionProperties` in my custom field and not on the parent...the goal is to re-use this field and not force all developers to duplicate the `expressionProperties`. In this way, they can just specify the type of the field and the key, then the field will manage all dynamic stuff ;).

I would like to use this new way but I feel that the old way with a `formly-form` ( https://stackblitz.com/edit/dynamic-field-v5-nvzdhy?file=src/app/select-user-field.component.ts) or with a `this.formlyBuilder.buildForm` (https://stackblitz.com/edit/dynamic-field-v5-jfnrfn?file=src/app/select-user-field.component.ts) are still easier to put in place

**Comment by aitboudad** [comment]
> I don't really know how to use the lifecycleFormlyExtension to solve this. I mean, I'll have to put my code oustide of my component...which is my concern for the next point

you can define those hooks in your component using a static function, I'll provide you an example!

> What this getMergedField is used for ? Merge configurations + build fields ?

only merge configurations

> Why did you add wrapper: undefined ?

in `getMergedField` when wrapper is undefined we set the default.

> I would like to specify the expressionProperties in my custom field and not on the parent...the goal is to re-use this field and not force all developers to duplicate the expressionProperties. In this way, they can just specify the type of the field and the key, then the field will manage all dynamic stuff ;).

it can be done using FormlyExtension

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/dynamic-field-v5-bgq6dz

for `expressionProperties` I'll look into it later.

**Comment by jogelin** [comment]
Ok thanks, I understand now how it it working.

But I am still not enthusiast with the implementation. It is a bit "cheating" with the component pattern ;). You put code in the component place but it doesn't belong to the component. It's still a global configuration that we have to create...

I agree with the last comment of @FritzHerbers in #1109, It is a really good idea to have a formly lifecycle but it should be specify in the same way as angular specify his licycle like `OnInit`, `AfterViewInit`, etc..I can understand it is not possible for the moment :s

Anyway, thank a lot for you work and your reactivity

**Comment by aitboudad** [comment]
seems possible :), just reopened  #1109. stay tuned!

**Comment by jogelin** [comment]
I am really enthusiast about the formly lifecycle.

Related to this issue, I still have some difficulties to use the expression properties even on the parent..

**Comment by aitboudad** [comment]
in order to take account of expression properties the field should be part of the main field so instead I suggest to follow the same way that you've done for `select-requester-field` rely on `fieldGroup`.

**Comment by jogelin** [comment]
Ok I'll wait your new lifecyle :(

Now, even if I use the static prePopulate, I have an issue with the observable configuration like the translate for example. It's injected as a service so not possible to use it in the static method `onPopulate`...

**Comment by aitboudad** [comment]
done in `beta.5` see https://stackblitz.com/edit/dynamic-field-v5-bgq6dz
