### ISSUE TITLE
filter()  not working for autocomplete of material while using JSON 

### ISSUE THREAD

**Issue by mungpara** [formly-js/ngx-formly#1148]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

filter() is woking while using in ts file but, if i fetch JSON data from server form is generated but method not binding

**Minimal reproduction of the problem with instructions**
Look this demo, i commented code which is not working
https://stackblitz.com/edit/angular-mcumws

* **Angular version:** 6.1.X

**Comment by aitboudad** [comment]
`filter` is not part of formly core, see https://github.com/formly-js/ngx-formly/issues/1102#issuecomment-411491538
