### ISSUE TITLE
Using ngx-chips with ngx-formly

### ISSUE THREAD

**Issue by darlontrofy** [formly-js/ngx-formly#1149]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```
**Current behavior**

I am trying to use the ngx-chips library with the ngx-formly library. I have created a custom component, but I can't figure out how to connect my list of tags present in a model with the ngx-chips-formly custom component. The template options does not have any property that is an array, and my chips are loaded externally from a model. Please see the custom component class I created below.
**Expected behavior**

Use ngx-chips with the ngx-formly library, and bind a model with the tags list to the ngx-chips model.
**Minimal reproduction of the problem with instructions**

Bootstrap
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

4
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
> Please see the custom component class I created below.

can you provide a stackblitz example that contains the component you've created.

**Comment by darlontrofy** [comment]
This is the link. As you will see, what I want to do is bind the model containing the chips data to the component for rendering the tags.

https://stackblitz.com/edit/angular-6emypy

thanks!

**Comment by aitboudad** [comment]
use `formControl` instead of `ngModel`:
```ts
[formControl]="formControl"
[formlyAttributes]="field"
```
here is a working example: https://stackblitz.com/edit/angular-6emypy-kz6eka

**Comment by darlontrofy** [comment]
Wow! That was quick. Thank you very much.

**Comment by michywiesner** [comment]
Hello, Im new using both libraries and i need a little help, please. I dont know how or where to put de [maxItems] property. I will use multiple ngx-chips's inputs that have different maxItems

**Comment by aitboudad** [comment]
@michywiesner `maxItems` can be set through `templateOptions`

1. add `maxItems` input:
```html
<tag-input
  ...
  [maxItems]="to.maxItems"
></tag-input>
```
`to`: is an alias of `field.templateOptions`

2. set `maxitems` option through the field config:
```ts
    {
      key: 'tags',
      type: 'chips',     
      templateOptions: {
        maxitems: 5,
      },
    }
```

**Comment by michywiesner** [comment]
Thank u so much @aitboudad
