### ISSUE TITLE
[Feature] Make `getFieldId` injectable

### ISSUE THREAD

**Issue by jogelin** [formly-js/ngx-formly#1150]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request
```

**Current behavior**
There are two ways to generate the `field.id`:
- let the default behavior to use the method `getFieldId` then you will have something like `formId_type_field.key_index`
- specifying the `id` inside the field configuration

**Expected behavior**
Be able to specify a global id generator that could be used across all fields generation via the options when we declare the FormlyModule

**Comment by aitboudad** [comment]
already possible with the new experimental extension feature here is a simple example https://stackblitz.com/edit/angular-kgzdw4.

to use a service we may need to export `FORMLY_CONFIG` injector (similar to https://github.com/formly-js/ngx-formly/blob/master/src/core/src/lib/core.module.ts#L13)

**Comment by jogelin** [comment]
ok nice, I missed this new extension
