### ISSUE TITLE
fix(core): Datepicker form controls in an ArrayFieldType's formArray when appending a new item causes Max Stack Size Exceeded error

### ISSUE THREAD

**Issue by kenisteward** [formly-js/ngx-formly#1158]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Broken Behavior (with an imbedded single form)
https://stackblitz.com/edit/angular-rv7jtn

Unbroken Behavior (with a simpler form setup)
https://stackblitz.com/edit/angular-rv7jtn-tmpdeo

when you use the datepicker type within an ArrayFieldType component and add it to the list of elements the ArrayFieldType calls _buildForm which attempts to clone the fieldArray based on the core extension.  

This causes an infinite loop but i haven't figured out yet why the datepicker has a circular reference with the ArrayFieldType's formArray.

Because of this, the model is updated but the formControl's value isn't due to the error.

I'm willing to contribute a fix I just haven't found the root cause yet.  I found this working on custom validations for the new jsonSchema support feature.

**Expected behavior**
Should properly add and update formControl.value

**Minimal reproduction of the problem with instructions**
go to the first stack blitz
click add item
click save
check console for errors

In the second stack blitz there are no errors if you just click add however it is directly adding a form child as opposed to creating something to have read only values and reading from the form child's data.

**What is the motivation / use case for changing the behavior?**
I think this shouldn't be causeing max call stack errors

**Please tell us about your environment:**

* **Angular version:** 6.X.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
currntly chrome / ie / firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS supported with NG 6+

**Comment by aitboudad** [comment]
I see on your example a wrong usage for `fieldArray` prop, you may pass a separate fields (ex. `singleField`), see the following example https://stackblitz.com/edit/angular-rv7jtn-s8uoee

**Comment by kenisteward** [comment]
So the issue was I was using field.fieldArray.fieldGroup to make the internal fields but had not dis associated that from the upper fields which causes a circular dependency and gives me the max stack exceeded.  This is why just cloning the object works fine?  I just want to make sure I understand it

**Comment by aitboudad** [comment]
when `fieldArray` is present we use `clone` to duplicate the `fieldArray` based on the model content which should not be used in a separate form to avoid some collision with the hidden props that we create during build form, the circular dependency  should be gone with the https://github.com/formly-js/ngx-formly/pull/1159.
