### ISSUE TITLE
hideExpression does not work on Array form

### ISSUE THREAD

**Issue by GabrielKatz** [formly-js/ngx-formly#1161]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
I have a checkbox and a repeating section on the same level a form. I want the repeating section to be shown only when the checkbox is checked. However, the repeating section is never shown.

**Expected behavior**
When the checkbox is checked, the repeating section should be displayed

**Minimal reproduction of the problem with instructions**

Minimal Reproduction with ngx-formly/bootstrap can be found [here](https://stackblitz.com/edit/angular-slkupq).

**What is the motivation / use case for changing the behavior?**
It would be nice to hide a complex section of the form until when it is needed in the UI.

There is a workaround to the issue if the form array is inside a form group [(see here)](https://stackblitz.com/edit/angular-slkupq-qsnwja).

**Please tell us about your environment:**

* **Angular version:** 6.1.6

* **Browser:** all (i guess)

* **Language:** TypeScript 1.9.3

**Comment by aitboudad** [comment]
see https://github.com/formly-js/ngx-formly/issues/704#issuecomment-364661614
