### ISSUE TITLE
Empty objects in repeating section when opening form with different data

### ISSUE THREAD

**Issue by FunkyFancy** [formly-js/ngx-formly#1162]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

Opening a form with multiple elements in an array results in empty objects in the model of the repeating section when opening a form with less elements.

**Expected behavior**

The model/array should not contain empty objects.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-rs9qn2

Big Data contains  4 elements
Small Data contains 1 elements

1. Click on "Small Data" -> everything is okay and the form is valid
2. Click "back" and then on "Big Data" -> also okay and the form is valid
3. Click "back" and then on "Small Data" -> model contains 3 empty objects and is not valid

If you then add items on the Small Data Page the Big Data Page will also be invalid with empty objects.

**What is the motivation / use case for changing the behavior?**

The form cannot be validated if the model contains empty objects and the fields for those objects are required. In my example empty objects are invisible since they are missing a aggregation type. 

**Please tell us about your environment:**

Windows 10, WebStorm 2018.1.3, npm

* **Angular version:** 6.1.2

* **Browser:** [Chrome 68.0.3440.106 | Firefox 61.0.2]

**Comment by aitboudad** [comment]
the BaseInformationFields is still shared between the tab forms (still copied as a reference), either use clone or use separate class to avoid a such expected behavior, see a working example using `clone`: see https://stackblitz.com/edit/angular-7lwskm
