### ISSUE TITLE
formarraytype component does not notice less row updated model

### ISSUE THREAD

**Issue by enricooliva** [formly-js/ngx-formly#1163]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

I use a custom component [DatatableTypeComponent](https://formly-js.github.io/ngx-formly/examples/advanced/datatable-integration)

when I load the model the first time always is ok 
when I update the model with less rows 
```
investments:[{
investmentName:"project1"
investmentDate:""
stockIdentifier:1
}]

```
some empty objects {} appear in the array.

My solution is: 
in the component I filter from the model the empty object

```
ngDoCheck() {    
    let ma = this.model as Array<any>;    
    this.model = ma.filter(x => Object.keys(x).length !== 0);         
}

```
is related to the issue #648 ? there is some better solution?

**Comment by enricooliva** [comment]
@aitboudad I made the example 

with two button to reproduce the issue:
load full data and load less data.

When I click to load less data the grid remain with two empty rows.

https://stackblitz.com/edit/angular-formly-datatable-a3d7ui

**Comment by aitboudad** [comment]
it should work with `5.0.0-beta.5` version, see https://stackblitz.com/edit/angular-formly-datatable-fwkaja

**Note**: `fieldset` wrapper is deprecated and replaced by `form-field`.
