### ISSUE TITLE
request: migration guide

### ISSUE THREAD

**Issue by joshvito** [formly-js/ngx-formly#1166]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```
How about a support document that lists the updates/steps on how to migrate from `angular-formly` to `ngx-formly`?

e.g. How does angular-formly's `interface IFieldConfigurationObject` translate to ngx-formly's `interface FormlyFieldConfig`?

* **Angular version:** 6.1.1

**Comment by aitboudad** [comment]
seems no one is interested, so I'm going to close this issue.
