### ISSUE TITLE
Problems with repeat

### ISSUE THREAD

**Issue by pouletfou** [formly-js/ngx-formly#1168]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => searched github for a similar issue or PR
[ ] feature request
[ ] support request
```

**Current behavior**
When I click the Add button, Input is not displayed and errors appear in the console.

**Expected behavior**
When I click an Add button, The input should be displayed.

**Minimal reproduction of the problem with instructions**
UI Material: [Stackblitz](https://stackblitz.com/edit/angular-8xzhcn)

**What is the motivation / use case for changing the behavior?**
I have a model with these properties:
```ts
{
 restricted: boolean,
 access_restriction: {
      emails: string[],
      email_domains: string[]
    }
}
```
I want the form to display the access_restrictions only when `restricted` is **true** and be able to add new restrictions (either `emails` or `email_domains`).

**Please tell us about your environment:**
OS: macos 10.13.6
IDE: Visual Studio Code

Package.json dependencies:
```json
"dependencies": {
    "@angular-devkit/core": "^0.7.5",
    "@angular/animations": "6.1.6",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "6.1.6",
    "@angular/compiler": "6.1.6",
    "@angular/core": "6.1.6",
    "@angular/flex-layout": "^6.0.0-beta.18",
    "@angular/forms": "6.1.6",
    "@angular/language-service": "6.1.6",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "6.1.6",
    "@angular/platform-browser-dynamic": "6.1.6",
    "@angular/router": "6.1.6",
    "@ngrx/effects": "6.1.0",
    "@ngrx/entity": "6.1.0",
    "@ngrx/router-store": "6.1.0",
    "@ngrx/store": "6.1.0",
    "@ngrx/store-devtools": "6.1.0",
    "@ngx-formly/core": "^4.7.2",
    "@ngx-formly/material": "^4.7.2",
    "@nrwl/nx": "6.3.0",
    "angular-text-input-highlight": "^1.3.0",
    "class-transformer": "^0.1.9",
    "core-js": "^2.4.1",
    "deep-equal": "^1.0.1",
    "flag-icon-css": "^3.0.0",
    "i18n-iso-countries": "^3.7.4",
    "jasmine-marbles": "^0.3.1",
    "libphonenumber-js": "^1.1.7",
    "moment": "^2.22.0",
    "ngrx-store-logger": "^0.2.2",
    "ngx-loading": "^1.0.14",
    "ngx-webstorage-service": "^3.1.1",
    "normalize.css": "^8.0.0",
    "resolve": "^1.7.1",
    "rxjs": "^6.3.1",
    "rxjs-tslint": "^0.1.5",
    "shallow-equals": "^1.0.0",
    "smooth-scrollbar": "^8.2.7",
    "tslib": "^1.9.3",
    "zone.js": "^0.8.26"
  }
```
* **Angular version:** 6.1.6

* **Browser:**  Chrome, Firefox, Safari

* **Language:** Typescript

**Comment by aitboudad** [comment]
> When I click the Add button, Input is not displayed and errors appear in the console.

the raised error is correct you have to define `email` validator https://stackblitz.com/edit/angular-t3xk4l
