### ISSUE TITLE
asyncvalidation custom template

### ISSUE THREAD

**Issue by enricooliva** [formly-js/ngx-formly#1170]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```
I elaborate this custom template:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-k8qmrc

The expected behavior is to validate the input of "code" control with the async validation with a check to the backend.

This is the layout of the custom template
![decode](https://user-images.githubusercontent.com/11843561/45294014-33484c80-b4fa-11e8-8c6e-0ba5acc8fa51.PNG)

The asyncvalidation not start.

**Comment by aitboudad** [comment]
the field is already initialized at that stage you have to initialize the field before `onInit` in order to take account of validation changes, you may use the new hook `onPopulate` which is available in `v5.0`:
```ts
  onPopulate(field: FormlyFieldConfig) {

  }
```

**Comment by enricooliva** [comment]
I used a custom template with inside a formly-field and input tag.
I created inside the custom template a new field.
I used the lifecycle to manage the validation
    
```
        lifecycle: {
          onInit: (form, field) => {
            
            field.formControl.valueChanges.pipe(
              takeUntil(this.onDestroy$),
              startWith(field.formControl.value),
              tap(selectedField => {
                if (field.formControl.value!==null){
                  let result = this.service.getById(field.formControl.value);
                  this.extDescription ="descrizione"  
                } else{                                             
                  ERROR --> field.formControl.setErrors({ notfound: true});
                }
              }),
            ).subscribe();
          },
```

but I get the error
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-k8qmrc

@aitboudad 
I'm not catch the solution with onPopulate and I still have problem to set the error state.

I'm not sure this is the right approach.

**Comment by enricooliva** [comment]
@aitboudad any idea?

**Comment by aitboudad** [comment]
I'll provide an answer when I have some time :) for the second question if it's not related to this issue, please open a another issue with a reproduction example, thanks!

**Comment by aitboudad** [comment]
I'm not clearly understand what do you want to achieve, the raised error is expected to me as a workarround you use `setTimeout` or use a custom validator instead similar to https://formly-js.github.io/ngx-formly/examples/validation/unique-value-async-validation

**Comment by enricooliva** [comment]
> I'm not clearly understand what do you want to achieve, the raised error is expected to me as a workarround you use `setTimeout` or use a custom validator instead similar to https://formly-js.github.io/ngx-formly/examples/validation/unique-value-async-validation

expected behaviour:

onblur event of the "code field" start a call to backend 

 * if find the record -> populate the "field description"
 * else set error to "Not Found" in "code field"

I hope is more clear. I found solution using lifecycle of the code field
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-y6k5jx
but the blur behavior is set outside custom template :( 

other desiderata behaviour
 * press F3 on the code field and start a modal form

**Comment by aitboudad** [comment]
here is how it should  be without using `external-type.component`:  https://stackblitz.com/edit/ngx-formly-ui-bootstrap-fhufq5

**Comment by enricooliva** [comment]
Great! @aitboudad  
is possible in custom template 

- add an asyncvalidator, 
- set the modeloptions to onblur 
- and change the type of the control

before the construction of the formcontrol?

**Comment by aitboudad** [comment]
possible using ` onPopulate(field: FormlyFieldConfig) {}` or `buildForm`,
I guess you want an example :thinking: then you have to wait until I have some time :smiley:

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/ngx-formly-ui-bootstrap-q8xwk8
