### ISSUE TITLE
Material custom input error message not showing

### ISSUE THREAD

**Issue by DSaralaya** [formly-js/ngx-formly#1171]
Work Url:

https://stackblitz.com/edit/angular-jrt3dm

Can you tell what the issue in this?

A click of submitting error message is not showing.

Another issue on JSON  if change 'wrapper' to 'wrappers' then the form is not loading.

**Comment by aitboudad** [comment]
1- import `FormlyMatFormFieldModule`
2- set `wrappers` to 'form-field' for `input`
3- remove `mat-form-field` in `InputComponent`

https://stackblitz.com/edit/angular-jrt3dm-pjqdzr
