### ISSUE TITLE
Layout disalignment using addon and icon bootstrap

### ISSUE THREAD

**Issue by enricooliva** [formly-js/ngx-formly#1176]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```
I use the addon feature with bootstrap and open-ionic icon
but the addon is disaligned.

![dis](https://user-images.githubusercontent.com/11843561/45483112-3e94b580-b750-11e8-9769-515c48c4740a.PNG)

This is the stackblitz to reproduce the problem:
https://stackblitz.com/angular/qkkndaxgodlq

**Comment by mohammedzamakhan** [comment]
Probably you shared the wrong stackblitz link

**Comment by enricooliva** [comment]
Ops @mohammedzamakhan you are right. 
This is the correct link:
https://stackblitz.com/edit/angular-usybfe-asjl7u

**Comment by aitboudad** [comment]
the issue is not caused by bootstrap but `open-iconic-bootstrap` style, setting `top: 0px;` for `oi` selector would solve the issue https://stackblitz.com/edit/angular-usybfe-gth5gr
