### ISSUE TITLE
 ng-select using patchValue does not update the model

### ISSUE THREAD

**Issue by smile2014** [formly-js/ngx-formly#1179]
Assigning a value to a field corresponding to ng-select using patchValue does not update the model

**Comment by aitboudad** [comment]
please provide a reproduction example!

**Comment by aitboudad** [comment]
you've missed passing `form` input to `formly-form`, https://stackblitz.com/edit/ngx-formly-custom-template-fmuf3f

**Comment by smile2014** [comment]
Thanks, the copied ngx-formly-custom-template modified, the official ngx-formly-custom-template has forgotten the binding form

**Comment by smile2014** [comment]
In my company's project, ng-select still has a form update, and the model is not updated. I will get a sample tomorrow to see if it can be reproduced. Thank you.
