### ISSUE TITLE
Default Validation is not applied in First Use

### ISSUE THREAD

**Issue by Sanjay10247** [formly-js/ngx-formly#1180]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search GitHub for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Default validation like max length and min length for a text input is not validating while first use but works fine when focus out and re-enter the text.

**Expected behavior**
Validation should work right from the first use.

**Minimal reproduction of the problem with instructions**
Please use the below link to reproduce the issue.
https://stackblitz.com/edit/angular-vzcukk

**What is the motivation/use case for changing the behavior?**
To make this reactive forms more usable.

**Please tell us about your environment:**

* **Angular version:**
Angular Version - 6.1.X
ngx-formly/core - 4.7.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

In all Browsers irrespective of the version.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] - ES7

* **Node (for AoT issues):** `node --version` =10

**Comment by aitboudad** [comment]
we rely on [touched](https://github.com/formly-js/ngx-formly/blob/master/src/core/src/lib/services/formly.config.ts#L37-L39) state, I think it can be done using `dirty` property instead.

**Comment by Sanjay10247** [comment]
Thanks @ugogiordano87 , this works...

**Comment by ugogiordano87** [comment]
@Sanjay10247 it can also be shorter as following:

```
      validation: {
        show: false,
      },
      expressionProperties: {
        'validation.show': 'model.text && ( ("" + model.text).length >= 5 )'
        },
      }
```

**Comment by aitboudad** [comment]
to have a such behavior globally use custom `showError` see https://stackblitz.com/edit/angular-npnf5d

```ts
export function showError(field: FieldType) {
  return field.formControl && field.formControl.invalid && (field.formControl.dirty || (field.options.parentForm && field.options.parentForm.submitted) || (field.field.validation && field.field.validation.show));
}

@NgModule({
  imports: [
    FormlyModule.forRoot({
      extras: { showError },
      ...
    }),
  ],
})
export class AppModule { }
```
