### ISSUE TITLE
File Upload Custom using Ngprime

### ISSUE THREAD

**Issue by kritisoft** [formly-js/ngx-formly#1181]
```
[X] bug report => search GitHub for a similar issue or PR before submitting
[ ] feature request
[X] support request
```
Prime File Upload with ngx-formly

I am able to set the file object from my custom file component to the Parent Component using the formControl.setValue

But I am not able to send data from the parent component to the Custom File Component. that is to list the previously added Files through an edit functionality.

1. how do I send the data to my custom file component?

2. After Adding the files and clicking the submit button, I am calling a reset function, but the reset is not working on the custom file component.

Kindly check this behavior.

I have added the stackblitz code for your reference.
[https://stackblitz.com/edit/angular-qfsvw3](url)

**What is the motivation/use case for changing the behavior?**

File Upload with listing previously Added Files.

Angular Version 6
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
you can get the previously added files from `formControl.value`

**Comment by kritisoft** [comment]
Can you be specific on which event of the custom component ? i need to use `formControl.value` ?
Also the reset is not working ?

**Comment by aitboudad** [comment]
instead of using `uploadedFiles` use `formControl.value`, see https://stackblitz.com/edit/angular-qfsvw3-jqwdmx

**Comment by kritisoft** [comment]
Thanks , Its working now.

**Comment by kritisoft** [comment]
Hi , Now the Upload functionality is not working ? when i add new files and click on the upload button  its not getting added .

**Comment by kritisoft** [comment]
Thanks :)
