### ISSUE TITLE
Ionic 4: Input Width and TextArea Issues with Fixes

### ISSUE THREAD

**Issue by innovateworld** [formly-js/ngx-formly#1183]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

1. The input boxes for `formly-field-ion-input` and `formly-field-ion-textarea` are not correctly taking the full width of the page. Instead the input box only takes up about 1/3 of the area toward the center.
![screenshot 2018-09-18 at 3 06 27 pm](https://user-images.githubusercontent.com/2464454/45721146-8a8a9480-bb6c-11e8-83e2-216594107dd4.png)
2. The input box for `formly-field-ion-textarea` is not accepting the `cols` or `rows` in `templateOptions`. This leads to the `ion-textarea` displaying like a standard `ion-input`. 

**Fixes**

I have taken the below steps to fix both issues.

-1. Add `styles: [':host { display: inherit; }'],` to `@component` to correct the input box width in the following places:

* ngx-formly/src/ionic/src/lib/types/input.ts
* ngx-formly/src/ionic/src/lib/types/textarea.ts
    
-2. Add `[cols]="to.cols"` and  `[rows]="to.rows"` to Template in:

* ngx-formly/src/ionic/src/lib/types/textarea.ts

-After Changes with `rows: 6` applied in `templateOptions`:
![screenshot 2018-09-18 at 6 02 59 pm](https://user-images.githubusercontent.com/2464454/45721320-3cc25c00-bb6d-11e8-9f3b-e3c4db11a94a.png)

-Ideas:

* I believe other components can also have the `rows`, `cols`, `inherit styles`, and other fields added. I'll be working with this more now that I found out about it yesterday and will update. 

### OS & Browser
ChromeOS: Version 70.0.3538.16 (Official Build) dev (64-bit)

### App Dependencies

``` json
  "dependencies": {
    "@angular/common": "~6.1.1",
    "@angular/core": "~6.1.1",
    "@angular/fire": "^5.0.0",
    "@angular/forms": "~6.1.1",
    "@angular/http": "~6.1.1",
    "@angular/platform-browser": "~6.1.1",
    "@angular/platform-browser-dynamic": "~6.1.1",
    "@angular/router": "~6.1.1",
    "@ionic-native/core": "5.0.0-beta.15",
    "@ionic-native/splash-screen": "5.0.0-beta.15",
    "@ionic-native/status-bar": "5.0.0-beta.15",
    "@ionic/angular": "4.0.0-beta.7",
    "@ngx-formly/core": "^5.0.0-beta.8",
    "@ngx-formly/ionic": "^5.0.0-beta.8",
    "core-js": "^2.5.3",
    "firebase": "^5.4.2",
    "rxjs": "6.2.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "~6.1.1",
    "@angular/compiler": "~6.1.1",
    "@angular/compiler-cli": "~6.1.1",
    "@angular/language-service": "~6.1.1",
    "@angular-devkit/architect": "~0.7.2",
    "@angular-devkit/build-angular": "~0.7.2",
    "@angular-devkit/core": "~0.7.2",
    "@angular-devkit/schematics": "~0.7.2",
    "@ionic/ng-toolkit": "^1.0.0",
    "@ionic/schematics-angular": "^1.0.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.9.2",
    "codelyzer": "~4.4.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  },
  "description": "An Ionic project"
```

**Comment by aitboudad** [comment]
hi, can you provide a PR ?

**Comment by innovateworld** [comment]
@aitboudad Yes. I will test the other Ionic Components today and then provide a PR. Shortly after that I'll help get the formgroup layout working for Ionic 4, test building new components, and build/test other features. I am going to attempt to build an app using this with Ionic 4 and implemet form creation with drag n drop to add form components and enable reordering.
