### ISSUE TITLE
Can you provide a way to convert jsonarray to FormlyFieldConfig[]

### ISSUE THREAD

**Issue by smile2014** [formly-js/ngx-formly#1184]
let str ={abc:[{
      key: 'ip',
      type: 'input',
      templateOptions: {
          label: 'IP Address (pattern = /(\d{1,3}\.){3}\d{1,3}/)',
          pattern: "/(\d{1,3}\.){3}\d{1,3}/",
          required: true,
          divCol: 24,
          lblCol: 6,
          inputCol: 18,
          keyup: function () {
              console.log('abc');
          }
      }]}

----->  toFormlyFieldConfig(str.abc);
pattern: "/(\d{1,3}\.){3}\d{1,3}/",------->  pattern: /(\d{1,3}\.){3}\d{1,3}/,

[{
      key: 'ip',
      type: 'input',
      templateOptions: {
          label: 'IP Address (pattern = /(\d{1,3}\.){3}\d{1,3}/)',
          pattern: /(\d{1,3}\.){3}\d{1,3}/,
          required: true,
          divCol: 24,
          lblCol: 6,
          inputCol: 18,
          keyup: function () {
              console.log('abc');
          }
      }]

**Comment by aitboudad** [comment]
see https://stackoverflow.com/questions/874709/converting-user-input-string-to-regular-expression

**Comment by smile2014** [comment]
thank  you,
