### ISSUE TITLE
Validation of fieldArray

### ISSUE THREAD

**Issue by HangLoop** [formly-js/ngx-formly#1185]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

What is the best way to compare and validate fields in fieldArray?

I have a number field in the fieldArray and I need to verify if the sum of the numbers in all fieldGroup is 10 or not.
Should I add a validation to the fieldArray?
Is there a way to access the value of sibling fieldGroup in a fieldArray?

**Minimal reproduction of the problem with instructions**
https://fieldarray-validation.stackblitz.io

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/fieldarray-validation-dwruxy
