### ISSUE TITLE
The "value" property on radio buttons isn't updated

### ISSUE THREAD

**Issue by shairez** [formly-js/ngx-formly#1187]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
I'm using bootstrap

When I query a radio input element, for example: `myRadioInput` and check it's value like `myRadioInput.value` I get "on" instead of the actual value from "option.value"

**Expected behavior**
I expect that `myRadioInput.value` will be the `option.value` I set on the options array.

**Minimal reproduction of the problem with instructions**

In the following link:
1. Open the console 
2. Click on the button
3. See that instead of "male" it says "on"

[https://stackblitz.com/edit/ngx-formly-ui-bootstrap-radio-value-bug](https://stackblitz.com/edit/ngx-formly-ui-bootstrap-radio-value-bug)

**What is the motivation / use case for changing the behavior?**
For testing purposes, I need to be able to click on a certain radio input to manually select it.
that's why it's important to be able to compare the radio.value to the manually selected value. 

**Please tell us about your environment:**

windows 10
yarn
Formly + formly-bootstrap versions: 4.7.2

* **Angular version:** 6.1.0

* **Browser:** [ Chrome 68.0.3440.106  ]

* **Language:** [TypeScript 2.9 ]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
it's an issue with angular reactive forms, I've tried with `[formControl]` directive for `checkGoodValue` radio
and I've got the same result.
see https://stackblitz.com/edit/ngx-formly-ui-bootstrap-radio-value-bug-qppiy8

I've got a workaround #1190 to make it work.

**Comment by shairez** [comment]
You're the man @aitboudad ! 
Thanks!

**Comment by shairez** [comment]
I opened up an issue on the Angular repo

https://github.com/angular/angular/issues/26037
