### ISSUE TITLE
How to set server side errors  on custom types  such as repeating sections and custom template and  mix of both

### ISSUE THREAD

**Issue by thetinshusasi** [formly-js/ngx-formly#1189]
you just need to register a custom validationMessages for `server-error` key:
```ts
  FormlyModule.forRoot({
    validationMessages: [
      {name: 'server-error', message: (err) => err },
    ],
  }),
```
and to display server error use the key `server-error`:
```ts
this.form.get('name').setErrors({'server-error':'error'});
```

_Originally posted by @aitboudad in https://github.com/formly-js/ngx-formly/issues/703#issuecomment-364660359_

**Comment by aitboudad** [comment]
if I understand correctly you want to display a global error that is not related to a specific field but a grouped one, right ?

**Comment by thetinshusasi** [comment]
> if I understand correctly you want to display a global error that is not related to a specific field but a grouped one, right ?

No , I want error to be for specific fields. And each error should display under  its specific field.

I am creating multiple input boxes  inside custom-template and the formly configuration object for this is created from  similar json (but not exactly the same ) from the backend.

And some of these custom templates have  functionnality  for repeating itself just like repeating section.

I need to show  server side error messages for these fields.

For custom template with non - repeating functionality , we are getting server messages in an object 
For custom template with  repeating functionality , we are getting server messages in an array of objects

Could you please suggest way to achieve this

**Comment by aitboudad** [comment]
still not clear to me :smile:, it's better to provide a stackblitz example, thanks!
