### ISSUE TITLE
"form-control-sm" css class in bootstrap input

### ISSUE THREAD

**Issue by rakeshbhalke** [formly-js/ngx-formly#1193]
Hi,
Question :
I am trying to set "form-control-sm" css class in bootstrap example.
ref Link :- https://formly-js.github.io/ngx-formly/examples/bootstrap-specific/advanced-layout

I found hard coded form-control class in bootstrap input component.
Template Ref 
<input *ngIf="type !== 'number' else numberTmp" [type]="type" [formControl]="formControl" **class="form-control"** [formlyAttributes]="field" [class.is-invalid]="showError">
    <ng-template #numberTmp>
      <input type="number" [formControl]="formControl" **class="form-control"** [formlyAttributes]="field" [class.is-invalid]="showError">
    </ng-template>

How can apply "form-control-sm" css class to bootstrap input field ?

**Comment by aitboudad** [comment]
you can use `attributes.class` to override it:
```ts
      templateOptions: {
        label: 'Input',
        placeholder: 'Placeholder',
        description: 'Description',
        required: true,
        attributes: {
          class: 'form-control form-control-sm'
        },
      },
```

here is an example https://stackblitz.com/edit/angular-npgmjw

**Comment by rakeshbhalke** [comment]
Its working fine.
Thanks.
