### ISSUE TITLE
Repeating List with Create and Edit

### ISSUE THREAD

**Issue by DSaralaya** [formly-js/ngx-formly#1194]
Hi,

The goal is to create repeat list and edit and Delete rows. Once I edit it, shows the forms UI, then on submit I can add or cancel the edit, back to the list.

If your create Working example its great help for me. I tried but Model value not accessible in template.

https://stackblitz.com/edit/angular-fdmkrs

![flow](https://user-images.githubusercontent.com/818354/45948991-ba77e300-c017-11e8-8a46-4f8cde002311.png)

**Comment by DSaralaya** [comment]
Yes, Example creates multiple rows, but I need list and edit section single UI. 
https://stackblitz.com/edit/angular-fdmkrs

**Comment by aitboudad** [comment]
Well I think that's something you can do by yourself :), we provided enough details/examples,
here is a starter example https://stackblitz.com/edit/angular-rv7jtn-pkhqkg.
But next time I'd prefer to avoid a such requests!

**Comment by DSaralaya** [comment]
Thanks

**Comment by DSaralaya** [comment]
Sorry for disturbing :)

In Field, Array Type can provide **FieldArrayType.prototype.update** function so the model can be updated by index.
In the above example am updating the list by manual click
code like this.

edit(model){
this.model[this.index]=model;
}

when **this.ops.resetModel()** fires updated values disappaer from the model.

**Comment by aitboudad** [comment]
use `patchValue`:
```ts
    this.formControl.at(this.index).patchValue(model);
```

**Comment by DSaralaya** [comment]
In the above, FormControl value array get's updated, but the model array value is undefined.

**Comment by aitboudad** [comment]
can you replicate an example using stackblitz, thanks!

**Comment by DSaralaya** [comment]
https://stackblitz.com/edit/angular-rv7jtn-hee1gk

Steps to reproduce
1. Add record
2. edit record and save
3. Again edit (In Textbox value, not appearing)

Also, how can I access  model value 'Application'(needed for hide expression)

**Comment by aitboudad** [comment]
> use clone in editForm:
```ts
  editForm(index) {
    this.index= index;
    this.mdl = clone(this.model[index]);
    this.showForm = true;
  }
```

> Also, how can I access model value 'Application'(needed for hide expression)

the model is available through the field itself and if you want to have access to the parent one use `parent` property

```ts
field.model
field.parent.model
```

**Comment by DSaralaya** [comment]
Great thanks.... you're awesome 👍
