### ISSUE TITLE
Select placeholder is removed on form reset.

### ISSUE THREAD

**Issue by ugogiordano87** [formly-js/ngx-formly#1195]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

When reset the form the select placeholder disappears.

**Expected behavior**

The select placeholder should be shown when the form is reset. 

**Minimal reproduction of the problem with instructions**

Please refer to this simple [demo](https://stackblitz.com/edit/angular-aq7d5c) where it can be noticed that while the "input" placeholder is set again, the "select" one disappears.

**Comment by aitboudad** [comment]
this has been fixed since `5.0.0-beta.9`, placeholder appear when the field value is `undefined` or `null`,
see https://stackblitz.com/edit/angular-aq7d5c-m6dxpf
