### ISSUE TITLE
[QUESTION] Object.assign in prePopulate

### ISSUE THREAD

**Issue by jogelin** [formly-js/ngx-formly#1196]
**I'm submitting a ...**  (check one with "x")
```
[X] Question
```

**Current behavior**
I am playing with your `New Lifecycle` and I really like it. I just met something strange but I just think this is probably not the best way to do it. In fact, when I use `Object.assign` on a `field` inside `prePopulate`, my component is completely replaced, even my template... and my ngOnInit is not called.

**Expected behavior**
I though that the field configurations were just overwritten...

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/dynamic-field-v5-3xjhse?file=src%2Fapp%2Fselect-user-field-not-ok.component.ts

I don't know how to manage it in this way, do we always need to use a fieldGroup ?

**Comment by aitboudad** [comment]
> my component is completely replaced, even my template... and my ngOnInit is not called.

that's expected because you've changed the `type` which belong to another component.

> I don't know how to manage it in this way, do we always need to use a fieldGroup ?

in case of you would like to delegate the field type I would say it's better to use `fieldGroup` as suggested in https://github.com/formly-js/ngx-formly/issues/1147#issuecomment-417684585

**Comment by aitboudad** [comment]
I'm going to close this one, let me know if you have any suggestion to improve this part before reaching the `RC` phase.

**Comment by jogelin** [comment]
@aitboudad Thx for your response.

Mainly my issue is that I would like that the parent provide main configurations like the key per example...then used these configuration in my sub-field....it seems it is not possible with the current system...

I don't if I am clear ?

You know like I want to use a component with a business name like "select-user" and, because I want to re-use it in multiple applications with multiple APIs, I want to tell to what key it's bind. And then the component "select-user" decide dynamically what kind of component is displayed...but it could be able to re-use the key from the "select-user"...

**Comment by aitboudad** [comment]
still not clear to me what's do you want to achieve with select-user, without providing a real use-case I can't help on that specific area.
