### ISSUE TITLE
Select on NgPrime

### ISSUE THREAD

**Issue by SalimDr** [formly-js/ngx-formly#1197]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
When using the select input with the require field without the placeholder, it always stuck on validator require

**Expected behavior**
The Select work with the default value or with one value

**Minimal reproduction of the problem with instructions**
use for example this schema:
{
      "key": "CurrencyId",
      "type": "select",
      "className": "form-group",
      "templateOptions": {
        "label": "Currency",
        "options": [
          {
            "value": "1",
            "label": "USD"
          }
        ],
        "required": true
      }
    }

* **Angular version:** 5.2.11

* **Browser:** all

* **Language:** TypeScript 2.6.2

**Comment by aitboudad** [comment]
well I've just checked and it seems to be an NgPrime issue, there is nothing we can do in our side, sorry  about that!

it may be better to open an issue in `NgPrime` repot and use a placeholder until it get fixed or use the `defaultValue`:
```
{
  "key": "CurrencyId",
  "type": "select",
   "defaultValue": "1"
}
```
