### ISSUE TITLE
how to assign value to hidden field type for ngx-formely repeater in incremental order 

### ISSUE THREAD

**Issue by mihirhapaliya** [formly-js/ngx-formly#1198]
Hi
Can you please help me on the following ?

I want to assign each repeater's index to hidden field in incremental order.

I have field _id(hidden) inside a repeat control , I want to assign repeater's index value to the _id field .
_id of the first repeater should be 1 and _id of the second repeater should be 2 and so on...     
so the model should be generated as below 
[
{_id:1,description:'some input from user' },
{_id:2,,description:'some input from user' }
]

this.ExampleFormlyFieldConfig = [
{
'type': 'repeat',
'fieldArray': {
'fieldGroupClassName': 'row',
'templateOptions': {
'btnAddText': 'Add another control',
'btnRemoveText': 'remove this control'
},
'fieldGroup': [
{
'key': '_id',
'type': 'input',
'templateOptions': {
'label': 'Source'
},
'hideExpression':true
},
{
'className': 'col-sm-12',
'type': 'textarea',
'key': 'description',
'templateOptions': {
'label': 'Description',
'required': true,
'rows': 3
},
}

      ],
    },
  },
];

**Comment by aitboudad** [comment]
the question is not clear, can you elaborate please!

**Comment by mihirhapaliya** [comment]
@aitboudad updated description.

**Comment by aitboudad** [comment]
in `RepeatTypeComponent` by overriding `add` and `remove` methods:
```ts
  add(i?: number) {
    const initialModel = { _id: this.model.length };
    super.add(i, initialModel);
  }

  remove(i: number) {
    super.remove(i);
    this.model.forEach((m, i) => m._id = i);
  }
```

**Comment by mihirhapaliya** [comment]
@aitboudad 
_id values are not getting populated to model after submitting the form.

0: {description: "some input from user"}
1: {description: "some input from user"}
2: {description: "some input from user"}

**Comment by aitboudad** [comment]
just checked and it seems to be working to me see https://stackblitz.com/edit/angular-h98263
