### ISSUE TITLE
Ng-select validation issue

### ISSUE THREAD

**Issue by DSaralaya** [formly-js/ngx-formly#1199]
I added ng-select in formly . On submit it's not showing validation message. 

So added wrappers: ['form-field'] then its showing validation message but its showing two times.

Check this
https://stackblitz.com/edit/hello-angular-6-7n5br1

**Comment by aitboudad** [comment]
you have to adjust ng-select to be compatible with `form-field` wrapper see https://stackblitz.com/edit/angular-ngx-formly-ngselect-material-beh7g8?file=app%2Ftypes%2Ftypeahead.type.component.scss

**Comment by yluijten** [comment]
@aitboudad; I've made a small change to your example;

[https://stackblitz.com/edit/angular-ngx-formly-ngselect-material-xxprzf](https://stackblitz.com/edit/angular-ngx-formly-ngselect-material-xxprzf)

Two cases where the `expressionProperties` are fired many times:
- When you click the select and hover the options
- When you disable the select and click on it

I have the same behaviour in my application. Any ideas how to solve this?

**Comment by aitboudad** [comment]
@yluijten check https://github.com/ngx-formly/ngx-formly/issues/1641#issuecomment-507368224

**Comment by yluijten** [comment]
@aitboudad Ok, thanks. Any estimate when these issues will be addressed and [v6](https://github.com/ngx-formly/ngx-formly/issues/1365) will be launched?

**Comment by aitboudad** [comment]
>  Any estimate when these issues will be addressed

will be addressed soon (probably this week)

> v6 will be launched?

not decided yet ;)
