### ISSUE TITLE
input type email is not validated in tabs form

### ISSUE THREAD

**Issue by mungpara** [formly-js/ngx-formly#1200]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
when using tabs form and set input type to email then it is not validating email.
https://formly-js.github.io/ngx-formly/examples/advanced/tabs
i use this example and change firstname with email and set input type email in templateOptions, after that email is not validated.

* **Angular version:** 6.1.7

**Comment by aitboudad** [comment]
`email` validation is not supported out of the box you have to define it by yourself see the demo example https://formly-js.github.io/ngx-formly/examples/validation/custom-validation
