### ISSUE TITLE
Validation not activated on Load of formly form

### ISSUE THREAD

**Issue by devesh23** [formly-js/ngx-formly#1201]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
I have a validation for calendar field and I am providing a default value for that calendar. I want the validation to run as soon as the form loads but until I focus/Blur out of the calendar field the validation does not activate. I think it may be because the calendar field has not been "touched"

**Expected behavior**
Expected behavior would be that validation runs on load

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
I would like to load data from excel and display in an formly form 

**Please tell us about your environment:**
Windows, Google Chrome

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
we rely `touched` property if you want force showing error state use `validation.show`,
see https://formly-js.github.io/ngx-formly/examples/validation/force-show-error

**Comment by devesh23** [comment]
Hey @aitboudad 

Thanks for replying so quickly. Appreciate it. 

Although the above would help but I am looking for it to dynamic and only affect those elements for whom the excel would provide values. 

Suppose my form has 5 fields 

Date
Time
Address
Name
ID

but the excel only provides data for 

Date
Time 

Therefore I would like to run the validation for date and time ( Here excel could be providing data for any of the 5 fields). I do understand that a possible workaround will be to use expressionProperties and check whether model has values for these form field or not. But for a complex form with lots of nesting and repeating section the model design would have to be standardize. 

Therefore to avoid this standardization would you be able to suggest some other solution?

**Comment by aitboudad** [comment]
well in that case you can create a custom extension that allow you to override/customize to passed field during build form see my comment https://github.com/formly-js/ngx-formly/issues/1109#issuecomment-412295111
