### ISSUE TITLE
Do we have a way to provide focus to one of the input field inside the repeating section

### ISSUE THREAD

**Issue by thetinshusasi** [formly-js/ngx-formly#1203]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
I am not able to provide focus to one of the input field inside the repeating section. I tried to set the focus property of the nested formlyFieldConfig to true, yet it is not getting focus
**Expected behavior**
Not able to provide focus to one of the input field inside the repeating section.
Do i have to get the native Element of this field and set the focus to true ? If Yes then how ?
**Minimal reproduction of the problem with instructions**
When trying to create Repeating section using "Json powered " forms . Try to focus on any of the input fields of the repeating section

**What is the motivation / use case for changing the behavior?**
Focus is getting lost when configuration is rebuild  for repeating section . However it working for normal section.

**Please tell us about your environment:**
Window
* **Angular version:** 2.0.X
Angular 6
* **Browser:** [all ]

* **Language:** [ TypeScript @latest]

* **Node (for AoT issues):** `node --version` = 8.XX

**Comment by aitboudad** [comment]
on that you can set focus using `expressionProperties`:
```ts
expressionProperties: {
  focus: 'this.field.parent.key == 0'
}
```
see https://stackblitz.com/edit/angular-pxyxsy

**Comment by vmtzgr** [comment]
Is there a solution available for this now?
