### ISSUE TITLE
Problem with multicheckbox

### ISSUE THREAD

**Issue by davidoween** [formly-js/ngx-formly#1204]
I have two multicheckboxs with same key and same name attribute. It not works.
I have the same example in a radio field and it works.
I have seen the code and the name attribute is not specified in the checkbox

We are using 3.1.0 version, and we can't update to the last one because of angular 6 dependency. Anyway, this problem also happens on v 4.x.x of formly. Could you make this fix also for v.3.0.X, please?

Example:
https://stackblitz.com/edit/angular-rjpqaw?file=app/app.component.ts

**Comment by aitboudad** [comment]
Not sure how to deal with it, so I would considered as feature.

>  Could you make this fix also for v.3.0.X, please?

if it get solved you can use a custom multicheckboxs, until you get the chance to upgrade into the latest version.

**Note**
supporting multiple versions it out of question unless I get paid for it :)

**Comment by aitboudad** [comment]
fixed by #1209, it'll be available in `v5` you can use the following workaround until updating to `v5`:
https://stackblitz.com/edit/angular-yub6jc?file=app%2Fmulticheckbox.ts

**Comment by davidoween** [comment]
So you can not help me with version 3? I helped you with the documentation before 😪  If you tell me what I have to do, I can do pull request

**Comment by aitboudad** [comment]
using https://stackblitz.com/edit/angular-yub6jc?file=app%2Fmulticheckbox.ts in version 3 would be enough for you, have you encountered an issue while using that example ?

**Comment by aitboudad** [comment]
just I did a small fix which you may need to apply in the custom `multicheckbox` type
```html
[checked]="formControl.value && formControl.value[option.key]"
```

https://stackblitz.com/edit/angular-5ccpqc
