### ISSUE TITLE
how to make filed required based on other fields value ? 

### ISSUE THREAD

**Issue by mihirhapaliya** [formly-js/ngx-formly#1206]
Can you please help me with following ?

I want to make contact field required only if I enter any value in name field.
contact field should not be required if name field is empty

 FormlyFieldConfig = [
      {
        'fieldGroupClassName': 'row',
        'fieldGroup': [
          {
            'className': 'col-12',
            'type': 'input',
            'key': 'name',
            'templateOptions': {
              'label': 'Name',              
            },		  
            {
            'className': 'col-12',
            'type': 'input',
            'key': 'contact',
            'templateOptions': {
              'label': 'Contact',
              'required': true,
            }            
          },
         
        ]
      },
      
    ];

**Comment by aitboudad** [comment]
use `expressionProperties`:
```ts
expressionProperties : {
  'templateOptions.required' : '!model.name'
}
```

here is an example https://stackblitz.com/edit/angular-jgye2p
