### ISSUE TITLE
Separate child component for each tab - multiatep approach

### ISSUE THREAD

**Issue by albertthinc** [formly-js/ngx-formly#1208]
Hi

I am building a large form in the multiatep approach in one of your examples.

I wanted to use 3 different component to 3 different tabs.
I created 3 component and conditionally switched based on the tab. But having trouble getting the controls and options.

Likes child components for each tab.

Can you help on how to achieve it.

Thanks innadvance

**Comment by aitboudad** [comment]
you may chack the demo https://formly-js.github.io/ngx-formly/examples/advanced/tabs
for a separate child component you can get child components using [Viewchildren](https://angular.io/api/core/ViewChildren) or [Viewchild](https://angular.io/api/core/ViewChild)

**Comment by albertthinc** [comment]
I wanted to handle some functions and validation in the child components for the specific tab.

Because I don't want to writing too many lines of code in a single component. 


Also,
What is the "component" property in the schema..? Can you please share an example of its usage.

Thank you

**Comment by aitboudad** [comment]
> What is the "component" property in the schema..? 

it's for internal usage, not part the schema anymore.

> Can you please share an example of its usage.

I have no example to provide, it's better to replicate yours using `stackblitz` and I'll check later.

**Comment by albertthinc** [comment]
I wanted to handle some functions and validation in the child components for the specific tab.
Because I don't want to writing too many lines of code in a single component.

Any comments..?

**Comment by aitboudad** [comment]
sorry without doing some initial steps from your side (a stackblitz example is required), I can't provide any help.

the above example show how to do it in a single component which may easily be split into child components by passing them the shared fields like `form` and `model`.
