### ISSUE TITLE
Can't display a field in function of another with updateSubmit

### ISSUE THREAD

**Issue by olivierscheffler** [formly-js/ngx-formly#1217]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ X ] support request
```

**Current behavior**
Actually, if I set :
` 
 modelOptions: {
  updateOn: 'submit',
 }
`
I'm not able to display another field in function of a value selected without make a submit and have the validation on the submit.
The only way to display a field is to have the validation onBlur but I can't do that because of UX Spec..

**Expected behavior**

I should be able to display a field in function of a select and have the validation on a submit without having the two behaviours depends to one each other..

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-kbjq9s?file=src%2Fapp%2Fapp.component.ts

**Comment by olivierscheffler** [comment]
I want to use updateOn because I want ti display an error message only when I click on submit and not on the blur of the field

**Comment by aitboudad** [comment]
then you're looking at the wrong place, to control when showing error message you have to pass a custom `showError`:

```ts
export function showError(field) {
  return field.formControl 
    && field.formControl.invalid 
    && (
      (field.options.parentForm && field.options.parentForm.submitted) 
      || (field.field.validation && field.field.validation.show)
    );
}

@NgModule({
  imports: [
    FormlyModule.forRoot({
      extras: { showError },
      ...
    }),
  ],
})
export class AppModule { }
```

https://stackblitz.com/edit/angular-qoriek
