### ISSUE TITLE
Use onClick for FormlyFieldConfig fetched from db

### ISSUE THREAD

**Issue by pselis** [formly-js/ngx-formly#1218]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X ] support request
```
**Current behavior**
When i load FormlyFieldConfig from external resources i'm not able to call any function

**Expected behavior**

**Minimal reproduction of the problem with instructions**
see https://stackblitz.com/edit/angular-t9xn4r

**What is the motivation / use case for changing the behavior?**
I would like to call a function from an externally defined FormlyFieldConfig

**Please tell us about your environment:**
* **Angular version:** 6.1.X
* **Ngx-formly: 4.7.2
* **Browser:** all

**Comment by aitboudad** [comment]
use `bind(this)`, see https://stackblitz.com/edit/angular-t9xn4r-kpx1pc
