### ISSUE TITLE
Getting Error while adding Multiselect for Primeng -- Error: No value accessor for form control with unspecified name attribute

### ISSUE THREAD

**Issue by babburi** [formly-js/ngx-formly#1219]
Hi Team,

I am trying to add some additional input elements to Prime NG such as Calendar and Multiselect. I got the calendar working but, I am getting this error  **_No value accessor_** for Multiselect.

Primeng Multiselect : https://www.primefaces.org/primeng/#/multiselect 

https://stackblitz.com/edit/ngx-formly-ui-primeng-wpgu3i

Please advice.

Regards,
Hari.

**Comment by aitboudad** [comment]
change you multiselect selector to match the primeng one:
```patch
-- p-multiselect
++ p-multiSelect
```
