### ISSUE TITLE
How to state of wrapper depending upon change in checkbox value inside wrapper. 

### ISSUE THREAD

**Issue by devesh23** [formly-js/ngx-formly#1220]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ X] support request
```

**Current behavior**

I have created a custom wrapper with a checkbox and then I am applying this wrapper over other fields. Now, When I click on checkbox, I am not able to manipulate the wrapper using the value of checkbox as it's not available in formControl. How to rectify this situation

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I am creating a form with two section. When I select the checkbox on any section, that section should be disabled.

**Please tell us about your environment:**

 Windows 10 

* **Angular version:** 2.0.X

Angular 6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
can you provide a stackblitz, a starter example is in the demo app.

**Comment by devesh23** [comment]
https://stackblitz.com/edit/angular-6bpybx?file=src%2Fapp%2Fapp.component.ts

Here is a reproduction. On select of checkbox I want to disable the section

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-6bpybx-sp9cyh

**Comment by devesh23** [comment]
Can I do the same using expression properties?
