### ISSUE TITLE
Multiple Checkbox allow labelProp and valueProp

### ISSUE THREAD

**Issue by mungpara** [formly-js/ngx-formly#1227]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
labelProp and valueProp not working

**Expected behavior**
Allow labelProp and valueProp like select

**Comment by aitboudad** [comment]
that's a feature which is fixed since `5.0.0-beta.10`
