### ISSUE TITLE
Listener of one field is activating other fields

### ISSUE THREAD

**Issue by devesh23** [formly-js/ngx-formly#1230]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ X] support request
```

**Current behavior**

I have 10 custom input field. In the custom component, I have defined an ngAfterViewChecked and am doing validation inside those. 

For the first field, I have a checkDecimal validation. Now, When I interact with any other field, I am able to see the console.log meant just for the first field. It means that listener for first field is always in the active state and is somehow linked to the other fields

**Expected behavior**

Each field should be independent of each other and interaction on one of the field should not activate other fields. 

**Minimal reproduction of the problem with instructions**

I would not be able to provide a sample implementation due to some issue.

**Comment by aitboudad** [comment]
without providing a sample example, it's difficult to figure-out what you're referring.

**Comment by devesh23** [comment]
My question is related to https://github.com/formly-js/angular-formly/issues/739 issue. I would be sharing a example for the same soon.

**Comment by devesh23** [comment]
Hey @aitboudad , 

https://stackblitz.com/edit/ngx-formly-ui-material-1vwjsm?file=app/app.module.ts <-Stackblizt

Open inspect element and just hover in any one of the text area component. You would find that console.log(this) is called for all text area and for any event in any component. 

Regards,
Devesh

**Comment by aitboudad** [comment]
why you would like to use `ngAfterViewChecked` ?

**Comment by devesh23** [comment]
I would like to add a default validation **checkDecimal** and would like to initiate the validation when data loads into the form i.e using the model i would be populating the form with some prefilled data. 

Also, Using ngAfterViewChecked, I was aiming to add custome validation which I could call directly using templateOptions. 

I would just assign checkDecimal: true in templateOptions and then would use ngAfterViewChecked to check whether the string is decimal or not. This way, i would save the time of user to not use validator:{validation: ['checkDecimal']} i.e I am providing another level of validation for the same.

**Comment by aitboudad** [comment]
that's not the better place, in `v5` we've introduce some hooks that allow a handling a such case:

`prePopulate`: before touching the field.
`onPopulate`: defaultOptions, Model, formControl are set (which is suitable to update the child element).
`postPopulate`: after populate children, if the field doesn't have children it should be the same as onPopulate event.

**Warning**:
These events can be called whenever the field model change not matter the field was initialized or not.

**Comment by devesh23** [comment]
@aitboudad But we would need to define these lifecycle in jsonConfig. 

I want to define the same in TS file and build default validations same as min, max, minLength, maxLength 

If postPopulate, prePopulate and onPopulcate can be used in ts file of extended component then I would be happy to hear the way to use them without facing the same problem as ngAfterViewChecked

**Comment by aitboudad** [comment]
> But we would need to define these lifecycle in jsonConfig.

not sure what do you means but for advanced usage you can define a custom extension for that as descibed in https://github.com/formly-js/ngx-formly/issues/1109#issuecomment-412295111

> If postPopulate, prePopulate and onPopulcate can be used in ts file of extended component then I would be happy to hear the way to use them without facing the same problem as ngAfterViewChecked

sorry but I don't have much time to provide a full example, try it on your side and let me know if you have some questions.

here is a simple example of initializing a field
```ts
export class AddressFieldType extends FieldType {
  prePopulate(field: FormlyFieldConfig) {
    if (field.fieldGroup) {
      return;
    }

    field.fieldGroup = [{
      type: 'select',
      key: 'city',
      },
      ....
    }];
  }
}
```

**Comment by devesh23** [comment]
Hey @aitboudad , 

I tried your example and it is not working **prePopulate** in TS file is being called even before the form is rendered,

Do you know any other way that I would be able to achieve the same

Regards,
Devesh

**Comment by aitboudad** [comment]
validation should be defined before the form is rendered, isn't it ?

**Comment by devesh23** [comment]
Hey @aitboudad , 

Sorry! We figured out how to restrict the listener to one element. 

But then when we tried to run validation ( Defined as a function not as a form config ) in TS file under postPopulate, the validation worked, but the formControl.markasdirty did not work as the form had not rendered.

**Comment by aitboudad** [comment]
we're relying on `touched` status instead, can you try with `.markAsTouched()`
