### ISSUE TITLE
Please add camera input type for mobile app

### ISSUE THREAD

**Issue by kevinleawu** [formly-js/ngx-formly#1231]
**I'm submitting a feature request for camera input field on mobile application **  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

A mobile input form that can take photo with device camera

**Please tell us about your environment:**

Mobile phone such as Android, iOS, etc..

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
it can be done by yourself here is a simple file input example https://formly-js.github.io/ngx-formly/examples/other/input-file

**Comment by aitboudad** [comment]
all you have to do is to add `capture` attribute to the file type if I'm not mistaken
