### ISSUE TITLE
Using multiple key in labelkey property for ngselect

### ISSUE THREAD

**Issue by albertthinc** [formly-js/ngx-formly#1232]
Hi

From service I am getting firstname and lastname.
In ng-select I want to display concatenated these 2 keys and display in lable. 

How to pass in the templateoptions..

Thanks in advance

**Comment by aitboudad** [comment]
you can apply map pipe to your options or use `formlySelectOptions` pipe see https://stackblitz.com/edit/angular-ngx-formly-ngselect-material-2bj3sf

**Comment by SudeshAK** [comment]
In this example can I add select all option?
