### ISSUE TITLE
Quick help switching schemes/FielsArrayType' based on value

### ISSUE THREAD

**Issue by albertthinc** [formly-js/ngx-formly#1236]
I need to switch the scheme based on a value..
For value = 1 set of fields and validation
If value = 1 different set of fields and validation.

Thank you

**Comment by aitboudad** [comment]
not sure If I clearly understand, you may use `hideExpression` https://stackblitz.com/edit/angular-nvzdec

**Comment by albertthinc** [comment]
Thank you.

Will this work if I do the same inside a repeat section..?
I will give it a try.

**Comment by aitboudad** [comment]
I think so!

**Comment by albertthinc** [comment]
When I use it inside a repeat section with a key.

The second set of fields is also affecting the first object.

But I don't want the second group of object for the first schema..

How to make the second schema ignored.

Please assist thank you

**Comment by albertthinc** [comment]
Any suggestions..?

**Comment by aitboudad** [comment]
to apply to the second object use the following condition: `this.field.key === 2` inside hideExpression

**Comment by albertthinc** [comment]
Hi,
In the below example, if you fill the textbox of 1 section and if you switch to another, the validation message is not displayed.

It is not validating the actual displayed formcontrols.

https://stackblitz.com/edit/angular-nvzdec

**Comment by aitboudad** [comment]
angular doesn't support using the same formControl in multiple fields https://github.com/angular/angular/issues/14451, try using different keys.

**Comment by albertthinc** [comment]
hi,
i need to display 2 different set of forms based on a product code. 

I tried to create 2 new object with filtered purpose code list. And passed the filtered model to 2 formly-form. But the issue i am facing is , the add() inside repeat is not working.

is there anyother way.

I need to use the same filtered, duplicated to 2 formly-form, and display the array for the specific product code.

**Comment by albertthinc** [comment]
Also, request a feature to get the parent object inside expression properties and hideexpressions inside a formArray/repeat section.

**Comment by aitboudad** [comment]
> I need to use the same filtered, duplicated to 2 formly-form, and display the array for the specific product code.

mot clear, please provide a stackblitz example of what you've done.

> Also, request a feature to get the parent object inside expression properties and hideexpressions inside a formArray/repeat section.

available in `v5` beta version.
