### ISSUE TITLE
Full FormlyFieldConfig Array Object not created In OnInit and OnChanges LifeCycle 

### ISSUE THREAD

**Issue by thetinshusasi** [formly-js/ngx-formly#1237]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

Full configuration object is not present in  OnInit and OnChanges Lifecycles, 

**Expected behavior**

Full configuration object is should be  present in  OnInit and OnChanges Lifecycles of the presentation
component ( "home.component.ts) 

Or 

Preferably should be able to generate in  parent component, which is passing the configuration

I need this to provide focus and individual  custom error messages  in the repeat type  fields

**Minimal reproduction of the problem with instructions**
Git Sample code:
https://github.com/thetinshusasi/NgxFormlyTestAppIssue.git

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X
Angular@latest

* **Browser:** [all ]

* **Language:** [all ]

* **Node (for AoT issues):** `node --version` =
Node 8.x

**Comment by aitboudad** [comment]
it's not possible since the `formly-form` component is not yet initialized at that stage, the only option you may use is to build form manually using `FormlyFormBuilder` service:
```ts
  constructor(private builder: FormlyFormBuilder) {}
  buildForm() {
    this.builder.buildForm(this.form, this.fields, this.model ...
  }
```

**Comment by thetinshusasi** [comment]
> > it's not possible since the `formly-form` component is not yet initialized at that stage, the only option you may use is to build form manually using `FormlyFormBuilder` service:
> > ```ts
> >   constructor(private builder: FormlyFormBuilder) {}
> >   buildForm() {
> >     this.builder.buildForm(this.form, this.fields, this.model ...
> >   }
> > ```
> 
> Could you please provide an stackblitz example in which we are manually building the form and not using formly-form component and still we are able to render with all its functionality

As the buidform() method in the formly-form component is executed again and its overriding the FormlyFieldConfig again

**Comment by thetinshusasi** [comment]
> > > it's not possible since the `formly-form` component is not yet initialized at that stage, the only option you may use is to build form manually using `FormlyFormBuilder` service:
> > > ```ts
> > >   constructor(private builder: FormlyFormBuilder) {}
> > >   buildForm() {
> > >     this.builder.buildForm(this.form, this.fields, this.model ...
> > >   }
> > > ```
> > 
> > 
> > Could you please provide an stackblitz example in which we are manually building the form and not using formly-form component and still we are able to render with all its functionality
> 
> As the buidform() method in the formly-form component is executed again and its overriding the FormlyFieldConfig again

Please find a sample of the issue : https://github.com/thetinshusasi/NgxFormlyFormBuilderIssue
