### ISSUE TITLE
Using ngx-uploader with ngx-formly

### ISSUE THREAD

**Issue by albertthinc** [formly-js/ngx-formly#1239]
Hi

Require you assistance on how to implement ngx-uploader with ngx-formly.

Thank you

**Comment by aitboudad** [comment]
by following the guide you can do it by yourself https://formly-js.github.io/ngx-formly/guide/custom-formly-field

also you may check the file upload example https://formly-js.github.io/ngx-formly/examples/other/input-file

**Comment by HarshitChhipa** [comment]
Did you succeed?
are you able to wrap the ngx-uploader in ngx-formly?
