### ISSUE TITLE
lifecycle/hooks regression + general bug (4.8.0 vs 5.0.0-beta.12)

### ISSUE THREAD

**Issue by htrex** [formly-js/ngx-formly#1241]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

On both version 5.0.0-beta.12 and 4.8.0 the onChanges hooks/lifecycle is never called when the user inputs a new value.
On version 5.0.0-beta.12 onChanges hook is also never called when the model is updated programmatically while on 4.8.0 it is.

**Expected behavior**

The onChanges hook/lifecycle should be consistently called both when the user inputs a new value or the model is updated programmatically.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/ngx-formly-lifecycle-sample480
https://stackblitz.com/edit/ngx-formly-hooks-sample500

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Linux

* **Angular version:** 6.1.10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Tested on Chrome 69.0.3497.100 (Official Build) (64-bit) + Firefox 62.0.3 (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
I think that's expected since we rely only on the `field` input, but to simplify upgrading I'll try to make it working when using lifecycle.
