### ISSUE TITLE
Returning tabs field from a function giving problem

### ISSUE THREAD

**Issue by SudeshAK** [formly-js/ngx-formly#1244]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```
Hi,
In this example https://stackblitz.com/edit/angular-oxq3ka
instead of giving fields in tabs array I am using getField function and returning fields value
based on the tabs index.

Problem I am facing is
1 The is multiple call to getField function (console.log('call') is called multiple times)
2.The fields are freezed I am not able to add any value in it

* **Angular version:** 5

**Comment by aitboudad** [comment]
you should avoid returning a new fields instance each time to avoid rebuilding fields, try store them somewhere.

see https://stackblitz.com/edit/angular-oxq3ka-8hlzjm

**Comment by SudeshAK** [comment]
In this example https://stackblitz.com/edit/angular-oxq3ka-8hlzjm also if we console.log we can see its multiple time called we cannot avoid this right?

**Comment by aitboudad** [comment]
each time change detection is triggered, `getField` will be called, enabling `OnPush` would solve the issue but not sure, also I think it's better to avoid that whenever possible

**Comment by SudeshAK** [comment]
Ok.. thank you ..
