### ISSUE TITLE
Don't update FormGroup errors property when there is invalid value

### ISSUE THREAD

**Issue by GetTaxSolutions** [formly-js/ngx-formly#1245]
Hello, I have form with one field which is required and have one validator. I'm displaying FormGroup object errors on the page and expect to see that there is one invalid field but errors property is null. The status is updated but errors not.

Example:
[https://stackblitz.com/edit/angular-wmq5dm](https://stackblitz.com/edit/angular-wmq5dm)

**Comment by aitboudad** [comment]
`form.errors` contains global errors which doesn't belong to `text` field. to get `text` errors try with:
```html
{{form.get('text').errors | json}}
```
