### ISSUE TITLE
Passing extra arguments to submit button

### ISSUE THREAD

**Issue by alexmantaut** [formly-js/ngx-formly#1246]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```
I would like to create a form with 2 buttons, one that saves and keeps on editing the current entity, and another that saves and starts creating a new entity. 

I've been trying to do so by passing a boolean parameter to my submit method, 

`submit(model:any, addAnother:boolean)`

Before trying to add the new button, my forn looks something like this:

`<form [formGroup]="form" (ngSubmit)="submit(model)">`
...
```
<button  type="submit" >Save and Add Another</button>
<button  type="submit" >Save</button>
```
...
`</form>`

To pass the parameter, I tried a few approaches, unsuccessfully:

**Approach 1**: getting rid of the submit method on the form, and instead assigning click methods on the buttons. 
Problem: Click method gets called ok, but inside the method form.valid is false, so I cannot proceed sending the form. Do I need to call some form validation from the click method?

**Approach 2**: Using an intermediate variable to pass to the submit method. The variable gets assigned on the click method on the buttons.
Problem: Submit method does not always get called after the click method, also I would like to avoid intermediate variables

My question would be... What is the best way to submit the form with different parameters, depending on the button clicked?

Thanks in advance,

**Comment by aitboudad** [comment]
use type `button` and update submitted status manually on click:
```ts
onSubmit() {
   this.options.parentForm.submitted = true;
   ...
}
```

**Comment by alexmantaut** [comment]
Additional quesiton: if I make my buttons of type button, how do I get the form to submit on pressing enter?
