### ISSUE TITLE
Translatable validationMessages

### ISSUE THREAD

**Issue by jojohoch** [formly-js/ngx-formly#1253]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

I'm using a custom wrapper to make labels and descriptions translatable with the ngx translate pipe:
```
<div class="form-group" [class.has-error]="showError">
  <label *ngIf="to.label && to.hideLabel !== true" [attr.for]="id">
    {{ to.label | translate }} <ng-container *ngIf="to.required && to.hideRequiredMarker !== true">*</ng-container>
  </label>
  <ng-template #fieldComponent></ng-template>
  <div *ngIf="showError" class="invalid-feedback" [style.display]="'block'">
    <formly-validation-message  [field]="field"></formly-validation-message>
  </div>
  <small *ngIf="to.description" class="form-text text-muted">{{ to.description | translate }}</small>
</div>
```

Is there a way to adapt this solution for validationMessages?

**Expected behavior**
```
<formly-validation-message  [field]="field">{{ validationMessage || translate }}</formly-validation-message> 
``` 

**What is the motivation / use case for changing the behavior?**
I'm devoloping a multi language web app  

* **Angular version:** 7.0.X

**Comment by aitboudad** [comment]
for label and description see https://formly-js.github.io/ngx-formly/examples/advanced/i18n,
validationMessage for now your can rely of component ref to get `formly-validation-message` instance but I think we should find a better way to manage a such case.
```html
 <formly-validation-message [style.display]="'none'" #validationRef  [field]="field"></formly-validation-message>
<ng-container *ngIf="validationRef && validationRef.errorMessage">
  {{ validation.errorMessage || translate }}
</ng-container>
```

**Comment by jojohoch** [comment]
Thank you. 
It works! I have to use formly in a pure json format,  I see no way to implement the suggested solution for labels and descriptions, because I can't add functions as values to formly.

Your solution could be useful for sombody else. Here a small correction

```
{{ validationRef.errorMessage | translate }}
```
