### ISSUE TITLE
Manually build FormlyConfig is getting overridden by Formly-form component

### ISSUE THREAD

**Issue by thetinshusasi** [formly-js/ngx-formly#1260]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
When we build formlyFieldConfig manually  using

constructor(private builder: FormlyFormBuilder) {
    this.builder.buildForm(this.form, this.fields, this.model, this.options);
    this.fields[0].fieldGroup[0].fieldGroup[0].focus = true;
  }
and assigning some value inside the fieldGroup such as ( focus as shown above ). 
it is getting overridden or lost .

**Expected behavior**
I need to keep the manually created FormlyfieldConfig and its changes intact and display the form accordingly 
i.e it should get overridden in formly-field component

**Minimal reproduction of the problem with instructions**
https://github.com/thetinshusasi/NgxFormlyFormBuilderIssue

**What is the motivation / use case for changing the behavior?**
Business Requirement  as we have multiple forms and its configuration at the container component and 
each complete configuration  is passed to a presentational (child) component containing following Html

<form [formGroup]="form" (ngSubmit)="submit()">
  <formly-form [model]="model" [fields]="fields" [options]="options" [form]="form">
    <button type="submit" class="btn btn-primary submit-button" [disabled]="!form.valid">Submit</button>
  </formly-form>
</form>
**Please tell us about your environment:**
Windows

* **Angular version:** 6.x

* **Browser:** [all ]

* **Language:** [all]

* **Node (for AoT issues):** `node --version` = 8.x

**Comment by aitboudad** [comment]
not sure I clearly understand the use-case but there is an internal input `isRoot` which we use to avoid building/evaluate expression for child fields that can be usefull to you, can you try it `<formly-form [isRoot]="false" ></formly-form>` and let me know if that's exactly the option that you are looking for.

**Comment by thetinshusasi** [comment]
> [isRoot]="false"

When setting [isRoot]="false" in the 
project   https://github.com/thetinshusasi/NgxFormlyFormBuilderIssue
the form is not painting in the UI and throws the following error

TypeError: this.options.showError is not a function
    at FormlyWrapperValidationMessages.get [as showError] (webpack-internal:///./node_modules/@ngx-formly/core/fesm5/ngx-formly-core.js:1988)
    at Object.eval [as updateDirectives] (ng:///FormlyBootstrapModule/FormlyWrapperValidationMessages.ngfactory.js:38)
    at Object.debugUpdateDirectives [as updateDirectives] (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14913)
    at checkAndUpdateView (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14060)
    at callViewAction (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14411)
    at execComponentViewsAction (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14343)
    at checkAndUpdateView (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14066)
    at callViewAction (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14411)
    at execEmbeddedViewsAction (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14369)
    at checkAndUpdateView (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14061)


Could you please look into the github sample project : https://github.com/thetinshusasi/NgxFormlyFormBuilderIssue

and suggest the  solution for it

**Comment by thetinshusasi** [comment]
> > [isRoot]="false"
> 
> When setting [isRoot]="false" in the
> project https://github.com/thetinshusasi/NgxFormlyFormBuilderIssue
> the form is not painting in the UI and throws the following error
> 
> TypeError: this.options.showError is not a function
> at FormlyWrapperValidationMessages.get [as showError] (webpack-internal:///./node_modules/@ngx-formly/core/fesm5/ngx-formly-core.js:1988)
> at Object.eval [as updateDirectives] (ng:///FormlyBootstrapModule/FormlyWrapperValidationMessages.ngfactory.js:38)
> at Object.debugUpdateDirectives [as updateDirectives] (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14913)
> at checkAndUpdateView (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14060)
> at callViewAction (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14411)
> at execComponentViewsAction (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14343)
> at checkAndUpdateView (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14066)
> at callViewAction (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14411)
> at execEmbeddedViewsAction (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14369)
> at checkAndUpdateView (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14061)
> 
> Could you please look into the github sample project : https://github.com/thetinshusasi/NgxFormlyFormBuilderIssue
> 
> and suggest the solution for it

Also by setting [isRoot]="false" , the model object is not also updating and i think it also stops other 
functionality of formly-form component OnChanges lifeCycle hook

**Comment by aitboudad** [comment]
the issue has been solved in `v5`
