### ISSUE TITLE
field.parent.key  property is coming undefined in @ngxFormly/Core 4.8 version 

### ISSUE THREAD

**Issue by thetinshusasi** [formly-js/ngx-formly#1264]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request
```

**Current behavior**
 expressionProperties: {
              focus: 'this.field.parent.key == 0'
            }

this.field.parent.key is coming undefined in @ngxformly/core 4.8
as 4.8 is the current stable version

**Expected behavior**
Should be able to get the parent property

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-pxyxsy

update the dependencies to from the dependencies tab , then this bug will manifest

**What is the motivation / use case for changing the behavior?**
Need to focus on one of input fields in of repeat type

**Please tell us about your environment:**
Windows

* **Angular version:** 6.x.x

* **Browser:** [all ]

* **Language:** [all ]

* **Node (for AoT issues):** `node --version` = 8.x.x

**Comment by aitboudad** [comment]
`parent` was introduced in `v5` not availbale in `v4`.

**Comment by thetinshusasi** [comment]
> `parent` was introduced in `v5` not availbale in `v4`.

Does V5 has breaking changes for V4

**Comment by aitboudad** [comment]
see https://github.com/formly-js/ngx-formly/blob/master/UPGRADE-5.0.md

**Comment by thetinshusasi** [comment]
> `parent` was introduced in `v5` not availbale in `v4`.

Could you please incorporate the Parent property in V4.8  or provide a way around to access it in V 4.8, that would be really appreciated as business will only allow stable version of formly and not the Beta Version

**Comment by aitboudad** [comment]
sorry not possible, it's a feature that will be only available in `v5`.
