### ISSUE TITLE
How to set asyncValidators inside a wrapper?

### ISSUE THREAD

**Issue by damsorian** [formly-js/ngx-formly#1270]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
I tried setting `this.field.asyncValidators` inside a wrapper component but it is not work.

**Expected behavior**
I would like to be able to set the asyncValidator inside a wrapper component, in order to pass a simple key and all the logic of remote validation have it already configured.

**Example code**
```typescript
@Component({
  selector: 'formly-custom-wrapper',
  template: `<ng-container #fieldComponent></ng-container>`,
})
export class FormlyWrapperComponent extends FieldWrapper implements OnInit {

  @ViewChild('fieldComponent', {read: ViewContainerRef})
  fieldComponent: ViewContainerRef;

  constructor(private formlyConfig: FormlyConfig) { super(); }

  ngOnInit() {
    this.field.asyncValidators = {
      uniqueUsername: {
        message: 'This username is already taken.',
        expression: (control: FormControl, fieldConfig: FormlyFieldConfig) => {
          return new Promise((resolve) => {
            setTimeout(() => {
              resolve(control.value.length >= 4);
            }, 2000);
          });
        },
      },
    },
  }
}
```

**Comment by aitboudad** [comment]
can you provide an example using StackBlitz

**Comment by damsorian** [comment]
@aitboudad thanks, I added an example code maybe with that you understand what I want to do?

**Comment by aitboudad** [comment]
the field is already initialized during that stage, in `v5` we've introduced some hooks that allow a such case but not supporting wrapper, you may use a custom extension https://github.com/formly-js/ngx-formly/issues/1109#issuecomment-412295111
