### ISSUE TITLE
Validate a multi-step form with repeatable fieldGroup

### ISSUE THREAD

**Issue by sampow** [formly-js/ngx-formly#1271]
**I'm submitting a ...**
```
[ ] bug report 
[ ] feature request
[  #x] support request
```

**Current behavior**
I use the multi-step form with repeatable fieldGroup in a fieldArray.
What I try to do is validate the form  and disable the submit button if the form is invalid or if the fieldArray has no content or the repeatable fieldGroup is not fully completed  .
Right now I try to use required equal to true in the fieldArray but with no sucess
I also tried to use the validators but it won't update the whole form

**Expected behavior**
Be able to get the fieldGroup status (valid or invalid) from the "global" form to enable or disable the next or submit button

**Minimal reproduction of the problem with instructions**

I've made a stackblitz that reproduce my settings: https://stackblitz.com/edit/angular-kfmshi 

**How can i validate the form with a repeatable element  ?**

**Comment by aitboudad** [comment]
use `hideExpression` instead of changing `hide` manually https://stackblitz.com/edit/angular-kfmshi-vcbk6j

**Comment by sampow** [comment]
@aitboudad , thank you for your quick reply. 
Unfortunately I was not clear enough. I updated my stackblitz with your answer.
At step 3 , if you choose no, the button submit remain disabled, How do I track change of status (valid or invalid)  from   the investments repeat ?

Thank you

**Comment by aitboudad** [comment]
the `investment` validators should be placed under `repeat` field type or a parent field in order to track change of status see the following example: https://stackblitz.com/edit/angular-kfmshi-nib6at

**Comment by sampow** [comment]
@aitboudad thank you. it works !
