### ISSUE TITLE
select with icon

### ISSUE THREAD

**Issue by KhaledJNA** [formly-js/ngx-formly#1274]
thanks for ngx formly
is it possible to add an icon to a select componant ?

Thank you.

**Comment by aitboudad** [comment]
we only support bootstrap select, if you want something custom  you can create a custom select type by following our guide https://formly-js.github.io/ngx-formly/guide/custom-formly-field also you may check the select type code https://github.com/formly-js/ngx-formly/blob/master/src/bootstrap/src/lib/types/select.ts

**Comment by KhaledJNA** [comment]
Ok Thx ! 
I will try to do it
