### ISSUE TITLE
Material - TypeScript build error with AOT and TypeScript strict mode

### ISSUE THREAD

**Issue by klemenoslaj** [formly-js/ngx-formly#1276]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
When has strict mode configured (_`strict` flag in tsconfig.json_), AOT `build` or `serve` will fail with the following TypeScript error:

```
ERROR in node_modules/@ngx-formly/material/form-field/ngx-formly-material-form-field.d.ts.ɵa.html(16,23): : Element implicitly has an 'any' type because type 'FormlyFieldConfig' has no index signature.
node_modules/@ngx-formly/material/form-field/ngx-formly-material-form-field.d.ts.ɵa.html(20,23): : Element implicitly has an 'any' type because type 'FormlyFieldConfig' has no index signature.
node_modules/@ngx-formly/material/checkbox/ngx-formly-material-checkbox.d.ts.FormlyFieldCheckbox.html(7,7): : Object is possibly 'undefined'.
```

**Expected behavior**
Should build normally with AOT without the error when TypeScript strict mode enabled.

**Minimal reproduction of the problem with instructions**

Execute the following command:

```
git clone git@github.com:klemenoslaj/ngx-formly-aot-bug-report.git && cd ngx-formly-aot-bug-report && yarn && ng build --aot
```

Notice `ng serve` is triggered with `--aot` command. With JIT compiler it works fine.

**Please tell us about your environment:**
OS X `10.13.6`
VSCode `1.28.2`
Yarn `1.12.1`
Node `10.13.0`

* **Language:** TypeScript `3.1.6`

* **Node (for AoT issues):** `10.13.0`

**Comment by aitboudad** [comment]
use `skipLibCheck` option:

```
{
  "compilerOptions": {
    "skipLibCheck": true
  },
  ...
}
```

**Comment by klemenoslaj** [comment]
@aitboudad, thanks for quick reply.

Yes with this flag it works, was wondering if library should be working with strict mode out of the box.

**Comment by aitboudad** [comment]
right now there is no interest on working on this but I'd be happy to accept a PR

**Comment by klemenoslaj** [comment]
@aitboudad, soon I might find the time to do something about it.
How would you tackle the problem? Fixing just these few examples to be ok in `strict` mode, or adjusting the tsconfig of `ngx-formly`?

**Comment by aitboudad** [comment]
adjusting the tsconfig of ngx-formly

**Comment by klemenoslaj** [comment]
@aitboudad, I just had a short peek and enabling strict mode will require a huge amount of modifications. Do you still wish to go down that road?

---

After the recent update errors from the issue are gone, but more errors appear from the template compilation(skipLibCheck will not help here). I have updated the repo from the issue to demonstrate that.

Here is the related issue in Angular repo: angular/angular#21353
All angular projects with strict typescript configuration are affected.

**Comment by aitboudad** [comment]
@klemenoslaj you can split it in a small PRs to keep it simple.
for example, the following PR https://github.com/formly-js/ngx-formly/pull/1312 has been solved some part of it indirectly.

**Comment by klemenoslaj** [comment]
@aitboudad, I made my first attempt to convert `@ngx-formly/material` to strict tsc mode.
If I install `core` and `material` from locally build sources,  I do not get any errors any longer.

Can you however have a look if it is somehow ok? Especially keep a close eye on optional properties of `FormlyFieldConfig`. While properties were optional they were always expected to be there in code. I therefore added `!`  to it in most places.

https://github.com/klemenoslaj/ngx-formly/commit/7989dcd6b08b64c90ee2ce41fcb22ea123a4758a
