### ISSUE TITLE
cascaded-select JSON powered

### ISSUE THREAD

**Issue by mvanhelmont** [formly-js/ngx-formly#1278]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
I am trying to do a cascaded select field by JSON. But setting the onInit function with a string getting callback is not a function

**Expected behavior**
Posible to create cascaded select from JSON file.

I don't know if it is possible to create a cascaded select by json, I have tried the sample but copy it compleet to json make the json invalid. JSON.stringify strips out the methods.

Hope you can help me on my why. thanks already.

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-zwcyah-shd2cq
