### ISSUE TITLE
formly-form component overrides the formlyfieldConfig Created manually using builder.buildForm( ) method

### ISSUE THREAD

**Issue by thetinshusasi** [formly-js/ngx-formly#1284]
> > > ```ts
> > >   constructor(private builder: FormlyFormBuilder) {}
> > >   buildForm() {
> > >     this.builder.buildForm(this.form, this.fields, this.model ...
> > >   }
> > > ```
> > 
> > 
> > Could you please provide an stackblitz example in which we are manually building the form and not using formly-form component and still we are able to render with all its functionality
> 
> As the buidform() method in the formly-form component is executed again and its overriding the FormlyFieldConfig again

Please find a sample of the issue : https://github.com/thetinshusasi/NgxFormlyFormBuilderIssue

_Originally posted by @thetinshusasi in https://github.com/formly-js/ngx-formly/issues/1237#issuecomment-434615099_

**Comment by aitboudad** [comment]
for the focus issue I think it has been solved in v5 beta version.
in overall there is no guarantee of what you've asked for, if there is a specific case which we can take care (like focus issue) let us know.
