### ISSUE TITLE
Support for nested multi-step and / or multi-tabs or similar

### ISSUE THREAD

**Issue by kevinleawu** [formly-js/ngx-formly#1286]
**I'm submitting a ...**  (check one with "x")
[ ] bug report => search github for a similar issue or PR before submitting
[ X] feature request
[ ] support request
```

**Current behavior**
There are example for Multi_step and Tabs Forms but no example for nested levels forms navigation like a combination of multi-step and tabs or even better with multi-level side bar menu.

**Expected behavior**
Nested level form model with nested level form navigation menu (side bar, multi-step or tabs, etc).
Could Steps and Tabs or similar multi-level form navigation be done with Field Type of Wrapper so they can be part of Field Config?

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/angular/gxalnabmlmx?file=src%2Fapp%2Fapp.component.ts
https://stackblitz.com/angular/roxvbmejray?file=src%2Fapp%2Fapp.component.ts

**What is the motivation / use case for changing the behavior?**
Need a multi-level form navigation menu for a multi-level form model.  Here is an example of form model (only 2 levels for simplicity but could have more levels)

    {
        "root": {
            "category1": { //<!-- First level navigation -->
                "UserName": "Test1",
                "Address": "110 My street",
                "CreateDate": "2018-09-14T00:00:00"
            },
            "category2": { //<!-- First level navigation -->
                "section1": { //<!-- Second level navigation -->
                    "check1": "true",
                    "check2": "false",
                    "commentlist": {
                        "row": [{
                                "comment": "1.1"
                            },
                            {
                                "comment": "1.2"
                            }
                        ]
                    },
                    "photolist": {
                        "row": [{
                                "Photo1": "oqpNlRSsfwqqwqwq",
                                "caption1": "Flower",
                                "Photo2": "AnU5HPOP89z9aKKKGI//2Q==",
                                "caption2": "Bird"
                            },
                            {
                                "Photo1": "asasaassasas",
                                "caption1": "Flower",
                                "Photo2": "AnU5HPOP89z9aKKKGI//2Q==",
                                "caption2": "Bird"
                            }
                        ]
                    }
                }
            },
            "category3": { //<!-- First level navigation -->
                "section1": { //<!-- Second level navigation -->
                    //<!-- fields -->
                },
                "section2": { //<!-- Second level navigation -->
                    //<!-- fields -->
                },
                "section3": { //<!-- Second level navigation -->
                    //<!-- fields -->
                }
            }
        }
    }

**Please tell us about your environment:**
Windows, npm, VS code

* **Angular version:** 2.0.X
6.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
<!-- All browsers where this could be reproduced -->

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7
* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
providing a such example would require much time and I think that's something you should/can deal with it based on what we've already provided.

**Comment by kevinleawu** [comment]
I found an example with nested step/tabs form.  However, it is still saved to a flat model.  How do I saved it as a hierarchy model just like the multi-level structure of the form?
https://stackblitz.com/edit/angular-ngx-formly-gq7bmn?file=app%2Fapp.component.ts

I want the model to look like this:

    {
        "root": {
            "category1": { //
                "UserName": "Test1",
                "Address": "110 My street",
                "CreateDate": "2018-09-14T00:00:00"
            },
            "category2": { //
                "section1": { //
                    "check1": "true",
                    "check2": "false",
                    "commentlist": {
                        "row": [{
                                "comment": "1.1"
                            },
                            {
                                "comment": "1.2"
                            }
                        ]
                    },
                    "photolist": {
                        "row": [{
                                "Photo1": "oqpNlRSsfwqqwqwq",
                                "caption1": "Flower",
                                "Photo2": "AnU5HPOP89z9aKKKGI//2Q==",
                                "caption2": "Bird"
                            },
                            {
                                "Photo1": "asasaassasas",
                                "caption1": "Flower",
                                "Photo2": "AnU5HPOP89z9aKKKGI//2Q==",
                                "caption2": "Bird"
                            }
                        ]
                    }
                }
            },
            "category3": { //
                "section1": { //
                    //
                },
                "section2": { //
                    //
                },
                "section3": { //
                    //
                }
            }
        }
    }

**Comment by aitboudad** [comment]
use dotted key something like  `key: 'root.category1.UserName'` or using fieldGroup https://formly-js.github.io/ngx-formly/examples/other/nested-formly-forms

**Comment by kevinleawu** [comment]
Thank you so much.  I was not aware of dotted key.
