### ISSUE TITLE
Problem with async Object.assign model update and refresh the UI

### ISSUE THREAD

**Issue by GetTaxSolutions** [formly-js/ngx-formly#1295]
Hi,

I have a problem when load model from the server API which return observable with model. The problem is that the model is large and I'm using Object.assign to set loaded model. But when use this method with Observer.subscribe it not fill the UI fields with loaded values. The values are in the model but the fields are not populated and show them in empty state. 

* If I use Object.assign out of subscribe callback it's working properly.
* If I use direct set of model using '=' it's working in and out of the callback
* If I use Object.assign in callback and also set fields' definition there also is working properly.

I have created all cases in the example (look into the constructor):
[https://stackblitz.com/edit/angular-yufcr9?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-yufcr9?file=src%2Fapp%2Fapp.component.ts)

Thank you
GetTaxSolutions Ltd

**Comment by FritzHerbers** [comment]
You are using the same object (address), data is just merged into the object.
`Object.assign(self.model, { User: {FirstName:'First',LastName:'Last'} });`

The `@Input` fields `model `and `field ` have to change for formly to receive the changes from angular and act on those.

Try this:
```
const temp = {}
Object.assign(temp, { User: { FirstName: 'First', LastName: 'Last' } });
self.model = temp;
```

Or use the data from the http observable, where model is a new object:
```
this.model = model;
```

**Comment by aitboudad** [comment]
`Object.assign` doesn't change the model reference which angular rely on to detect changes, either use spread assign or `form.setValue`

1. this.model = { ...this.model, ...data };
2. form.setValue({ ...this.model, ...data });
3. this.options.resetModel({ ...this.model, ...data });

**Comment by GleidsonHenrique** [comment]
What if I'm using multi step form?

**Comment by aitboudad** [comment]
it should be the same for `model`, `options` and `form` should depend on the step index
