### ISSUE TITLE
Change model without resetModel function

### ISSUE THREAD

**Issue by davidoween** [formly-js/ngx-formly#1296]
Is it possible to reset the model, without resetModel ?, I do not want to mark the form as pristine and untouched because my error messages disappear.

**Comment by aitboudad** [comment]
just change the new value to the main model:
```ts
this.model = newData;
```

**Comment by davidoween** [comment]
but since when is this done? I use formly version 3

**Comment by aitboudad** [comment]
I think it should work with v3
