### ISSUE TITLE
Having options side by side

### ISSUE THREAD

**Issue by AliCharper** [formly-js/ngx-formly#1300]
If you look at this sample :
[https://stackblitz.com/edit/formly-css-pg-1ezeez?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/formly-css-pg-1ezeez?file=src%2Fapp%2Fapp.component.ts)

Options are vertically aligned very well, but I need them side by side. Is this possible ?.

Regards

**Comment by aitboudad** [comment]
just use a custom css class, if you mean horizontally then just remove `className`
