### ISSUE TITLE
compile custom view-only template 

### ISSUE THREAD

**Issue by ron-liu** [formly-js/ngx-formly#1302]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**
I try to introduce a custom template, which is for view only. When the template is static, it is ok, but if I try to introduce some angular operation, it doesn't work.
```
@Component({
  selector: 'my-app',
  template: `
    <form [formGroup]="form" (ngSubmit)="submit(model)">
      <formly-form [model]="model" [fields]="fields">
        <button type="submit">Submit</button>
      </formly-form>
    </form>

    {{ model|json }}
  `,
})
export class AppComponent {
  form = new FormGroup({});
  model = {};
  name = "John";
  fields: FormlyFieldConfig[] = [
    {template: `<div>{{name}}</div>`}, // <-- I expected to see John, but I saw {{name}}
    {
      key: 'name',
      type: 'input',
      templateOptions: {
        label: 'Field 1',
        placeholder: 'Formly is terrific!',
      },
    },
  ];

  submit(model) {
    console.log(model);
  }
}
```

**Expected behavior**
`ngx-formly` will compile the `template` before render.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
For example, when I am updating a user, I want to show the photo (not updatable) in the form, how can I achieve using current implementation? 

**Please tell us about your environment:**
MCOS 10.14.1

* **Angular version:** 2.0.X
6.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.9

* **Node (for AoT issues):** `node --version` =
10.11.0

**Comment by aitboudad** [comment]
see https://github.com/formly-js/ngx-formly/issues/640#issuecomment-356994765

**Comment by ron-liu** [comment]
@aitboudad Thanks for you reference, it works. 👍 

Another, is it possible to resolve observable? check [here](https://stackblitz.com/edit/ngx-formly-custom-template-asawaa) or the code below, Thanks.

```
export class AppComponent {
  form = new FormGroup({});
  model = {};
  name = of("John");
  fields: FormlyFieldConfig[] = [
    {
      type: 'template',
      templateOptions: {
        template: '',
      },
      expressionProperties: {
        'templateOptions.template': () => `
          <h4 class="panel-title">
            Employment Information: ${this.name}  
          </h4>
        `                                                                   // <-- is it possible to resolve name which is observable
      }
    },
    {
      key: 'name',
      type: 'input',
      templateOptions: {
        label: 'Field 1',
        placeholder: 'Formly is terrific!',
      },
    },
  ];
```

**Comment by aitboudad** [comment]
possible but only in v5 beta version:

```ts
'templateOptions.template': this.name.pipe(map(name => `<h4 class="panel-title">
   Employment Information: ${name}
</h4>`))     
```

**Comment by ron-liu** [comment]
Awesome, that is exactly what I want, thanks. It works, check [here](https://stackblitz.com/edit/ngx-formly-custom-template-asawaa)
