### ISSUE TITLE
pdf viewer template error state in form

### ISSUE THREAD

**Issue by enricooliva** [formly-js/ngx-formly#1304]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```
I build a template "pdfviewer" when I click button "open" all fields of form became in error state.
This is the stackbliz example: 
https://ngx-formly-ui-bootstrap-htuh7z.stackblitz.io

![image](https://user-images.githubusercontent.com/11843561/48831178-96feb980-ed76-11e8-8853-afeace8f4a47.png)

**Comment by aitboudad** [comment]
the default type for buttons inside a form is `submit` you should explicitly set type attr to avoid triggering submit:
```html
<button type="button" ...
```

**Comment by enricooliva** [comment]
Ops... I was to distracted to other stuff. Thank you.
