### ISSUE TITLE
pdf viewer add a formly-field

### ISSUE THREAD

**Issue by enricooliva** [formly-js/ngx-formly#1305]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

You think is possible substitute `<div>{{ filename }} </div>`  with a 
`formly-field`  inside the template constructed dynamically.

https://ngx-formly-ui-bootstrap-htuh7z.stackblitz.io

![image](https://user-images.githubusercontent.com/11843561/48833391-8d2b8500-ed7b-11e8-9cd5-a3985884a7e1.png)

**Comment by aitboudad** [comment]
it's better to avoid asking a lot of questions, that's something you should deal with it based on your knowledge else use stackoverflow.

sorry :pray:

**Comment by enricooliva** [comment]
@aitboudad ok, thank you for your time. 👍 
Eventually I will use stackoverflow.  👍 
My objective is to find faster and good solution.

**Comment by enricooliva** [comment]
I elaborate a solution
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-mcvzfp
one main template and two sub-templates

**Comment by aitboudad** [comment]
Thanks!
