### ISSUE TITLE
Add inputs dynamically with different dynamic labels (Not repeating fields) to an existing form.

### ISSUE THREAD

**Issue by darlontrofy** [formly-js/ngx-formly#1307]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

**Current behavior**

I have created a ngx form via JSON. When user selects a value in a dropdown, I make an async call and get values (labels) from an API and want to create DIFFERENT input fields with different labels and input fields. These are not repeated fields. How can I do this?
**Expected behavior**

Add distinct input fields with different dynamic labels to an existing form dynamically after initialization populated via an observable call.

**Minimal reproduction of the problem with instructions**

Bootstrap
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript
* **Node (for AoT issues):** `node --version` =

**Comment by devesh23** [comment]
@darlontrofy : I might have an answer for you but request @aitboudad to verify it. 

1) Create a custom component which extends FieldType
2) In that custom component, define an tag with ngFor and iterate all the new labels
3) Inside the tag with ngFor, Have different ng container tag with a ngIf attribute for all the different components. 
4) Utilize this component in your json.

Hope this answers your quesry

**Comment by darlontrofy** [comment]
Ok. I'm not sure I understand completely what you mean. I tried to update the fieldgroup array dynamically with new items, but when I submit, it does not handle validations and does not have the new input fields in the form. Hoping someone can provide a solution.

**Comment by aitboudad** [comment]
@darlontrofy could you please provide a stackblitz example that contains what you've done.

**Comment by darlontrofy** [comment]
@aitboudad this is what I did that seems to be working but I don't know if its right.

https://stackblitz.com/edit/angular-dpt2ui

**Comment by darlontrofy** [comment]
This solved my issue:

https://github.com/formly-js/ngx-formly/issues/1011

**Comment by BabaDorin** [comment]
I have another problem - I've got a nested form, which has the same properties and keys as the parent form. How to unlink inputs with the same key? I want them to have the same key, but the value to be different. Thank you!
