### ISSUE TITLE
Show loading icon and hide select when options are being loaded, and then show after loaded.

### ISSUE THREAD

**Issue by darlontrofy** [formly-js/ngx-formly#1308]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

**Current behavior**

I would like to hide the select dropdown on my form when the options are being loaded asynchronously, and only show then after they a re loaded. Currently, because there is a little delay, dropdown is empty. Is there an option to set this?
**Expected behavior**

Hide select field until observable returns with options for it.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Be more user friendly so user is not kept wondering why no options are available.
**Please tell us about your environment:**

* **Angular version:** 2.0.X

Angular 4
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
here is a simple example that shows you how you can deal with such case https://stackblitz.com/edit/angular-rqc6wa

**Comment by aitboudad** [comment]
another alternative is to use a custom wrapper https://github.com/formly-js/ngx-formly/issues/1090#issuecomment-428517547 instead of css class
