### ISSUE TITLE
update model not working ngx-datatable

### ISSUE THREAD

**Issue by ShashikantMaurya** [formly-js/ngx-formly#1309]
Hi, 

I am using ngx-datatable in formly, on cancel button click I am trying to reset row data(data might be modified by user), but model is not updating. please help me out.

I am performing CRUD operation using Ngx-Datatable.

 <ngx-datatable
      #table
      class="material"
      [rows]="model"
      [columns]="to.columns"
      [rowHeight] = "auto"
      [columnMode]="to.columnMode"     
      [headerHeight]="to.headerHeight"
      [footerHeight]="to.footerHeight"
      [limit]="to.limit"
      [scrollbarH]="to.scrollbarH"
      [reorderable]="to.reorderable"
      [externalSorting]="true"
      [sortType]="'multi'"
      [selectionType]="'checkbox'">
      <ng-template #genericcolumn ngx-datatable-cell-template let-rowIndex="rowIndex" let-value="value" let-row="row" let-column="column">
        <formly-field              
          [field]="getField(field,column, rowIndex)"
          [model]="getModel(model,column,rowIndex)"
          [options]="options"
          [form]="formControl">
        </formly-field>
      </ng-template>
      <ng-template #buttonTmpl let-row="row"  let-rowIndex="rowIndex" let-value="value" let-button="column.button">
         <button *ngIf="editing[rowIndex + '-edit']" class="btn btn-info btn-sm" type="button" (click)="$event.stopPropagation();edit(row,rowIndex);">
            <span>Edit</span>
         </button>
         <button *ngIf="editing[rowIndex + '-update']" class="btn btn-success btn-sm" type="button" (click)="$event.stopPropagation();update(rowIndex);">
            <span>Update</span>
         </button>
         <button *ngIf="editing[rowIndex + '-update']" class="btn btn-danger btn-sm" type="button" (click)="$event.stopPropagation();cancel(rowIndex);">
            <span>Cancel</span>
         </button> 
         <span></span>        
      </ng-template>      
    </ngx-datatable>    

  edit(row, rowIndex) {
    this.currentRowData = row;    
    this.editing[rowIndex + '-edit'] = false;
    this.editing[rowIndex + '-update'] = true;
  }

 cancel(rowIndex) {    
    this.model[rowIndex] = this.currentRowData;
    this.model = [...this.model];    
    this.editing[rowIndex + '-edit'] = true;
    this.editing[rowIndex + '-update'] = false;     
  }

 update(rowIndex) {    
    this.editing[rowIndex + '-edit'] = true;
    this.editing[rowIndex + '-update'] = false;
  }

**Comment by aitboudad** [comment]
can you show me the code that you use to update the model value

**Comment by ShashikantMaurya** [comment]
Hi aitboudad,

I have updated the code, basically I am performing crud operation,so whenever user clicks on edit button, he/she can see update & cancel button that allows user to update data, there might me chances when user edit some data and clicks cancel button, as we know making changes also reflact model object, so i want to undo user changes on cancel button by updating model object.

Please help me out:)

**Comment by aitboudad** [comment]
can't help without a reproduction example, sorry!

**Comment by aitboudad** [comment]
use 
```ts
  this.formControl.at(rowIndex).patchValue(model);
```

for a crud example see https://github.com/formly-js/ngx-formly/issues/1194#issuecomment-423947411

**Comment by ShashikantMaurya** [comment]
> use
> 
> ```ts
>   this.formControl.at(rowIndex).patchValue(model);
> ```
> 
> for a crud example see [#1194 (comment)](https://github.com/formly-js/ngx-formly/issues/1194#issuecomment-423947411)



> use
> 
> ```ts
>   this.formControl.at(rowIndex).patchValue(model);
> ```
> 
> for a crud example see [#1194 (comment)](https://github.com/formly-js/ngx-formly/issues/1194#issuecomment-423947411)

It worked for me, Thanks aitboudad for valuable time and support.
