### ISSUE TITLE
multiple listeners to focus event of the field

### ISSUE THREAD

**Issue by deexita** [formly-js/ngx-formly#1311]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request
```

**Current behavior**
 When field is focussed, we can provide focus implementation in field.templateOptions.focus. I have a wrapper that do something whenever field is focussed. For that field.templateOptions.focus is set to a function when wrapper is initialized. Now I want to give some specific focus implementation also to that field. Currently, the field focus implementation is getting overwritten with wrapper's one 

**Expected behavior**
How both implementations can be triggered on Focus? 

**Minimal reproduction of the problem with instructions**
**https://stackblitz.com/edit/angular-b7iga2**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
wrap the focus callback instead of overriding it:
```ts
  ngOnInit()
  {
    const fieldFocus = this.to.focus;
    this.to.focus = () => {
      console.log('wrapper level focus called');
      fieldFocus && fieldFocus();
    }
  }
```
