### ISSUE TITLE
How to add "hideExpression" for steps in multi step form?

### ISSUE THREAD

**Issue by lubkoKuzenko** [formly-js/ngx-formly#1314]
Documentation declare option "hideExpression: '!model.name'" for conditional questions rendering. Do we have the same functionality for steps in multi step form or how it's possible to implement it?

**Comment by aitboudad** [comment]
for step form, you can use `*ngIf`:
```html
<mat-step *ngFor="let step of steps; let index = index; let last = last;">
  <ng-container *ngIf="your_condition">
    ...
  </ng-container>
</mat-step>
```

**Comment by lartheon** [comment]
Sorry to bump this thread, but is there any example of e.g requiring a field within step 1 being filled in order to have step 2 visible? If the field is not filled then step 2 is hidden.

**Comment by kenisteward** [comment]
I don't have access to a computer right now but have you tried binding the
exact samw model and then simply using hideExpression looking for the first
field?

I could have sworn that was in the steps example as well.

**Comment by lartheon** [comment]
I made a work around, I just made sure everything in the next step was hidden unless a particular required field in the current step had been completed.

**Comment by aitboudad** [comment]
`Side note`: There is another approach to manage stepper where you can use `hideExpression` through a custom field type which you may check: https://stackblitz.com/edit/angular-yu7bzv-uucyxg

**Comment by paritosh291219** [comment]
Hello Aitboudad

Can i use customise model in multi step formly field. 
For eg when I clicked submit button i want to fill my own model. I want to fill value in defaultValue in formlyfieldconfig
