### ISSUE TITLE
Remove validation error in input field based upon value of another input field

### ISSUE THREAD

**Issue by devesh23** [formly-js/ngx-formly#1315]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ X ] support request
```

**Current behavior**

I have three fields. Field A, Field B and Field C. 

The sum of values in Field A and Field B should be equal to Field C. 
Its given that Field C will always have a value before hand. 

Lets suppose value of Field C is 10

When I enter value 5 in Field A, It displays the error that the sum is not equal to Field C (Expected)
When I enter value 5 in Field B, It does not display the error for Field B which is expected but the error which was displayed for Field A is still present. 

**Expected behavior**

Expected Behaviour should be that error for Field A should also disappear

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by devesh23** [comment]
@aitboudad : Please look into the same as it is quite urgent. It would be very grateful of you for the same

**Comment by aitboudad** [comment]
in that case, the validation should be defined in the parent field see [Matching Two Fields](https://formly-js.github.io/ngx-formly/examples/validation/matching-two-fields) example

**Comment by devesh23** [comment]
Let me modify it a bit. Suppose I enter 4 in Field B. Then it should show error in Field B which is expected. 

Now when I enter 5 in field B it would remove the error from Field B but not remove the error in Field A

**Comment by aitboudad** [comment]
could you provide a stackblitz example of what you've done

**Comment by aitboudad** [comment]
@devesh23 you didn't follow what I said in my previous comment, totalPercent should be defined in the parent field similar to the [Matching Two Fields](https://formly-js.github.io/ngx-formly/examples/validation/matching-two-fields) example

**Comment by devesh23** [comment]
@aitboudad Changed to reflect the same and the issue is still persistent

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-nr4cob-fz7vgz

**Comment by devesh23** [comment]
@aitboudad According to our requirement the message should be shown at the component level instead of at the field level. Is there any way to achieve the same behaviour but keep the message in component level

**Comment by aitboudad** [comment]
use `errorPath`:
```ts
expression: totalPercent,
message: 'Sum of all values should be equal to 6',
errorPath: '0.summableRepeatSection',
```

**Comment by devesh23** [comment]
@aitboudad This only works for the first repeat but when I add another repeat and add value 3 to it. The error does not get propogated

**Comment by aitboudad** [comment]
`errorPath` only allow passing a specific field, there is another solution which you can try by keeping the old way of validation and call `updateValueAndValidity` whenever the field change:
https://stackblitz.com/edit/angular-nr4cob-sr8mdw

**Comment by devesh23** [comment]
Even this is not working. When you enter 2 in the first repeat field. It shows an error and now when you enter 4 in second repeat field it does not show an error because sum is 6 but the error which was shown previously for first repeat field does not go away and is still present

**Comment by aitboudad** [comment]
well I've provided all possible cases, your case requires to set validation manually whenever field change here is a quick attempt https://stackblitz.com/edit/angular-nr4cob-tmlheq which you can try, the rest is up to you

**Comment by devesh23** [comment]
Thank you so much @aitboudad. It has been an eventful learning session! I'll try my best to contribute to formly and thus payback to the community for helping.
