### ISSUE TITLE
Material with formlyAttributes

### ISSUE THREAD

**Issue by klemenoslaj** [formly-js/ngx-formly#1317]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**What is the motivation / use case for changing the behavior?**

Every now and then I observe a strange minor glitch in how material components with ngx-formly. Some of them were already reported(#1281, #1277, #1276).

---

Latest issue I found is that `tabindex` is probably not provided to material components as expected.
Material checks for `tabindex` attribute, it does not have `tabindex` Input:

```
  constructor(elementRef: ElementRef<HTMLElement>,
              private _changeDetectorRef: ChangeDetectorRef,
              private _focusMonitor: FocusMonitor,
              private _ngZone: NgZone,
              @Attribute('tabindex') tabIndex: string, <<<<<-------- HERE
              @Optional() @Inject(MAT_CHECKBOX_CLICK_ACTION)
                  private _clickAction: MatCheckboxClickAction,
              @Optional() @Inject(ANIMATION_MODULE_TYPE) public _animationMode?: string) {
```

This means, that tabindex provided by `FormlyAttributes` does not reach this constructor:

```
host: {
    '[attr.name]': 'field.name',
    '[attr.placeholder]': 'to.placeholder',
    '[attr.tabindex]': 'to.tabindex || 0', <<<<-------- HERE
    '[attr.readonly]': 'to.readonly',
    '[attr.step]': 'to.step',
```

I am not 100% sure, but we might expect some issues because of that, since we are setting tab index in a way component does not expect.

Simplified demo of `[attr.tabindex]` and `@Attribute('tabindex')`: https://stackblitz.com/edit/angular-tbqg1t?file=src%2Fapp%2Fattr.directive.ts

---

In order to avoid all these issues it maybe makes sense not to use `[attr.]` for Material components, but add them directly to the component?

This will however not solve the `tabindex` issue, since Material seems to expect hardcoded value there?

**Comment by aitboudad** [comment]
Material is not fully compatible with `formlyAttributes` and the only valuable solution is to hardcode those attributes.

**Comment by devesh23** [comment]
Instead of defining the material components inside the formly library, one can define the component outside formly by extending field in component class. 

This way they would avoid the weird behaviour that material is causing when used along with formly

**Comment by klemenoslaj** [comment]
@aitboudad do I understand you right? In @ngx-formly/material we should remove formlyAttributes and add all the attributes manually to avoid further issues?

Or did you mean something different?

**Comment by aitboudad** [comment]
> we should remove formlyAttributes 

 keep formlyAttributes, and add `tabindex` attribute manually

**Comment by klemenoslaj** [comment]
But that will not solve the problem, will it?
Angular material uses @Atrribute decorator which just works with hardcoded attribute value. Id you use interpolation or binding, Material will not know about your tabindex.

Correct me if I'm wrong

**Comment by aitboudad** [comment]
sorry I see now what you mean, the real fix should be landed by the material itself (can you fill an issue in `material2` repo ?)

I'll try to add workaround for that when I have time.

**Comment by aitboudad** [comment]
just checked and it seems possible by passing `tabindex` input, would you like to send a PR ?
```ts
[tabindex]="to.tabindex"
```

**Comment by klemenoslaj** [comment]
Are you sure material actually acknowledges that? As far as I know `@Attribute()` decorator only takes the hardcoded value. It does nothing if you try interpolation or anything dynamic.

---

Here is the simple example: https://stackblitz.com/edit/angular-fem9sk

Having template in `app-two`:
```
<app-one [tabindex]="tabindex"></app-one>
```

And constructor in `app-one`:
```
constructor(@Attribute('tabindex') tabindex: string) {
  this.tabindex = parseInt(tabindex) || 0;
  console.log(this.tabindex);
}
```

Console.log here is logging `0` no matter what. `tabindex` will be null unless provided statically like `tabindex="1"`.

---

I actually noticed that issue because `mat-checkbox` behaves strange with tabindex from formlyAttributes. Quite funny, the side effect is that `touched` state is not adjusted correctly(_removing tabindex binding solves the issue completely_).

I will create a reproduction of this issue tomorrow(_it's late here :D _).

---

Regarding a PR...Yes  I would be happy to. But wanna first understand the real problem and align it with you.

**Comment by aitboudad** [comment]
see https://github.com/angular/material2/blob/master/src/lib/checkbox/checkbox.ts#L130

**Comment by klemenoslaj** [comment]
Woot! I totally missed that. Sorry for the confusion then :+1:
Not really used to look into `host:` so I just missed it.

---

Does it maybe makes sense to to the same for all the Material components and all the remaining attributes?
