### ISSUE TITLE
FieldArray Type repeater , assign value to one field on change of the other field in repeater

### ISSUE THREAD

**Issue by mihirhapaliya** [formly-js/ngx-formly#1318]
I have three fields in repeater , qty , cost and subtotal.
subtotal = qty * cost
I want to assign value to subtotal automatically based on the qty and cost changes.
how can we achieve that one ?

here is the project link to replicate 
https://stackblitz.com/edit/angular-uypkuw

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-2jcfs7
