### ISSUE TITLE
Coupling a field conditionally

### ISSUE THREAD

**Issue by sreyemnayr** [formly-js/ngx-formly#1319]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

I don't know how to do it, so it's not doing anything. I've tried playing with parsers and expressions to no avail.

**Expected behavior**

Given two fields, First Name and Preferred Name,
If Preferred Name is blank, on updating First Name (onBlur) it would assign the same value to Preferred Name. If it is not blank (a different name is actually preferred), leave it alone.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 7.1.1

* **Browser:** [all  ]

* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-lxghus

**Comment by sreyemnayr** [comment]
This is perfect, thank you so much @aitboudad ! Is there documentation somewhere on the templateOptions like blur that I missed?
