### ISSUE TITLE
Help on how to achieve double hideExpression

### ISSUE THREAD

**Issue by albertthinc** [formly-js/ngx-formly#1321]
Hi

Need your help

1. I am having a large form. List of fields applicable for a category will be retrieved from backend. Based on that list I have to display the fields.

Is there a way to do this in a generic way, like extending formly-field or fieldtransform

2. There can be some business logic for radio buttons. Using hideExpression for that. This should not get affected.

Thanks in advance

**Comment by albertthinc** [comment]
How to disable validation when I hide a field..?

Because for the above scenario, I used hide, but when hidden the validation is happening.

Thank you

**Comment by aitboudad** [comment]
> I am having a large form. List of fields applicable for a category will be retrieved from backend. Based on that list I have to display the fields.

see https://github.com/formly-js/ngx-formly/issues/1316#issuecomment-442497457
for a generic way you can use custom extension which is available in v5 beta see https://github.com/formly-js/ngx-formly/issues/1109#issuecomment-412295111

> There can be some business logic for radio buttons. Using hideExpression for that. This should not get affected.

can you provide a reproduction stackblitz example 

> How to disable validation when I hide a field..?

use hideExpression
