### ISSUE TITLE
hideExpression not work on repeat itself

### ISSUE THREAD

**Issue by HangLoop** [formly-js/ngx-formly#1324]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

In the reproduction, when you check the test checkbox, the input field 'name' is displayed, but the repeat section didn't display. I expect the repeat section should display as their hideExpression are the same.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-y4sgsy

**Comment by aitboudad** [comment]
for a workaround wrap it within a `fieldGroup`: https://stackblitz.com/edit/angular-y4sgsy-kgbjj7

**Comment by HangLoop** [comment]
And I am not sure why the hideExpression is working on repeat section on my project, just cannot reproduce in stackblitz. And I am using the same version of formly.

I got another problem which is the data is being cloned after the repeat section hide and show.
Steps:
1. added one section, so the screen got two sections. 
2. hide the repeat section
3. show the repeat section
4. the data from second section is cloned to the first section

Do you have any ideas? Thanks!

**Comment by aitboudad** [comment]
I've figured out why it doesn't work on repeat field see my comment https://github.com/formly-js/ngx-formly/issues/704#issuecomment-364661614

for the second issue that you've noticed, could you provide me a reproduction example

**Comment by HangLoop** [comment]
@aitboudad For the second issue,

https://stackblitz.com/edit/angular-y4sgsy-dzzhbk

Step to reproduce:
1. fill something in 'Name of Investment'
2. press Add another investment
3. check the test checkbox and uncheck it
4. both 'Name of Investment' will fill with the first 'Name of Investment' value on screen

The model didn't change, and seems the formControl of second repeat section cannot be created.
I am using v4.7.2, seems v5.0.0 beta17 doesn't have this issue.

I figured out a workaround to solve this, in the repeat custom type, I reset model after the repeat section is shown. (Please see below code) But I think it isn't a good practice. Do you have any recommendation to solve this problem? Thanks!
```
this.options.fieldChanges.subscribe(({ field, type, value }) => {
        if (type === 'hidden' && field.formControl && !value) {
          this.options.updateInitialValue();
          this.options.resetModel();
        }
      });
```

**Comment by aitboudad** [comment]
this can be only fixed using the `v5` approach, so I'd suggest upgrading into v5.0.0 beta17.

**Comment by HangLoop** [comment]
@aitboudad If I upgrade to v5.0.0 beta23, any break changes that I need to aware? Or any way I can check the break changes?

**Comment by aitboudad** [comment]
@HangLoop see https://github.com/ngx-formly/ngx-formly/blob/master/UPGRADE-5.0.md
