### ISSUE TITLE
MaskConfig with AOT

### ISSUE THREAD

**Issue by ShahanaFarooqui** [formly-js/ngx-formly#1329]
**I'm submitting a ...**  (check one with "x")
```
[] feature request
[x] support request
```

**Current behavior**
I am passing mask into formlyConfig as  mask: [/\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/]. 
and the application passes with JIT compilation but fails at AOT compilation with error message as:

ERROR in Error during template compile of 'AppModule'
  Expression form not supported in 'formlyConfig'
    'formlyConfig' contains the error at src\app\app.module.ts(21,22).

**Expected behavior**
The application should successfully compile with AOT.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-rnsqb1
The example is not working online but working locally.

pass type into config as below for FormlyModule.forRoot(config):
name: 'mask-input', component: MaskInputComponent,
        defaultOptions: {
          templateOptions: {
            maskConfig: {
              mask: [/\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/],
              showMask: false,
              guide: true
            }
          }
        }
And compile the application with 'ng build --aot'

**What is the motivation / use case for changing the behavior?**
AOT compilation

**Please tell us about your environment:**
OS: Windows,
IDE: VSC,
Package Manager: ng-packager

* **Angular version:** 2.0.X
Angular 7.0.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 

* **Node (for AoT issues):** `node --version` =
Node 10.13.0

**Comment by aitboudad** [comment]
Well, I think that an angular limitation (passing a regex value not allowed in config part), seems `text-mask` allow passing a function as the mask which solve the issue, see https://stackblitz.com/edit/angular-9adsnw
