### ISSUE TITLE
Stepper linear mode does not work as expected

### ISSUE THREAD

**Issue by cunundrummer** [formly-js/ngx-formly#1330]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

In linear mode of the multi-step form, we can still access the next steps. 
ex.  If on step1 (of 3), and we  click on the 3rd step, with linear mode set to true, we cannot get there - which is the proper behaviour.  However, if on step1, and we click on step2, we enter step2, which is bad.  Step1's next button remains disabled, yet we still can access step2 by clicking on the step header for step2.

**Expected behavior**

All following steps after activated should remain disabled when <mat-horizontal-stepper linear=true>.
See [material stepper overview](https://material.angular.io/components/stepper/overview) **and** enable linear mode on their example.

**Minimal reproduction of the problem with instructions**

[Formly's stackblitz](https://stackblitz.com/angular/qlmgoydrvkl?file=src%2Fapp%2Fapp.component.html)
Add **linear** to <mat-horizontal-stepper> --> <mat-horizontal-stepper **linear**>
Then try clicking on step3, back to 1, then to 2, then 3.
  

**What is the motivation / use case for changing the behavior?**
I want to ensure that the steps are secured.

**Please tell us about your environment:**

MacOS High Sierra 10.13.6 (17G3025)
WebStorm 2018.2 / Visual Studio
NPM 6.4.1
Node 10.8.0

* **Angular version:** 7.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Version 70.0.3538.110 (Official Build) (64-bit) 
Safari Version 12.0.1 (13606.2.104.1.2)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
just add `[stepControl]="form.at(index)"` and it should work https://stackblitz.com/edit/angular-4ywd54

**Comment by cunundrummer** [comment]
Thank you.  It seems I added it in the wrong place when I first tried.
