### ISSUE TITLE
No component factory found for ...

### ISSUE THREAD

**Issue by juristr** [formly-js/ngx-formly#1334]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

![image](https://user-images.githubusercontent.com/542458/49612421-fe3a8180-f9a4-11e8-9cc4-cbd02313fc82.png)

I'm basically having a lazy loaded module that uses `FormlyModule.forChild(...)` to register a custom formly type. It worked before `5.0.0-beta.19` but the change in #1333 seems to have broken it.
Adding my custom formly component to the `entryComponents` doesn't really solve the issue.

Usually this happens with dynamically instantiating components and lazy modules. Most probably this line is the reason

https://github.com/formly-js/ngx-formly/blob/d7db5f4d1327b772f636f49ab9c10d0db7d47777/src/core/src/lib/services/formly.form.builder.ts#L9

The `ComponentFactoryResolver` gets instantiated in the main app since it gets "imported" via `FormlyModule.forRoot()`, however the component that needs to be instantiated dynamically resides in a lazy loaded module. That's why it fails in my opinion. I had a similar issue with the CDK Dialogs. The service that instantiates the dynamic component needs to live in the same injector as the component itself. Lazy modules have their own inject, this is why it might break in this case

**Comment by aitboudad** [comment]
could you try to include `FormlyFormBuilder` in that loaded module:
```
  providers: [FormlyFormBuilder],
```

**Comment by juristr** [comment]
That works, yep. Because now the service creating the component is again in injector of the lazy loaded module 👍 . 
Not sure it's intuitive for the end-user though 😅 .

Oh btw, the bug intended to be solved in #1333 is solved now, great job.

**Comment by aitboudad** [comment]
``componentFactoryResolver`` is required to get the same behavior as building form through `formly-form`.

but I think we can avoid that by setting `FormlyFormBuilder` in [forChild](https://github.com/formly-js/ngx-formly/blob/master/src/core/src/lib/core.module.ts#L59) declaration

**Comment by juristr** [comment]
Yep, that could work
