### ISSUE TITLE
Optional disable of focus bubbling of the form-field wrapper

### ISSUE THREAD

**Issue by ThePenguin1140** [formly-js/ngx-formly#1337]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**
Sometimes a mat-input wrapped into the supplied form-field wrapper will be focused if the form-field element is focused. However, this results in some odd bugs where the input is focused but the focus event isn't fired on the input element. 

**Expected behavior**
Either the child will fire the appropriate events, or the parent form-field should not bubble focus events to disable it from focusing child elements.

**Minimal reproduction of the problem with instructions**
The problem use case is a custom mat-autocomplete that is supposed to open a panel of suggestions on focus. However, when wrapping it into the form-field wrapper there can be misclicks that don't focus the element but do focus it? Anyway, just click on the red that's above the green and you'll see how the focus is in the element. The onFocus function of that element was not called though, as you will see if you click into the green.
https://stackblitz.com/edit/angular-76hazm

**What is the motivation / use case for changing the behavior?**
Consistent behavior

* **Angular version:** 7.0.1

* **Browser:** all

* **Language:** TypeScript (other language not checked)

**Comment by ThePenguin1140** [comment]
One way that I've found that can fix this is to disable the focus bubbling of the `mat-form-field` so that clicking it doesn't focus the child. I wanted to know whether you guys were already aware of this or whether I should make a PR.

**Comment by aitboudad** [comment]
to use formly-form you have to extends `FieldType` from `@ngx-formly/material/form-field` instead check https://stackblitz.com/edit/angular-gsn6z7

**Comment by samtsai** [comment]
I am actually having the same issue specifically for autocomplete:
https://stackblitz.com/edit/angular-jnurbp?file=src%2Fapp%2Fautocomplete-type.component.ts

**Comment by samtsai** [comment]
Good idea, done #1385
