### ISSUE TITLE
Repeating section hide expression not working

### ISSUE THREAD

**Issue by deepak-saralaya** [formly-js/ngx-formly#1338]
Hi,

Here is below example 
https://stackblitz.com/edit/angular-rv7jtn-p88wog

Steps to Produce
1. Add Item
2. Click  checkbox (simply String)

Expected result when the checkbox is checked repeating section should show.

**Comment by aitboudad** [comment]
see https://github.com/formly-js/ngx-formly/issues/704#issuecomment-364661614

**Comment by deepak-saralaya** [comment]
Yes but i cant write Hide expression as a function because  JSON is coming from Server. Formly JSON created from Server side.

**Comment by aitboudad** [comment]
in your case, use `formState` as described in my comment:
```ts
  options = {
    formState: {
      : this.model,
    },
  };
  ....

 hideExpression:"!formState.mainModel['simpleString']",
```
