### ISSUE TITLE
How to bind url query params and ngx-formly

### ISSUE THREAD

**Issue by picomis** [formly-js/ngx-formly#1342]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

I am trying to bind the model from ngx-formly and angular router so that I can use browser forward / backward buttons. But when using forward and backward buttons ngx-formly is not redrawn.

**Expected behavior**

Ideally, I want to implement undo/redo with ngx-formly and query params.

**Minimal reproduction of the problem with instructions**

Small example: https://stackblitz.com/edit/ngx-formly-ui-bootstrap-qlyxqu

**What is the motivation / use case for changing the behavior?**

I use ngx-formly as a ui filter for tabular data.

**Please tell us about your environment:**

* **Angular version:** 7.0.1

**Comment by aitboudad** [comment]
formly expect a boolean value for `checkbox` type which is not the case of router params (string value),
so you just need to adjust `flattenObject`/`unflattenObject` to take account of boolean value

**Comment by picomis** [comment]
I created a more complex example similar to the one in my project. I try to use forward and backward buttons, but the form is not redrawn. Link: https://stackblitz.com/edit/angular-fmqvsc.
Thank you!

**Comment by aitboudad** [comment]
I don't think there is an issue in formly redraw, probably `dropdown-list` doesn't properly takes account of new changed values.

**Comment by picomis** [comment]
You're right, thanks!
