### ISSUE TITLE
Render Fields between radio button

### ISSUE THREAD

**Issue by deepak-saralaya** [formly-js/ngx-formly#1344]
Hi,

Can you guide me how to render fields between the radio button list?

check below link

https://stackblitz.com/edit/angular-2tdkxm-epnrzn

**Comment by aitboudad** [comment]
see https://github.com/formly-js/ngx-formly/issues/1122#issuecomment-412668610

**Comment by deepak-saralaya** [comment]
Yes

But I can't create a separate field (radio). Please check my formly JSON in 

https://stackblitz.com/edit/angular-2tdkxm-epnrzn

**Comment by aitboudad** [comment]
then create a separate service that can transform your config into the proposed one, or you have to define a custom field type that can deal with your config format.
