### ISSUE TITLE
Applying directive dynamically

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ngx-formly#253]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Expected behavior**
No way of attaching directives dynamically, suppose I want to use this third party library of masking https://www.npmjs.com/package/angular2-text-mask, I can't use it, except with the change in the input template.

I should be able to add it using field configuration. like ngModelAttrs in angular-formly.

**Comment by kavi87** [comment]
Thanks for your work on this. 

Do you have any progress on this feature ? Dynamic templates looks very hard in ng2. Maybe the ComponentFactoryResolver can be used to create dummy component dynamically for a given template while the formly module would expose a static method for registering all dynamic component to its entryComponent section.

**Comment by aitboudad** [comment]
not sure if there is a clean way for this right now, we should wait until https://github.com/angular/angular/issues/11716 is implemented

**Comment by aitboudad** [comment]
I'm going to close this issue since it's not actionable right now, we'll reopen this once fixed in angular side.

**Comment by AshMcConnell** [comment]
Is this possible now?  It would be great to be able to apply directives using formly

**Comment by aitboudad** [comment]
@AshMcConnell not possible, Angular doesn't support that yet.
