### ISSUE TITLE
Label wrapper should be able to render html-formatted string

### ISSUE THREAD

**Issue by hnguyenec** [formly-js/ngx-formly#428]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request
```

**Current behavior**

`<label [attr.for]="id" class="form-control-label">{{to.label}}</label>`
**Expected behavior**

`<label [attr.for]="id" class="form-control-label" [innerHtml]="to.label"></label>`
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
Hi, render an html in label is not a common use case and so instead we can introduce a new option that render html content WDYT ?

**Comment by hnguyenec** [comment]
Yep, html-label is a good option
Thanks

**Comment by aitboudad** [comment]
cancelled as it can be done using a custom wrapper.
