### ISSUE TITLE
Suggestion: provide better documentation

### ISSUE THREAD

**Issue by alexzaytsev-newsroomly** [formly-js/ngx-formly#509]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```

I suggest there is better documentation available for ng-formly for ng2+.
As it is really not clear what are the possible ```type``` values, and specifically are file inputs supported? I found examples for angularjs-formly but nothing for ng2+.

**What is the motivation / use case for changing the behavior?**
Reduce the learning curve for using the framework.

**Please tell us about your environment:**
Mac OS X Sierra

* **Angular version:** 4.3.6

* **Browser:** 
Chrome

**Comment by frettarenan** [comment]
I'm also having the same difficulty.
I'm thinking of writing some tutorials after I finish my study of this tool.

**Comment by jayasrinagrale** [comment]
There is absolutely no documentation. :(

**Comment by aitboudad** [comment]
it's in our priority now but don't expect anything soon, we have a limited time for open source projects.
in the meantime there are a plenty of examples in our [demo](https://github.com/formly-js/ng-formly/tree/v1/demo) and https://ng2.angular-formly.com that cover the most use cases. 
For ui templates we support bootstrap and recently we added material support too you may check the source code to have an idea of how to create you own ui templates or override the existing ones see https://github.com/formly-js/ng-formly/issues/531#issuecomment-337715530.

Also if you have any questions just left us an issue :wink:

**Comment by aitboudad** [comment]
http://angular-formly.com for angular.js can give you a quick intro

**Comment by jayasrinagrale** [comment]
I recommend that you prioritize documentation before adding any more features. That way you will be able to get more people to contribute to the project :)

**Comment by aitboudad** [comment]
@jayasrinagrale we're pretty close, the next step is #543

**Comment by byhoratiss** [comment]
I'm struggling with documentation, it's hard to understand all the examples if you dont know what means each property of the configuration.

**Comment by aitboudad** [comment]
@byhoratiss see http://formly-js.github.io/ng-formly/docs/interfaces/FormlyFieldConfig.html, each property has now a small description, we'll add an example for each one.

**Comment by aitboudad** [comment]
https://www.youtube.com/watch?v=WiljtPGZtW8

**Comment by aitboudad** [comment]
added two section in the docs ([Custom Templates](https://formly-js.github.io/ngx-formly/guide/custom-formly-field) and [Properties and Options](https://formly-js.github.io/ngx-formly/guide/properties-options)) + a bunch of [examples](https://formly-js.github.io/ngx-formly/examples/introduction).

**Comment by aitboudad** [comment]
close in favor of #820, that's the only part that prevent us to release `V2` any kind of help is welcomed!
