### ISSUE TITLE
Cleanup npm deploys

### ISSUE THREAD

**Issue by juristr** [formly-js/ngx-formly#540]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
If you search on Google for `ng-formly` you might end up in one of these places:

- https://www.npmjs.com/package/ng-formly
- https://www.npmjs.com/package/@ng-formly/core

but not necessarily on the correct one which is [this one](https://www.npmjs.com/package/@ngx-formly/core). I ran into this and it created quite some confusion 😅 .

The fix could be as simple as deploying a readme which says DEPRECATED with the link to the correct repository :). Wouldn't delete the it from npm as you never know who's using it. In the end I guess it's no more possible even to remove from npm.

Some other things I've noted always related to the npm deployed package

- Make sure to add some README.md to the npm publish of the final repository.
- publish the latest releases; on npm the latest one is alpha.8 while on GitHub it's already around beta.14

**What is the motivation / use case for changing the behavior?**

Less confusion for people :)

**Please tell us about your environment:**
Latest npm

Keep up the great work 👍

**Comment by aitboudad** [comment]
The `README.md` part was done by #538 and the deprecation is on the way ;)

**Comment by juristr** [comment]
@aitboudad cool 😄 , ya I was kinda confused as I saw the `1.0.0` in RC mode but then over npm I got `2.0.0` in alpha and saw a beta on the github repo 🤔 

😄
