### ISSUE TITLE
Move doc into demo-example

### ISSUE THREAD

**Issue by aitboudad** [formly-js/ngx-formly#543]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**

The [doc](https://github.com/formly-js/ng2.angular-formly.com) repo is not up to date and it's hard for us to maintain several repos without any real benefits
also I think it should be builded with angular similar to https://github.com/ng-bootstrap/ng-bootstrap/tree/master/demo/src

\cc @mohammedzamakhan

**Comment by aitboudad** [comment]
now we have auto deploy https://formly-js.github.io/ng-formly/

**Comment by davidoween** [comment]
https://formly-js.github.io/ng-formly/ no work

**Comment by aitboudad** [comment]
@davidoween see https://formly-js.github.io/ngx-formly

**Comment by aitboudad** [comment]
@mohammedzamakhan can you please point the domain https://ng.angular-formly.com/ to https://formly-js.github.io/ngx-formly

**Comment by donaldinho** [comment]
@aitboudad this domain doesn't seem to have been updated. The only reason I found out there were new docs was via this issue

**Comment by aitboudad** [comment]
ping @mohammedzamakhan :smile:
