### ISSUE TITLE
Values not populated when using hideExpression

### ISSUE THREAD

**Issue by sveatlo** [formly-js/ngx-formly#580]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

When formModel is loaded asynchronously (eg. editing some data from server) and the form uses `hideExpression` on some of its fields, values for these fields don't get populated to form.

**Expected behavior**

Values from the model should be available in the form.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-jjhxfl

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.3.6 and 5.0.2

* **Browser:** all

 
* **Language:** TypeScript 2.4.2

* **Node (for AoT issues):** `node --version` =   v9.2.0

**Comment by aitboudad** [comment]
neither model nor validation are applied when combining `hideExpression`  with the `key`, you can achieve your use case using `fieldGroup`:
```ts
    {
      hideExpression: 'model.group_id !== "3"',
      fieldGroup: [
        {
          type: 'input',
          key: 'group.demo_input',
          templateOptions: {
            label: 'Demo input'
          },
        }
      ]
    }
```

**Comment by aitboudad** [comment]
well I think this is bug and the new model value should be taken into account
