### ISSUE TITLE
ExpressionProperty for required property issue

### ISSUE THREAD

**Issue by Constantinos-Impact** [formly-js/ngx-formly#582]
**I'm submitting a ...** 

[ x] bug report
[ ] feature request
[ ] support request

**Current behavior**
Seems that the expressionProperty for the required rule does not behave as expected. 

**Minimal reproduction of the problem with instructions**
You can find a plunker example demonstrating the problem  https://plnkr.co/edit/k46yzLpBngBO3AnfIPld?p=preview

**Please tell us about your environment:**
I am using latest formly version v2.0.0-beta.8

* **Angular version:** 4.2.4

* **Browser:**  Chrome Version 62.0.3202.94 (Official Build) (64-bit) 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v6.11.4

**Comment by aitboudad** [comment]
@Constantinos-Impact  can you elaborate more about the expected behavior ?

**Comment by Constantinos-Impact** [comment]
@aitboudad sorry for the late reply.  Did you manage to reproduce the issue? 
Thanks

**Comment by aitboudad** [comment]
@Constantinos-Impact fixed in `2.0.0-rc.1`
