### ISSUE TITLE
KendoUI for Angular support

### ISSUE THREAD

**Issue by GreenAirplane** [formly-js/ngx-formly#599]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```

Hello, we are considering to use formly but we need to use it with kendoui (https://www.telerik.com/kendo-angular-ui/). It looks like we can relatively quickly implement its support for formly, so my question is would you consider adding support of kendoui (like bootstrap and material)? In this case, we can submit a PR with it.

**Comment by aitboudad** [comment]
why not, PR welcomed!
