### ISSUE TITLE
Problem with the new way of select store

### ISSUE THREAD

**Issue by Gaedr** [formly-js/ngx-formly#601]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
Actually in the new version, before adding the multiselect, the value of the singular select is stored as array with one value instead a non array value.

**Expected behavior**
Store the value select, with no multiple active, as non array value.

**What is the motivation / use case for changing the behavior?**
I've a lot of code implemented using the old way select store and I don't want to rewrite that code.

* **Angular version:** 4.1.3

**Comment by aitboudad** [comment]
fixed in `2.0.0-rc.3`, demo: https://formly-js.github.io/ngx-formly/examples/bootstrap-formly/select
