### ISSUE TITLE
Material labels do not show an asterisk when required as the bootstrap elements do

### ISSUE THREAD

**Issue by dwaldrum** [formly-js/ngx-formly#604]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
When using the material design, form elements that are required do not have an asterisk.

**Expected behavior**
Elements that are required should show an asterisk as they do with the bootstrap module.

**Minimal reproduction of the problem with instructions**
https://angular-dece1p.stackblitz.io

**What is the motivation / use case for changing the behavior?**
Fixing 

**Please tell us about your environment:**
Windows 10
WLS Ubuntu
Visual Studio Code

* **Angular version:** 5.0.0
* **Ngx-formly version:** 2.0.0-rc.3

* **Browser:**
All
 
* **Language:**
All

**Comment by aitboudad** [comment]
let me know if you want to work on this,  change should be made at: [form-field](https://github.com/formly-js/ngx-formly/blob/master/src/ui-material/src/wrappers/form-field.ts#L15)
similar to bootstrap [label](https://github.com/formly-js/ngx-formly/blob/master/src/ui-bootstrap/src/wrappers/label.ts#L9)

**Comment by davewaldrum** [comment]
I've already fixed it and I want to put a PR up for it, but I'm running into an issue trying to test formly as I work on it with material.

First off, I can't npm link the library to an angular project to test it as I work.

Second, I wanted to update the documentation (examples) to add material ui examples. If you take any of the examples, and swap out the bootstrap module for the material one, you get an error:

'mat-label' is not a known element:

I've tried including the material modules that are required in the example's module file, but nothing seems to work. I'm still not 100% up to speed with Angular's new module system so maybe you could shed some light on this.

Once I can figure that these out, I can help add material examples to the documentation and it would make working on any features in regards to material easier.

**Comment by aitboudad** [comment]
> First off, I can't npm link the library to an angular project to test it as I work.

you should go into `dist` folder and link the package you wish to include.

> Second, I wanted to update the documentation (examples) to add material ui examples. If you take any of the examples, and swap out the bootstrap module for the material one, you get an error: 'mat-label' is not a known element:

yep it's a known issue, that's why I didn't include it in doc example, material require angular `5.0`, if you want to check it just update all @angular package into `v5` and it should work!
