### ISSUE TITLE
Nativescript support

### ISSUE THREAD

**Issue by aitboudad** [formly-js/ngx-formly#610]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**

initial work https://github.com/formly-js/ng-formly-nativescript

**Comment by geraldapeoples** [comment]
@aitboudad Hi Abdellatif, is it still on the roadmap to support Nativescript?

**Comment by aitboudad** [comment]
@geraldapeoples yes still on the roadmap with a low priority for now :)

**Comment by geraldapeoples** [comment]
@aitboudad thank you for the update, I will have a look at the original plugin and see if I can get my head around it, if so then hopefully I can contribute

**Comment by aitboudad** [comment]
I've played with text field type a little bit, so let me to push an initial work and then you can follow the same direction for other types

**Comment by geraldapeoples** [comment]
Cheers :)

**Comment by aitboudad** [comment]
Done, to give it a try in a nativescript app:

1. install npm packages
```
npm install @ngx-formly/core @ngx-formly/nativescript@0.0.1 --save
```
2. import `FormlyModule`:
```ts
import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";

import { ReactiveFormsModule } from '@angular/forms';
import { FormlyModule } from '@ngx-formly/core';
import { FormlyNativescriptModule } from '@ngx-formly/nativescript';

import { AppComponent } from "./app.component";

@NgModule({
  declarations: [AppComponent],
  bootstrap: [AppComponent],
  imports: [
    NativeScriptModule,

    ReactiveFormsModule,
    FormlyNativescriptModule,
    FormlyModule.forRoot({
      validationMessages: [
        { name: 'required', message: 'This field is required' },
      ],
    }),
  ],
  schemas: [NO_ERRORS_SCHEMA],
})
export class AppModule {}
```

3. edit `app.component.ts`

```ts
import { Component } from "@angular/core";
import { FormGroup } from '@angular/forms';
import { FormlyFormOptions, FormlyFieldConfig } from '@ngx-formly/core';

@Component({
  selector: "my-app",
  template: `
    <ActionBar title="Ngx Formly" class="action-bar"></ActionBar>
    <StackLayout class="form" sdkExampleTitle sdkToggleNavButton>
      <form [formGroup]="form">
        <formly-form [model]="model" [fields]="fields" [options]="options" [form]="form">
        </formly-form>
      </form>
    </StackLayout>
  `
})
export class AppComponent {
  // Your TypeScript logic goes here
  form = new FormGroup({});
  model: any = {};
  options: FormlyFormOptions = {};
  fields: FormlyFieldConfig[] = [
    {
      key: 'firstname',
      type: 'text-field',
      templateOptions: {
        label: 'firstname',
        hint: 'TEST',
        required: true,
      },
    },
  ];
}
```
### Output
![selection_143](https://user-images.githubusercontent.com/1753742/42708875-77eea138-86d6-11e8-88ae-01f53fd0bd50.png)

**Comment by aitboudad** [comment]
@geraldapeoples right now only `field-text` is supported the source code is in https://github.com/formly-js/ngx-formly/tree/master/src/nativescript/text-field,  all new types should follow the same way so it up to you now :) for adding more features.

**Comment by amoswachanga** [comment]
Hi @aitboudad, thanks for this. 
Could you please advise if to add the additional field types/question types, whether on Nativescript we can still do the same as on the web version similar to the [date picker example here](https://stackblitz.com/edit/angular-formly-datepicker?file=app%2Fapp.module.ts); or is there a recommended way?

**Comment by amoswachanga** [comment]
Another question, could you advice how can I get the reference classes for the labels and the actual field?

**Comment by aitboudad** [comment]
@amoswachanga your last question is not clear could you elaborate please and for ` datepicker` basically it should be similar
