### ISSUE TITLE
Support for Nested Forms.

### ISSUE THREAD

**Issue by kritisoft** [formly-js/ngx-formly#613]
**I'm submitting a ...**  (check one with "x")
```
[ X] support request
```

I would like to know , if the ngx-formly support nested forms available in angular 1 . 
If yes , It would be helpful if a documentation of the same can be added .

**Comment by aitboudad** [comment]
yep it's supported

**Comment by kritisoft** [comment]
any plunker or documentation  which illustrates the same ?

**Comment by aitboudad** [comment]
basically the same, I'm on it!

**Comment by kritisoft** [comment]
Thanks , and Good work .. !!

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-jtvczd

**Comment by aitboudad** [comment]
TODO: 
- [ ] add example in our demo.
