### ISSUE TITLE
Material Auto-Complete

### ISSUE THREAD

**Issue by subratawebops** [formly-js/ngx-formly#615]
Even I don't see any autocomplete support. If you are providing one could you please provide the documentation.

**Comment by aitboudad** [comment]
the same as  https://github.com/formly-js/ngx-formly/issues/614#issuecomment-354092281, but not sure if this will part of our ui,

**Comment by aitboudad** [comment]
fixed by #903

**Comment by somnathswami** [comment]
@aitboudad can you please add demo application with observable for formly autocomplete

**Comment by aitboudad** [comment]
@somnathswami sorry nop, you have enough info to made it by yourself :)

**Comment by juristr** [comment]
@somnathswami in case: https://formly-js.github.io/ngx-formly/examples/other/observable-select
