### ISSUE TITLE
Material Checkbox & Radio type creates textbox

### ISSUE THREAD

**Issue by subratawebops** [formly-js/ngx-formly#616]
![capture_190](https://user-images.githubusercontent.com/15680580/34376337-426d795a-eb11-11e7-977e-82aa4e61b71f.PNG)

```
{
            key: 'awesome',
            type: 'checkbox',
            templateOptions: { label: '' },
            expressionProperties: {
              'templateOptions.disabled': 'formState.awesomeIsForced',
              'templateOptions.label': (model, formState) => {
                if (formState.awesomeIsForced) {
                  return 'Too bad, formly is really awesome...';
                } else {
                  return 'Is formly totally awesome? (uncheck this and see what happens)';
                }
              },
            },
          }
```

**Comment by aitboudad** [comment]
I'm waiting for material issue  https://github.com/angular/material2/issues/7891 to be solved, I guest the underline should be hidden right ?

**Comment by subratawebops** [comment]
@aitboudad Yes, the underline should be hidden. Thank you

**Comment by aitboudad** [comment]
I'll look into it later, in the meantime you can hide it using css

**Comment by abdelhadibentabet** [comment]
Fix not working when appearance: "outline"
Same thing must be done for "mat-form-field-outline" class
