### ISSUE TITLE
Custom Validation

### ISSUE THREAD

**Issue by DSaralaya** [formly-js/ngx-formly#617]
How can we write below code in formly 2?.

Below fromly  Json is coming from the server.
{
	"key": "mileage__c",
	"type": "mileage",
	"className": "col-md-6",
	"templateOptions": {
	  "label": "mileage",
	  "required": true
	},
	"data":{
	  "maxValue":200,
	  "ValidationMessage":"Max mileage is 200"
	}
}

 this is my config type.

formlyConfig.setType({
        name: 'mileage',
        extends: 'input',
        defaultOptions: {
          validators: {
            mileage: function($viewValue, $modelValue, scope) {
              var value = $modelValue || $viewValue, valid = true;
              if (value > scope.options.data.maxValue) { valid = false; }
              return valid;
            }
          },
          validation: {
            messages: {
              mileage: function (viewValue, modelValue, scope) {
                return scope.options.data.ValidationMessage;
              }
            }
          }
        }
      });

**Comment by aitboudad** [comment]
Please ensure to upgrade into `2.0.0-rc.5`, here is an example: https://stackblitz.com/edit/angular-8bdmfg
