### ISSUE TITLE
On Hide Clear value

### ISSUE THREAD

**Issue by DSaralaya** [formly-js/ngx-formly#620]
How can  write below code in formly2

Formly JSON
{
  key: 'FundingType__c',
  type: 'input',
  className: 'col-md-3',
  templateOptions: {
	required: true,
	label: 'Funding Type',
	fieldName:'FundingType__c'
  }
},
{
  key: 'Amount__c',
  type: 'currency',
  className: 'col-md-3',
  hideExpression: '!model.FundingType__c',
  templateOptions: {
	required: true,
	label: 'Amount',
	fieldName:'Amount__c'
  }
}

Config type

  formlyConfig.setType({
        name: 'currency',
        extends: 'input',
        defaultOptions: {
          extras: {
            validateOnModelChange: true
          },
	 modelOptions: {
            updateOn: 'change'
          },
	 ngModelAttrs: {
            customAttrVal: {
              attribute: 'ng-currency'
            }
          },
          templateOptions: {
            customAttrVal: ''
          },
          validators: {
            validFund : function ($viewValue, $modelValue, scope) {
              return scope.Check($viewValue);
            }
          },
          validation: {
            validFund: function (viewValue, modelValue, scope) {
              return 'Insufficient funds.';
            }
          }
        },
        controller: ['$scope', 'callExternalMethod', function($scope, callExternalMethod) {
		   var fieldName = $scope.to.fieldName;
		   $scope.Check=function(amount)
		   {
		      if(amount===1)
			  {
			    return true;
			  }
			  else{
			     return false;
			  }
		   }
		   $scope.$on('$destroy', function() { $scope.model[fieldName] = ''; });
        }
      ]});

**Comment by aitboudad** [comment]
hideExpression can be passed as a function which allow you can clear model value,
see the example https://stackblitz.com/edit/angular-qgposz, hi

**Comment by DSaralaya** [comment]
Yes, it will work but still, validation error message will be there.If its possible remove error message.

**Comment by aitboudad** [comment]
validation are shown if the field is touched or the form is submitted you can override the default behavior by passing an extra option in the form module the default value is https://github.com/formly-js/ngx-formly/blob/master/src/core/src/services/formly.config.ts#L38-L40:

```ts
FormlyModule.forRoot({
  extras: {
    showError: customShowError
  }
})
```

but you can do some tweaks to achieve your needs, I updated the above example https://stackblitz.com/edit/angular-qgposz?file=app%2Fapp.component.ts

if you have a better suggestion/proposal feel free to open a new issue!

**Comment by DSaralaya** [comment]
Can we do the same thing in Component instead of Formly JSON?

In the below code When fields hides, it clears the value, but when make  mark as Untouched
getting error 'ExpressionChangedAfterItHasBeenCheckedError:'

@Component({
  selector: "formly-field-input",
  template: `
    <input   [type]="type" [maxlength]="maxlength" [formControl]="formControl" class="form-control"  [formlyAttributes]="field" > `
})

export class FormlyInput extends FieldType  {
  constructor(private _cdr: ChangeDetectorRef) {
    super();
 }
  get type(): string {
    return this.to.type || "text";
  }

  get maxlength(): number {
    return this.to["maxlength"];
  }
  
  ngAfterContentChecked() {
    if(this.to.hidden)
    {
      this.model[this.to['fieldName']]='';
      (this.options.parentForm as any).submitted = false;
       this.form.markAsUntouched();
       this._cdr.detectChanges();
    }
  }
}

**Comment by aitboudad** [comment]
You can add `setTimeout` to make it work but I don't prefer to go with that way, there is another option that will help you to achieve your need:
```ts
this.options.fieldChanges.subscribe(({field, type, value}) => {
  if (type === 'hidden' && field.formControl && value) {
    field.formControl.setValue(null);
    (this.options.parentForm as any).submitted = false;
    this.form.markAsUntouched();
  }
});
```

**Comment by DSaralaya** [comment]
I added above code. But still, it not removing validation error message.

**Comment by DSaralaya** [comment]
Temparary i added below code it worked for me.IF you have any better solution please suggest.

export function showErrorOption(field) {
	if (field.to.hidden==true) {
		field.formControl.setValue(null);
		field.formControl.markAsUntouched();
	}
	return (field.formControl.touched || (field.field.validation && field.field.validation.show)) && !field.formControl.valid;
}

**Comment by aitboudad** [comment]
I think it's something we should support by default but I couldn't find a better approach right now :(

**Comment by aitboudad** [comment]
I'll look into it later

**Comment by augustas1** [comment]
@aitboudad Hi, I like this approach you suggested:
```typescript
this.options.fieldChanges.subscribe(({field, type, value}) => {
  if (type === 'hidden' && field.formControl && value) {
    field.formControl.setValue(null);
    (this.options.parentForm as any).submitted = false;
    this.form.markAsUntouched();
  }
});
```
But if I want to do this for all fields, do you have a suggestion how could I subscribe to fieldChanges in root component (the one which has formly form)? Because formly don't have any onLoad event, and I don't know when fieldChanges Subject is already created.

**Comment by aitboudad** [comment]
you can initialize options or use life-cycle hooks in a field config:

```ts
options = {
  fieldChanges: new Subject(),
  ...
}
```

> Because formly don't have any onLoad event

any proposal is welcomed, just fill an issue with more details :)
