### ISSUE TITLE
Configuring Field Config From Webservice.

### ISSUE THREAD

**Issue by kritisoft** [formly-js/ngx-formly#621]
**I'm submitting a ...**  (check one with "x")
[X ] support request

**Current behavior**
`
    steps: any[] = [
    {
      label: 'Personal data',
      fields: [
        {
          key: 'firstname',
          type: 'input',
          templateOptions: {
            label: 'First name',
            required: true,
          },
        },
        {
          type: 'input',
          key: 'middleName',
          templateOptions: {
            label: 'Middle Name',
          },
        },
        {
          key: 'age',
          type: 'input',
          templateOptions: {
            type: 'number',
            label: 'Age',
            required: true,
          },
        },
      ],
    }
    ,
    {
      label: 'Destination',
      fields: [
        {
          key: 'country',
          type: 'input',
          templateOptions: {
            label: 'Country',
            required: true,
          },
        },
      ],
    },
    {
      label: 'Day of the trip',
      fields: [
        {
          key: 'day',
          type: 'input',
          templateOptions: {
            type: 'date',
            label: 'Day of the trip',
            required: true,
          },
        },
      ],
    },
    {
      label: 'Sub Form',
      fields: [
        {
          fieldGroupClassName: 'row',
          fieldGroup: [
            {
              className: 'col-md-6',
              type: 'input',
              key: 'firstName',
              templateOptions: {
                label: 'First Name',
              },
            },
            {
              className: 'col-md-6',
              type: 'input',
              key: 'lastName',
              templateOptions: {
                label: 'Last Name',
              },
              expressionProperties: {
                'templateOptions.disabled': '!model.firstName',
              },
            },
          ],
        },
        {
          className: 'section-label',
          template: '<hr /><div><strong>Address:</strong></div>',
        },
        {
          fieldGroupClassName: 'row',
          fieldGroup: [
            {
              className: 'col-md-6',
              type: 'input',
              key: 'street',
              templateOptions: {
                label: 'Street',
              },
            },
            {
              className: 'col-md-3',
              type: 'input',
              key: 'cityName',
              templateOptions: {
                label: 'City',
              },
            },
            {
              className: 'col-md-3',
              type: 'input',
              key: 'zip',
              templateOptions: {
                type: 'number',
                label: 'Zip',
                max: 99999,
                min: 0,
                pattern: '\\d{5}',
              },
            },
          ],
        },
        { template: '<hr />' },
        {
          type: 'textarea',
          key: 'otherInput',
          templateOptions: {
            label: 'Other Input',
          },
        },
        {
          type: 'checkbox',
          key: 'otherToo',
          templateOptions: {
            label: 'Other Checkbox',
          },
        },
        {
          key: 'sport',
          type: 'select',
          templateOptions: {
            label: 'Sport',
            options: [
              { id: '1', name: 'Soccer' },
              { id: '2', name: 'Basketball' },
            ],
            valueProp: 'id',
            labelProp: 'name',
          },
          lifecycle: {
            onInit: (form, field) => {
              field.formControl.valueChanges.subscribe(v => {
                form.get('team').setValue('');
              });
            },
          },
        },
        {
          key: 'team',
          type: 'select',
          templateOptions: {
            label: 'Team',
            options: [],
            valueProp: 'id',
            labelProp: 'name',
          },
          expressionProperties: {
            'templateOptions.options': (model) => {
              const teams = [
                { id: '1', name: 'Player1', sportId: '1' },
                { id: '2', name: 'Player2', sportId: '1' },
                { id: '3', name: 'Player3', sportId: '2' },
              ];

              return teams.filter(team => team.sportId === model.team);
            },
          },
          lifecycle: {
            onInit: (form, field) => {
              field.formControl.valueChanges.subscribe(v => {
                form.get('player').setValue('');
              });
            },
          },
        },
        {
          key: 'player',
          type: 'select',
          templateOptions: {
            label: 'player',
            options: [],
            valueProp: 'id',
            labelProp: 'name',
          },
          expressionProperties: {
            'templateOptions.options': (model) => {
              const players = [
                { id: '1', name: 'Bayern Munich', playerId: '1' },
                { id: '2', name: 'Real Madrid', playerId: '1' },
                { id: '3', name: 'Cleveland', playerId: '2' },
              ];

              return players.filter(player => player.playerId === model.team);
            },
          }
        },
        {
          key: 'investments',
          type: 'repeat',
          fieldArray: {
            fieldGroupClassName: 'row',
            templateOptions: {
              btnText: 'Add another investment',
            },
            fieldGroup: [
              {
                className: 'col-sm-4',
                type: 'input',
                key: 'investmentName',
                templateOptions: {
                  label: 'Name of Investment:',
                  required: true,
                },
              },
              {
                type: 'input',
                key: 'investmentDate',
                className: 'col-sm-4',
                templateOptions: {
                  type: 'date',
                  label: 'Date of Investment:',
                },
              },
              {
                type: 'input',
                key: 'stockIdentifier',
                className: 'col-sm-4',
                templateOptions: {
                  label: 'Stock Identifier:',
                  addonRight: {
                    class: 'fa fa-code',
                    onClick: (to, fieldType, $event) => console.log(to, fieldType, $event),
                  },
                },
              },
            ],
          },
        }
      ],
    }
  

The Above Field Config is working when i am declaring it in the component file.

I Need 3 Clarification required .

1. I have an Cascading List , which is of three level , but the example shown in the Demo App is of two , Can you help me with Three or 4 Level of cascading list.

2. How do we populate the above Field config from a Web Service with the expression property and lifecycle.

3. Also is it possible to do a Expression property with some calculation like field3 = field1+field2 .

Please Provide a Example or a way to resolve these.

**Comment by Ore4444** [comment]
@kritisoft try to wrap your code snippet with ``` so that it's readable

**Comment by aitboudad** [comment]
1. updated in the doc example see https://formly-js.github.io/ngx-formly/examples/other/cascaded-select
2. the obvious answer is to parse and edit the config after http call, see the example https://stackblitz.com/edit/angular-tns2ve which update the select options it can give you an idea of how to do it.
3. yes, `expressionProperties` can be a function which allows you to do what you want
