### ISSUE TITLE
Checkbox required validtion not working

### ISSUE THREAD

**Issue by DSaralaya** [formly-js/ngx-formly#623]
Check below formly JSON

 {
      key: 'Agree__c',
      type: 'checkbox',
      className: 'col-md-3',
      templateOptions: {
        required: true,
        label: 'Funding Type',
        fieldName:'Agree__c'
      }
    },

1) Its not showing asetrick(*) mark
2) When uncheck the chekbox not showing validation

**Comment by aitboudad** [comment]
1. fixed by #624
2. you have to use `requiredTrue` validator see: https://stackblitz.com/edit/angular-euheew:
```ts
      validators: {
        validation: [Validators.requiredTrue],
      },
```

**Comment by DSaralaya** [comment]
But How can I write custom validation, I need Different error message.
In the below example how can write a custom message?
https://stackblitz.com/edit/angular-8bdmfg

**Comment by aitboudad** [comment]
@DSaralaya you can pass the error message globally in the module declaration [required message](https://github.com/formly-js/ngx-formly/blob/master/demo/src/app/examples/introduction/app.module.ts#L17)
or define it in the form field config using `validation` entry:

```ts
validation: {
  messages: {
    required: 'This field is required',
  },
},
```
