### ISSUE TITLE
ngx-formly/material Docs

### ISSUE THREAD

**Issue by nithinar** [formly-js/ngx-formly#627]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[] support request
```

**Current behavior**
ngx-formly/material functionalities not provided in docs

**Expected behavior**
Need documentation for ngx-formly/material

**Minimal reproduction of the problem with instructions**

I am trying to implement datepicker and autocomplete functionality using FormlyMaterial. I have checked the link for datepicker (https://stackblitz.com/edit/angular-gkwj6z), but it is difficult to understand without any docs for it. 
Also, kindly suggest as to how to implement custom buttons in angular formly.

Kindly provide the latest link to ngx-formly/material docs or if it is not released yet, kindly mention the possible date of release. 

**What is the motivation / use case for changing the behavior?**
As formly provides an easy way to build forms, it is important to have all possible features which can be present in a form which may include Datepicker and autocomplete as well. Hence we require all possible docs for the usage.

**Please tell us about your environment:**
 Operating system - Windows 8, IDE - Visual Studio code

* **Angular version:** 2.0.X

* **Browser:** [all]

 
* **Language:** [ES6/7]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
> how to implement custom buttons in angular formly.

In general to create a custom type you have to create a custom component and register it in the config module so it basically in three steps:

1. create your custom component that extend `FieldType`:

```ts
import { Component } from '@angular/core';
import { FieldType } from '@ngx-formly/core';

@Component({
  selector: 'formly-field-custom-radio',
  template: ` .... `,
})
export class FormlyFieldCustomRadio extends FieldType {}
```

2. register the new type in `FormlyModule`, you have to set the name which you have to use in the form declaration and the related component template.

```ts
@NgModule({
  declarations: [FormlyFieldCustomRadio],
  imports: [
    ....
    FormlyBootstrapModule,
    FormlyModule.forRoot({ types: [
        { name: 'custom-radio', component: FormlyFieldCustomRadio },
    ] }),
  ],
})
export class AppModule {}
```

3. use the new type in your form declaration:
```ts
  fields: FormlyFieldConfig[] = [
    {
      key: 'gender',
      type: 'custom-radio',
   }
   ...
]
```

> Kindly provide the latest link to ngx-formly/material docs or if it is not released yet, kindly mention the possible date of release.

Blocked by [Doc](https://github.com/formly-js/ngx-formly/issues/509) which is in progress.

You may check theses useful resources too:
- https://www.youtube.com/watch?v=WiljtPGZtW8
- https://alligator.io/angular/formly/

Also I think you have to know that formly is mainly based on [Angular reactive forms](https://angular.io/guide/reactive-forms), below I nice post that introduce a reactive-forms
- https://juristr.com/blog/2017/10/demystify-dynamic-angular-forms/

**Comment by aitboudad** [comment]
added the button type example in the doc example see https://formly-js.github.io/ngx-formly/examples/other/button
I'm going to close this issue in favor of https://github.com/formly-js/ngx-formly/issues/509.
