### ISSUE TITLE
Access the model value in validation class

### ISSUE THREAD

**Issue by DSaralaya** [formly-js/ngx-formly#631]
How to access the model value in validation class.
**formly config**

FormlyModule.forRoot({
{
			name:'compareFields',
			defaultOptions: {
				validators: {
					validation:(control: FormControl, field: any) =>
                                        ValidationService.compareFields(control, field)
				}
			}		
		}
})

**validation service class**
export class ValidationService {
  static compareFields(control,field)
   {
        //here how can i access the model 
   }
}
  
**JSON from server**
{
            "key": "Application__c.Years__c",
            "type": "input",
            "optionsTypes": [
              "compareFields"
            ],
            "data": {
              "fieldToCompare": "Application__c.Months__c"
            },
            "className": "col-xs-6 col-sm-3 col-md-2 col-lg-2",
            "templateOptions": {
              "label": "Years",
              "required": true,
              "objectName": "Application__c",
              "fieldName": "Years__c",
              "maxlength": 2
            }
          },
          {
            "key": "Application__c.Months__c",
            "type": "input",
            "optionsTypes": [
              "compareFields"
            ],
            "data": {
              "fieldToCompare": "Application__c.Years__c"
            },
            "className": "col-xs-6 col-sm-3 col-md-2 col-lg-2",
            "templateOptions": {
              "label": "Months",
              "required": true,
              "objectName": "Application__c",
              "fieldName": "Months__c",
              "maxlength": "2"
            },
            "defaultValue": "0"
          }

**Comment by aitboudad** [comment]
you can use your global model value see https://formly-js.github.io/ngx-formly/examples/validation/matching-two-fields, or get the value from `control.parent`
