### ISSUE TITLE
 extras: { validateOnModelChange: true} missing in ngx-formly

### ISSUE THREAD

**Issue by DSaralaya** [formly-js/ngx-formly#635]
In Angular formly  validateOnModelChange: true option is there. Please suggest how to achieve this.

FormlyModule.forRoot({ 
types: [
{
name:'compareFields',
   defaultOptions: {
            extras: {
               validateOnModelChange: true
                }
          }
    }
]
})

**Comment by aitboudad** [comment]
changing form model directly is not recommended, I suggest to use `formControl.setValue` instead (this will check validation automatically) and if you want to recheck validation manually you can call `updateValueAndValidity` method
