### ISSUE TITLE
Template Render

### ISSUE THREAD

**Issue by DSaralaya** [formly-js/ngx-formly#640]
Please check below  formly JSON  template {{model['Application__c']['First_Name_J__c']}} not rendering.It shows as  text.How can we render this one.

{
      "template": "<div class=\"panel-inline-divider\"></div><div class=\"\"><div class=\"\" role=\"tab\"><h4 class=\"panel-title\">Employment Information: {{model['Application__c']['First_Name_J__c']}} {{Application__c.Last_Name_J__c}}</h4></div><div class=\"card-block\" role=\"tabpanel\">",
      "className": "input-wrapper inline-section-header",
      "data": {
        "sectionType": "EP-header_J1"
      },
      "hideExpression": "!model['Application__c']['First_Joint_Applicant__c']"
    }

**Comment by aitboudad** [comment]
it's not possible  with the new angular (only possible with JIT compiler), so instead you can create a custom component type.

Another approach is to use `expressionProperties`,  see the following example: 
https://stackblitz.com/edit/angular-hd17hb

**Comment by ron-liu** [comment]
Awesome, that is exactly what I want, thanks. It works, check [here](https://stackblitz.com/edit/ngx-formly-custom-template-asawaa)
