### ISSUE TITLE
Implement formly rules for @angular-devkit/schematics

### ISSUE THREAD

**Issue by aitboudad** [formly-js/ngx-formly#644]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

similar to https://github.com/ngrx/platform/issues/53, which include:
- Setting up the form
- Generating a custom type
- Generating a custom wrapper
- Generating a component with form

**Comment by juristr** [comment]
Oh that sounds interesting. I planned to look into schematics, so when I'm ready, I may use this issue to create some of these 👍. Subscribed to it

**Comment by thorgod** [comment]
Looks concept! Might take a look later in the week if I have time.

**Comment by juristr** [comment]
@thorgod awesome. Keep us posted. I planned to contribute as well, just probably won't make it this and next week as I'm too busy with other stuff.

**Comment by samtsai** [comment]
Hi @juristr @thorgod @aitboudad I think I'll have something to review today. It took the longest to get the tests setup. I've been looking at:
- angular material2's repo
- angular devkit
- https://medium.com/@tomastrajan/%EF%B8%8F-how-to-create-your-first-custom-angular-schematics-with-ease-%EF%B8%8F-bca859f3055d

**Comment by samtsai** [comment]
The [PR](#963) can be the beginning of schematics. It doesn't actually tackle the list above but it begins with just bootstrapping an application to install the `@ngx-formly/core` and UI theme if passed.

**Comment by aitboudad** [comment]
initial support has been landed if anyone wanted to add more features on this part just send a PRs :)
