### ISSUE TITLE
Ionic support

### ISSUE THREAD

**Issue by thm1118** [formly-js/ngx-formly#646]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   

ngx-formly is easy to extend other UI library. 
I extended ionic3 form component even although I am new to angular2+ and ionic3. 
I try to package it follow the ui-bootstrap extend package config ，but ng-package can not package lib dependency ionic-anglular.  maybe due to  [issue of Ionic umd module ids](https://github.com/dherges/ng-packagr/issues/434).

are there any suggestions?

**Comment by thm1118** [comment]
[extended ionic3 form component](https://github.com/thm1118/ngx-formly/commit/e0d7bb4c50038cad71e5906acfe2a2eb3d07dd65)

**Comment by aitboudad** [comment]
Hi, sound interesting :),
you may need to add all external libs (ionic-angular, ...) in [ng-package.json](https://github.com/formly-js/ngx-formly/blob/master/src/ui-material/ng-package.json#L5)

**Comment by thm1118** [comment]
i added all external libs in ng-package.json.  but ng-package build error message:
`$ npm run build

> @ngx-formly/common@2.0.0-rc.9 build D:\works\github\ngx-formly
> npm run build:core && npm run build:bootstrap && npm run build:material && npm run build:ionic && node .config/build.js


> @ngx-formly/common@2.0.0-rc.9 build:core D:\works\github\ngx-formly
> ng-packagr -p src/core/ng-package.json

Building Angular library
Generating bundle for @ngx-formly/core
Cleaning bundle build directory
Processing assets
Running ngc
Compiling to FESM15
Compiling to FESM5
Compiling to UMD
Minifying UMD bundle
Dropping duplicated definition of variable a70 [0:202,16]
Dropping unreachable code [0:888,24]
Declarations in unreachable code! [0:888,24]
Dropping duplicated definition of variable a415 [0:1437,38]
Remapping source maps
Copying staged files
Writing package metadata
Built Angular bundle for @ngx-formly/core
Built Angular library from D:\works\github\ngx-formly\src\core, written to D:\works\github\ngx-formly\dist\core

> @ngx-formly/common@2.0.0-rc.9 build:bootstrap D:\works\github\ngx-formly
> ng-packagr -p src/ui-bootstrap/ng-package.json

Building Angular library
Generating bundle for @ngx-formly/bootstrap
Cleaning bundle build directory
Processing assets
Running ngc
Compiling to FESM15
Compiling to FESM5
Compiling to UMD
Minifying UMD bundle
Remapping source maps
Copying staged files
Writing package metadata
Built Angular bundle for @ngx-formly/bootstrap
Built Angular library from D:\works\github\ngx-formly\src\ui-bootstrap, written to D:\works\github\ngx-formly\dist\bootstrap

> @ngx-formly/common@2.0.0-rc.9 build:material D:\works\github\ngx-formly
> ng-packagr -p src/ui-material/ng-package.json

Building Angular library
Generating bundle for @ngx-formly/material
Cleaning bundle build directory
Processing assets
Running ngc
Compiling to FESM15
Compiling to FESM5
Compiling to UMD
Minifying UMD bundle
Remapping source maps
Copying staged files
Writing package metadata
Built Angular bundle for @ngx-formly/material
Built Angular library from D:\works\github\ngx-formly\src\ui-material, written to D:\works\github\ngx-formly\dist\material

> @ngx-formly/common@2.0.0-rc.9 build:ionic D:\works\github\ngx-formly
> ng-packagr -p src/ui-ionic/ng-package.json

Building Angular library
Generating bundle for @ngx-formly/ionic
Cleaning bundle build directory
Processing assets
Running ngc
Compiling to FESM15
'default' is not exported by 'node_modules\rxjs\add\operator\toPromise.js'

BUILD ERROR
ENOENT: no such file or directory, open 'D:\works\github\ngx-formly\node_modules\ionic-angular\components\app\app-constants.ts'
Error: ENOENT: no such file or directory, open 'D:\works\github\ngx-formly\node_modules\ionic-angular\components\app\app-constants.ts'

npm ERR! code ELIFECYCLE
npm ERR! errno 111
npm ERR! @ngx-formly/common@2.0.0-rc.9 build:ionic: `ng-packagr -p src/ui-ionic/ng-package.json`
npm ERR! Exit status 111
npm ERR!
npm ERR! Failed at the @ngx-formly/common@2.0.0-rc.9 build:ionic script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tiger\AppData\Roaming\npm-cache\_logs\2018-01-13T03_09_30_036Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 111
npm ERR! @ngx-formly/common@2.0.0-rc.9 build: `npm run build:core && npm run build:bootstrap && npm run build:material && npm run build:ionic && node .config/build.js`
npm ERR! Exit status 111
npm ERR!
npm ERR! Failed at the @ngx-formly/common@2.0.0-rc.9 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tiger\AppData\Roaming\npm-cache\_logs\2018-01-13T03_09_30_227Z-debug.log
error Command failed with exit code 111.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

D:\works\github\ngx-formly>`

from the build output message,  error threw when `Compiling to FESM15` 

but the good news is these ionic3 extended can be run and build in my project src directory as the project's part.

**Comment by aitboudad** [comment]
I tried on my side and it seems to be working, the version of rxjs was the cause of failure try to update it into `5.4`:
```patch
--"rxjs": "^5.5.2",
++"rxjs": "~5.4.0",
```

**Comment by thm1118** [comment]
Downgrade rxjs's  version to 5.4.0 only resolve  `'default' is not exported by 'node_modules\rxjs\add\operator\toPromise.js'`, but cannot build: ionic yet, ng-package try to build FESM15 target, but maybe ionic not support it.
by the way, Downgrade rxjs's  version to 5.4.0 cause another problem: build: material threw an error of rxjs export.

**Comment by thm1118** [comment]
I commit these ionic extended in my  [repo](https://github.com/thm1118/ngx-formly/commit/e0d7bb4c50038cad71e5906acfe2a2eb3d07dd65), I plan to make PR to ngx-formly if build:ionic target achieved the goal.
would you please check the repo if you are willing to?

**Comment by aitboudad** [comment]
just go I'll take a look once you made a PR, I have one remark for now we will support only the basic types:
- input
- textarea
- select
- radio
- checkbox
- multicheckbox

and in the next major version (V3) we will try to add the most valuable ones (Datepicker, Autocomplete...) and the rest can be part of doc demo

**Comment by toewai** [comment]
How can i use autocomplete in ionic

**Comment by aitboudad** [comment]
@toewai see https://formly.dev/guide/custom-formly-field
