### ISSUE TITLE
Repeat-section does not notice updated model

### ISSUE THREAD

**Issue by FritzHerbers** [formly-js/ngx-formly#648]
```
[X] bug report
```

**Current behavior**
When the model is updated a repeat-section is not updated.

**Minimal reproduction of the problem with instructions**
(Would be nice to find in the contribute section information with a actual plunkr to clone from)

* **Angular version:** 5.0.1

I changed your repeating-section example:
app.component.html
```
<form [formGroup]="form" (ngSubmit)="submit()">
  <formly-form [model]="model" [fields]="fields" [options]="options" [form]="form">
    <button type="submit" class="btn btn-primary submit-button" [disabled]="!form.valid">Submit</button>
    <button type="button" class="btn btn-primary submit-button" (click)="updateModel()">Update Model</button>
  </formly-form>
</form>
<pre>{{ model | json }}</pre>
```

Added in app.component.ts
```
  updateModel() {
    this.model = {
      investments: [
        {
          investmentName: 'aaa',
          investmentDate: '2001-01-01',
          stockIdentifier: 'aaa',
        },
        {
          investmentName: 'bbb',
          investmentDate: '2002-02-02',
          stockIdentifier: 'bbb',
        },
      ],
    };
    this.options.resetModel();   // from 470
  }
```

Pressing the update Model button does not change the repeat section.

https://github.com/formly-js/ngx-formly/issues/470 explains to use `options.resetModel()`.

Is this a bug?
Could you please update the repeat section example to show how to act on model changes.

**Comment by aitboudad** [comment]
Hi, I would prefer to consider the model as a readonly, can you try passing the new value into `resetModel`:
```ts
this.options.resetModel({ investments: ... });
```

**Comment by FritzHerbers** [comment]
That worked to update the model, however still only one investment is shown, but see two "Remove" buttons.
Pressing "Add more Investments" it shows the second investment too.

It seems no fields are populated. How can we fix that?

We use this repeating-section within a bigger hierarchical (fieldGroups) formly and is somewhere deeply used. Hope that the fix is also working when we only have easy access on the top formly.

**Comment by aitboudad** [comment]
@FritzHerbers I see what's happens, the fix will take a little bit time, so I prefer to provide you a workaround until it fixed.

add the following code inside `repeat-section.type.ts`

```ts
  ngOnInit() {
    if (this.model) {
      setTimeout(() => this.model.map(() => this.add()));
    }

    // temporary fix for https://github.com/formly-js/ngx-formly/issues/648
    const parentResetModel = this.options.resetModel;
    this.options.resetModel = (formModel) => {
      parentResetModel(formModel);

      while (this.formControl.length !== 0) {
        this.formControl.removeAt(0);
      }

      this.fields.length = 0;
      this.model.map((item) => {
        this.add();
      });
    };
  }
```
let met know if that work for you.

**Comment by FritzHerbers** [comment]
That worked, thanks for the workaround.

Looking forward for your fix.

**Comment by aitboudad** [comment]
fixed in `2.0.0-rc.32`.

Please make sure to update your `RepeatTypeComponent`: https://formly-js.github.io/ngx-formly/examples/advanced/repeating-section

```ts
import { Component, OnInit } from '@angular/core';
import { FieldArrayType, FormlyFormBuilder } from '@ngx-formly/core';

@Component({
  selector: 'formly-repeat-section',
  template: `
    <div *ngFor="let field of field.fieldGroup; let i = index;">
      <formly-group
        [model]="model[i]"
        [field]="field"
        [options]="options"
        [form]="formControl">
      </formly-group>
      <div class="col-md-2">
        <button class="btn btn-danger" type="button" (click)="remove(i)">Remove</button>
      </div>
    </div>
    <div style="margin:30px 0;">
      <button class="btn btn-primary" type="button" (click)="add()">Add More Investments</button>
    </div>
  `,
})
export class RepeatTypeComponent extends FieldArrayType {
  constructor(builder: FormlyFormBuilder) {
    super(builder);
  }
}
```

**Comment by anasvn** [comment]
add() functionality is calling inside the formly-repeat-section component. How can I call from the parent component. I have to implement a add button in a separate section. I have an idea in my mind to use subscription to trigger add() function inside the formly-repeat-section component. Is there any other idea in your mind ?

**Comment by aitboudad** [comment]
@anasvn assing `add` to the field templateOptions:
```ts
export class RepeatTypeComponent extends FieldArrayType {
  ngOnInit() {
    this.field.templateOptions.add = this.add.bind(this);
  }
}
```

**Comment by neosis** [comment]
@aitboudad  is it possible for you to provide with a working stackblitz demo for this addition to templateOptions?
