### ISSUE TITLE
Custom type definition with validation

### ISSUE THREAD

**Issue by FritzHerbers** [formly-js/ngx-formly#649]
```
[x] feature request
```

In formly-js it was possible to set validators on a type, in addition to specifying it on a field as with ngx-formly.
```
angular
  .module('app.formly')
  .run(['formlyConfig', function (formlyConfig) {
	  formlyConfig.setType({
		  name: 'Integer',
		  extends: 'input',
		  defaultOptions: {
			  validators: {
				  input_check: function (viewValue, modelValue) {
					  var value = modelValue || viewValue;
					  return /^\d+$/.test(value);
				  }
			  }
		  }
	  });
  }]);
```

Would be nice that FormlyModule.forRoot->types would allow to specify validators.
```
export function IntegerValidator(control: FormControl): ValidationErrors {
    return /^\d+$/.test(control.value) ? null : { 'integer': true };
}

FormlyModule.forRoot({
  types: [
    { name: 'vtInteger', extends: 'input' , validators: [IntegerValidator]},
```

**Comment by aitboudad** [comment]
see https://formly-js.github.io/ngx-formly/examples/validation/custom-validation

**Comment by FritzHerbers** [comment]
That didn't work.

It would also be very confusing when FormlyFieldConfig takes a validators array (not within defaultOptions) and ConfigOption->types->TypeOption it should go into defaultOptions.

It would be nice to define types like
```
FormlyModule.forRoot({
      types: [
        { name: 'vtInteger', extends: 'input', validators: [IntegerValidator] },
```

**Comment by aitboudad** [comment]
I would prefer to keep it simple right now, we can focus on simplification later right, now we can achieve the desired behavior using `defaultOptions`.

here is a working example: https://stackblitz.com/edit/angular-mhr7ym
it should be passed as an object not an array:
```ts
{ 
    name: 'vtInteger',
    extends: 'input' , 
    defaultOptions: {
      validators: {
        integer: IntegerValidator
      }
    },
},
```

**Comment by FritzHerbers** [comment]
Looks good. Is it in 2.0.0-rc.13?
Your stackblitz example references the latest version (as I see 2.0.0-rc.8 in the dependencies)?

I updated locally to rc.13, adapted to your example and got the following error:
```
ERROR TypeError: path.split is not a function
    at _find (forms.js:2817)
    at FormGroup.AbstractControl.get (forms.js:3581)
    at FormlyFormBuilder.addFormControl (core.es5.js:933)
    at eval (core.es5.js:726)
    at Array.forEach (<anonymous>)
    at eval (core.es5.js:723)
    at Array.forEach (<anonymous>)
    at FormlyFormBuilder.registerFormControls (core.es5.js:711)
    at FormlyFormBuilder.buildForm (core.es5.js:700)
    at eval (core.es5.js:746)
```

It is not high priority as we have to develop several more things, for now we can use the fields way.

**Comment by aitboudad** [comment]
I think it's another issue there not related to this, could you please open another issue with a reproduction example ?

updated the example into the latest version without getting any issue see  https://stackblitz.com/edit/angular-mhr7ym.

**Comment by FritzHerbers** [comment]
I have it working now (back on rc8 due to https://github.com/formly-js/ngx-formly/issues/665).

But I had to change from 

```
export function IntegerValidator(control: FormControl): ValidationErrors {
    return /^\d+$/.test(control.value) ? null : { 'integer': true };
}
```
Taken from the example https://formly-js.github.io/ngx-formly/examples/validation/custom-validation

to
```
export function IntegerValidator(control: FormControl): boolean {
    return /^\d+$/.test(control.value);
}
```

Can you please elaborate why returning a boolean works and returning ValidationErrors does not work.
What is the preferred return type?

**Comment by FritzHerbers** [comment]
Hi, the issue is closed, still hope you can have a look at my last comment.

**Comment by aitboudad** [comment]
sorry I was busy, we support both signatures, when key is provided then we expect a boolean return type, see [formly.field.config.ts#L47-L48](https://github.com/formly-js/ngx-formly/blob/master/src/core/src/components/formly.field.config.ts#L47-L48)
