### ISSUE TITLE
Input add-ons not displayed correctly in Examples section of online documentation.

### ISSUE THREAD

**Issue by agileorange** [formly-js/ngx-formly#656]
In the Examples section of your [documentation](https://formly-js.github.io/ngx-formly/examples/bootstrap-specific/input-add-ons) the Input add-ons are not rendering correctly either in Chrome or IE.

**Comment by travis1234** [comment]
Sorry but this is still not fixed, the input field facing the add-on has a border radius which seems to be causing the issue. This is not the case on the bootstrap exmaples

![image](https://user-images.githubusercontent.com/4219774/38479610-b9072cc6-3c03-11e8-8392-cc8e48e032ab.png)

**Comment by chaosLegacy** [comment]
Hi,
Is their any way i can make an input add-ons as function ?
something like that:
`addonRight: () => {
                return {text: 'hello world'};
              },`
my goal is to display diffrent text each time the user change an option is it possible ?

**Comment by aitboudad** [comment]
can you try with:
```ts
addonRight: {
  onClick: () => { return {text: 'hello world'}; },
}
```

**Comment by chaosLegacy** [comment]
Thanks for the quick reply but no the text change according  to a result of an input select my idea is to get the it model value in according to the value selected i will change the text of the input add-ons
Here is my code:
this the select input that the user will change 
`{
            key: 'repetition',
            type: 'select',
            defaultValue: 'SELECT_VALUE',
            wrappers: ['fieldset', 'horizontalWrapper'],
            templateOptions: {
              label: 'Récurrence',
              options: [
                 {value: '1', label:'ANNUAL'},
                {value: '2', label:'MONTHLY'},
               {value: '3', label:'HALF'},
               {value: '4', label:'QUARTERLY'},
             ],
              class: {
                colLabel: 'col-3',
                col: 'col-3'
              }
            }
}`
This is the input that should display the user result
`
{
            key: 'repeatedEvery',
            type: 'horizontalInput',
            wrappers: ['fieldset', 'horizontalWrapper'],
            defaultValue: 1,
            templateOptions: {
              type: 'number',
              label: 'Nombre de répétitions',
              min: 1,
              addonRight: () => {
                return {
                  text: function () {
                    return 'hello world'; // Here the result of the model.repetition
                  }
                };
              },
              class: {
                colLabel: 'col-3',
                col: 'col-3'
              }
            }
          }`
Hope i make it easy to understand thank you a lot

**Comment by chaosLegacy** [comment]
Hi,
I've found a way to do the tweak that i wanted by adding a affecting text to a function like so:
`addonRight: {
                text: this.repetitionLabelChange(formlyForm)
              },`
and this is the function that do the change:
`private repetitionLabelChange(formlyForm): string {
    let output = 'repetition'; // default value
    const repetition = formlyForm.get('repetition');
    if (repetition) {

      switch (repetition.value) {
        case 'ANNUAL':
          output = 'ans';
          break;
        case 'MONTHLY':
          output = 'mois';
          break;
        case 'WEEKLY':
          output = 'semaines';
          break;
        case 'DAILY':
          output = 'jours';
          break;
        default:
          output = 'repetition';
      }
    }
    console.log(output);
    return output;
  }`
its working only the first time the input add-ons text display 'repetition' i call the same function on the when i change my select the console.log display the correct value but the add-ons is not affected
i guess its only display on the render time because i put a timeout in the repetitionLabelChange function and it didn't display anything
