### ISSUE TITLE
Unable to load options to select field type using API request

### ISSUE THREAD

**Issue by GetTaxSolutions** [formly-js/ngx-formly#658]
I'm trying to async load of data from API request in select type of field. I'm trying this one:
'templateOptions.options': (model) => {
return this.apiService.getAll<CountryModel>("country").subscribe((data: any) => {
return data;
}, error => () => { this.notificationService.error('Error', error.message); }, () => { });
}
in expressionProperties but id doesn't work
and go in endless loop
the browser debugger show follow error: ERROR TypeError: this.to.options.map is not a function
Can you help me what is the pattern to load these options in select from API?

The apiService method return Observable<CountryModel> which have Id and Name. In templateOptions I have : valueProp: "Id",
labelProp: 'Name',

I created small example what I tried but only with timeout instead of real API call:
[https://stackblitz.com/edit/angular-hbsgnw?file=app/app.component.ts](https://stackblitz.com/edit/angular-hbsgnw?file=app/app.component.ts)

Can you modify with proper design pattern?

Thank you,
Gettaxsolutions Ltd

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-9ylozx

**Comment by GetTaxSolutions** [comment]
Cool. It's working to load options. But now have something else. I'm using init component's method from life cicle to load the data in the model. It will set default value 
ngOnInit() {
      Observable.timer(1000).subscribe(() => {
          this.formModel = { email: 'email@gmail.com', CountryId: 1 };
      });
  }
This set the values into the form controls but if you try to change something into the controls it's not applied to the model. I print the model into the result and make some changes into the email or change the value in dropdown. The model is not touched.

[https://stackblitz.com/edit/angular-scfhhr?file=app/app.component.ts](https://stackblitz.com/edit/angular-scfhhr?file=app/app.component.ts)

**Comment by aitboudad** [comment]
because it lose the model reference, try to use `form.setValue` to update the model value:
```
this.form.setValue({ email: 'email@gmail.com', CountryId: 1 });
```

see https://stackblitz.com/edit/angular-rl9xxy

**Comment by GetTaxSolutions** [comment]
Looks like that using form.setValue is working but what is the reason to lose reference to model? Is it a bug?

**Comment by aitboudad** [comment]
well it's a bug here, I look into it later.
