### ISSUE TITLE
Example for a dynamic form with JSON received from the server

### ISSUE THREAD

**Issue by andyfensham** [formly-js/ngx-formly#662]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

I am trying to find an example where a form config comes from json data from a server, but am unable to find anything. Can someone please point me to an example or give me a short sample or put an example on the website.

**Comment by aitboudad** [comment]
see https://formly-js.github.io/ngx-formly/examples/other/json-powered

**Comment by andyfensham** [comment]
Thanks so much. Appreciate it.
