### ISSUE TITLE
Get selected files in input type=file

### ISSUE THREAD

**Issue by nikul1993** [formly-js/ngx-formly#668]
Hello Team,

i am using input type = "file" in formly form but i can not find the selected file in formcontrol. how do i get it?

Thank you.

**Comment by aitboudad** [comment]
input type file isn't supported by the angular forms yet (https://github.com/angular/angular/issues/7341), firstly you have to create a `ControlValueAccessor` for file input and then create a custom field type.
see the example https://formly-js.github.io/ngx-formly/examples/other/input-file
