### ISSUE TITLE
File Input and Signature.

### ISSUE THREAD

**Issue by kritisoft** [formly-js/ngx-formly#673]
**I'm submitting a ...**  (check one with "x")
```
[X ] support request
```
I am Using the File Input from Ngprime  and Signature Pad from angular2-signature-pad

1. The Signature Pad and Files are getting rendered , but it seems it has no binding to the model or form.

2. Also let me know if their is any possibility of finding area , when i enter the values for length and width.

Reproduction of the same is  available at https://stackblitz.com/edit/angular-mtvbhp

Please let me know , what i am doing wrong , since it is not getting binded to the model.

**Comment by aitboudad** [comment]
> 1. The Signature Pad and Files are getting rendered , but it seems it has no binding to the model or form.

use `setValue` from `formcontrol`
```ts
  onClearHandler() {
    this.formControl.setValue(null)
  }

  onSaveHandler(data) {
    this.formControl.setValue(data);
  }
```

> 2. Also let me know if their is any possibility of finding area , when i enter the values for length and width.

not clear, can you elaborate more on this please

**Comment by kritisoft** [comment]
Thanks , The Signature Pad , is working now. but how about the files ? it not getting updated into the model. 

> 2 . Also let me know if their is any possibility of finding area , when i enter the values for length and width.
**I have completed this one. Thanks for the Support** 

I would highly appreciate if the files can also be the part of the  model object as shown in your site example ( which is done for simple input type=file). 
But the ngprime control for file is not working the same way as shown in your example .
