### ISSUE TITLE
Multiple cascade selection in repeat

### ISSUE THREAD

**Issue by uouo690** [formly-js/ngx-formly#681]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
       I created a [repeat ](https://formly-js.github.io/ngx-formly/examples/advanced/repeating-section) with cascade select for each row ,I followed the steps of this [link](https://stackblitz.com/edit/angular-9wekfg?file=app%2Fapp.component.ts) but it didn't work for me because I could't get cascade select work to its related select .

**Expected behavior**
![relation](https://user-images.githubusercontent.com/19722038/35403602-e2aaf470-0208-11e8-9c71-7249129dc083.png)
  
  As shown in this image I need the cascade select to be related to its row only

 I had made a work around :
I added an index to each field  in the repeat component , so that I can use the index to get the corresponding select value.

   - Added index in interface FormlyFieldConfig in file formly.field.config.d.ts.
   
    - In the repeat component I add index for each filed.
     ` <div *ngFor="let control of formControl.controls; let i = index;">
      <formly-form
        [model]="model[i]"
        ** [fields]="addIndex(fields[i],i)"**
        [options]="options"
        [form]="this.formControl.at(i)"
        [ngClass]="field.fieldArray.fieldGroupClassName">
      </formly-form>
      </div>`

      - In the RepeatTypeComponent

       `addIndex(input,index){
                 input.forEach( field =>{
                         field .index = index;
                 }
             );
         return input;
        }`

      - Finally in the cascade selection I added in the lifecycle a condition to get the corresponding select value to make sure 

       `lifecycle: {
              onInit: ( field) => {
                const updateOptions = (v) => {
                  
                 

                  > var index = field.index;

                 
                  if (v.fields[index].type === 'select' || v.fields[index].type === 'repeat') {
                    this.databaseService.get().subscribe( data => {
                        field.templateOptions.options = ........
                    });
                 
                 }
                };

                updateOptions(form.value);
                this.form.valueChanges.subscribe(v => updateOptions(v));
              },
            },`
           Where "fields: FormlyFieldConfig[]"

But I am sure there is a better solution than this workaround.
Thanks in advance

**Comment by aitboudad** [comment]
@uouo690 have you tried the demo example https://formly-js.github.io/ngx-formly/examples/other/cascaded-select ?

**Comment by uouo690** [comment]
Thanks for your quick response ,
It worked just fine , when I use fixed list in the options .

But there is another issue it seems the , 
"expressionProperties: { 'templateOptions.options': (model) => {"
Is called too many time and I am using observable to populate the cascaded select, that make infinite call to back end API .

I will try to create a reproduce the issue and send you the stackblitz link .

**Comment by uouo690** [comment]
Please review this https://stackblitz.com/edit/angular-m9swpu

**Comment by aitboudad** [comment]
`expressionProperties` doesn't allow take account of observable try use it  in `onInit`
see https://stackblitz.com/edit/angular-51saw6?file=app/app.component.ts

**Comment by uouo690** [comment]
Thanks for you help @aitboudad
