### ISSUE TITLE
an example of using formly with advanced layout build with flex-layout and angular-material rather than bootstrap

### ISSUE THREAD

**Issue by rafszul** [formly-js/ngx-formly#683]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x ] support request
```
an example of using formly with advanced layout build with flex-layout and angular-material rather than bootstrap

**Comment by aitboudad** [comment]
hi, 
here is a quick solution https://stackblitz.com/edit/ngx-formly-flex-layout, I'll keep this issue open until I find a better approach

**Comment by rafszul** [comment]
https://formly-js.github.io/ngx-formly/examples/other/advanced-layout-flex

**Comment by aitboudad** [comment]
yep, keep it simple!
I thought you've asked for https://github.com/angular/flex-layout integration

**Comment by bogacg** [comment]
@aitboudad while solution you provided works well with fields, when I wanted to add flex-layout to  `fieldGroup`s so that elements below act accordingly (Ex: `fieldGroup` has `fxLayout` attribute) by using wrapper.
Problem is, wrapper wraps `fieldGroup` therefore whole group is just one elment, can't affect fields below.

**Comment by aitboudad** [comment]
**Note**: the `@angular/flex-layout` example has been updated which use a better way by relying on a custom field type, here is an example https://stackblitz.com/edit/ngx-formly-flex-layout

**Comment by GlauberF** [comment]
@aitboudad 
In the example you posted, you set up `fxLayout`, how can I specify the size for each` fxFlex` field?

In case it is not possible, where this type is located in the repository, for me to create a custom one, based on it
