### ISSUE TITLE
Unclear docs on which basic example to follow

### ISSUE THREAD

**Issue by snoop244** [formly-js/ngx-formly#686]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

I'm worried that I'm following various example documentations and guides that are out of sync with the current release.

After following the basic guide on the GitHub main page, I got Formly working and it worked for about a month.  When I rebuilt the project on a new machine Formly stopped working.  I assumed that there might have been some breaking changes in the updated version (??).  The specific issue was that the model no longer populated on submit().  Everything else still worked.  I checked my code against a Google search that yielded this page: https://ng2.angular-formly.com/guides/getting-started.html.  and realized that my code was very different than the code on that page.  When I tried to follow the pattern on that page I got warnings in my IDE like: "Type 'FormGroup' is not assignable to type 'typeof FormGroup'.Property 'prototype' is missing in type 'FormGroup'.".  

My application is way too complicated to post any code and resolve my issue with the model not returning values on submit - so I'm just pointing out that there are Formly basic examples that are found in the first, second and third position in my Google search that each show a very different way of implementing the Formly basic example.

**Comment by aitboudad** [comment]
The new doc is landed in https://formly-js.github.io/ngx-formly/ now,
For breaking-changes see the [CHANGELOG](https://github.com/formly-js/ngx-formly/blob/master/CHANGELOG.md#breaking-changes)

> "Type 'FormGroup' is not assignable to type 'typeof FormGroup'.Property 'prototype' is missing in type 'FormGroup'.".

I have no idea :thinking:

**Comment by snoop244** [comment]
Thanks.  Ok, I adapted my code to the latest example.  The model is still not getting data.  I updated my Material and CDK libraries and now I'm getting this error in the console on each keystroke. Submit just gives me an empty model object and the only error I'm getting is this error on entering the data in the fields on each keystroke.  I can't reproduce it on a fresh project and my project is far too complex to post - so I'm hoping this error is meaningful:

ERROR TypeError: jit_nodeValue_5(...).$any is not a function
    at Object.eval [as handleEvent] (FormlyFieldInput.html:2)
    at handleEvent (core.js:13255)
    at callWithDebugContext (core.js:14740)
    at Object.debugHandleEvent [as handleEvent] (core.js:14327)
    at dispatchEvent (core.js:9704)
    at eval (core.js:10318)
    at HTMLInputElement.eval (platform-browser.js:2614)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4620)
    at ZoneDelegate.invokeTask (zone.js:424)

**Comment by aitboudad** [comment]
The error is similar to https://github.com/formly-js/ngx-formly/issues/661, but without a reproduction I can't help unfortunately, please ensure that all of your deps(angular, zone.js, material) is up to date also the model should be passed into `formly-form` componenent:
```html
<formly-form [model]="model" ...></formly-form>
```

**Comment by snoop244** [comment]
Sure.  I appreciate the help.  Again, the error in the console is triggered on every keystroke.  Note that my submit is not part of the form as I load multiple buttons, only one of which is submit.  When I put my buttons inside the form, they all invoke submit, which is not desired.  I did test with the submit inside the form and it made no difference.

`{
  "name": "automlapp",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-mdc/web": "^0.6.1",
    "@angular-mdl/core": "^4.0.8",
    "@angular/animations": "^5.0.3",
    "@angular/cdk": "^5.1.1",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.1.1",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.1.1",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@ng-dynamic-forms/core": "^5.4.4",
    "@ng-dynamic-forms/ui-material": "^5.4.4",
    "@ngui/utils": "^0.8.1",
    "@ngx-formly/core": "^2.0.0-rc.2",
    "@ngx-formly/material": "^2.0.0-rc.2",
    "angular2-text-mask": "^8.0.4",
    "animate.css": "^3.5.2",
    "core-js": "^2.4.1",
    "default-passive-events": "^1.0.0",
    "hammerjs": "^2.0.8",
    "horizontal-scroll": "^1.1.0",
    "iscroll": "^5.2.0",
    "jquery": "^2.2.4",
    "lodash": "^4.17.4",
    "mdi": "^2.0.46",
    "ng2-animate-on-scroll": "^1.0.8",
    "ngx-carousel": "^1.3.5",
    "ngx-page-scroll": "^4.0.2",
    "number-generator": "^1.0.1",
    "queueing-subject": "^0.1.1",
    "rxjs": "^5.5.2",
    "rxjs-websockets": "^4.0.0",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.7",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}
`
I assume this is what you mean by form field config:
`<form [formGroup]="form" (ngSubmit)="submit(model)">
    <formly-form [model]="model" [fields]="fields" >

    </formly-form>
</form>
  <mat-action-row>
      <div  *ngFor="let command of enabledCommands" >
          
              <button mat-button (click)="onCommandClick(command.commandExecutionURI, command.commandType, objectId, processInstanceId)">
              {{command.commandName}}
            </button>
      </div>

   </mat-action-row>`

The code sets up the fields.  The fields appear correctly on the formly form.  I'm not showing the code to fetch the field structure from my backend as I doubt the problem is there.  If you need to see it. lmk:

`getFields(taskForm: FieldDataCapture[]): FormlyFieldConfig[] {
  let fields: FormlyFieldConfig[] = []; 
  console.log(taskForm);
  for (let field of taskForm) {
        console.log('field.key: ' + field.key);
        console.log('field.template.label ' + field.templateOptions.label);
         let newField = {
              key: field.key, 
              type: 'input',
              templateOptions: {
                label: field.templateOptions.label,
                placeholder: '',  // this was placehlder in Formly example... typo?
                required: field.templateOptions.required
            }
          };
      fields.push(newField);
    }
      return fields;
    }`

I haven't included the submit command because, as I mentioned, there are a number of commands and the code is hard to understand out of context.  Having said that, I don't think that code is the source of the problem because even if you put the submit button into the form in the HTML above, the model does not populate.
Thanks for your help.  Much appreciated.
S.

**Comment by aitboudad** [comment]
can you ensure that the initial value of model is an object
Note: the model value can be retrieved from `form.value` too

>  I'm not showing the code to fetch the field structure from my backend as I doubt the problem is there. If you need to see it. lmk:

yes, please.

**Comment by snoop244** [comment]
Ok, I hope this gives you the context you need.  First, the parent component, then the child that holds the Formly module and then the data models.  Forgive me, I'm just learning Angular and so you will see some bad code, I'm sure.  Also, note that the forms appear to load properly.

Parent component:
```
import { Component, OnInit, ViewChild } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/do';
import {HttpClient, HttpParams} from '@angular/common/http';
import * as _ from 'lodash';
import {FormGroup} from '@angular/forms';
import {FormlyFieldConfig} from '@ngx-formly/core';
import {Task} from '../../task';
import {  Router, ActivatedRoute } from '@angular/router';
import { AppComponent } from '../../app.component'; // seems to be required to properly fetch routeData
import {RouteData} from '../../route';
import { Recommendation } from '../../recommendation';
import { RecommenderDataService } from '../../recommender-data.service';
import { DataCaptureComponent } from '../../data-capture/data-capture.component';


@Component({
  selector: 'app-task',
  templateUrl: './task.component.html',
  styleUrls: ['./task.component.css'],
  
})

// Fetches tasks and task form variables from backend and passes them as @Input to child data capture form.  
// NOTE: multiple tasks may be passed concurrently, but usually there is only one.
export class TaskComponent implements OnInit {
  
  @ViewChild(DataCaptureComponent) dataCaptureComponent: DataCaptureComponent; // required to properly fire submit of this parent on the child
  BPMNTasksCurrent$: Observable<Task[]>; // NOTE: usually a single task, but may return multiple if parallel tasks are part of process!!
  routeData: RouteData; // holds the id of the task(s) to fetch

  constructor(
    private recommenderService: RecommenderDataService,
    private http: HttpClient,
    private appComponent: AppComponent, // seems to be required to properly fetch routeData
    private route: ActivatedRoute,
    private router: Router
  )  {  }

  ngOnInit() {
    // Does a GET on the next incomplete task(s) from the backend
    this.refreshTasks('bpmn-process-current-task');
    // then subscribe so that task form variables can be fetched
    this.BPMNTasksCurrent$.subscribe(  // this returns an array of Task
        );

  }

  refreshTasks(commandExecutionURI: string) { // called from this OnInit and after submit from child DataCaptureComponent
    this.BPMNTasksCurrent$ = this.httpGetTasks(commandExecutionURI); 
  }

  refreshNextTask(event) { // triggered by event emitter attached to the child dataCaptureComponent and invoked to get subsequent Task(s)
    this.refreshTasks('bpmn-process-current-task');
  }

  httpGetTasks(commandExecutionURI: string): Observable<any[]> {
          console.log('Command execution: ' + commandExecutionURI + ' sent as a: GET');
          this.routeData = this.appComponent.routeData; // includes process ID that allows sub-Task(s) to be fetched
          const params = new HttpParams().set('processInstanceId', this.routeData.itemId ); //pass process instance ID as params to call
          const url = 'http://localhost:8080/bpmn/' + commandExecutionURI;
          return this.http
            .get<Task[]>(url, {params: params})
            .map(data => _.values(data))
            .do(console.log)
            .share();
        }

}
```
Parent component's HTML:
```
<main>
  <div id="discuss">
    <h3 class="section-title">Discuss: ongoing discussions related to this process </h3>
    <app-discuss></app-discuss>
  </div>
  <h3 class="section-title"> Finish:  Work through the process steps, below</h3>
  <div *ngIf="BPMNTasksCurrent$ | async as BPMNTasksCurrent else loading">
      <mat-card class="task-card" *ngFor="let BPMNTask of BPMNTasksCurrent">
          <mat-card-header>
            <mat-icon >assignment_turned_in</mat-icon>
            <mat-card-title>{{BPMNTask.name}}</mat-card-title>
            <mat-card-subtitle>Step 1 of 3</mat-card-subtitle>
          </mat-card-header>
          <mat-card-content>
            <p>
              {{BPMNTask.description}}
            </p> 
            <app-data-capture 
                (refreshForm)="refreshNextTask($event)" 
                [objectId]=BPMNTask.id 
                [processInstanceId]=BPMNTask.processInstanceId 
                [captureFields]=BPMNTask.dataCaptureFields 
                [enabledCommands]=BPMNTask.enabledCommands>
            </app-data-capture>
          </mat-card-content>
        </mat-card>
  </div>
</main>
<ng-template #loading> <app-loading></app-loading> </ng-template>
```
Child component that hosts Formly form:
```
import { Component, Input, Output, OnInit, EventEmitter } from '@angular/core';
import { FormGroup, } from '@angular/forms';
import { FormlyFormOptions, FormlyFieldConfig } from '@ngx-formly/core';
import {  Task } from '../task';
import { FieldDataCapture, CapturedData } from '../data-cap';
import { Command } from '../command';
import {HttpClient} from '@angular/common/http';
import {  Router } from '@angular/router';
import { AppComponent } from '../app.component';
import {RouteData} from '../route';
import { TaskComponent } from '../case-detail/task/task.component';


@Component({
  selector: 'app-data-capture',
  templateUrl: './data-capture.component.html',
  styleUrls: ['./data-capture.component.css']
})
export class DataCaptureComponent implements OnInit {
 @Input() captureFields: FieldDataCapture[];
 @Input() enabledCommands: Command[];
 @Input() objectId: string;
 @Input() processInstanceId: string;
 @Output() refreshForm: EventEmitter<any> = new EventEmitter();


  form = new FormGroup({});
  model: any = {}; // initialize empty object
  fields: Array<FormlyFieldConfig> = [];

  constructor(private http: HttpClient,
    public router: Router,
    private appComponent: AppComponent) { }

    ngOnInit() {
      console.log('task form object: ');
      console.log(this.captureFields);
      this.fields = this.getFields(this.captureFields); // NEEDED to do this here to ensure this.taskForm has a value
    }


getFields(taskForm: FieldDataCapture[]): FormlyFieldConfig[] {
  let fields: FormlyFieldConfig[] = []; // need to initialize with empty array??
  console.log(taskForm);
  for (let field of taskForm) {
        console.log('field.key: ' + field.key);
        console.log('field.template.label ' + field.templateOptions.label);
         let newField = {
              key: field.key, 
              type: 'input',
              templateOptions: {
                label: field.templateOptions.label,
                placeholder: '',  // this was placehlder in Formly example... typo?
                required: field.templateOptions.required
            }
          };
      fields.push(newField);
    }
      return fields;
    }


  onCommandClick(commandExecutionURI, commandType, objectId, processInstanceId)  {
          console.log('Command execution: ' + commandExecutionURI + ' sent as a: ' + commandType + ' for object id: ' + objectId);
          const url = 'http://localhost:8080/bpmn/' + commandExecutionURI;
          // FIXME: need to remove bpmn from the static URL to make this more generic
          switch (commandType) {
            case 'POST': {
                   const formData: CapturedData = {
                    objectId: objectId,
                    processInstanceId: processInstanceId, // needed when getting next task
                    // FIXME: NB: this.model is just a JSON object like a blob so would need proper validation at some stage
                    capturedData: this.model // FIXME: this does not seem to be populating???
                                    };
                  const postedCommand$ = this.http.post(url, formData)
                    .map((nextTask: Task) => {
                       console.log('next task: ');
                       console.log(nextTask);
                       this.refreshForm.emit();
                                       }
                  );
                  postedCommand$.subscribe();
                  console.log('command URI: ' + commandExecutionURI + 'for objectId: ' + objectId + 'returning model: ');
                  console.log(this.model);
                  break;
            }
            case 'NAVIGATE': {
                  break; // just navigate
            }
          }

        }

        submit() { // used to test as model is not populating??
          if (this.form.valid) {
            alert(JSON.stringify(this.model));
          }
        }
}
```
Child component HTML:
```
<form [formGroup]="form" (ngSubmit)="submit(model)">
    <formly-form [model]="model" [fields]="fields" >

    </formly-form>
</form>
  <mat-action-row>
      <div  *ngFor="let command of enabledCommands" >
          <!-- NOTE: keep button outside of form or it defaults to a form submit!! -->
              <button mat-button (click)="onCommandClick(command.commandExecutionURI, command.commandType, objectId, processInstanceId)">
              {{command.commandName}}
            </button>
      </div>

   </mat-action-row>
```
... and finally, the relevant models (I realize I should be using interfaces here..., but assume that isn't the problem:
```

export class Task {
  id: string ; //	The id of the task.
  name: string; //	The tasks name.
  assignee:  string ; //	The user assigned to this task.
  created:  string; //	The time the task was created. Format yyyy-MM-dd'T'HH:mm:ss.
  due:  string ; //	The due date for the task. Format yyyy-MM-dd'T'HH:mm:ss.
  followUp:  string; //	The follow-up date for the task. Format yyyy-MM-dd'T'HH:mm:ss.
  delegationState:  string; //	The delegation state of the task. Corresponds to the DelegationState enum in the engine. Possible values are RESOLVED and PENDING.
  description:  string; //	The task description.
  executionId:  string; //	The id of the execution the task belongs to.
  owner:  string; //	The owner of the task.
  parentTaskId:  string; //	The id of the parent task, if this task is a subtask.
  priority:	number;	//The priority of the task.
  processDefinitionId:  string; //	The id of the process definition this task belongs to.
  processInstanceId:  string; //	The id of the process instance this task belongs to.
  caseExecutionId:  string; //	The id of the case execution the task belongs to.
  caseDefinitionId:  string; //	The id of the case definition the task belongs to.
  suspended: boolean;
  caseInstanceId:  string; //	The id of the case instance the task belongs to.
  taskDefinitionKey:  string; //	The task definition key.
 // formKey:  string = ''; // FIXME: Camunda error: The form key is not initialized. You must call initializeFormKeys() on the task query before you can retrieve the form key.	If not null, the form key for the task.
  tenantId:  string; //	If not null, the tenantId for the task.
  enabledCommands: [Command];
  dataCaptureFields: [FieldDataCapture];
// see Creating Todo Class in https://www.sitepoint.com/angular-2-tutorial/
    constructor(values: Object = {}) {
        Object.assign(this, values);
    }
}


export class FieldDataCapture {
  key: string;
  type: string ;
  templateOptions: TemplateOptions;
    constructor(values: Object = {}) {
        Object.assign(this, values);
    }
}

export class TemplateOptions {
  type: string ;
  label: string ;
  placeholder: string;
  required: boolean;
  // templateOptions: TemplateOptions;
    constructor(values: Object = {}) {
        Object.assign(this, values);
    }
}
    /**
     * FIXME: DOES Camunda need to know the type??
     * Data from Formly model to backend
     * */
export class CapturedData{
      processInstanceId: string;
      objectId: string; // whatever object is getting the data
      capturedData: string; // sending as a big string...ideally would be an object but formly model doesn't expose enough to parse it.
  }

```

**Comment by aitboudad** [comment]
> I'm just learning Angular and so you will see some bad code

I'm coding bad code too ;p just don't worry there is no perfect code!

ok seems without a deep debugging I can't help, is there any chance to give me a private access to your project ?

**Comment by snoop244** [comment]
Yes - can I PM you to make arrangements?  I'm out of town until next week
so I can't do it this week.  Also I would like to donate to the project, so
lmk your preference for donations.

**Comment by aitboudad** [comment]
take your time, here is my email: a.aitboudad at gmail dot com

**Comment by Ubaid-ur-Rehman** [comment]
Hi,
I am getting the same error.
Can anyone help?
Thanks
