### ISSUE TITLE
className not applied to template

### ISSUE THREAD

**Issue by emiles002** [formly-js/ngx-formly#687]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

json file contains:
[
  {
    "className": "banner",
    "template": "<h5>Title</h5><h3>sub-title</h3>"
  }
]

angular component .css file contains:
formly-field.banner {
   color: white;
   background: black;
}

**Expected behavior**

I expect the rendered html to be reverse color, i.e., white on black

**Minimal reproduction of the problem with instructions**

simple code above

**What is the motivation / use case for changing the behavior?**

changing styles

**Please tell us about your environment:**

Mac OS X (latest), IntelliJ IDE, webpack

* **Angular version:** 2.0.X

5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
tested on my side and seems working to me here is a an example: https://stackblitz.com/edit/angular-nkue6r?file=styles.css

for style you have to add `display: block;` for `formly-field.banner` selector

**Comment by emiles002** [comment]
Thanks! Interestingly, if I put the same css code in the component css file, it does not work. For example, my angular component is called ngx-formly:

@Component({
  selector: 'app-ngx-formly',
  templateUrl: './ngx-formly.component.html',
  styleUrls: ['./ngx-formly.component.css']
})

Putting the style in ngx-formly.component.css does not work. Putting the style in the global style.css works.

**Comment by aitboudad** [comment]
@emiles002 add `::ng-deep` before the [selector](https://stackblitz.com/edit/angular-nkue6r?file=app%2Fapp.component.ts), also I suggest you to learn more about view encapsulation to understand how style is applied in angular

**Comment by emiles002** [comment]
That worked. Thanks for the help and tips. My first angular app, here.

**Comment by Pranjalich** [comment]
Doesn't work for me. Looks like ::ng-deep is deprecated.

**Comment by RedtigerAV** [comment]
> @emiles002 add `::ng-deep` before the [selector](https://stackblitz.com/edit/angular-nkue6r?file=app%2Fapp.component.ts), also I suggest you to learn more about view encapsulation to understand how style is applied in angular

::ng-deep is now deprecated, how can we patch styles by className to custom formly-templates without ::ng-deep and ViewEncapsulation.None?

**Comment by aitboudad** [comment]
related to https://github.com/angular/angular/issues/25160, I would expect a replacement plan from `angular` team (probably [slotted](https://github.com/angular/angular/issues/27614))

**Comment by aitboudad** [comment]
here are some alternatives as I think angular/angular#25160 may take some time to be resolved and it's not recommended to rely on a deprecated feature 😄:

- change the default view encapsulation (https://stackblitz.com/edit/angular-nkue6r?file=app%2Fapp.component.ts):
```ts

@Component({
  selector: 'my-app',
  encapsulation: ViewEncapsulation.Native,
  styles: [`
    formly-field.banner {
      color: white;
      background: black;
      display: block;
    }
  `]
})
export class AppComponent {}
```

- or simply use the global style
