### ISSUE TITLE
Hidden fields are not present in form value

### ISSUE THREAD

**Issue by thiagogjt** [formly-js/ngx-formly#689]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

if a field is marked as hidden (hiddenExpression: true), it will not be present on form.value()

**Expected behavior**

The field must no be showed but its value must be present on form value

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-guyypd?file=app/app.component.ts

**What is the motivation / use case for changing the behavior?**

After submit the form value for update on server, the id field will tell if it is an update or insert.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

5.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.5.3
* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
it's an expected behavior because the hidden field is not part of the form else we should take account of it's validation too.
why not relying on `model` value instead ?

**Comment by lluis-stage** [comment]
So hidden form elements cannot be validated through formly? Is that correct?

**Comment by juristr** [comment]
Exactly. Hidden values shouldn't be in the form value as it should only contain what the user see and compiles.
As @aitboudad mentioned you can rely on the model value however.

**Comment by boufenzi** [comment]
In your  example, how can you change the statut of the hide expression using another formcontrol, for example after i click on a checkbox the hideExpression of the current formControl should change.

**Comment by juristr** [comment]
> example after i click on a checkbox the hideExpression of the current formControl should change.

@boufenzi Can you be more explicit, or maybe create a Stackblitz repro 😃? In the `hideExpression` you have access to the model, so you can use that to hide/show based on the checkbox value (which is mapped onto your model).  
Alternatively you can always use the `hooks` and in the `onInit` of it, you use the form to get a reference to the checkbox control, from which point on you just rely on the plain normal reactive forms of Angular. That is, registering to the valueChanges etc...
