### ISSUE TITLE
Repeating Section in demo creating duplicate id's

### ISSUE THREAD

**Issue by GertB1** [formly-js/ngx-formly#694]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

If you press F12 in the browser and run the introductory example with the repeating section, you will notice errors appearing in the console window. It seems when it creates the second investments element it assign's the same id that causes the below error:
_[DOM] Found 2 elements with non-unique id #formly_9_input_investmentName_0: (More info: https://goo.gl/9p2vKq) <input class=​"form-control ng-untouched ng-pristine ng-valid" id=​"formly_9_input_investmentName_0" name=​"input" aria-describedby=​"formly_9_input_investmentName_0-message" type=​"text">​_

This also causes that the bindings is picking the first element in the array.

Here is the URL to the introductory example:
https://plnkr.co/edit/x4ev1QmJ8gm7USGsJdMQ?p=preview

Thanks
Gert

**Comment by aitboudad** [comment]
hi, I noticed that the example provided is using the old version,
please check the new version https://formly-js.github.io/ngx-formly/examples/advanced/repeating-section
