### ISSUE TITLE
Support for ng-select

### ISSUE THREAD

**Issue by tonyrames** [formly-js/ngx-formly#698]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```
Can the default cascading selectlist changed into ng-select
(https://github.com/ng-select/ng-select)

kindly show an usage of ng-select with cascading list on the default example
provided on site.

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-ntysej

**Comment by aitboudad** [comment]
I think it should be part of demo example

**Comment by tonyrames** [comment]
I meant the  **cascading selectlist** (https://formly-js.github.io/ngx-formly/examples/other/cascaded-select)  as per your demo example and not the multi select

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-qtmgbw

**Comment by aitboudad** [comment]
FYI for  performance reason I updated the demo example, it should work for `ng-select` too.
see:

https://github.com/formly-js/ngx-formly/pull/705/files
https://formly-js.github.io/ngx-formly/examples/other/cascaded-select
