### ISSUE TITLE
Is there any support for data tables?

### ISSUE THREAD

**Issue by diegosliver** [formly-js/ngx-formly#701]
Exists any way to create data tables ?

**Comment by aitboudad** [comment]
can you elaborate more

**Comment by diegosliver** [comment]
Sorry,

I need to build a table from an array of records, each row would list a record, and also have the possibility to have a button to edit that record.

Imagine that you have a city register and want to list those records.

Have a way to pass to the directive the type as being list, passing also the columns and column titles.

I looked for something like this in the documentation but I did not find it.

Exemple:
https://github.com/swimlane/ngx-datatable

**Comment by aitboudad** [comment]
here is a simple example: https://stackblitz.com/edit/angular-gmswdm

**Comment by diegosliver** [comment]
Hello, 
Another example is the integration that exists for AngularJS

http://angular-formly.com/#!/example/integrations/ui-grid

**Comment by thorgod** [comment]
+1 To this idea, I am looking at trying to implement this as well.  

Where columns are dynamic (Not fixed) as well as well as rows. 

[Column Headers] => [ID]        [Input] [Test]
                                    Static      Input    Test

**Comment by aitboudad** [comment]
@thorgod you can do whatever you want just you need to find a better tool/libs :),
updated the example to show how it can be done see https://stackblitz.com/edit/angular-hiihhc

**Comment by aitboudad** [comment]
@diegosliver `ui-grid` doesn't support `angular > 2` yet.
