### ISSUE TITLE
Repeat section button text doesn't update

### ISSUE THREAD

**Issue by AndrewCarney** [formly-js/ngx-formly#702]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
The 'Add More investments' button text cannot be changed in the app.ts file, only in the repeatedSection.ts file

**Expected behavior**
The button text would change to 'Add'

**Minimal reproduction of the problem with instructions**
For example changing the btnText in the snippet below in this plnkr, I would expect the button to display 'Add' but it still shows 'Add More investments' reading it from the repeatedSection.ts file
```
        type: 'repeatSection',
        key: 'investments',
        fieldArray: {
          className: 'row',
          templateOptions: {
            btnText: 'Add',
          },
```
 https://plnkr.co/edit/l6peH8jFj4ygkWB2LQA4?p=preview

* **Angular version:** 5.0.0

**Comment by aitboudad** [comment]
firstly please note that the version used is outdated you should use the new version (https://formly-js.github.io/ngx-formly/examples/advanced/repeating-section)

'Add More investments' can be changed, to change the btn text dunamically try the following code:

```
  type: 'repeatSection',
  key: 'investments',
  templateOptions: {
    btnText: 'Add',
  },
  fieldArray: { ... }
```

and change the text `Add More investments` in `repeat-section.type.ts` into:
```patch
-- <button class="btn btn-primary" type="button" (click)="add()">Add More Investments</button>
++ <button class="btn btn-primary" type="button" (click)="add()">{{ to.btnText }}</button>
```

**Comment by AndrewCarney** [comment]
Thanks, moving the templateOptions and btnText into the level above the fieldArray worked well! One other question on this, is it possible to hide the button based on an earlier element in the form?

In the example below I would be looking to hide the repeat section unless the user selected "Yes" in the radio button

```
{
  template : '<hr /><strong>Question to determine whether repeat section shows?</strong>'
},
{
  key : 'section.show',
  type : 'radio',
  templateOptions: {
    options:[
      {key: 'Yes', value : 'Yes'},
      {key: 'No', value : 'No'}
    ]
  }
},
{
  key: 'rptSection',
  type: 'repeat',
  templateOptions: {
    btnText: 'Add',
    },
  fieldArray: {
    fieldGroupClassName: 'display-flex',
    hideExpression: 'model.section.show !== "Yes"',
    fieldGroup: [
          {
            key: 'location',
            type: 'input',
            templateOptions: {
              type: 'input',
              label: 'enter',
              placeholder: 'enter'
            },
          },
      ],
   },
},
```

**Comment by aitboudad** [comment]
use `hideExpression` property:
```ts
{
  key: 'rptSection',
  hideExpression: (model) => model.section.show !== 'Yes',
 ...
}
```

**Comment by AndrewCarney** [comment]
Sorry to bother you again, but I can't get that to work. I get an error: Cannot read property 'show' of undefined. I've also tried putting the yes in double quotation marks but that doesn't work either. Any ideas?

**Comment by aitboudad** [comment]
ahh I see, you need to have access into the main model:
see my comment https://github.com/formly-js/ngx-formly/issues/704#issuecomment-364661614

**Comment by AndrewCarney** [comment]
Thanks for all your help, that works now!
