### ISSUE TITLE
SetErrors on FormControl doesn't show the errors on the field

### ISSUE THREAD

**Issue by Constantinos-Impact** [formly-js/ngx-formly#703]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

When setting the error on FormControl formly doesn't show the errors.
`this.form.get('name').setErrors({'error':'error'});`

Here is an [example](https://angular-formly-jmbure.stackblitz.io) of that behavior.

The idea is to show server site validation errors on the controls same as shown with the angular validators without the need to setup custom validators. Just get the errors from the api response and set the fields with the errors using `this.form.get('name').setErrors({'error':'error'});`

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-formly-x8ugdz

you just need to register a custom validationMessages for `server-error` key:
```ts
  FormlyModule.forRoot({
    validationMessages: [
      {name: 'server-error', message: (err) => err },
    ],
  }),
```
and to display server error use the key `server-error`:
```ts
this.form.get('name').setErrors({'server-error':'error'});
```

**Comment by Constantinos-Impact** [comment]
Thanks @aitboudad :)

**Comment by aitboudad** [comment]
**Note**: update the above example into a simplified way, all you've to do is to pass an object with the server message (there is no need to register it throughout NgModule declaration).

**Comment by vardhan1122** [comment]
This not working..., Could you please send proper code?

**Comment by aitboudad** [comment]
@vardhan1122 check `setErrors` method in the above `stackblitz` example (the code is included)
