### ISSUE TITLE
Support for Typeahead 

### ISSUE THREAD

**Issue by phani2791** [formly-js/ngx-formly#708]
I'm submitting a feature request
**Current behavior**
No support for Typeahead in the present version

**Expected behavior**
 Typeahead behavior.

**Comment by aitboudad** [comment]
it's depend on which plugin you want to use, here is an example using `ng-select`:
https://stackblitz.com/edit/angular-ngx-formly

**Comment by zbralex** [comment]
```
fields: FormlyFieldConfig[] = [
    {
      key: 'state',
      type: 'select',
      templateOptions: {
        placeholder: 'Search for a state:',
        search$: (term) => {
          if ((!term || term === '')) {
            return observableOf(states);
          }

          return observableOf(states.filter(v => v.toLowerCase().indexOf(term.toLowerCase()) > -1).slice(0, 10));
        },
      }
    },
  ];
```
in your example, you are setting the **search$** function property. How can I set this feature if I receive fields from the server?
