### ISSUE TITLE
Material matPrefix and matSuffix directives don't work in a form-field wrapper

### ISSUE THREAD

**Issue by antegadzo** [formly-js/ngx-formly#715]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

I add the Material date-picker type and added a form-field wrapper to this type.

Example of mat-datepicker-toggle with **matSuffix**:
```html
<mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
```
Then I realized that **matSuffix** and **matPrefix** did not work when they are in a wrapper.
I want to add suffixes and prefixes to other types but can't because they do not work when they are in a wrapper. Now I'm trying to customize form-field wrapper.

Here I created an example:
https://stackblitz.com/edit/angular-3sdpwq

I would appreciate some help.

**Comment by aitboudad** [comment]
true, there is a pending issue in material https://github.com/angular/material2/issues/6728

**Comment by aitboudad** [comment]
I'll try to find a workaround since it'll take time to be solved form `material2`

**Comment by aitboudad** [comment]
I simplified the creation a custom field type for material, all you have todo is to wrap your prefix/suffix inside a `<ng-template #matSuffix>` and extends `FieldType` from `@ngx-formly/material`:

```ts
@Component({
  selector: 'app-form-datepicker-type',
  template: `
    ....
    <ng-template #matSuffix>
      <mat-datepicker-toggle [for]="picker"></mat-datepicker-toggle>
    </ng-template>
  `,
})
export class DatepickerTypeComponent extends FieldType {}
```
see https://stackblitz.com/edit/angular-jr89x1

**Comment by antegadzo** [comment]
Thank you very much
