### ISSUE TITLE
Reset field when it is disabled/hidden

### ISSUE THREAD

**Issue by Etchelon** [formly-js/ngx-formly#723]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```
I'd like to be able to specify, just by JSON configuration, that a field's value must be reset upon a certain event. The most common use case is: I choose "other..." from a select item, and a textarea with additional details becomes enabled; if I then change the select value, the textarea should reset.

**Current behavior**
I am currently unable to find how to achieve this behavior, either because it's not implemented or I can't find the documentation/example

**Expected behavior**
To be able to write something like:
```
{
    key: "detailsField",
    expressionOptions: {
        "model.detailsField": "templateOptions.disabled ? '' : model.detailsField"
    }
}
```

**Minimal reproduction of the problem with instructions**
Cannot reprodure a feature request

**What is the motivation / use case for changing the behavior?**
To prevent dirty values from remaining in the model when the associated control is actually disabled or invisible

* **Angular version:** 2.0.X
Angular @latest

**Comment by aitboudad** [comment]
try with:
```ts
"model.detailsField": "this.field.templateOptions.disabled ? '' : model.detailsField"
```

**Comment by Etchelon** [comment]
Unfortunately not working. I'll try to investigate further.

**Comment by aitboudad** [comment]
I'll provide you an example

**Comment by aitboudad** [comment]
Seems it doesn't work properly, I'll try to see what's going wrong.

**Comment by Etchelon** [comment]
I’m not at the pc right now but, if it can help, I’ve noticed earlier that another expression that has model as target gets update, just the UI doesn’t.
I’ve created an input with an expression that calculates its value based on other form field values. Using the model | json to show the model state showed the calculated value correctly. The input element however always showed 0 and didn’t update.
When I get to work again I’ll provide more details

**Comment by Etchelon** [comment]
As u can see, the disabled input should display 21, which is calculated from 2 other values (30 and 14).
The model actually gets updated, just the control doesn't:

![image](https://user-images.githubusercontent.com/4141889/36340087-db9ed6d2-13d4-11e8-98f8-0af643645d66.png)

The expression I've used is:
`expressionProperties: {
					"(model.was_smoker || {}).smokingPacksPerYear": "(((model.was_smoker || {}).sigarettesPerDay * (model.was_smoker || {}).smokingForYears) || 0) / 20"
				}`

**Comment by aitboudad** [comment]
the key should follow `model.key` and not `(model || {}).key` in order to take account of it's value

**Comment by aitboudad** [comment]
fixed and released under `2.0.0-rc.26`.

**Comment by Etchelon** [comment]
I had to use (model.key.nested_object || {}).key because at initialization nested_object was undefined, but now it works fine, great! Thanks!

**Comment by Etchelon** [comment]
One last thing. This:

![image](https://user-images.githubusercontent.com/4141889/36370532-6907a5d6-155f-11e8-8536-e0ee0035b5e0.png)
doesn't work because "cannot read property indexOf of undefined. I have to write:
`"templateOptions.disabled": "(model.smoker_what || {}).indexOf('altro') === -1"`

**Comment by aitboudad** [comment]
it's ok, just avoid using that syntax for key also providing a default value for model would solve the issue:

```ts
expressionOptions: {
  // ok
  "model.detailsField": "whatever"
  // not ok
  "(model || {}).detailsField": "whatever"
}
```

**Comment by HarshitChhipa** [comment]
disable does not work with multiple keys.
Where there is nesting of keys it breaks and says undefined of key.

**Comment by aitboudad** [comment]
@HarshitChhipa `formly` doesn't touch the passed model until you explicitly set `defaultValue`,
 either check the model value before accessing to its value or initializes it using `defaultValue`

https://stackblitz.com/edit/angular-1fosq5-wkjfvw

**Comment by jesseboydgsa** [comment]
![image](https://user-images.githubusercontent.com/58823468/88240664-a1a0de80-cc3c-11ea-8e64-812476869b3d.png)

This is how I cleared the value when the field is hidden

**Comment by aitboudad** [comment]
@jesseboydgsa see https://github.com/ngx-formly/ngx-formly/issues/2381#issuecomment-662953993
