### ISSUE TITLE
Form validation and hidden fieldGroups

### ISSUE THREAD

**Issue by IustiNN** [formly-js/ngx-formly#731]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

Currently I have a really big form with multiple use cases based on a few select inputs. So if the user selects an option form the first select input I show different fieldGroups.

The problem I have is that in the beginning only the displayed inputs have values in the model ( I think it's normal ) but even though all the hidden options are required, after the user completes the first 4 inputs displayed, the form is VALID even though the initially hidden inputs are empty.

**Expected behavior**

How can I stop the form from being valid even though there are empty inputs ?
Thank you !

**Minimal reproduction of the problem with instructions**

This is just a small portion of the form. There are actually several select inputs and based on their values I show other fieldGroups.
```
   for (let i in this.users) {
            this.fields = [...this.fields,
                {
                    className: "section-label",
                    template: `<h2>User ${i + 1}</h2><hr />`,
                },
                {
                    fieldGroupClassName: "row",
                    fieldGroup: [
                        {
                            key: `users[${i}].firstName`,
                            type: "input",
                            className: "col-6",
                            templateOptions: {
                                label: "Prenom",
                                required: true,
                            },
                        },
                        {
                            ...
                        },
                    ]
                },
                {
                    fieldGroupClassName: "row",
                    fieldGroup: [
                        {
                            ...
                        },
                        {
                            key: `users[${i}].status`,
                            type: "select",
                            className: "col-6",
                            templateOptions: {
                                options: [
                                    {label: "Sélectionner", disabled: true, value: null},
                                    {label: "Etudiant", value: "student"},
                                    {label: "Independant", value: "freelancer"},
                                    {label: "Salarie", value: "employed"},
                                ],
                                label: "Status",
                                required: true,
                            },
                        },
                    ]
                },
                // Situation if student is selected
                {
                    className: "section-label",
                    hideExpression: `model.locataires[${i}].status != 'student'`,
                    template: `<hr /><h4>Situation de l'etudiant</h4>`,
                },
                {
                    fieldGroupClassName: "row situation",
                    hideExpression: `model.users[${i}].status != 'student'`,
                    templateOptions: {label: "Situation de l'etudiant" },
                    fieldGroup: [
                        {
                            key: `locataires[${i}].revenue`,
                            type: "input",
                            className: "col-6",
                            templateOptions: {
                                type: "number",
                                addonRight: {
                                    class: "fa fa-euro"
                                },
                                label: "Revenus nets",
                                required: true,
                            },
                        },
                        {
                           ...
                        },
                        {
                            ....
                        },
                    ]
                },
...
...

] };
```
               
* **Angular version:** 5.0.X

* **Browser:** [all]

**Comment by aitboudad** [comment]
still not clear to me, if `fieldGroups` is hidden then all it's fields should not affect the form validation. is that what you asked for ?

**Comment by IustiNN** [comment]
If they are hidden they should not affect the validation. But after I select a value from the select input, they are visible and required so should affect validation.

**Comment by aitboudad** [comment]
given a form that contains one field: `firstname`, if `firstname` is required and hidden then the should be valid and that's an expected behavior.
can you provide me a reproduction example here is a good start: https://stackblitz.com/edit/angular-fkdaxi
Thanks!

**Comment by IustiNN** [comment]
Hello. Thanks for taking time to look into my problem. So exactly the same thing I want to happen in my form, the same as in your example.

I tried to replicate my problem using a small example, but strangely it was still working. So I'm sure it must be something about my implementation. I ended up putting almost all my form in there, sorry for that.

https://stackblitz.com/edit/angular-heko5x

But there is a different thing happening. On stackblitz if I check form.value, all the inputs in the form has a null value. In my app, only the first 4 inputs (initially visible) have a null value, hence the form valid after completing only these inputs.

Sorry if I'm not clear enough, I'm new to Angular and also it's the first time I use formly.

Thanks again.

**Comment by aitboudad** [comment]
I'm able to reproduce it, thanks!

**Comment by aitboudad** [comment]
it should work now using `2.0.0-rc.29` version.

**Comment by IustiNN** [comment]
Thank you so much! It works like a charm now.
