### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by sefas90** [formly-js/ngx-formly#737]
I can't install because I have this error... and I don't know why

npm install ngx-formly/core
+-- UNMET PEER DEPENDENCY angular/core 4.4.6
+-- UNMET PEER DEPENDENCY angular/router 4.4.6
`-- ngx-formly/core@2.0.0-rc.29

ang I have 

ng -v
angular/animations: 4.4.6
angular/common: 4.4.6
angular/compiler: 4.4.6
angular/core: 4.4.6
angular/forms: 4.4.6
angular/http: 4.4.6
angular/platform-browser: 4.4.6
angular/platform-browser-dynamic: 4.4.6
angular/router: 4.4.6
angular/cli: 1.0.0
angular/compiler-cli: 4.4.6

**Comment by aitboudad** [comment]
```patch
-- npm install ngx-formly/core
++ npm install @ngx-formly/core
```

**Comment by sefas90** [comment]
npm install @ ngx-formly/core
+-- UNMET PEER DEPENDENCY @ angular/core @ 4.4.6
+-- UNMET PEER DEPENDENCY @ angular/router @ 4.4.6
`-- @ ngx-formly/core @ 2.0.0-rc.29

**Comment by aitboudad** [comment]
sorry but I'm not able to reproduce your issue, try to add it manually on your `package.json`:
```json
"@ngx-formly/core": "^2.0.0-rc.29",
```
and then use:
```batch
npm install
```
