### ISSUE TITLE
Additional blank field in select dropdown

### ISSUE THREAD

**Issue by shaunmnemonic** [formly-js/ngx-formly#739]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Currently, when using a select field type, an additional blank value is added to the options. Setting the `default_value` does allow you to pre-select, but upon activating the dropdown, the first blank value is still selectable. 

**Expected behavior**
No additional blank field.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-fsudff

* **Angular version:** 2.0.X
5.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by IustiNN** [comment]
I have the same problem.
