### ISSUE TITLE
[SUPPORT] ChildModule having type extending ParentModule

### ISSUE THREAD

**Issue by jogelin** [formly-js/ngx-formly#746]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
I am trying to configure multiple modules with child configuration and I don't know why my model is not updated on my child module

**Expected behavior**
Model should be update and the validators & pattern functions should be used

**Minimal reproduction of the problem with instructions**
[StackBlitz example](https://stackblitz.com/edit/formly-mask-nested-configs)

**FormCoreModule** : 

- import FormlyModule.Core() + FormlyMaterialModule
- contain a common configs: type `input-mask` + validationMessages

**FormFeatureModule** : 

- import FormCoreModule + import FormlyModule.Child()
- contain specific type `nrn-field` that extends the type `input-mask` and specify the config and default option

**Comment by aitboudad** [comment]
importing `ReactiveFormsModule` is missing in `FormlyCoreModule`. once added it should work also please note that you can use `forChild` to add extra config in the child module.

**Comment by jogelin** [comment]
Sorry, my bad ! Thx a lot
