### ISSUE TITLE
JSONPowered issue while using API call

### ISSUE THREAD

**Issue by rameshpalipi** [formly-js/ngx-formly#747]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
https://formly-js.github.io/ngx-formly/examples/other/json-powered
replace the  user.service.ts  getUser() with API call.
getUser() {
    return return this.http.get<FormlyFieldConfig[]>('http://www.mocky.io/v2/5a90c76d2f00002b006cad19');
  }
throwing error:
ERROR TypeError: this.validator is not a function
    at FormControl.AbstractControl._runValidator (forms.js:3378)
    at FormControl.AbstractControl.updateValueAndValidity (forms.js:3332)
    at new FormControl (forms.js:3850)
    at FormlyFormBuilder.addFormControl (formly.form.builder.js:225)
    at eval (formly.form.builder.js:71)
    at Array.map (<anonymous>)
    at FormlyFormBuilder.registerFormControls (formly.form.builder.js:35)
    at FormlyFormBuilder.buildForm (formly.form.builder.js:31)
    at eval (formly.form.builder.js:87)
    at Array.map (<anonymous>)

**Expected behavior**
should work same using local JSON files.  Not sure how to delay this.validator till API response being received. 
Would like to see an example real API call. ( using API mocking online tools like https://www.mocky.io/)

**Comment by aitboudad** [comment]
I tried your example but didn't get any issue, see https://stackblitz.com/edit/angular-grqlsh?file=app%2Fuser.service.ts

Ensure you have the latest version.

**Comment by rameshpalipi** [comment]
Thank you.
Got latest version.
I tried and working fine having "GET" call.
Issue start when you replace the "GET" with "POST" 

getFieldsAPICall() {
    let body = { action: 'getJSON', formName:'userForm'};
    let bodyString = JSON.stringify(body); // Stringify payload
    let url = 'https://REST API URL';
    const headers = new HttpHeaders({ 'Content-Type': 'application/json; charset=utf-8' });
    return this.http.post<FormlyFieldConfig[]>(url, bodyString,
      {
        headers: new HttpHeaders().set('Content-Type', 'application/json')
      });
  }

AppComponent.html:2 ERROR TypeError: this.validator is not a function
    at FormControl.AbstractControl._runValidator (forms.js:3416)
    at FormControl.AbstractControl.updateValueAndValidity (forms.js:3370)
    at new FormControl (forms.js:3888)
    at FormlyFormBuilder.addFormControl (core.es5.js:992)
    at eval (core.es5.js:779)
    at Array.forEach (<anonymous>)
    at eval (core.es5.js:774)
    at Array.forEach (<anonymous>)
    at FormlyFormBuilder.registerFormControls (core.es5.js:762)
    at FormlyFormBuilder._buildForm (core.es5.js:751)

**Comment by aitboudad** [comment]
it doesn't make sense, probably the issue is related to the response,
can you please show me the response content ?

**Comment by rameshpalipi** [comment]
Here is the request: 
[{"fieldGroup":[{"className":"row","fieldGroup":[{"className":"col-xs-6","key":"email","type":"input","templateOptions":{"type":"email","label":"Email address","placeholder":"Enter email"},"validators":{"validation":"Validators.compose([Validators.required])"}},{"className":"col-xs-6","key":"password","type":"input","templateOptions":{"type":"password","label":"Password","placeholder":"Password","pattern":""},"validators":{"validation":"Validators.compose([Validators.required])"}}]}]}]

**Comment by aitboudad** [comment]
the validation part is not valid `Validators.compose` is only possible when providing field-config using javascript not json.

you can use [built-in validations](https://formly-js.github.io/ngx-formly/examples/validation/built-in-validations):

```json
"key": "name",
"type": "input",
"templateOptions": {
  "required": true,
},
```

 Or define a custom one, see the example: [IP Address (using custom validation declared in ngModule)](https://formly-js.github.io/ngx-formly/examples/validation/custom-validation)

```json
"key": "name",
"type": "input",
"validators": {
  "validation": ["ip"]
}
```

**Comment by rameshpalipi** [comment]
Just want confirm what are the limitations if we use JSON driven 
 https://github.com/formly-js/ngx-formly 
vs using field-config using Javascript. As one would want to make changes to UI look & feel , validations and simple business logic via ngx-formly instead of requiring a deployment.

**Comment by aitboudad** [comment]
for a simple business logic I think there is no limitation.
