### ISSUE TITLE
Formly error when trying to use with @ngx-formly/bootstrap

### ISSUE THREAD

**Issue by gruntz12** [formly-js/ngx-formly#752]
**I'm submitting a ...**  
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x ] support request
```

**Current behavior**
Error: [Formly Error] There is no type by the name of "input"

**Expected behavior**
Working form with bootstrap

**Minimal reproduction of the problem with instructions**
I'm following the official tutorial but can't get working form with @ngx-formly/bootstrap. It's look like the @ngx-formly/bootstrap field config doesn't load

* **Angular version:** newest with angular cli

**Comment by aitboudad** [comment]
just followed the tutorial steps and everything seems working, ensure that `@ngx-formly/core` and `@ngx-formly/bootstrap` match the same version on your package.

see https://stackblitz.com/edit/angular-138ggc

**Comment by gruntz12** [comment]
Ohh.. Yes, they were not the same. Thanks!
