### ISSUE TITLE
The syntax to create validators change ¿why? 

### ISSUE THREAD

**Issue by davidoween** [formly-js/ngx-formly#757]
Hello, in my team we used the following syntax to add validators to our fields. But it seems that the way to add validators has been changed. Why has it been changed? Is it possible to reuse the previous syntax? We are developing a big project and This has been broken  
{key:"example" 
validators = {
          validation: Validators.compose(arrayFunctionsvalidators), // syn
        };

**Comment by aitboudad** [comment]
it shouldn't be, can you please provide me a working example https://stackblitz.com/edit/angular-rorusy

**Comment by davidoween** [comment]
Tomorrow I send it to you. Thanks

**Comment by davidoween** [comment]
Hello, this is the minimal example. I detected the problem. it is necessary that the field be required to do the validation. That was the problem. This is a bug.

https://stackblitz.com/edit/angular-wkijpa?file=app/app.component.ts

**Comment by aitboudad** [comment]
I don't see where is the issue, can you elaborate please, Thanks!

**Comment by davidoween** [comment]
This example works great, because the field has require: true.
https://stackblitz.com/edit/angular-ubjmg7?file=app/app.component.ts

But... if I remove require: true, the error message doesn't appear, althought the field is invalid.
https://stackblitz.com/edit/angular-tr7qbk?file=app/app.component.ts
