### ISSUE TITLE
Use repeat section inside repeat section

### ISSUE THREAD

**Issue by iustin-nita** [formly-js/ngx-formly#761]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

I'm trying to use a repeat section inside another repeat section. 
The parent repeat section is an Array, as it should, but the child repeat section is converted to Object.

So the problem is when I click on the button to add a new child repeat section I get the error 
`app.js?1519842509:27270 Uncaught TypeError: this.model.push is not a function`

If I check form.value everything is good (the child repeat section is an array also). But in the model it is an object.

**Expected behavior**

Both repeat sections to be arrays.

**Minimal reproduction of the problem with instructions**

Form Value: {
  "users": [
    {
      "investmentName": "daf",
      "investmentDate": "0432-03-12",
      "stockIdentifier": "fasdf",
      "jobs": []
    }
  ]
}
model.users Value: [
  {
    "jobs": {},
    "investmentName": "daf",
    "investmentDate": "0432-03-12",
    "stockIdentifier": "fasdf"
  }
]

**Comment by aitboudad** [comment]
reproduction please :pray: https://stackblitz.com/edit/angular-rorusy

**Comment by aitboudad** [comment]
Would you like I release a new version now or wait until tomorrow ?

**Comment by iustin-nita** [comment]
It would be really great now if you can.
Thanks a lot!

**Comment by aitboudad** [comment]
done!

**Comment by iustin-nita** [comment]
You rock!

**Comment by iustin-nita** [comment]
Hello again. Do you have any idea of how could i reach the model of the parent repeat section? 

I need to hide the child repeat section based on a value from the parent one. But in my hideExpression I only have access to model (which contains only the values of the child section) and formState.parentModel (which I can't use because I don't know the indexes of the parents/child).

**Comment by aitboudad** [comment]
it's clear but an example is always helpful

**Comment by iustin-nita** [comment]
Ok, here it is: https://stackblitz.com/edit/angular-gsdrfs

**Comment by aitboudad** [comment]
There is no easy way for that, can you fill an issue as a feature ?

in the meantime I found a workaround but it's ugly https://stackblitz.com/edit/angular-kxgrdj.
firstly you should overide `add` function in `Repeat1TypeComponent` and `Repeat2TypeComponent` then in order to access to the parent mdoel, you should call `getParentModel` which require passing the current `field` and the level of parents (in your case it's 3) also `hideExpression` should be define as a `function` not arrow function.

it's just a temporary solution, we should find a better way but it will take a long time so.

**Comment by iustin-nita** [comment]
I am actually trying to hide the whole repeat2 section before completing an input in repeat1.
But gladly, I think I can use your workaround. I just moved the hideExpression to the repeat2 and changed the level of parents to 1.

`hideExpression: function() {
              const model = getParentModel(this.field, 1);
              if (model && model.investmentName === "asd") {
                  return true;
              }
            },
`

That was not the correct version of the stackblitz... I edited it 1 minute after I posted.  

Thanks a lot for taking time to help me with this and I'll open a issue later today!

**Comment by iustin-nita** [comment]
Actually this works only if model is empty and I add all my sections. If I already have a populated model it's not working :(

**Comment by aitboudad** [comment]
try to override [createControl](https://github.com/formly-js/ngx-formly/blob/master/src/core/src/templates/field-array.type.ts#L10) too, similar to `add` method.

**Comment by iustin-nita** [comment]
I tried but I can't make it work. I mean I don't know how to override it.

**Comment by aitboudad** [comment]
updated the example https://stackblitz.com/edit/angular-kxgrdj.

**Comment by iustin-nita** [comment]
Thanks, but it's not working.
https://stackblitz.com/edit/angular-hnymwo
Now when a model exists the form crashes and returns`TypeError: Cannot set property 'parent' of undefined`
Both in your updated example and in my app.

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-1rszh6

```patch
in asignParentField:
++ field.templateOptions = field.templateOptions || {};
++ f.templateOptions = f.templateOptions || {};
```

**Comment by iustin-nita** [comment]
You are a life saver 👍 And sorry for being such a pain in the ass.

Thx again! You're doing a great job

**Comment by albertthinc** [comment]
Hi

This is not working for me.
When I tried to implement, in the RepeatTypeComponent I am getting an error 

"Property 'createControl' does not exist on type 'typeof FielsArrayType'.

Can you please help me on this.

Thanks
