### ISSUE TITLE
Be able to access the parent model when using two repeat sections

### ISSUE THREAD

**Issue by iustin-nita** [formly-js/ngx-formly#764]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**

I am using two repeat sections on the same form. The second one is part of the first one.
 
I need to hide the child repeat section based on a value from the parent one.
But in my hideExpression I only have access to model (which contains only the values of the child section) and formState.parentModel (which I can't use because I don't know the indexes of the parents/child).

**Expected behavior**

Be able to access the parent repeat section model.

**Minimal reproduction of the problem with instructions**

Reproduction here: https://stackblitz.com/edit/angular-gsdrfs

**What is the motivation / use case for changing the behavior?**

I need to hide the second repeat section until a field from the first one is completed.

**Comment by aitboudad** [comment]
in `v3`, the model value can be retrieved from the field instance:
```ts
const value = field.model;
```

**Comment by thorgod** [comment]
Sounds good I will work on creating a PR to access parent field. (This should gain access to the model of the parent.)
