### ISSUE TITLE
When custom validator return null, the errors object contains {"0": true}

### ISSUE THREAD

**Issue by jogelin** [formly-js/ngx-formly#765]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When I create a simple input field and I specify a custom validator, by default, even if my validator is returning `null`, the `errors` of the `FormControl` is:

```
{
  "0": true
}
```

**Expected behavior**
If a validator is return null, the `errors` object should be empty

**Minimal reproduction of the problem with instructions**
See [Stackblitz](https://stackblitz.com/edit/angular-formly-max-length-validators?file=app%2Fapp.component.ts)

**Comment by jogelin** [comment]
I am stupid...I did:

```
validators: [ForceLengthValidators.maxLength(50)]
```

instead of 

```
      validators: {
        validation: [ForceLengthValidators.maxLength(50)]
      }
```

**Comment by aitboudad** [comment]
`validators` API should be improved to avoid a such confusion :)
