### ISSUE TITLE
RepeatTypeComponent not working properly

### ISSUE THREAD

**Issue by juristr** [formly-js/ngx-formly#768]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

Using the [repeat example](https://formly-js.github.io/ngx-formly/examples/advanced/repeating-section), it seems like there's an issue since the last change of the `repeat` since it started extending from the `FieldArrayType`.

This might either be my misunderstanding in properly using it, or a bug. Taking the current example on the website, if the `investments` are loaded later, asynchronously and then added to the model, the model doesn't reflect this change on the fields.

**Expected behavior**

As said, somehow it should recognize the changes and generate the new fields. Right now, when clicking the "Add More Investements" button, the fields are correctly bound, so it seems to be an issue with the creation of the fields only.

**Minimal reproduction of the problem with instructions**

Here's a Stackblitz example that shows the wrong behaviour: https://stackblitz.com/edit/angular-ngxformly-repeat

* **Angular version:** 5.0.1

Also willing to submit a PR if I get some guidance where to fix the thing

**Comment by aitboudad** [comment]
> Also willing to submit a PR if I get some guidance where to fix the thing

just replace the [formly.form.ts#L50](https://github.com/formly-js/ngx-formly/blob/master/src/core/src/components/formly.form.ts#L50) with

```ts
this.resetModel(this.model);
```

Then to take account of model changes you should replace the hole model:
```ts
      this.model = {
        ...this.model,
        investments: [
          {
            investmentName: 'bitcoin',
            stockIdentifier: 'abc'
          },
          {
            investmentName: 'bitcoin2',
            stockIdentifier: 'abc2'
          }
        ]
      };
```
