### ISSUE TITLE
Upgrade Angular dependencies

### ISSUE THREAD

**Issue by juristr** [formly-js/ngx-formly#769]
I'm **currently working on this**. A PR will follow shortly

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**What is the motivation / use case for changing the behavior?**

Currently there's otherwise an issue that on some machines (apparently) the examples page of the demo app doesn't start.

**Tasks**

- [x] Upgrade dependencies (currently working on [here](https://github.com/juristr/ng-formly/tree/angular-deps-upgrade))
- [ ] Adjust library packaging with `ng-packagr` (currently working on [here](https://github.com/juristr/ng-formly/tree/nx-workspace-setup))

**Comment by juristr** [comment]
@aitboudad Status update: will have some time probably next week to work on this and hopefully finish it. I'll send you a PR. It's not just the updating of the deps, which I already have. But a setup similar to what I tested here: https://github.com/juristr/ngx-tabs-libdemo/tree/with-demoproj-setup

Will let you know

**Comment by aitboudad** [comment]
if you're looking for a workaround to make `ng-packagr` working with the current base, see https://github.com/aitboudad/ngx-loading-bar/blob/next/.config/ng-packagr.patch ;)
