### ISSUE TITLE
Advice please: custom value returning (getter) for form element

### ISSUE THREAD

**Issue by nop1984** [formly-js/ngx-formly#771]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x ] support request
```

What I am trying to do, is create a new field type based on custom Component. Lets imagine for simplicity this component is just a `<div>Any text to show on screen</div>`.
I want this Component to return a just a constant value, e.g. "I am a result of form for Custom Component".
I want this to be reactive or on submit.
I have reproduced a expample from ngx-formly repo. I have created new FieldType for Formly. All works if Component is classic `<input>` or `<textarea>`, I get the value back on Formly submit. But I wish to learn to return a value of <div> because later I need this knowledge for embeding in Formly custom Table component which gonna "ask" each its cell per row to return a value of cell (cells store objects, key needed for existing in DB objects or representation to create new in DB)

Help please to learn how to return a value from `<div>`

I have tried to implement Component from ControlValueAccessor with providing NG_VALUE_ACCESSOR, extending AbstractControl ... no luck

UPD. Stackblitz example https://github.com/formly-js/ngx-formly/issues/771#issuecomment-370526362

**Comment by aitboudad** [comment]
still not clear to me what do you want to achieve, maybe I can understand by providing an example, here is a starter example https://stackblitz.com/edit/angular-138ggc

**Comment by nop1984** [comment]
@aitboudad thanks for help with starter, using stackblitz first time, will to example asap right now

**Comment by nop1984** [comment]
Here it is. https://stackblitz.com/edit/angular-formly-custom-control-value-get2

"I expect this text to get in form reactive model/submission" -- this text I wish to get as value from form.
I have ommited all experimental code I was using to reach expected behaviour.

P.S. Also noticed my initial git post markup broken - will fix it now

**Comment by aitboudad** [comment]
if I understand, you want the div content to be part of form ?

**Comment by nop1984** [comment]
@aitboudad yes, I want him to return his "value" to form, to behaive native to Form API. 
To set a value I have to implement ControlValueAccessor interface and redefine writeValue() method. But what should I do to make him to return a value to form model ?

P.S. Later I will use this practice to embed in Fromly a Table component which will return to form its value, looping per row and asking each cell its value.

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-formly-custom-control-value-get2-ksayel

**Comment by aitboudad** [comment]
here is an example of formly withing table https://stackblitz.com/edit/angular-gmswdm

**Comment by nop1984** [comment]
@aitboudad thanks a lot! I will dive in ngx-datatable to formly example later.

On the example with div you used AbstractControl::patchValue() which changes a value property as I understand. In which class this value actually stored? https://angular.io/api/forms/AbstractControl#value declares it is in AbstractControl:: get value but github code says its public readonly value: any

There is no chance to have value getter? (`get value():any {return "My constant text to return"}`) ?

**Comment by aitboudad** [comment]
the value is store in the `FormControl` class and can be retrieved from main model, why you want to use a getter ?

**Comment by nop1984** [comment]
@aitboudad asking just have imagination/knowledge 

Yet right now to use patchValue() each time any cell of table changes looks complicated, I imagined it getter of value before got your answer ... Will reconsider all tomorrow on fresh head (its 22:21 here in UA)
Thanks much for help! I would lost few days more on experiments if not your swift answer.

**Comment by aitboudad** [comment]
using getter will not solve your issue you have to find a way to detect changes in the DOM then call `patchValue`,
but honestly the way you want to achieve that kind of task looks wrong to me ;)

**Comment by nop1984** [comment]
May be you are right, it would be more clear to me after I play with solution you have found to me tomorrow. 
In my case with table - each cell has own component to display/edit value and each cell stores its value. So value of table dont existis physically and assembled on demand and to store and update a value looks like memory overusage for me now (as actually its a copy of each cell data)
