### ISSUE TITLE
this.options.showError is not a function

### ISSUE THREAD

**Issue by Pat-Lovelace** [formly-js/ngx-formly#774]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
I'm trying to upgrade a project which was using a previous version of ngx-formly, specifically 2.0.0-rc.17.

My FormlyModule config is:

```typescript
FormlyModule.forRoot({ 
      wrappers: Config.wrapper(),
      types: Config.types() ,
      validationMessages: Config.messages(),
    })
```

Config is a class with static methods to get my wrappers, types and messages.

This config worked great, but I wanted to have the new features of Formly in my project.

When I try to upgrade to version 2.0.0.rc-35, I get the next error: **this.options.showError is not a function**. I don't modify the _showError_ function in anyway in my project, so... it is supposed to use the default function implemented. 

I checked that the next function...:
```typescript
    Object.defineProperty(Field.prototype, "showError", {
        /**
         * @return {?}
         */
        get: function () { return this.options.showError(this); },
        enumerable: true,
        configurable: true
    });
```
In the version: 2.0.0-rc.17: this.options.showError is the function: 

```typescript
f (field) {
return field.formControl && field.formControl.invalid && (field.formControl.touched || (field.options.parentForm && field.options.parentForm.submitted) || (field.field.validation && field.field.validation.show));
```

In the version: 2.0.0-rc.35: this.options.showError is undefined.

I checked the error begins since version 2.0.0-rc.20.

**Expected behavior**
I don't see anything related to this problem in the changelog, so... is there any specific configuration of the FormlyModule for this?

Thank you. 

Updated:

If I use the following config, I get the same error:

```typescript
FormlyModule.forRoot({
      wrappers: Config.wrapper(),
      types: Config.types(),
      validationMessages: Config.messages(),
      extras: {
        fieldTransform: undefined,
        showError: (field: any) => {
          return field.formControl && field.formControl.invalid && (field.formControl.touched ||
            (field.options.parentForm && field.options.parentForm.submitted) ||
            (field.field.validation && field.field.validation.show));
        },
      }
    })
```
Update II:

If I modify the library method: 

 ```typescript
Object.defineProperty(Field.prototype, "showError", {
        /**
         * @return {?}
         */
        get: function () { 
            return this.formControl && this.formControl.invalid && (this.formControl.touched || (this.options.parentForm && this.options.parentForm.submitted) || (this.field.validation && this.field.validation.show));
            //return this.options.showError(this); 
        },
        enumerable: true,
        configurable: true
    });
```

This works... but I don't now why in the last version of formly, the FormlyModule don't use the default showError implemented function, or the showError defined in the forRoot() method

**Comment by aitboudad** [comment]
can you check if you didn't override options reference:
```ts
this.options = value
// or
get options() {
   ...this.options;
}
```

**Comment by Pat-Lovelace** [comment]
Thanks a lot! 

That was the problem...

**Comment by manoel-freitas** [comment]
**I'm submitting a ... (check one with "x")**

[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
**Current behavior**
I'm using the ngx-formly with an agular-5.0.0 poject with angular material 5.2.3 and using the formly inside a dialog. It works fine until i submit the form and close the dialog. If i show up the dialog again, i have the following error output
`
FormlyFieldInput.html:2 ERROR TypeError: this.options.showError is not a function
    at FormlyFieldInput.get [as showError] (core.es5.js:1550)
    at FormlyErrorStateMatcher.isErrorState (material.es5.js:34)
    at MatInput.class_1.updateErrorState (core.es5.js:439)
    at MatInput.ngDoCheck (input.es5.js:555)
    at checkAndUpdateDirectiveInline (core.js:12372)
    at checkAndUpdateNodeInline (core.js:13893)
    at checkAndUpdateNode (core.js:13836)
    at debugCheckAndUpdateNode (core.js:14729)
    at debugCheckDirectivesFn (core.js:14670)
    at Object.eval [as updateDirectives] (FormlyFieldInput.html:2)
`
this is my completly dialog component

`
<h1 mat-dialog-title>Adicionar nova empresa</h1>
<div mat-dialog-content>
  <form [formGroup]="companyForm"  novalidate  id="companyForm">
    <formly-form [model]="company" [fields]="companyFormFields">
    </formly-form>
  </form>
</div>
<div mat-dialog-actions>
<button mat-raised-button color="primary" [mat-dialog-close]="company" type="submit" form="companyForm">
    Adicionar
</button>
</div>
`
and my component.

`
import { IndexComponent } from './../index/index.component';
import { Company } from './../models/company.model';
import { Component, OnInit, Inject } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { FormlyFieldConfig } from '@ngx-formly/core';
import { companyFormFields } from './form.config';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material';

@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.scss']
})
export class FormComponent implements OnInit {
  companyForm = new FormGroup({});
  company: Company = {
    code: '',
    name: ''
  };
  companyFormFields: FormlyFieldConfig[] = companyFormFields ;
  constructor(
    public dialogRef: MatDialogRef<IndexComponent>,
    @Inject(MAT_DIALOG_DATA) public data: any) { }

  ngOnInit() {
  }
}
`

For import module i'm using only FormlyModule.forRoot().


Any ideais of what is it ? I try to see if i override the options attribute but did'nt in any place.

**Comment by aitboudad** [comment]
hi @manoel-freitas, can you replicate your example using the starter example https://stackblitz.com/edit/ngx-formly-material-9nwfmk

**Comment by aitboudad** [comment]
@manoel-freitas I'm able to reproduce it now, working on a fix!

**Comment by manoel-freitas** [comment]
Hi @aitbound for somehow it worming with the first solution of @Pat-lovance on override the option showError. Sorry for the delay on respond this

**Comment by bunomasud** [comment]
Hi, I am using latest angular CLI 6.1.5 and Ngx-formly 4.7.2, however i am getting this error msg while trying to implement the repeating section example. I am not doing anything new, just copy pasting the code but still getting this error.

**Comment by aitboudad** [comment]
maybe you've missed something :)

**Comment by bunomasud** [comment]
If you click the little refresh button of npm packages on the link [](https://stackblitz.com/angular/pdqnxrxrooq?file=src%2Fapp%2Fapp.component.ts) , an npm update command is run and i think then the example doesnt work anymore.

**Comment by aitboudad** [comment]
ahh I see, the example in the doc refer to the version `5.0.0-beta.8` of `ngx-formly` and when trying `npm update` it get the latest stable version `4.7.2` to solve it either use  `5.0.0-beta.8` or pass `options` to the `formly-field`: https://stackblitz.com/edit/angular-w3cyfp

**Comment by bunomasud** [comment]
Thanks, works like a charm! :)
