### ISSUE TITLE
StackBlitz error Conflicting components: MatFormField,MatFormField

### ISSUE THREAD

**Issue by jogelin** [formly-js/ngx-formly#777]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When I upgrade the version of ngx-formly in stackblitz, I have an error:
```
Error in /turbo_modules/@angular/compiler@5.1.2/bundles/compiler.umd.js (528:34)
Template parse errors:
More than one component matched on this element.
Make sure that only one component's selector can match a given element.
Conflicting components: MatFormField,MatFormField ("
<!-- fix https://github.com/angular/material2/pull/7083 by setting width to 100% -->
[ERROR ->]<mat-form-field [hideRequiredMarker]="true" [floatLabel]="to.floatLabel" [style.width]="'100%'">
"): ng:///FormlyMaterialModule/FormlyWrapperFormField.html@2:4
Evaluating main.ts
Booting application
```
You can simply take your [example of datepicker](https://stackblitz.com/edit/angular-gkwj6z):
- remove the dependencies `@ngx-formly/core` and `@ngx-formly/material`
- click on the button `Install missing dependencies` proposed by stackblitz
- the version rc.24 will be upgraded to rc.35

**Expected behavior**
No error

**Comment by aitboudad** [comment]
it's a [material2 issue](https://github.com/angular/material2/issues/7947), just apply the same step for `@angular/material` and `@angular/cdk` deps and it should work.
