### ISSUE TITLE
No way to use horizontalWrapper with select or textarea

### ISSUE THREAD

**Issue by iustin-nita** [formly-js/ngx-formly#780]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

I'm using a horizontalWrapper but I can add only "input" types, not select or textarea.

**Expected behavior**

Should be able to use with select or textarea.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-asr1qg

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-eundmq
