### ISSUE TITLE
Reset Button Validating the form

### ISSUE THREAD

**Issue by SudeshAK** [formly-js/ngx-formly#785]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report  
[ ] feature request
[ ] support request
```

**Current behavior**
When you click on reset button for the first time reset will not validate the form but when you click on Submit (after adding some text) and then click on reset button then the "required" validation is triggered 

**Expected behavior**
It must not validate the form when you click on reset button as it is just resetting the form

**Minimal reproduction of the problem with instructions**
It can be replicated in the example itself
https://formly-js.github.io/ngx-formly/examples/form-options/reset-model

**Please tell us about your environment:**

* **Angular version:** 5.0

* **Browser:**  all
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =   8.9.4

**Comment by SudeshAK** [comment]
Hi @aitboudad thanks for fixing the bug,its working fine now.

**Comment by AbdulRazaq02** [comment]
Hi @aitboudad 
I am facing the same issue with version: 4.8.3
Whenever I tried to reset the model using `options.resetModel()` the required validation is being triggered. 

Please help me out.

**Comment by aitboudad** [comment]
@AbdulRazaq02 please fil a new issue with a reproduction example, also I'd suggest upgrading to the V5 if possible, thanks!
