### ISSUE TITLE
Asterisk is not shown when field wrapper is used

### ISSUE THREAD

**Issue by SudeshAK** [formly-js/ngx-formly#790]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
[ ] support request
```

**Current behavior**
When field is marked as required asterisk is not shown when you create a 'field wrapper' 

**Expected behavior**
Asterisk should be shown when field is marked as 'required'

**Minimal reproduction of the problem with instructions**
It can be replicated in the example itself

https://formly-js.github.io/ngx-formly/examples/bootstrap-specific/bootstrap-horizontal

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.0

* **Browser:** all
 
* **Language:**  TypeScript

* **Node (for AoT issues):** `node --version` =   8.9.4

**Comment by aitboudad** [comment]
example fixed and updated.

**Comment by SudeshAK** [comment]
Thanks for fixing..
