### ISSUE TITLE
Repeating section default value not working (when selecting from async select options)

### ISSUE THREAD

**Issue by michalkubat** [formly-js/ngx-formly#791]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Default selected value of a select with asynchronous options is not working, when defined in repeating section. I have tried the same defined in normal (non-repeating section) fields and it works as expected.

**Minimal reproduction of the problem with instructions**
I used repeating section component provided in example (well, outdated one, where repeating section type is extending FieldType, not FieldArrayType). Select is populated through API call.

* **Angular version:** 5.2.5
* **Browser:** Chrome
* **Language:** TypeScript 2.4.2
* **Node (for AoT issues):** `node --version` =  v9.5.0

**Comment by aitboudad** [comment]
can you provide me a reproduction example using `stackblitz`, here is a starter example: https://stackblitz.com/edit/angular-ngxformly-repeat-3ewxjc

**Comment by aitboudad** [comment]
also I highly suggest to use the new `FieldArrayType`

**Comment by michalkubat** [comment]
Actually, after tinkering for a while with the stackblitz I have found, that my problem lies elsewhere. The problem is, when model has desired key set as null. Then the default value is ignored. Here is example of my problem: https://stackblitz.com/edit/angular-ngxformly-repeat-evkbvm (bitcoin and bitcoin3 should both get option 'A' pre-selected).

**Comment by aitboudad** [comment]
`defaultValue` is assigned only when the model value is undefined. so if you want to take account of `defaultValue` pass an undefined value instead.

**Comment by michalkubat** [comment]
I see. Thanks for your help!
