### ISSUE TITLE
 this.options.resetModel doesn't work on a FormArray

### ISSUE THREAD

**Issue by Pat-Lovelace** [formly-js/ngx-formly#796]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
I have a step-form which shares the same model and the same options between its tabs. 
  
I need to change the model dynamically, so I used this.options.resetModel(newModel).  
This doesn't work, it resets the model to an empty model, I think.

**Expected behavior**
The expected behavior is changing the model rightly. I tested this with a form which type was a FormGroup and it worked great [EXAMPLE-OK](https://stackblitz.com/edit/angular-xfa6yv?file=app/app.component.ts) but with a FormArray failed. 

**Minimal reproduction of the problem with instructions**
I reproduced the problem with your tab-example:
[EXAMPLE-KO](https://stackblitz.com/edit/angular-whmbag?file=app%2Fapp.component.ts)

**What is the motivation / use case for changing the behavior?**
I would like to change the model of a FormArray with shared model dinamically.

**Please tell us about your environment:**
@ngx-formly/core and @ngx-formly/bootstrap 2.0.0.rc-39.

* **Angular version:** 
5.2.8

**Comment by aitboudad** [comment]
each tab should has its own `options`, I'll update the example.

**Comment by Pat-Lovelace** [comment]
I tried with an array of FormlyFormOptions, but it doesn't work either. I don't know if I did it rightly.
[options-array](https://stackblitz.com/edit/angular-g2rt8f?file=app/app.component.ts)

**Comment by aitboudad** [comment]
there is an issue in option, currently you can use `form` instead
```ts
  resetModel1() {
    this.tabs.map((t, i) => this.form.at(i).reset(this.model1));
  }
```
