### ISSUE TITLE
hideExpression in wrapper

### ISSUE THREAD

**Issue by davidoween** [formly-js/ngx-formly#804]
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request
 
I need to add a hideExpression in wrapper. It is very important for me. Example:

https://stackblitz.com/edit/angular-kk8uww?file=app/app.component.ts

Thanks

**Comment by aitboudad** [comment]
see https://github.com/formly-js/ngx-formly/issues/704#issuecomment-364661614

**Comment by davidoween** [comment]
The wrapper type could accept a boolean expression or a string expression instead of a function? I need to access to the model with a string expression.

**Comment by aitboudad** [comment]
yes, see https://stackblitz.com/edit/angular-b7r5yx

**Comment by aitboudad** [comment]
also ensure to pass `form` and `options` input

**Comment by davidoween** [comment]
But, I would be great if I could access to the model like the input "surname" in the example [demo](https://stackblitz.com/edit/angular-formly-oqsbcl?file=app/app.component.ts), because I don't have the main-model saved in the options.formstate.

**Comment by aitboudad** [comment]
then wrap the address within a fieldGroup without key, see https://stackblitz.com/edit/angular-b7r5yx?file=app%2Fapp.component.ts

```ts
    {
      hideExpression: '!model.firstName',
      fieldGroup: [
        {
          key: 'address',
          wrappers: ['panelEdit'],
          templateOptions: { label: 'Address' },
          fieldGroup: [{
            key: 'town',
            type: 'input',
            templateOptions: {
              required: true,
              type: 'text',
              label: 'Town',
            },
          }],
        },
      ],
    }
```

**Comment by davidoween** [comment]
Thanks, you are a genius :)
