### ISSUE TITLE
After update model with an non-existing member the old value is still displayed (within FieldGroup)

### ISSUE THREAD

**Issue by FritzHerbers** [formly-js/ngx-formly#805]
[x ] bug report

After update model with an non-existing member the old value is still displayed (within FieldGroup)
https://stackblitz.com/edit/angular-my5ihw?file=app%2Fapp.component.html

After update model with the same member the previous model gets corrupted (within FieldGroup)
https://stackblitz.com/edit/angular-rgmqgt?file=app%2Fapp.component.html

2.0.0-rc.40/41

Thx for all your work done, we really appreciate it.

**Comment by aitboudad** [comment]
related to #799

**Comment by FritzHerbers** [comment]
@aitboudad 
Thx for the updates.

After update model with an non-existing member the old value is still displayed (within FieldGroup)
https://stackblitz.com/edit/angular-my5ihw?file=app%2Fapp.component.html
Updated to rc.42 still shows a bug.

After update model with the same member the previous model gets corrupted (within FieldGroup)
https://stackblitz.com/edit/angular-rgmqgt?file=app%2Fapp.component.html
The second issue is resolved.

**Comment by aitboudad** [comment]
it should work now with `rc.43`.

**Comment by FritzHerbers** [comment]
First issue is solved with rc.43.
Thx for all your updates and hope all possible field/model changes are tackled.
