### ISSUE TITLE
Custom input for angular material 2 is not getting material ui

### ISSUE THREAD

**Issue by somnathswami** [formly-js/ngx-formly#806]
![customf](https://user-images.githubusercontent.com/11055661/37452075-8b4dd55e-2859-11e8-9d92-a2e8a473b574.png)

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

custom element is not looking as expected as angular material looks
**Expected behavior**

same ui for every input element 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.0.X

angular material 2+

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
you should extend `FieldType` from `@ngx-formly/material` and use `form-field` as a wrapper, see the datepicker example: https://stackblitz.com/edit/angular-gkwj6z

**Comment by somnathswami** [comment]
Got it thanks need to add  matInput  to custom element template
 `  <input matInput [type]="type" [formControl]="formControl" [formlyAttributes]="field">`
