### ISSUE TITLE
Validate in custom type formly

### ISSUE THREAD

**Issue by davidoween** [formly-js/ngx-formly#807]
I need to validate my custom type, but it does not work. I sent him a demo

https://stackblitz.com/edit/angular-swkgvt?file=app/my-custom-type/custom.html

**Comment by aitboudad** [comment]
`required` validation is applied first and doesn't have a message validation try to register require message in NgModule declaration:

```ts
    FormlyModule.forRoot({
      validationMessages: [
        { name: 'required', message: 'This field is required' },
      ],
    }),
```

**Comment by aitboudad** [comment]
just remove `[(ngModel)]="model.expressionProperties['templateOptions.disabled']"` in the custom type and it should work, if you want to assign a new value you should use `formControl.setValue()`.

**Comment by davidoween** [comment]
I just need to be able to change the value of: 
this.model.expressionProperties = {
      'templateOptions.disabled' : this.value
    }

So my model would be:
model = {
expressionProperties: {
 'templateOptions.disabled' : NEW_VALUE
}
}
https://stackblitz.com/edit/angular-totgj3?file=app/my-custom-type/custom.ts

**Comment by aitboudad** [comment]
you want to mark custom field disabled if firstName2 is set ?

**Comment by davidoween** [comment]
No, the model linked to the custom input has to be:
model = {
expressionProperties: {
'templateOptions.disabled' : NEW_VALUE
} , 
NEW_VALUE would be the value of custom  input.

**Comment by aitboudad** [comment]
ahh, then just set the key into ` key: 'expressionProperties.templateOptions.disabled',`
see https://stackblitz.com/edit/angular-1kkblq

**Comment by davidoween** [comment]
yeah, but that create: 

model =   "expressionProperties": {
    "templateOptions": {
      "disabled": "helloworld"
    }
  },

and I would need: 

model =   "expressionProperties": {
    "templateOptions.disabled": "helloworld"
  },

**Comment by aitboudad** [comment]
updated the example https://stackblitz.com/edit/angular-1kkblq

**Comment by davidoween** [comment]
That's great! But the validator doesn't work in the custom input...

**Comment by aitboudad** [comment]
fixed

**Comment by davidoween** [comment]
Thanks.

**Comment by akhilamittapally** [comment]
hi @aitboudad, how can I change the border color as red
