### ISSUE TITLE
Formly Material - Validation error message doesn't seem to show

### ISSUE THREAD

**Issue by juristr** [formly-js/ngx-formly#813]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

When configuring formly as follows:

```
{
  key: 'name',
  type: 'input',
  templateOptions: {
    label: 'Name (required)',
    required: true
  }
}
```

..the form is properly invalidated, but the error message doesn't display. **I'm using Angular Material** here.

**Expected behavior**

The validation message shows 😉 

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-formly-material-vaidation-msg?file=app%2Fform-field-overview-example.ts

**Comment by aitboudad** [comment]
you have missed one small step, the error message should be defined in `NgModule` declaration:

```ts
    FormlyModule.forRoot({
      validationMessages: [
        { name: 'required', message: 'This field is required' },
      ],
    }),
```

**Comment by juristr** [comment]
@aitboudad Oh, I thought those are built-in, as I didn't find them in the demo examples: https://formly-js.github.io/ngx-formly/examples/validation/built-in-validations

**Comment by juristr** [comment]
Oh, stupid me...it's in the `FormlyModule.forRoot` 🙄 

sorry 😓

**Comment by aitboudad** [comment]
no worry :smile: , a bunch of examples that cover all validation possibilities :) are there:

![selection_124](https://user-images.githubusercontent.com/1753742/37590518-683ed784-2b60-11e8-82bb-f10282042950.png)
