### ISSUE TITLE
How to add controls on custom type field?

### ISSUE THREAD

**Issue by Jukien** [formly-js/ngx-formly#814]
**I'm submitting a**
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

Hi,

I used formly with angularjs 2 years ago for a project. It's save me some time to create forms.
Now, I'm working on another project and I try to use the new version of formly with Angular 5.

With formly 1.0, when we wanted to add some control to our custom field, we simply added a controller function in the field declaration:

```
{
    key: 'treatment',
    type: 'todo',
    templateOptions: {
        disease: null == treatment.drugName ? treatment.drug_not_find : treatment.drugName,
        dateDisease: 'depuis le ' + moment(treatment.date_start).format('D MMMM YYYY'),
        iconClass1: 'fa-times',
        action1: 'Supprimer',
        disabledButton1: false
    },
    controller: function ($scope) {
        $scope.onButton1 = onDelete;

        function onDelete() {
            $http.delete('treatment.php', { params: { id: treatment.id } })
                .then(function (getResponse) {
                    Messenger().post({ type: 'info', message: 'Le traitement a été supprimé' });
                    updateTreatmentSummary();
                }, function (error) { }
                );
        }
    }
}
```

I used your exemple with [repeat-section](https://formly-js.github.io/ngx-formly/examples/advanced/repeating-section).
But I would like to customize the *remove()* and the *add()* function.
Do you have a way to do that?

Thank you in advance,

Sincerely,

Julien DIEMER

* **Angular version:** 5.2.0
* **ngx-formly/core:** ^2.0.0-rc.36

* **Browser:** Chrome 65
 
* **Language:** TypeScript 2.5.3

* **Node (for AoT issues):** `node --version` = 6.11.1

**Comment by aitboudad** [comment]
> How to add controls on custom type field?

see https://formly-js.github.io/ngx-formly/guide/custom-formly-field

> But I would like to customize the remove() and the add() function.

just define `add` and `remove` in `RepeatTypeComponent`

```ts
export class RepeatTypeComponent extends FieldArrayType {
   ...
   add() {
       ...
       // super.add();
   }

   remove(i) {
       ...
       // super.remove(i);
   }
}
```

**Comment by Jukien** [comment]
Hi,

Thank you for your answer.
I did overide *add()* and *remove()* function on the **RepeatTypeComponent** class.
But if I do that, every time I want to use the custom input field I can't implement the *add()* and *remove()* functions differently. 
There is no way to declare for each custom field created its own controller?

Thanks a lot,

Sincerely,


Julien DIEMER

**Comment by aitboudad** [comment]
you can do it without controller, I'll provide you an example!

**Comment by aitboudad** [comment]
the following example show confirm message when user want to add/remove an item.
see https://stackblitz.com/edit/angular-ngxformly-repeat-ocy1dg

**Comment by Jukien** [comment]
Thank you very much!
It's perfect. It works!

Sincerely,

Julien DIEMER
