### ISSUE TITLE
events and lifecycle usage

### ISSUE THREAD

**Issue by gvasilevskiy** [formly-js/ngx-formly#815]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] question
```

**Current behavior**

Hello,
I am trying to make the application json driven:
a) how should I store events and lifecycle invocations using json?
b) IN case I dynamically build javascript functions(new Function), how would I be able to get access to the generated elements(how does json code relate to the generated id)?
thank you
Gennadiy  
**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
Hi, I think it's better to provide you an example so can you tell me some use-cases ?

**Comment by gvasilevskiy** [comment]
Hi, my general example is loading json from the database. It is very similar to example that you provided in the examples section https://formly-js.github.io/ngx-formly/examples/other/json-powered. But in addition to having json to build the form, I also want to put json to react to events (inside template options or lifecycle). Storing something like :
-----------------------------
lifecycle: {
        onInit: (form, field) => {
          const teams = [
            { id: '1', name: 'Bayern Munich', sportId: '1' },
            { id: '2', name: 'Real Madrid', sportId: '1' },
            { id: '3', name: 'Cleveland', sportId: '2' },
          ];

          form.get('sport').valueChanges.pipe(
            takeUntil(this.onDestroy$),
            tap(sportId => {
              field.formControl.setValue('');
              field.templateOptions.options = teams.filter(team => team.sportId === sportId);
            }),
          ).subscribe();
        },
      },
---------------------
in json format is not possible. Would you have any suggestions to address it?
thank you
Gennadiy

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-ngxformly, you can define a helper function `getField` to find a field by key and then apply your custom events.

```ts
    this.fields = loadForm();
    this.getField('firstName').templateOptions.label = '*** Edited firstName **';
```

**Comment by SudeshAK** [comment]
if in case I am using dependent dropdown then in `this.getField('firstName')`  `firstName` will be on the fly. how to get which dropdown templateOptions has to be changed?
