### ISSUE TITLE
Question on Date Field

### ISSUE THREAD

**Issue by SudeshAK** [formly-js/ngx-formly#816]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] question

Two Question
1. Is it possible in formly to have a linked bootstrap date field i.e for example, when I change date from first date field automatically date prior to the first date field should be disabled on the second date field?
2. Is it possible in formly to validate two date fields i,e date in the date field 2 should be more than date in the date field 1 ?


* **Angular version:** 5.0

**Comment by aitboudad** [comment]
> 1. Is it possible in formly to have a linked bootstrap date field i.e for example, when I change date from first date field automatically date prior to the first date field should be disabled on the second date field?

The following example provide you an example with material datepicker but you can do the same for bootstrap see https://stackblitz.com/edit/angular-zrdjzq
I used `matDatepickerFilter` feature.
```ts
filter: (d: Date): boolean => {
  return this.model.startDate && d > this.model.startDate;
},
```

> 2. Is it possible in formly to validate two date fields i,e date in the date field 2 should be more than date in the date field 1 ?

see https://formly-js.github.io/ngx-formly/examples/validation/matching-two-fields

**Comment by SudeshAK** [comment]
Thanks for your help!!

**Comment by aitboudad** [comment]
don't use `[(ngModel)]`, just formControl is enough,
```html
[formlyAttributes]="field" [formControl]="formControl"
```
ngx-formly is based on angular reactive-form https://angular.io/guide/reactive-forms

For validation part you don't have to rely on datepicker plugin if you want, just follow the doc https://formly-js.github.io/ngx-formly/guide/validation

**Comment by chaosLegacy** [comment]
@aitboudad Thanks man it works 👍
