### ISSUE TITLE
Click on the magnifying glass to enter the user ID user name, determine the backfill to the form

### ISSUE THREAD

**Issue by smile2014** [formly-js/ngx-formly#817]
https://stackblitz.com/edit/angular-oprfhy

**Comment by smile2014** [comment]
Field id in bullets may be inconsistent with the form, how to write a generic method

**Comment by smile2014** [comment]
The dialog field is also dynamically generated by the clicked field

**Comment by aitboudad** [comment]
hi,
thanks for the example but it's not clear to me what are you asking for, can you please clarify a little bit thanks!

**Comment by smile2014** [comment]
Sorry, English is not good, so it is difficult to describe clearly. My purpose is to have a bullet when clicking on the magnifying glass, which is the query data, select a row to bring the data to the present form

**Comment by aitboudad** [comment]
I understand now but what's the issue there ?

**Comment by smile2014** [comment]
No problem, thanks, but I did not expect a better solution
