### ISSUE TITLE
No work button and input with 2.0.0-rc.43

### ISSUE THREAD

**Issue by davidoween** [formly-js/ngx-formly#818]
Demo:

https://stackblitz.com/edit/angular-ngx-formly-pwpww7?file=app/app.component.ts

**Comment by aitboudad** [comment]
the button type is not available by default you should register it first see the doc example https://formly-js.github.io/ngx-formly/examples/other/button
also take a look of How to create a custom type https://formly-js.github.io/ngx-formly/guide/custom-formly-field.
