### ISSUE TITLE
force show message in input 

### ISSUE THREAD

**Issue by davidoween** [formly-js/ngx-formly#825]
I need to force to show a message in the input after an action. I need to show a validation message or change the description. Is very importante for me.

DEMO

https://stackblitz.com/edit/angular-5q4txv?file=app/app.component.ts

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-gnalxr

**Comment by aitboudad** [comment]
I added a quick fix to take account of `description` changes in `rc.45` also updated the example to include `distinctUntilChanged` in subscription.

To update a description, use:
```ts
field.templateOptions.description = 'ddddd';
```
To show a custom message validation:
```ts
// set message
field.formControl.setErrors({'server-error': 'sss'});
//force show message validate
field.formControl.markAsTouched();
```
```ts
FormlyModule.forRoot({
  validationMessages: [
    {name: 'server-error', message: (err) => err },
  ],
}),
```

**Comment by davidoween** [comment]
Is it not possible to do it without lifecycle? simply in  templateOptions.change? thanks again

**Comment by aitboudad** [comment]
yes possible:
```ts
change: (field) => {
  // set message
  field.formControl.setErrors({'server-error': 'error'});
  //force show message validate
  field.formControl.markAsTouched();
}
```

**Comment by davidoween** [comment]
yeahhh thanks. And how could the description change from change event?

**Comment by davidoween** [comment]
Actually I want to show an error message if the field is invalid, but a valid message if the field is valid (for this I change the description...)

**Comment by aitboudad** [comment]
```ts
change: (field) => {
  field.templateOptions.description = 'ddddd';
}
```

**Comment by davidoween** [comment]
Thanks.
