### ISSUE TITLE
Input radio key attribute name

### ISSUE THREAD

**Issue by davidoween** [formly-js/ngx-formly#828]
the key must have the same value as the name. I want the following (uncheked radio)

Demo:
https://stackblitz.com/edit/angular-qlbrvk?file=app/app.component.ts

**Comment by aitboudad** [comment]
you can explicitly set the name for both field:
```ts
    {
      key: "radio",
      type: "radio",
      name: 'radio',
    }
```

**Comment by davidoween** [comment]
Thanks
