### ISSUE TITLE
How to get gird value in dynamic form, click post test

### ISSUE THREAD

**Issue by smile2014** [formly-js/ngx-formly#830]
https://stackblitz.com/edit/angular-oprfhy

**Comment by aitboudad** [comment]
ag-gird doesn't support reactive-form so you have to manually update the grid value based on ag-grid events:

so firstly you have to remove `formControl` in the `FormlyFieldGrid` component:
```html
[formControl]="formControl"
```
and then rely ag-grid events in my example I used `cellEditingStopped` output:
```html
(cellEditingStopped)="columnValueChanged($event)"
```
https://stackblitz.com/edit/angular-hdk8wa

**Comment by smile2014** [comment]
thank you,I also tried the solution you mentioned. There may be some details that are not handled well, causing the ag-grid to die.
