### ISSUE TITLE
Question on field required validation

### ISSUE THREAD

**Issue by SudeshAK** [formly-js/ngx-formly#831]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report 
[ ] feature request
[ ] support request
[x] question

How to add required field validation in the example 
https://stackblitz.com/edit/ngx-formly-custom-template ?

I have tried but I was not able to make the field required.

* **Angular version:** 5

**Comment by aitboudad** [comment]
if you use `ui-bootstrap` or `ui-material` then I think the only step you have to do is to define `validationMessages` in the `NgModule` declaration:
see https://formly-js.github.io/ngx-formly/examples/validation/built-in-validations
```ts
    FormlyModule.forRoot({
      validationMessages: [
        { name: 'required', message: 'This field is required' },
      ]
   })
```
else see https://stackblitz.com/edit/ngx-formly-custom-template-sqchcw which use `showError` and 
 `formly-validation-message` component inside `FormlyFieldInput`.
and to avoid duplicate that part on each type, you can define a wrapper type that contains the validation part similar to ui-boostrap see https://github.com/formly-js/ngx-formly/blob/master/src/ui-bootstrap/src/wrappers/message-validation.ts

Also please not that the documentation is in progress, luckily the validation part has been just added see 
 https://github.com/formly-js/ngx-formly/issues/820#issuecomment-375650555

**Comment by SudeshAK** [comment]
Thank you very much this https://stackblitz.com/edit/ngx-formly-custom-template-sqchcw  example helped me..
