### ISSUE TITLE
HiddeExpression boolean var

### ISSUE THREAD

**Issue by davidoween** [formly-js/ngx-formly#832]
Hello, I'm doing the HideExpressión documentation but I think it does not work well with boolean. You can see it in the following example

https://stackblitz.com/edit/angular-formly-dhfuza?file=app/app.component.ts

**Comment by aitboudad** [comment]
we take account of boolean value only on initialization, so `hideExpression` should be a function:
```ts
fields: FormlyFieldConfig[] = [
   ...
   hideExpression: () => this.show
]
```

and if users prefer to change the hide manually then `hide` is the preferred option:
```ts
this.fields[1].hide = this.show;
```

**Comment by aitboudad** [comment]
after checking I think we can allow passing a boolean value for `hideExpression` so it's a bug, I'm working on fix!

**Comment by davidoween** [comment]
Ok. Notify me when you solve this. I will add an example in the documentation

**Comment by aitboudad** [comment]
done in `2.0.0-rc.47`

**Comment by davidoween** [comment]
The same thing happens with 

`  expressionProperties: {
        'templateOptions.disabled': this.show
   }`

**Comment by aitboudad** [comment]
`expressionProperties` is different here we only allow passing function or a string expression value.
