### ISSUE TITLE
Can an expression be extended like the following format

### ISSUE THREAD

**Issue by smile2014** [formly-js/ngx-formly#838]
'templateOptions.disabled': [('state', 'in', ('purchase', 'to approve','done', 'cancel'))]

 
attrs=['purchase', 'to approve','done', 'cancel'];
var state='purchase';
alert(['purchase', 'to approve','done', 'cancel'].indexOf(state)>=0);

**Comment by aitboudad** [comment]
ahh I see now, we will see if it can be possible :)

**Comment by smile2014** [comment]
thank you

**Comment by smile2014** [comment]
@aitboudad  https://github.com/ag-grid/ag-grid/tree/master/src/ts/valueService

The expression parsing in this link is good

**Comment by smile2014** [comment]
compute(values) {
        if (this._data === true || this._data === false) {
            // The domain is a always-true or a always-false domain
            return this._data;
        } else if (Array.isArray(this._data)) {
            // The domain is a [name, operator, value] entity
            // First check if we have the field value in the field values set
            // and if the first part of the domain contains 'parent.field'
            // get the value from the parent record.
            let isParentField = false;
            let fieldName = this._data[0];
            // We split the domain first part and check if it's a match
            // for the syntax 'parent.field'.
            const parentField = this._data[0].split('.');
            if ('parent' in values && parentField.length === 2) {
                fieldName = parentField[1];
                isParentField = parentField[0] === 'parent' &&
                    fieldName in values.parent;
            }
            if (!(this._data[0] in values) && !(isParentField)) {
                throw new Error(_.str.sprintf(
                    "Unknown field %s in domain",
                    this._data[0]
                ));
            }
            let fieldValue;
            if (!isParentField) {
                fieldValue = values[fieldName];
            } else {
                fieldValue = values.parent[fieldName];
            }

            switch (this._data[1]) {
                case "=":
                case "==":
                    return _.isEqual(fieldValue, this._data[2]);
                case "!=":
                case "<>":
                    return !_.isEqual(fieldValue, this._data[2]);
                case "<":
                    return (fieldValue < this._data[2]);
                case ">":
                    return (fieldValue > this._data[2]);
                case "<=":
                    return (fieldValue <= this._data[2]);
                case ">=":
                    return (fieldValue >= this._data[2]);
                case "in":
                    return _.contains(
                        _.isArray(this._data[2]) ? this._data[2] : [this._data[2]],
                        fieldValue
                    );
                case "not in":
                    return !_.contains(
                        _.isArray(this._data[2]) ? this._data[2] : [this._data[2]],
                        fieldValue
                    );
                case "like":
                    return (fieldValue.toLowerCase().indexOf(this._data[2].toLowerCase()) >= 0);
                case "ilike":
                    return (fieldValue.indexOf(this._data[2]) >= 0);
                default:
                    throw new Error(_.str.sprintf(
                        "Domain %s uses an unsupported operator",
                        this._data
                    ));
            }
        } else { // The domain is a set of [name, operator, value] entitie(s)
            switch (this._data) {
                case "&":
                    return _.every(this._children, function (child) {
                        return child.compute(values);
                    });
                case "|":
                    return _.some(this._children, function (child) {
                        return child.compute(values);
                    });
                case "!":
                    return !this._children[0].compute(values);
            }
        }
    }

**Comment by smile2014** [comment]
@aitboudad  Can you add this resolution to it? It looks like you can use eval to convert it.

expressionProperties: {
         'templateOptions.disabled': "`!model.is_shipped && ['purchase','done'].indexOf(model.state) > -1)`"
      }

**Comment by smile2014** [comment]
https://github.com/iLambda/expr-tree

**Comment by smile2014** [comment]
I have implemented new function() with reference to the ag-grid expression parsing

**Comment by thorgod** [comment]
@smile2014  I never seen ag-grid, it looks interesting, are you currently using it ngx-formly?
