### ISSUE TITLE
Disabled wrapper

### ISSUE THREAD

**Issue by davidoween** [formly-js/ngx-formly#841]
Disabled wrapper does not work with model but with formState

[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request

https://stackblitz.com/edit/angular-gosuhm?file=app/app.component.ts

**Comment by davidoween** [comment]
and that?

https://stackblitz.com/edit/angular-ahwyqb?file=app/app.component.ts

**Comment by aitboudad** [comment]
I think it's an expected behavior and the most confused one :), see my comment https://github.com/formly-js/ngx-formly/issues/704#issuecomment-364661614

**Comment by davidoween** [comment]
I did not remember it. Thanks

**Comment by davidoween** [comment]
I did not remember it. Thanks
