### ISSUE TITLE
Cascaded select - Parent with predefined value

### ISSUE THREAD

**Issue by Ronen-dev** [formly-js/ngx-formly#846]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
To explain the situation, I will take as an example the [demo](https://formly-js.github.io/ngx-formly/examples/other/cascaded-select) **Cascaded select**.

In the demo, the dropdown select **sport** has no predefined value. So, on change, `form.get('sport')` in **team** `onInit` from `lifecycle` is correctly bound.

But imagine that the first value of **sport** dropdown is already set while opening the form. In that case, `form.get('sport')` isn't bound, and no options while be available in **team** dropdown.

**Expected behavior**
If **sport** dropdown has a predefined value while opening the form, **team** dropdown values must be loaded.

**Minimal reproduction of the problem with instructions**
In the model, set `sport` with a value.

* **Angular version:** 5.2.X

 
* **Language:** [TypeScript 2.5.3 | ES6/7]

**Comment by aitboudad** [comment]
I see, using `startWith` operator would solve the issue, 
```ts
form.get('team').valueChanges.pipe(
  ...
  startWith(form.get('team').value)
)
````

can you make a PR ?

**Comment by Ronen-dev** [comment]
Thanks for the answer, I tried it and it works perfectly !

In the same vein, imagine that **team** value is also predefined (the value exist in the model), how do I make this value selected in **team** dropdown ?
I tried with `field.formControl.setValue()`, but it doesn't seems to work :
``` js
// Team field
form.get('sport').valueChanges.pipe(
    startWith(form.get('famille').value),
    takeUntil(this.onDestroy$),
    tap(sport_id => {
        ...
        field.formControl.setValue(form.value.team);
        field.templateOptions.options = sousFamilleFormValues;
    })
)
field.formControl.setValue(form.value.team)
```

---

For the PR, do you mean adding this case in the Cascaded select demo page ?

**Comment by aitboudad** [comment]
I think it should work without explicitly calling `setValue`,

> For the PR, do you mean adding this case in the Cascaded select demo page ?

yep

**Comment by Ronen-dev** [comment]
> I think it should work without explicitly calling `setValue`

Still doesn't work.

> For the PR, do you mean adding this case in the Cascaded select demo page ?
>> yep

I'm taking care of it.

**Comment by aitboudad** [comment]
can you try with:
```ts
          form.get('sport').valueChanges.pipe(
            takeUntil(this.onDestroy$),
            startWith(form.get('sport').value),
            tap(sportId => {
              field.templateOptions.options = teams.filter(team => team.sportId === sportId);
              if (field.formControl.value && !field.templateOptions.options.find(o => o.id === field.formControl.value)) {
                // issue with angular select field: we should add an extra empty option to avoid select the first option
                // TODO: report to angular
                field.templateOptions.options = [
                  {},
                  ...field.templateOptions.options,
                ];
                field.formControl.setValue(null);
              }
            }),
          ).subscribe();
```

The same should be applied to `player` field.
