### ISSUE TITLE
Disabled custom type 

### ISSUE THREAD

**Issue by davidoween** [formly-js/ngx-formly#848]
Disable wrapper with custom type inside. 
It only disables the default types of formly

It does not work for me

**Comment by aitboudad** [comment]
I think so, it should only support reactive form, can you provide me an example using stackblitz?

Thanks in advance!

**Comment by davidoween** [comment]
Tomorrow I send you an example

**Comment by davidoween** [comment]
Demo: https://stackblitz.com/edit/angular-y7fuj8?file=app/custom/custom.html

**Comment by aitboudad** [comment]
you have missed to add `[formControl]="formControl"` on input:

```patch
- <input [formlyAttributes]="field" type="text" class="form-control"> 
+ <input [formControl]="formControl" [formlyAttributes]="field" type="text" class="form-control"> 
```
