### ISSUE TITLE
templateOptions' disabled property not working

### ISSUE THREAD

**Issue by werts** [formly-js/ngx-formly#851]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

this.baseFields[0].fieldGroup.forEach(element => {
       element.templateOptions.disabled = true;
 });
however, its not set correctelly,not working

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   
current version:1.0.0-rc.12  
Also not working on 2.0.0-rc.49

**Comment by aitboudad** [comment]
hi, can you provide a reproduction example, here is a starter demo https://stackblitz.com/edit/ngx-formly-bootstrap.

Thanks!

**Comment by werts** [comment]
many thanks to you. I forked an example here.  [https://stackblitz.com/edit/ngx-formly-bootstrap-vhadem](https://stackblitz.com/edit/ngx-formly-bootstrap-vhadem)  thanks again.
