### ISSUE TITLE
Complex Data Model Changes

### ISSUE THREAD

**Issue by cwitheridge** [formly-js/ngx-formly#854]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
I have a very large number of form groups interacting with a single data model supplied through a service. When a field is updated with inputs, I'm using the modelChange event to trigger a some functions in other components that change data in the model using formulas.

These other data keys are also displayed in form and could be changed with user input. But, they don't update when the data in the model changes.

**Expected behavior**
I believe the above is expected behaviour, in that the form maintains a copy of the data model and then makes changes to the data model through input. But, it can't detect changes in the data model itself.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Similar to the modelChange output, could this be used to trigger a reload of the data model to pick up any changes that were made externally to the form?

If not, is there a way to have formly reload the data model? I do understand that there are methods to change individual values in the model as detailed in Issue #493.

**Please tell us about your environment:**

* **Angular version:** 5.2.4

* **Browser:** All
 
* **Language:** TypeScript 2.4.2

* **Node (for AoT issues):** `node --version` =   9.10.1

**Comment by aitboudad** [comment]
hi, have you tried using `options.resetModel` ?

**Comment by cwitheridge** [comment]
Thanks for that, I did try using it as I thought it might do the trick. But, I wasn't getting the changes. I can see the model changes by dumping it to the console and to simplify things, I've implemented a simple button on the form to test it, like the example:
```
<button type="button" (click)="options.resetModel()">Reset</button>
```
and have my options set to:
```
options: FormlyFormOptions = {};
```
in the component and my import is:
```
import {
  FormlyFieldConfig, FormlyFormOptions
} from '@ngx-formly/core';
```
But, it doesn't seem to do anything.

**Comment by aitboudad** [comment]
options should be passed to `formly-form` component:
```html
<formly-form [options]="options" ...>
```

**Comment by aitboudad** [comment]
if it doesn't work, then you have to provide me a reproduction example, here is a starter example  https://stackblitz.com/edit/ngx-formly-bootstrap.

**Comment by cwitheridge** [comment]
Thanks again. I do have the:
```
<formly-form [options]="options" ...>
```
in my template. 

I've recreated a much simpler example of what I'm trying to achieve using the link you sent. Frustratingly, it works. I will have to go back to my code and try and work it out.

https://stackblitz.com/edit/ngx-formly-bootstrap-resetmodel

**Comment by aitboudad** [comment]
ensure you use the latest version `2.0.0-rc.50`

**Comment by cwitheridge** [comment]
@aitboudad.

Thanks for everything on a Sunday...I found my bug...it was buried in a form field config - two fields with the same key value. It was all my code. But, you certainly helped me eliminate a cause. Awesome!
