### ISSUE TITLE
Custom templates and Lazy Loaded modules

### ISSUE THREAD

**Issue by techla** [formly-js/ngx-formly#855]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
Custom templates doesn't work with lazyloading. The custom fields appears but is not connected to the update stream.

**Expected behavior**
work with lazyloaded modules

**Minimal reproduction of the problem with instructions**
create an appModule with a customFormlyField
create a lazyLoaded module
use the custom filed in the lazyLoaded module

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
just use `forChild` to register your custom field in the lazyLoaded module and it should work:

```ts
FormlyForm.forChild({
   types: [ ... ]
})
```

**Comment by techla** [comment]
To factorize my app, I put the custom formly inputs on a module on its own named custom-formly, and I import it from other modules, including lazy loaded modules (the custom-formly module is not directly lazyloaded). I tried to declare le custom inputs on the custom-formly module with the forChild method but I doesn't seems to work. Is that use case covered by the module ?

**Comment by techla** [comment]
And if I try to declare it directly on the AppModule with the forChild method (no custom-formly module anymore), It says
"There is no type by the name of "password"

**Comment by techla** [comment]
It works only if I declare the custom filed cvomponent directly to the lazyLoaded module with the forChild method. Is there any way to put on all my cutom fields Component in one place in order to get it work with lazy loading ?

**Comment by aitboudad** [comment]
can you replicate an example using the starter demo example: https://stackblitz.com/edit/ngx-formly-bootstrap

there is another way to register a new types using the `FormlyConfig` service, but not recommended.

```ts
  constructor(config: FormlyConfig) {
    config.setType(...);
  }
```
