### ISSUE TITLE
Question on Required Message related to multiselect dropdown

### ISSUE THREAD

**Issue by SudeshAK** [formly-js/ngx-formly#859]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] question

Hi,
I was working with a multiselect dropdown component with help of your suggestion, I have handled the 
required error using [class.error]="showError". 
Everything is working fine but when I place the options of multiselect dropdown inside setTimeout
then by default This field is required message is shown
Below is the example

https://stackblitz.com/edit/ngx-formly-custom-template-tghnre 

When I remove setTimeout it works fine. But I need it to be inside setTimeout. Can you please help me
on this?



* **Angular version:** 5.0

**Comment by aitboudad** [comment]
there is something wrong with multiselect-dropdown lib instead of using `setTimeout` which is not a clean way you can use `*ngIf="iOptions"` and everything should work.

```ts
        <ss-multiselect-dropdown
          *ngIf="iOptions"
          ...
        </ss-multiselect-dropdown>
```

**Comment by SudeshAK** [comment]
I have made changes as you said. It works,but the problem is the dropdown  is not shown until the options are built and the options in my case is coming from server so till then page will be blank and once the options are received it shows the dropdown.

**Comment by aitboudad** [comment]
you can try another better lib such as `ng-select` see https://stackblitz.com/edit/angular-ntysej

**Comment by SudeshAK** [comment]
I have tried this.In this dropdown,options does not have checkbox. I have tried with older version of angular-2-dropdown-multiselect and I have removed settimeout as u mentioned and added *ngIf. It is working fine there is a small delay but its fine compared to new dropdown which took several seconds to show. 
**Thank you for your help.**
