### ISSUE TITLE
Question dynamic inputs.

### ISSUE THREAD

**Issue by nico281** [formly-js/ngx-formly#860]
Hi, how are you? It could be possible to add dynamic attributes to the form by changing the FormlyFieldConfig[]? for example with a button add a new input. 

Cheers!!
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
see https://formly-js.github.io/ngx-formly/examples/advanced/repeating-section

**Comment by nico281** [comment]
Thanks @aitboudad!! Maybe you can help me. I need to create a drag and drop form builder, that's why i need to add fields dynamically and that's the part i'm struggling. In a drop event change the json list

**Comment by aitboudad** [comment]
check this one https://github.com/franzeal/ng-formly-designer
