### ISSUE TITLE
Custom component with child components

### ISSUE THREAD

**Issue by tkolsty89** [formly-js/ngx-formly#861]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
Can get the blank component template to display with custom type but Inputs will not load into template TS file when using templateOptions. Component has associated TypeScript file but launches empty child component.

**Expected behavior**
Load template with inputs from parent component and then load child component with data.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** TypeScript 2.4.2

**Comment by aitboudad** [comment]
can you elaborate more please else try to replicate your example using starter demo https://stackblitz.com/edit/ngx-formly-bootstrap.

**Comment by tkolsty89** [comment]
Sure, thanks for the quick response!
https://stackblitz.com/edit/ngx-formly-bootstrap-vh64d3

Basically I'm trying to pass info from the parent module to the component date-selector (set up as a custom type). I want to be able to run methods inside of the date-selector component. I can't seem to get the values to pass through.

**Comment by aitboudad** [comment]
firstly you have to extends `FieldType` and then you can access to the field option through `to` or `field.templateOptions` in  date-selector component

```ts
import { FieldType} from '@ngx-formly/core';

@Component({
  template: `
    {{ to.stringFromParent }}
  `,
})
export class DateSelectorComponent extends FieldType {
}
```

https://stackblitz.com/edit/ngx-formly-bootstrap-ajsb1y
