### ISSUE TITLE
Question on Error handling from backend

### ISSUE THREAD

**Issue by SudeshAK** [formly-js/ngx-formly#864]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] question
```
Hi,
I have one question related to error handling. In this example 
https://stackblitz.com/edit/ngx-formly-custom-template-sqchcw 
I can handle required field error,but if I want to set the error which is returned from backend
How can I do that?

* **Angular version:** 5

**Comment by aitboudad** [comment]
see https://github.com/formly-js/ngx-formly/issues/703#issuecomment-364660359

**Comment by SudeshAK** [comment]
Thank you...
