### ISSUE TITLE
FlexLayout in Angular Material (elementAttributes is not effecting)

### ISSUE THREAD

**Issue by KashyakSupport** [formly-js/ngx-formly#865]
```
[x] bug report 

[ x ] support request
```

**Current behavior**
![image](https://user-images.githubusercontent.com/30410542/38304389-e06648b4-3826-11e8-8ec3-9dd24be0ab3a.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/30410542/38304399-ef7c041a-3826-11e8-8d9e-c3d0fe82de01.png)

**Minimal reproduction of the problem with instructions**

Followed  this URL to build this but here it is bootstrap but am trying with material
> http://angular-formly.com/#!/example/integrations/angular-material

**# Code**
**Html File**
```
 <form [formGroup]="form" (ngSubmit)="submit(model)">
    <formly-form [form]="form" [fields]="fields" [model]="model" >
      <button type="submit" class="btn btn-default">Submit</button>
    </formly-form>
  </form>
```
**TypeScript File**
 ```
form = new FormGroup({});
  model = { email: 'email@gmail.com' };
  fields = [{
    'key': 'text',
    'type': 'input',
    className: 'flex',
    'templateOptions': {
      'label': 'Input',
    }
  },
  {
    elementAttributes: {
      layout: 'column',
      fieldGroupClassName: 'flex flex-50'
    },
    'fieldGroup': [
      {
        'key': 'firstName',
        className: 'flex',
        'type': 'input',
        'templateOptions': {
          'label': 'First Name',
        }
      },
      {
        'key': 'lastName',
        className: 'flex',
        'type': 'input',
        'templateOptions': {
          'label': 'Last Name'
        }
      }
    ]
  },
  {
    'key': 'knowsMuffinMan',
    'type': 'checkbox',
    'templateOptions': {
      'label': 'Do you know the muffin man?'
    }
  }
  ];
```

**App.Module. file**

```
import {ReactiveFormsModule, FormsModule} from '@angular/forms';
import {FormlyModule} from '@ngx-formly/core';
import { AppComponent } from './app.component';
import {FormlyMaterialModule} from '@ngx-formly/material';
import {FlexLayoutModule} from '@angular/flex-layout';

```
**What is the motivation / use case for changing the behavior?**
dynamically  display Side by side columns in row ,from JSON file usin flex layout

**Please tell us about your environment:**

* **Angular version:** ^5.0.0
* **Angular Formly/Material:** "^2.0.0-rc.50"
* **Browser:** [all | Chrome Version 65.0.3325.181 
 
* **Language:** [all |  "typescript": "~2.4.2" | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =  8.9.1

**Comment by aitboudad** [comment]
hi, have you tried the example https://stackblitz.com/edit/ngx-formly-flex-layout ?

**Comment by KashyakSupport** [comment]
Yes i tried with that one and am getting error **Can't bind to 'form' since it isn't a known property of 'formly-form-flex'.**

**Comment by aitboudad** [comment]
Ahh I see you should ensure to declare `FormlyFormFlexLayout` component inside the `AppModuel`:

```ts
import { FormlyFormFlexLayout } from './formly-form-flex';

@NgModule({
  imports: [ 
    ...,
    FlexLayoutModule, 
    FormlyModule.forRoot(),
  ],
  declarations: [ 
    ...,
    FormlyFormFlexLayout
  ],
})
export class AppModule { }
```

**Comment by KashyakSupport** [comment]
In typescript imported this `import { Component, ViewEncapsulation } from '@angular/core';`

```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  encapsulation: ViewEncapsulation.None,
})
```
View is achieved what ever required  for me

**Comment by KashyakSupport** [comment]
Is it good approach  @aitboudad

**Comment by aitboudad** [comment]
sorry, not sure what do you want to mean!

**Comment by KashyakSupport** [comment]
Actually typescript without this `encapsulation: ViewEncapsulation.None, `  is not effecting my HTML with css

**Comment by jogelin** [comment]
There are no way to manage flex with wrappers ? Only specific form or css ? 

I tried something like this [https://stackblitz.com/edit/ngx-formly-flex-layout-18vx6y?file=app%2Fflex-wrapper.component.ts](https://stackblitz.com/edit/ngx-formly-flex-layout-18vx6y?file=app%2Fflex-wrapper.component.t)s but indeed, tags are generated between and stop flex-layout to work properly...

**Comment by aitboudad** [comment]
@jogelin I haven't yet the time the look deeply into it, I prefer to use className instead.

**Comment by aitboudad** [comment]
@KashyakSupport there is no css for @ngx-formly material.

**Comment by jogelin** [comment]
@aitboudad Indeed, I prefer css too....any advice about a library that could propose the same functionalities ?

**Comment by aitboudad** [comment]
https://github.com/formly-js/ngx-formly/blob/master/demo/src/styles.scss#L2

**Comment by aitboudad** [comment]
in some-case you may need to react to screen-size changes using js, generally I use  https://material.angular.io/cdk/layout/overview

**Comment by KashyakSupport** [comment]
@aitboudad  Issue related to styles.  Building form with **

> MatExpansionPanel

**
Here is my code https://angular-syo244.stackblitz.io/

**Comment by aitboudad** [comment]
@KashyakSupport add `display-flex` to `formly-form` component:
```html
<formly-form [class.display-flex]="field.fieldGroupClassName"  ...
```

**Comment by KashyakSupport** [comment]
@aitboudad above change is working fine but if i adding fields in fieldGroup those are all showing in column-wise but i want only two fields side by side per one row.  Tried with **flex-wrap: wrap** but it is showing 4 columns for row

When i am trying to apply css for className which is in fieldGroup it is not applying 
because in a row have multiple columns but i want to display only two side by side

**Comment by aitboudad** [comment]
@KashyakSupport I don't know, if you don't have enough knowledge in css flex, I suggest you to use bootstrap grid.

**Comment by jogelin** [comment]
@KashyakSupport in our project, we introduced [http://basscss.com/](http://basscss.com/). It allowed grid & flex & other small utils.

But we choose to keep `@angular/flex-layout` because it a bit more powerful than just css classes by dynamically inject styles...

@aitboudad I think it could be good to be able to extends templateOptions in ui-material or another lib and allow fxLayout, fxFlex, fxFlexLayout ... and apply them to the field groups/fields maybe in v3 ? ;)

**Comment by aitboudad** [comment]
well I'm going to close this one since I think the only clean solution is to to have the ability to apply directive dynamically which is not possible with angular right now, closing in favor of #253

**Comment by aitboudad** [comment]
**Note**: just figure out another better way to manage the flex-layout which rely on a custom field type, here is an example https://stackblitz.com/edit/ngx-formly-flex-layout
