### ISSUE TITLE
[SUPPORT] how to manage keyup.enter

### ISSUE THREAD

**Issue by jogelin** [formly-js/ngx-formly#867]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
We can specify a keyup using templateOptions but it seems that the event is not provided. We only have: 
```
keypress?: (field: FormlyFieldConfig, formControl: AbstractControl) => void;
```

**Expected behavior**
Provide the event to be able to check the type of key that was pressed

**Comment by aitboudad** [comment]
the event is now available as a second argument:
```ts
keyup: (field, event, useEvent) => { ... }
```
the third argument (`useEvent` is required in order to use the new api), it will be optional in the next major version.
