### ISSUE TITLE
Question: ExpressionChangedAfterItHasBeenCheckedError while creating custom controls

### ISSUE THREAD

**Issue by SudeshAK** [formly-js/ngx-formly#868]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] question
```
Hi,
I was trying with JSON powered example. In my example below
https://stackblitz.com/edit/angular-eeo7qk
In JSON I have mentioned the custom control name.
I have created a custom control with name my-input which will render me a text box.
The problem is if u do inspect element on chrome browser
then you will see a error as
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked

If I remove required validation from custom control then there is no error If I put required true then
above error will occur

Please help me to resolve this

* **Angular version:** 5.0.X

**Comment by aitboudad** [comment]
is there any reason of using `formly-form` inside `MyInputComponent` ?

**Comment by aitboudad** [comment]
Still not clear to me what do you want to achieve, anyway the reason of `ExpressionChangedAfterItHasBeenCheckedError` is the usage of `form` input which is already builded from the parent `formly-form`, you have to pass a new form or build form manually before passing it into `formly-form`:

```ts
export class MyInputComponent extends FieldType {
  constructor(private builder: FormlyFormBuilder) {
    super();
  }
  
  ...
  this.builder.buildForm(this.form, this.fields, this.model, this.options);
```

if you are looking for a repeat section please check https://formly-js.github.io/ngx-formly/examples/advanced/repeating-section

**Comment by SudeshAK** [comment]
Thanks for this. Actually I want to create this https://formly-js.github.io/ngx-formly/examples/advanced/repeating-section  using JSON powered i.e creating a custom controls using JSON powered.

**Comment by aitboudad** [comment]
repeat type require to provide config through `fieldArray` see https://github.com/formly-js/ngx-formly/blob/master/demo/src/app/examples/advanced/repeating-section/app.component.ts#L20

**Comment by SudeshAK** [comment]
Hi @aitboudad 
I have another question if  I want a async validation in JSON powered example how can I do that?

**Comment by aitboudad** [comment]
it should be the same as `validators`
```ts
      // field config
      asyncValidators: {
        validation: ['uniqueUsername'],
      },
```

```ts
      // AppModule
    FormlyModule.forRoot({
      validators: [
        { name: 'uniqueUsername', validation: uniqueUsername },
      ],
    ....
```

**Comment by SudeshAK** [comment]
In this example 
https://stackblitz.com/edit/angular-eeo7qk
I have created a textbox using json and in my-input.component.ts I have defined the template
In this case instead of defining validation in app.module.ts I want to handle validation and validation messages inside my-input.component.ts. How to do that?

**Comment by aitboudad** [comment]
please the check the doc.

**Comment by aitboudad** [comment]
you don't have to use `ngModel`, we rely on reactive-form using `[formControl]` would do the job.

**Comment by chaosLegacy** [comment]
@aitboudad Yep, I've just figured it out, Great stuff thanks a lot :)
