### ISSUE TITLE
If model is with values i want to display view form  otherwise need to display create form 

### ISSUE THREAD

**Issue by KashyakSupport** [formly-js/ngx-formly#875]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

Presently working with two components one is for create a user and another one is for to get data from server and assigning it to model and displaying data .
 **Expected behavior**

Both Functionality to be in  one form and after creating a record and will  redirects to detail view 
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** ^5.0.0
* **Angular Formly/Material:** "^2.0.0-rc.50"
* **Browser:** [all | Chrome Version 65.0.3325.181 
 
* **Language:** [all |  "typescript": "~2.4.2" | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =  8.9.1

**Comment by aitboudad** [comment]
I can's provide a full example, try to do it by yourself and let me know if you have some problems.
here is a starter example: https://stackblitz.com/edit/ngx-formly-bootstrap.

**Comment by KashyakSupport** [comment]
Thank you

**Comment by KashyakSupport** [comment]
If field dont have value it is overlapping , iam using angular material and may be issue with place holder how to fix it 
Here is screen capture
![t](https://user-images.githubusercontent.com/30410542/38659766-7f7a41d6-3e48-11e8-956a-e4caa4eb965d.png)

**Comment by aitboudad** [comment]
nop, can you provide a reproduction example, here is a starter demo https://stackblitz.com/edit/ngx-formly-ui-material

**Comment by KashyakSupport** [comment]
https://ngx-formly-ui-material-8cgodd.stackblitz.io    please check with edit button

**Comment by aitboudad** [comment]
use `&nbsp;` when value is empty.
```patch
<ng-container *ngIf="readOnly">
-   {{ value }}
+   {{ value || '&nbsp;' }}
</ng-container>
```

**Comment by aitboudad** [comment]
you can use css to remove it.

**Comment by srinigroup** [comment]
I am using disable:true in formly field and it is disables field. But those disable fields are auto populated fields So I want to get those values in from while submitting. but These disable fields are not adding to form. How to get those values even if it is disabled?

**Comment by aitboudad** [comment]
but the value is still present in the model value.
