### ISSUE TITLE
Dynamically add new field depending on another field

### ISSUE THREAD

**Issue by Ronen-dev** [formly-js/ngx-formly#876]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Expected behavior**
Imagine that I have a model as follow :

```js
{
    parent: string[], // used as multiselect,
    childs: [{  // used as dropdowns
        parent: string,
        name: string
    }]
}
```

I would like to create something like : when I click on an option in `parent` dropdown, it create a new field thats depends on previous choice.

Each child dropdown will contains options depending on `parent` value (i'll could use cascaded select for this).

* **Angular version:** 5.2.X

* **Language:** [TypeScript 2.5.3 | ES6/7]

**Comment by aitboudad** [comment]
https://formly-js.github.io/ngx-formly/examples/advanced/repeating-section ?

**Comment by aitboudad** [comment]
then you would like to have something like https://github.com/franzeal/ng-formly-designer ?

**Comment by Ronen-dev** [comment]
Hum I don't know, never heard about `ng-formly-designer`. I just check it out, I don't think it while solve my issue.

In the meantime I found a solution, by looping on `parent` possible options, to create hidden fields. Then, if I choose an option on `parent` multiselect, I simply show the dedicated child field.

Thanks for you help anyway @aitboudad !

**Comment by anatolic** [comment]
Hi @Ronen-dev 
Can you provide more info about your solution. Also is based on some API which means dynamic, or static?
Thank you
