### ISSUE TITLE
resetModel don't update other tabs

### ISSUE THREAD

**Issue by Pat-Lovelace** [formly-js/ngx-formly#880]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
As I found on 2.0.0-rc.39, _resetModel_ on a FormArray didn't update the model. The solution was to have a options for every tab, so now I have an array of options and I change the model with a function similar to:
```typescript
resetModel2() {
    this.options.forEach(tabOptions => tabOptions.resetModel(this.model2));
  }
```
This solution worked, but I think it worked partially, because as you can check from version 2.0.0-rc.40 forward, the model of the other tabs doesn't change. 
I checked that if you change the function for your temporal fixing function, it works: 
```typescript
  resetModel3() {
    this.tabs.map((t, i) => this.form.at(i).reset(this.model3));
  }
```

**Expected behavior**
I think that going through the options-array should be enough to reset the model for all tabs.

**Minimal reproduction of the problem with instructions**
I've updated the example used on [#796](https://github.com/formly-js/ngx-formly/issues/796).
[Tabs example with 2.0.0-rc.40](https://stackblitz.com/edit/angular-shpwdh?file=app/app.component.html)

**What is the motivation / use case for changing the behavior?**
I would like to change the model of a FormArray with shared model dinamically.

**Comment by aitboudad** [comment]
there is something wrong with `fill` which use the same ref for all options, so instead of
```ts
  options: Array<FormlyFormOptions> = Array(this.tabs.length).fill({});
```
use 
```ts
  options: Array<FormlyFormOptions> = this.tabs.map(() => ({}));
```

**Comment by Pat-Lovelace** [comment]
Thanks! My bad :sweat_smile:
