### ISSUE TITLE
Question - Individual forms for each tab

### ISSUE THREAD

**Issue by SudeshAK** [formly-js/ngx-formly#884]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] question
```
Hi,
I was working with tab example. Is it possible to 
1. Each tab should have a submit button and when I click on submit on first page validation must happen on only first tab and when I click submit on second tab validation must happen on only second tab 
2. When I click on submit on  first tab the data in the first tab must be passed to the datatabase
3. Only after first tab data is saved into the database the second tab must be enabled

Thanks

* **Angular version:** 5.0

**Comment by aitboudad** [comment]
yes possible, try to move `form` inside `tab` component to be able to control each form separately.
I can't provide a full example, you can do it by yourself :) and if you encounter any issue let me know !

**Comment by SudeshAK** [comment]
Ok @aitboudad thanks I am doing as you said

**Comment by SudeshAK** [comment]
@aitboudad correct we can do using above example but I have created tabs referring to this
https://plnkr.co/edit/hMZo3sXMqk35NckwYJCy?p=preview 
how  in this case I can create a form inside a tab?

**Comment by SudeshAK** [comment]
I have replicated the example 
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-pcwqtr 
Please look into it when u have time 
Thank u

**Comment by aitboudad** [comment]
Hi, I could find a better way, the only clean way to handle a such case is https://formly-js.github.io/ngx-formly/examples/advanced/tabs

**Comment by SudeshAK** [comment]
Thank you @aitboudad . As u said I have used above approach and I was able to create individual forms and also able to validate individual forms.Only problem is I am not able to submit individual form
When I submit it will submit entire model this is because we have `[options]="options[index]"` and ` [form]="form.at(index)"` but we don't have something like `[model]="model[i]"` . Can we submit individual form model?

**Comment by aitboudad** [comment]
to get the individual model use `form.at(index).value` instead of `model`.
