### ISSUE TITLE
As a developer I want to call a method using custom event from formly input field

### ISSUE THREAD

**Issue by stankusl** [formly-js/ngx-formly#886]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
Can't find a way to do it. 

**Expected behavior**
Expecting to have simple functionality like this working. 

**What is the motivation / use case for changing the behavior?**

I would like to introduce Store management into my project that will have lots of different fields and every change on any field will update all form values. Todo so I need custom functions firing from every input field when it is changed. 

* **Angular version:** 
5.x.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] - TSC 2.6

* **Node (for AoT issues):** `node --version` = latesat

**Comment by aitboudad** [comment]
you can use `(modelChange)` output

**Comment by aitboudad** [comment]
also please note that formly is mainly based on [Angular Reactive form](https://angular.io/guide/reactive-forms) so if `modelChange` doesn't fits to your need, you can rely on form instance which you can subsribe into its events (valueChanges, statusChanges).

**Comment by Alcantara6** [comment]
> also please note that formly is mainly based on [Angular Reactive form](https://angular.io/guide/reactive-forms) so if `modelChange` doesn't fits to your need, you can rely on form instance which you can subsribe into its events (valueChanges, statusChanges).

what is the differentce between formly modelChange and Angular valueChanges?

**Comment by Alcantara6** [comment]
> also please note that formly is mainly based on [Angular Reactive form](https://angular.io/guide/reactive-forms) so if `modelChange` doesn't fits to your need, you can rely on form instance which you can subsribe into its events (valueChanges, statusChanges).

what is the difference between formly modelChange and Angular valueChanges?

**Comment by aitboudad** [comment]
> what is the difference between formly modelChange and Angular valueChanges?

- `valueChanges`: is an observable object which emits the form value whenever a new change is emitted.
- `modelChange` is a `formly-form` component output which emits the `model` object whenever a new change is emitted.
