### ISSUE TITLE
template formly no show css

### ISSUE THREAD

**Issue by davidoween** [formly-js/ngx-formly#888]
template property does not show css. I need it without creating a custom component

https://stackblitz.com/edit/angular-ritmcc?file=app/app.component.ts

thanks

**Comment by aitboudad** [comment]
use `DomSanitizer` see https://stackblitz.com/edit/angular-nnieuq

**Comment by davidoween** [comment]
why doesn't work this?

https://stackblitz.com/edit/angular-ritaz8?file=app/app.component.ts

**Comment by davidoween** [comment]
fixed
