### ISSUE TITLE
Is there any way to apply mask to fields using NgxFormly

### ISSUE THREAD

**Issue by abnersouza** [formly-js/ngx-formly#889]
Hi, Im submitting a question to ask about masks, if there is anyway to use masks using the ngxformly, i check that for the AngularJs there were the ng-mask intergrated, is there any example or anyway to integrate with the ngx version?

I'm planning to use the formly but mask as essencial for the software we are building.

Thnks

**Comment by aitboudad** [comment]
you have to create a custom field type see https://stackblitz.com/edit/formly-mask-nested-configs

**Comment by aitboudad** [comment]
@ashwani11 for bootstrap just copy the input type https://github.com/formly-js/ngx-formly/blob/master/src/bootstrap/src/lib/types/input.ts and add the `textMask` attr `[textMask]="to.maskConfig"`

> is there any way to add masking configuration inside field config without creating a custom type ?

for now I think it may not be possible but when https://github.com/formly-js/ngx-formly/issues/253 and https://github.com/formly-js/ngx-formly/issues/180 is done then it could be easy to have a such feature without creating a custom type!

Note: if you have a good proposal why not!

**Comment by HarshitChhipa** [comment]
https://stackblitz.com/edit/angular-hddeh3-dlpjig?file=app%2Fcustom-input.component.ts

I tried wrapping ngx-mask with the input but it says ...
Template parse errors:
Can't bind to 'textMask' since it isn't a known property of 'input'. ("
<input [ERROR ->][textMask]="to.maskConfig" [type]="type" [formControl]="formControl" [formlyAttributes]="field">
Any Idea how to make a wrapper for making of the input.

**Comment by thorgod** [comment]
I could not open your stack blitz example. (Did you fork/save?)

**Comment by HarshitChhipa** [comment]
https://stackblitz.com/edit/angular-masking-as878?file=app/custom-input.component.ts

**Comment by thorgod** [comment]
First you need to change the type to custom in the json.....
app.component.ts Line 20
See bellow, your mask seems to work, after changing the type
https://stackblitz.com/edit/angular-masking-as878-ai6v7n?file=app/app.component.ts

**Comment by HarshitChhipa** [comment]
Thank you, man, for the answer.
It worked but then it became static. I tried making it dynamic it neither giving me any error nor it is working.
Can You please tell me where I m missing something.
Here is the stackblitz demo.
https://stackblitz.com/edit/angular-masking-dynamics?file=app/custom-input.component.ts

**Comment by HarshitChhipa** [comment]
Sorry don't answer it I m an idiot I missed square brackets.
