### ISSUE TITLE
Dynamically add fields on button click

### ISSUE THREAD

**Issue by hariharanpalani** [formly-js/ngx-formly#891]
Can you please help me to achieve the following feature (I am using angular 4),
1. On button click, I want to add new field to the FormlyFieldConfig. Currently it is not working.

Please help me handle this scenario.

**Comment by aitboudad** [comment]
see https://formly-js.github.io/ngx-formly/examples/advanced/repeating-section

**Comment by mihirhapaliya** [comment]
Hi 
Can you please help me on the following ?

I want to assign each repeater's index to hidden field in incremental order.

  this.ExampleFormlyFieldConfig = [
      {       
        'type': 'repeat',
        'fieldArray': {
          'fieldGroupClassName': 'row',
          'templateOptions': {
            'btnAddText': 'Add another control',
            'btnRemoveText': 'remove this control'
          },
          'fieldGroup': [
            {
              'key': '_id',
              'type': 'input',
              'templateOptions': {
              'label': 'Source'
                },
              'hideExpression':true
            },
            {
              'className': 'col-sm-12',
              'type': 'textarea',
              'key': 'description',
              'templateOptions': {
                'label': 'Description',
                'required': true,
                'rows': 3
              },
            }
            
          ],
        },
      },
    ];
