### ISSUE TITLE
Building Project Question

### ISSUE THREAD

**Issue by thorgod** [formly-js/ngx-formly#892]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

Best just to see stackbliz example, but I put the github source of core into a folder, and referenced the module. I am getting [Formly Error] There is no type by the name of "input".  

**Expected result**
I would like to use the project with the core loaded, so I can test things quickly. (Not use ng-packagr) 

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-zqmacd?file=app/app.module.ts

See Console log

**Comment by aitboudad** [comment]
you  to do the same for `@ngx-formly/bootstrap`

**Comment by thorgod** [comment]
That fixed it, thank you. 

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-zqmacd?file=app%2Fapp.component.ts

For others trying it out here is a example. Had to change all import @ngx-formly to local directly. (I think you can use alias tsconfig.json to point to directly maybe on local computer.)
