### ISSUE TITLE
Personally feel that you should add a functional data backfill

### ISSUE THREAD

**Issue by smile2014** [formly-js/ngx-formly#893]
Personally feel that you should add a functional data backfill, such as templateOptions:{
Context="{'partner_id':parent.partner_id, 'quantity':product_qty,'uom':product_uom, 'company_id': parent.company_id}" }

Backfilling other fields in the current form after I select a value

**Comment by smile2014** [comment]
import {Component} from '@angular/core';
import {FieldType} from '@ngx-formly/core';
import {backDataField} from '../../../../utils/utils';
@Component({
  selector: 'formly-field-select',
  template: `
      <div nz-form-item nz-col [nzMd]="to.divCol? to.divCol: 8" style="margin-bottom:4px;">
          <div nz-form-label nz-col [nzMd]="to.lblCol? to.lblCol :6">
              <label *ngIf="to.required" [title]="to.label" nz-form-item-required>{{to.label}}</label>
              <label *ngIf="!to.required" [title]="to.label">{{to.label}}</label>
          </div>
          <div nz-form-control nz-col [nzMd]="to.inputCol? to.inputCol: 18">
              <apes-select [api]="to.api" (backFillData)="backData($event)"  [disabled]="to.disabled" [formlyAttributes]="field" [formControl]="formControl" ></apes-select>
          </div>
      </div>
  `,
})
export class FormlyFieldSelect extends FieldType {
   backData() {
       console.log(this);
       const backField = this.to.context || '';
       backDataField(this, backField);
   }
}

**Comment by smile2014** [comment]
import { FormGroup } from "@angular/forms";

export function backDataField(content: any, backField: string) {
    if (backField !== '') {
        const controlValue = content.formControl.value;
        backField.split(',').forEach(key => {
        if (key.indexOf(':') > -1) {
            const arryField = key.split(':');
            const a = {};
            if (controlValue == null) {
               a[arryField[0]] = "";
            } else
                a[arryField[0]] = controlValue[arryField[1]];
           // delete this.formControl.value[arryField[1]];
           content.form.patchValue(a);
         } else {
           const a = {};
           if (controlValue == null) {
              a[key] = "";
           } else
              a[key] = controlValue[key];
           content.form.patchValue(a);
           //delete this.formControl.value[key];
         }
     });
  }
}

**Comment by smile2014** [comment]
Like this, now I'm simple to achieve, not very elegant

**Comment by smile2014** [comment]
{
                                    key: 'contract',
                                    type: 'select',
                                    templateOptions: {
                                        label: 'order',
                                        placeholder: '',
                                        required: true,
                                        divCol: 8,
                                        lblCol: 6,
                                        inputCol: 18,
                                        context: 'department,company,supplier:partner',
                                        api: 'acc.contract.find'
                                    }
                                }

**Comment by smile2014** [comment]
I think data backfilling is very common in forms and it's better to integrate them in

**Comment by aitboudad** [comment]
you can use `defaultValue` option: 
```ts
{
  ....
  defaultValue: 'test'
}
```

https://formly-js.github.io/ngx-formly/examples/field-options/default-value

**Comment by smile2014** [comment]
I clicked select on the interface to trigger backfill  @aitboudad
