### ISSUE TITLE
Reusing formly-form and loading new fields and model fails

### ISSUE THREAD

**Issue by FritzHerbers** [formly-js/ngx-formly#909]
```
[x ] bug report
```

**Current behavior**
Reusing a formly-form and loading new fields and model fails. This was some time ago fixed.

https://stackblitz.com/edit/angular-fw3yua?file=app%2Fapp.component.ts

Would be nice to have some tests for the following situations:
- change of fields
- change of model
- change of both

Version ngx-formly 2.1.1

**Comment by aitboudad** [comment]
`form` should be initialized too in that case to make it work, the fix may introduce a breaking change for those who use the old way for repeat section (targeted to v3 instead)
