### ISSUE TITLE
Question: Field Array Rows Advanced

### ISSUE THREAD

**Issue by thorgod** [formly-js/ngx-formly#914]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[X] support request
```

Looking to develop a new feature for repeating rows/field array for the Core V3. I might need some help.

Right now it is copying the setting from only the first row. 
https://github.com/formly-js/ngx-formly/blob/master/src/core/src/templates/field-array.type.ts#L18-L20

What if we have settings for different rows. So instead of copying always the first field.fieldArry setting we copy from a index if it exists. (Otherwise copy from the first)

**Current behavior**
```
      fieldArray: {
        fieldGroup: [
        ],
```

**Proposed behavior**
```
      fieldArray: {
        fieldGroups: [
             { fieldGroup: [ {} ]}, //Row 1 settings
             { fieldGroup: [ {} ]}  //Row 2 settings
             ...
        ],
```
**Thoughts**
Maybe there is a better idea to approach this problem or architecture. Let me know if you have any thoughts or idea.

I do not mind creating a PR for it but might need some help designing it and coding it

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-nwtzoh

**Comment by thorgod** [comment]
@aitboudad Thank you!

**Comment by thorgod** [comment]
Can we re-open this.

https://stackblitz.com/edit/angular-nwtzoh-vk5ifg?file=app%2Fapp.component.ts

Currently
![image](https://user-images.githubusercontent.com/13910170/39258555-1bda6874-4869-11e8-89c7-0b52082e8bba.png)

What I need.
![image](https://user-images.githubusercontent.com/13910170/39258654-58db8b36-4869-11e8-91b2-072234a1d231.png)


I would like to apply a different template/formly config based on row.

**Comment by thorgod** [comment]
Interesting idea to use hideExpression. Thanks for the example, that might work for now.

However, it seems like a workaround; I don't mind creating a new type or trying to change field-array.type.ts for a more permanent solution.

**Comment by aitboudad** [comment]
to me it's not a workaround :), if you have a better approach without complicating the core code then I would say PR welcomed

**Comment by thorgod** [comment]
Haha I understand where you are coming from. The forms I will be displaying will have a lot of fields, and  rows (100~fields maybe) wanted to keep it light weight. If the hideExpression does not cause the extra fields to build then it might be a good solution. I need to do some testing.

 
FYI, try hitting the plus button in your example, (I can add code to compensate to make sure it displays correct copy when plus is hit), this is why I think its kind of a workaround.

**Comment by thorgod** [comment]
@aitboudad  
I was able to accomplish it pretty easily by changing one line.  --Line 20  (I still need to fix adding/subtraction) 
`     { ...clone(field.fieldArray.fieldGroup[i]), key: `${i}` },`

https://stackblitz.com/edit/first-try-at-row-settings?file=app%2Fngx-formly%2Ftemplates%2Ffield-array.type.ts

(Take a look, it would be breaking change, is there a way I could implement it work with backward compatibility for other people using ngx-formly)

**Comment by aitboudad** [comment]
`createControl` has been removed (https://github.com/formly-js/ngx-formly/pull/912),
based on your last example I think you can separate them using defferent key to keep thing simple https://stackblitz.com/edit/angular-nwtzoh-zvzc93

**Comment by thorgod** [comment]
I saw that, you moved it into the builder, sadly now I cant override it. (But it did fix reloading the model)  

Thanks, that example is another interesting idea to use the key. However, that brings about more problems for me. I am using rows for calculations and referencing the model. It easier to have more of a flat model.

With your Model
```
  "Table1": [
    {
      "Row1": [
        {
          "A1": "2"
        }
      ],
      "Row2": [
        {
          "B1": "2"
        },
        {
          "B1": "2"
        }
      ]
    }
```

When its flat its easier to do calculations. (This calculations/compares/ ect are generated dynamically based on keys)
```
{
  "table1": [
    {
      "A1": "3",
      "A2": "3"
    },
    {
      "B1": "3"
    }
  ]
}
```

Need to do some thinking/testing your proposed idea is interesting but gets messy when I start having multiple tables, and rows.
https://stackblitz.com/edit/angular-nwtzoh-ujkztv

**Comment by thorgod** [comment]
@aitboudad  I think the answer will be no. 


So the `createControl` got moved to the builder `registerFormControls`, is there a way to bring back `createControl` for FieldArrayType so I can override the method by using my own class `FieldArrayType` inside the application that uses ngx-formly?

Maybe there is some sort of dependency injection I can do to create a special FieldArrayType? (Unsure how to do that)

I would hate for our application to have fork from the core, just so I can get this working in our project. (Trying to prevent that)

**Comment by thorgod** [comment]
Yah the hide might be a good workaround for now. I think I will go with that. 

Hopefully we can come back to it and get something that works for everyone! Thanks for the help.
