### ISSUE TITLE
Select does not display the default value when is an object

### ISSUE THREAD

**Issue by lorenzonet** [formly-js/ngx-formly#917]
**I'm submitting a ...** 
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```
**Current behavior**
Select component does not set the default value if it is an object, event though the field value is correct

**Expected behavior**
Show the correct label when a default value is set

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-psn6rl?file=app%2Fapp.component.ts

**Please tell us about your environment:**
Windows

* **Angular version:** 2.0.X
5.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =
v7.10.1

**Comment by aitboudad** [comment]
in that case you have to pass an object from option instead see https://stackblitz.com/edit/angular-sdcltu

**Comment by tadas-subonis** [comment]
@aitboudad I've noticed that on RepeatTypeComponent (as in the guide) the object values are reset for existing select fields when a new field is added. Is there a way to fix that?

**Comment by aitboudad** [comment]
@tadas-subonis could you please provide a reproduction example?

**Comment by tadas-subonis** [comment]
So I've found a quick-fix for my case with "compareWith" method

```
                {
                  'key': 'assignedUser',
                  'type': 'select',
                  'templateOptions': {
                    required: true,
                    'label': 'Persion',
                    'options': userOptions,
                    compareWith: compareIdObjects,
                  },
                },

```

where

```
    function compareIdObjects(o1, o2) {
      if (!o2 && !o1) {
        return true;
      }

      if (!o2) {
        return false;
      }

      return o1.id === o2.id;
    }
```
