### ISSUE TITLE
Question: Life Cycle (Documentation)

### ISSUE THREAD

**Issue by thorgod** [formly-js/ngx-formly#919]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

It would be nice to figure out the life cycle of ngx-formly and the hooks. 

Just trying to get a understanding of the inner workings of ngx-formly.

**Comment by aitboudad** [comment]
1. [build field](https://github.com/formly-js/ngx-formly/blob/master/src/core/src/components/formly.form.ts#L61)
2. [evaluate field expressions](https://github.com/formly-js/ngx-formly/blob/master/src/core/src/services/formly.form.builder.ts#L34)
3. [render field](https://github.com/formly-js/ngx-formly/blob/master/src/core/src/components/formly.field.ts#L57):
    * pre-wrappers
    * field component
    * post-wrapper
