### ISSUE TITLE
Focusing the input by pressing Enter should not trigger the click event of the test button

### ISSUE THREAD

**Issue by smile2014** [formly-js/ngx-formly#921]
Focusing the input by pressing Enter should not trigger the click event of the test button

https://stackblitz.com/edit/angular-pt46kn

**Comment by aitboudad** [comment]
when  pressing Enter, the browser trigger a submit form, all buttons without `type` inside form are considered a submit one try to use button:
```ts
<button type="button">
```

**Comment by smile2014** [comment]
thank you
