### ISSUE TITLE
Reset Model at once

### ISSUE THREAD

**Issue by SudeshAK** [formly-js/ngx-formly#922]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] Question
```
In this example https://stackblitz.com/angular/gkmymknklla
If I want to use resetModel then I have to write
`this.options[0].resetModel();`
This will reset the first tab. Is it possible to reset all the tab at once instead of resetting each tab
one after the other?

* **Angular version:** 5.0

**Comment by aitboudad** [comment]
just create a function `resetAll` that reset all options at once:
```ts
resetAll() {
  this.options.forEach(option => option.resetModel());
}
```
