### ISSUE TITLE
Error using datepicker with angular-cli 1.7.3 and material 5.2.5

### ISSUE THREAD

**Issue by rbonillajr** [formly-js/ngx-formly#923]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

ERROR in src/app/app.module.ts(16,43): error TS2307: Cannot find module @ngx-formly/material/datepicker.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

create new angular-cli project
install material 2
install ngx-formy
config with this post: [issue 614](https://github.com/formly-js/ngx-formly/issues/614#issuecomment-379567907)

attach zip file with my code:
[datepicker_test.zip](https://github.com/formly-js/ngx-formly/files/1959130/datepicker_test.zip)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.2.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [TypeScript 2.5]

* **Node (for AoT issues):** `node --version` =8.10

**Comment by aitboudad** [comment]
Hi, can you update typescript version into `"typescript": "~2.7.2"` an try again, thanks!

**Comment by rbonillajr** [comment]
Thanks!!
this works.
