### ISSUE TITLE
using validation and custom validator

### ISSUE THREAD

**Issue by rajeshscontact** [formly-js/ngx-formly#926]
is it possible to use both validation array and custom validation as part of validators?

validators: {
        ip: {
          expression: (c) => /(\d{1,3}\.){3}\d{1,3}/.test(c.value),
          message: (error, field: FormlyFieldConfig) => `"${field.formControl.value}" is not a valid IP Address`,
        },
       validation: ['someOtherPredefinedValidation']
      }

**Comment by thorgod** [comment]
FYI Did you look at the guide you might use a different approach. What is the use case?
https://formly-js.github.io/ngx-formly/guide/validation

Also here is what you are asking, and no it didnt work.
https://stackblitz.com/edit/angular-dfkhrz?file=app/app.component.ts

**Comment by aitboudad** [comment]
fixed in `3.0.1`

**Comment by VidhyaK29** [comment]
Hi,

I need to push set of fields inside the FormlyFieldConfig array on change of select event within the FormlyFieldConfig.


   this.Formtemplate = [
            {
                key: 'FormName',
                type: 'select',
                templateOptions: {
                    required: true,
                    type: 'text',
                    label: 'Form Name',
                    options: this.appData.get(this.appData.url.getTitleList, []),
                    valueProp: 'id',
                    labelProp: 'title',
                    change: (field, $event) => {
                        const id = $event.value;
                        this.appData.get(this.appData.url.getTemplate, [id]).subscribe((res) => {
                            this.templateArr = JSON.parse(res[0].form_tempate).form;
                            this.pushData();
                        });
                    }
                }
            }


/************/

    public pushData() {
        if (this.templateArr.length) {
            map(this.templateArr, (template) => {
                this.Formtemplate.push(
                    {
                        key: template.fieldname.toLowerCase(),
                        type: template.fieldtype,
                        templateOptions: {
                            label: template.fieldname,
                            placeholder: template.placeholder

                        }
                    });
            });
        }
    }

Field is pushed in a array. But following error is showing. The field doesn't seem to have form control.

Cannot find control with unspecified name attribute.

**Comment by aitboudad** [comment]
@VidhyaK29 a rebuild is required to take account of the new pushed fields, use spread operator instead of push:
```ts
this.Formtemplate = [
  ...this.Formtemplate,
  { key: template.fieldname.toLowerCase(), ... }
];
```

**Comment by VidhyaK29** [comment]
Hi ,
Have tried the above.
 But it doesn't creating a field. Simply it just pushing the value. Controls is not all creating.
..
![formly](https://user-images.githubusercontent.com/52420846/60698825-e01f0a80-9f0e-11e9-882e-a28fd5b8a762.PNG)

**Comment by VidhyaK29** [comment]
map(this.templateArr, (template) => {
                this.Formtemplate = [
                    ...this.Formtemplate,
                    {
                        key: template.fieldname.toLowerCase(),
                        type: template.fieldtype,
                        templateOptions: {
                            label: template.fieldname,
                            placeholder: template.placeholder

                        },
                        formControl: template.fieldname.toLowerCase()
                    }
                ];
            });

The formfieldconfig array is having the field . Field is not at all rendering in the UI.

**Comment by VidhyaK29** [comment]
I have used subscribe to render. It is working . Thanks!
