### ISSUE TITLE
Custom validator messages with minLength and maxLength not working

### ISSUE THREAD

**Issue by Carbammato** [formly-js/ngx-formly#927]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Hello there. I'm trying to create some forms, and I want to show a validation message in one of my input field. Nothing complicated, I just want to use _minLength_ and the _maxLength_ properties included in the _templateOptions_. But I want also to show a customized error message, so I decided to add a string inside _field.validation.messages.minLength_.

So, I created something like this:
```
fields: FormlyFieldConfig[] = [
    {
      key: 'test01',
      type: 'input',
      templateOptions: {
        label: 'Test',
        required: true,
        minLength: 5
      },
      validation: {
        messages: {
          minLength: "lower than 5!"
        },
      },
    },
];
```
Well, the input become red, but no message showing up. Than I noticed something:  inside _messages_, if I type _minlength_ instead of _minLength_, than it works. (Stackblitz below)

**Expected behavior**
When I type something in an input field without respecting the minLength (or maxLength) validation rule, a custom error message must show up if I added a  _field.validation.messages.minLength_ in my code.

I expect that properties related to the same behaviour (in this case: an error message in case a typed input is too short) should have the same name. I'm reporting as a bug, although I'm not sure if my code is entirely correct.

**Minimal reproduction of the problem with instructions**
Here is a quick representation of this issue in Stackblitz. Note that I created two different components: the first contains _field.validation.messages.minlength_ and works, the second contains_field.validation.messages.minLength_ and no error message is shown.
https://stackblitz.com/edit/formly-minlength

**What is the motivation / use case for changing the behavior?**
Parser recognize _minlength_ instead of _minLength_

(please, note I'm quite a newbie here in github and in programming in general - any kind of advice will be more than appreciated)

**Comment by aitboudad** [comment]
see https://formly-js.github.io/ngx-formly/examples/validation/built-in-validations

**Comment by lluis-stage** [comment]
minlength all in minus.

**Comment by minhhieugma** [comment]
@aitboudad In the example, I see that we cannot input exceed the max length. So, why do we need the max length validation message when we cannot go beyond that?
