### ISSUE TITLE
Field type number with Bootstrap UI, bug when entering character 'e'

### ISSUE THREAD

**Issue by Juceztp** [formly-js/ngx-formly#929]
Hi!

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
In the fields type number allows to enter the letter e, the problem is when you want to avoid with a validator. If you enter '1e1' and add a `console.log (control.value)` in the validator function, it prints in console [1 - null - 10] and in the common bootstrap prints [1 - null - 1e1].

Reviewing a similar issue, the print [1 - null - 1e1], which seems to be a problem in later versions.
https://stackblitz.com/edit/angular-44tgas

**Expected behavior**
I think I should print [1-null-1e1] as in the common bootstrap or better yet [1-1e-1e1]

**Minimal reproduction of the problem with instructions**
First form: Common bootstrap
Second form: Formly
Instructions: Enter '1e1' and check console log.
UI Bootstrap: https://stackblitz.com/edit/formly-type-number-with-bootstrap

**What is the motivation / use case for changing the behavior?**
I am implementing an 'age' field and should not allow the characters (e,., -), only positive integers.

'1e1'
1 => control.value (1) and return true
1e => control.value (null) and return false
1e1 => control.value (10) and return true

If I put a field as a text type it works but I lose the arrows on the right that allows to increase or decrease and also shortcuts with keyboard.

**Please tell us about your environment:**
Operating System: Linux - Ubuntu 17.10
IDE: Visual Studio
Package manager: NPM

* **Angular version:** 5.0.0 & 5.2.0
https://gist.github.com/Juceztp/10b176262ba64876e1754a9346247e7e

* **Browser:** Chromium - Versión 65.0.3325.181 (Build oficial) Built on Ubuntu , running on Ubuntu 17.10 (64 bits)

* **Language:** TypeScript 2.5.3

* **Node (for AoT issues):** `node --version` = 9.2.1

Thanks :)

**Comment by danielcaris** [comment]
+1

**Comment by aitboudad** [comment]
`e1e` is a valid number :), angular forms apply [parseFloat] (https://github.com/angular/angular/blob/master/packages/forms/src/directives/number_value_accessor.ts#L51) for number input type which allow lose a such info, 
so I would say it's an issue in angular,
in your example `First form: Common bootstrap` try to use `[formControl]="formControl"` and you'll get the same result (https://stackblitz.com/edit/formly-type-number-with-bootstrap-zdlfta)

to solve that issue, you can create a custom field type, similar to the old version https://github.com/formly-js/ngx-formly/commit/8a3009262ca118df7e069edeeaff7793ec09c60e#diff-314d8a3b8f1ee85e33757e5735e130e6 but you have to deal with converting the model value to number manually
