### ISSUE TITLE
chips

### ISSUE THREAD

**Issue by michalkubat** [formly-js/ngx-formly#934]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[x] support request
```

**Minimal reproduction of the problem with instructions**
Hello. I am having a problem with implementing "input chips" functionality, as you can see in the provided example. Is it somehow possible to "erase" input (after chip creation) without manipulating the model, or is there any chip example I could follow? Thank you.

Example: https://stackblitz.com/edit/angular-2tdkxm-p3zjqq _(chip is created after comma keypress)_

**Comment by thorgod** [comment]
Just a  note, I really like ngx-chips over materials
 https://github.com/Gbuomprisco/ngx-chips

**Comment by aitboudad** [comment]
sorry not clear to me what's going wrong :), can you explain please?

**Comment by michalkubat** [comment]
Sorry for not providing enough details. My problem was with using material chips. As @thorgod suggested, ngx-chips solved my problems.
