### ISSUE TITLE
Errors with angular 6 using angular-cli 

### ISSUE THREAD

**Issue by rbonillajr** [formly-js/ngx-formly#936]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

![image](https://user-images.githubusercontent.com/8268226/39610546-bcee686a-4f16-11e8-8304-fa9eb5f029ae.png)

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** TypeScript 2.7.2

* **Node (for AoT issues):** `node --version` =8.10

**Comment by aitboudad** [comment]
you have to use `rxjs-compat` until we add `rxjs@6.0` support

**Comment by aitboudad** [comment]
added in `4.0.0-alpha.0`, here is a working example: https://stackblitz.com/edit/angular-2ulhgf

**Comment by thorgod** [comment]
Nice I am going to give it a try today.
