### ISSUE TITLE
FieldArrayType repeater reordering

### ISSUE THREAD

**Issue by Ore4444** [formly-js/ngx-formly#940]
**I'm submitting a ...** 
```
[X] feature request
```

Before the addition of FieldArrayType, I wrote a simple reordering function for the repeater.

```javascript
reorderUp(i) {
    if (i === 0) {
        return
    }

    this.reorder(i, i - 1)
}

reorderDown(i) {
    if (i === this.formControl.length - 1) {
        return
    }

    this.reorder(i, i + 1)
}

private reorder(oldI: number, newI: number) {
    const thisModel = this.model.splice(oldI, 1)[0]
    this.model.splice(newI, 0, thisModel)

    const thisFields = this.field.fieldGroup.splice(oldI, 1)[0]
    this.field.fieldGroup.splice(newI, 0, thisFields)
    this.field.fieldGroup.forEach((f, index) => f.key = `${index}`)

    const thisField = this.formControl.at(oldI)
    this.formControl.removeAt(oldI)
    this.formControl.insert(newI, thisField)
}
```

Following the new repeater field example with FieldArrayType, I can't get my function to work. Since `add` and `remove` were moved to core, should `reorderUp` and `reorderDown` be added to core as well?

**Comment by aitboudad** [comment]
with `3.1.0` you can can easily implement it using `add` and `remove`, see https://stackblitz.com/angular/emaddlpyevj

**Comment by Ore4444** [comment]
@aitboudad WOW thanks a lot :)
I love using Formly btw, we use it in production and couldn't be happier
