### ISSUE TITLE
Model cannot update correctly when reuse a form  (Repeat Section)

### ISSUE THREAD

**Issue by zd5043039119** [formly-js/ngx-formly#942]
```
[x] bug report
```

**Current behavior**

When i use formly-js to build a dynamic form,it's correct when i open the modal first time,
![2018-05-07 17-23-23](https://user-images.githubusercontent.com/754059/39695030-cc4d2ece-521b-11e8-99cf-8f94b4f8b54b.png)
and i when i open it the second time,it shows
![2018-05-07 17-24-23](https://user-images.githubusercontent.com/754059/39695070-eb9e01b8-521b-11e8-8307-d7a95f9dbec4.png)

i checked all the code and finally find the problem is at formly.form.ts,the function called setOptions
```
    if (!(<any> this.options).resetTrackModelChanges) {
        (<any> this.options).resetTrackModelChanges = () => {
            this.clearModelSubscriptions();
            this.trackModelChanges(this.fields);
        };
    }
```

When i build the form the second time, resetTrackModelChanges has been defined,and i called add function in field-array.type.ts, then "this.fields" is the fields defined when it first time init, and can not track model change correctly.

So i have to clear this form options every time when i close the modal or change the code to redefined the resetTrackModelChanges, which is better?
**Please tell us about your environment:**

* **Angular version:** 5.2.X

* **Browser:** [all]

* **Language:** [all]

* **Node (for AoT issues):** `node --version` = 9.3.0

**Comment by aitboudad** [comment]
Hi, can you provide a reproduction example,  here is a starter example https://stackblitz.com/edit/angular-3fmi3c

**Comment by zd5043039119** [comment]
[https://stackblitz.com/edit/angular-3fmi3c-rcvrjk](url), and i found that i renew the form and the model,but not the options,my bad!
Thank you for your help!
