### ISSUE TITLE
Checking changes.model.currentValue in ngOnChanges

### ISSUE THREAD

**Issue by Pat-Lovelace** [formly-js/ngx-formly#944]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[x] support request
```

**Current behavior**
I have a problem with a custom-formly-type (a custom-table with a modal to edit the rows) that follows the idea of your Repeating Section. 

Trying to debug it, I realized that when I use a splice on the model of the custom-component, which in this case is different from the principal model, but it's binding, the method: **patchModel** throws an error because the `changes.model.currentValue` is undefined. If you change the method ngOnChanges adding a pre checking of this value, everything works fine: 

```javascript
    FormlyForm.prototype.ngOnChanges = function (changes) {
        debugger
        if (!this.fields || this.fields.length === 0 || !this.isRoot) {
            return;
        }
        if (changes.fields || changes.form) {
            this.model = this.model || {};
            this.form = this.form || (new FormGroup({}));
            this.setOptions();
            this.clearModelSubscriptions();
            this.formlyBuilder.buildForm(this.form, this.fields, this.model, this.options);
            this.trackModelChanges(this.fields);
            this.updateInitialValue();
        }
        else if (changes.model && changes.model.currentValue) {
            this.patchModel(this.model);
        }
    };
```

**Expected behavior**
Would it be possible to have this changes? In particular, I use the version 2.1.1 and I'm not sure if it is possible to upgrade my proyect to the last compatible version. Would it be possible to have this changes on version 2.1.X? 

**Minimal reproduction of the problem with instructions**
I tried to emuled the problem but I'm not able to reproduct it on stackblitz. This occurs when I use something similar to this.model.splice(index,1) and **ngOnChanges** receives `changes.model.currentValue = undefined`. **this.model** is inside the component and it's an array of the rows of the table.

**What is the motivation / use case for changing the behavior?**
I want to remove rows of a custom-table. 

**Please tell us about your environment:**
Current version: 2.1.1 of @ngx-formly.

**Comment by aitboudad** [comment]
> Would it be possible to have this changes on version 2.1.X?

possible but I highly recommend to upgrade to the new version ;), maintaining multiple version is a waste of time for me

can you provide a reproduction example, thanks!

**Comment by Pat-Lovelace** [comment]
Hi! Uff I finally got to replicated my problem. I recreated a short version of my custom-table: [https://stackblitz.com/edit/ngx-formly-ui-bootstrap-4r223i?file=app/custom-table/custom-table.component.html](https://stackblitz.com/edit/ngx-formly-ui-bootstrap-4r223i?file=app/custom-table/custom-table.component.html)
As you can check, if you add new rows, it works fine, but if you remove an element (or cancel a creation of a new element), changes.model.currentValue = undefined, and it doesn't work. 

PD: I'll try to upgrade my proyect ASAP, but I would need this on version 2.1.x for now. Thanks!

**Comment by aitboudad** [comment]
just add `*ngIf="showModalAdd"` to form and it should work, see https://stackblitz.com/edit/ngx-formly-ui-bootstrap-f3msa1

**Comment by Pat-Lovelace** [comment]
Omg! That works! It was driving me crazy. Thank you for your help :)
