### ISSUE TITLE
Problem with some exports from @ngx-formly/core

### ISSUE THREAD

**Issue by davideperozzi** [formly-js/ngx-formly#945]
**I'm submitting a ...** 
```
[ ] bug report
[ ] feature request
[ x ] support request
```

**Current behavior**
I currently have a shared module which wraps around the formly module. In order to do this, 
I've added all the providers with `forRoot` and `forChild` by myself. So I'm adding the providers 
directly to my shared module. The Problem I have is that all the components and services 
needed for the providers aren't exported from the `public_api`. Instead they are exported from 
` ../core/ngx-formly-core.d.ts` with an alias like this: 
```
export { FormlyGroup as ɵc } from './lib/components/formly.group';
export { FORMLY_CONFIG_TOKEN as ɵa } from './lib/services/formly.config';
export { FormlyFormExpression as ɵb } from './lib/services/formly.form.expression';
export { FormlyValidationMessage as ɵd } from './lib/templates/formly.validation-message';
```
And currently I'm importing them by the alias like so (which doesn't feel right): 
```
import {
    ɵa as FORMLY_CONFIG_TOKEN, 
    ɵb as FormlyFormExpression, 
    ɵc as FormlyGroup
} from '@ngx-formly/core'; 
```

**Expected behavior**
It would be nice the mentioned services and components would be importable from the package "@ngx-formly/core" directly (without an alias).

I think the solution is to put the exports in the `public_api`, like mentioned here: https://github.com/dherges/ng-packagr/issues/520#issuecomment-359427430

**Steps to reproduce**
- Install `@ngrx-formly/core` and `@ngrx-formly/bootstrap`:
```
"@ngx-formly/bootstrap": "^4.0.0",
"@ngx-formly/core": "^4.0.0"
```
- Create a shared module with `FormlyModule` in the `imports`
- Copy the two static functions `forRoot` and `forChild` from the core module into your shared module
- If you're using an IDE with (e.g. with ItelliSense) you will already see, that the core doesn't export all the necessary classes directly

**What is the motivation / use case for changing the behavior?**
By changing this, it would be possible to use the injector token directly and add the providers manually to any module.

**Please tell us about your environment:**
* **Angular version:** 6.0.X
* **Browser:**  `all`
* **Language:** `TypeScript`
* **Node (for AoT issues):** `node --version` = v10.1.0

Maybe someone knows a better way to integrate the providers from ngrx-formly into a custom module?

**Comment by aitboudad** [comment]
do you have a valid use-case to use them outside `ngx-formly` ?

**Comment by davideperozzi** [comment]
@aitboudad 

I want to have a single shared module for my forms. In which I can import into other modules. This way I don't need to import two separate modules for my forms. Maybe there is a better solution. My module currently looks like this: 

```javascript
....
import { formConfig, usedTypes, usedWrappers } from './form.config';
import { 
   ConfigOption, 
   FormlyConfig, 
   FormlyFormBuilder, 
   FormlyModule, 
   ɵa as FORMLY_CONFIG_TOKEN, 
   ɵb as FormlyFormExpression, 
   ɵc as FormlyGroup 
} from '@ngx-formly/core';

@NgModule({
  imports: [
    ButtonModule, // A shared ui module
    ApiModule,  // Another shared module
    NgCommonModule,
    NgFormsModule,
    ReactiveFormsModule,
    FormlyBootstrapModule,
    FormlyModule
  ],
  declarations: [
    ...usedTypes,
    ...usedWrappers,
    FormErrorComponent,
    FormComponent
  ],
  exports: [
    FormComponent
  ]
})
export class FormModule {
  public static forRoot(): ModuleWithProviders {
    return {
      ngModule: FormModule,
      providers: [
        FormlyFormBuilder,
        FormlyFormExpression,
        FormlyConfig,
        { provide: FORMLY_CONFIG_TOKEN, useValue: { types: [{ name: 'formly-group', component: FormlyGroup }] }, multi: true },
        { provide: FORMLY_CONFIG_TOKEN, useValue: formConfig, multi: true },
        { provide: ANALYZE_FOR_ENTRY_COMPONENTS, useValue: formConfig, multi: true },
      ]
    };
  }

  public static forChild(config: ConfigOption = {}): ModuleWithProviders {
    return {
      ngModule: FormModule,
      providers: [
        { provide: FORMLY_CONFIG_TOKEN, useValue: config, multi: true },
        { provide: ANALYZE_FOR_ENTRY_COMPONENTS, useValue: config, multi: true },
      ]
    };
  }
}  
```

Now I can use this as a shared module, (for example) like this: 

```javascript
...
import { FormModule } from 'my/shared/modules';

@NgModule({
  imports: [
    CommonModule, 
    ApiModule, // Shared ui module
    FormModule // The shared form module coming with all components for building forms
  ],
  ...
})
export class ExampleModule { }
``` 

I also tried to create separate form modules called 
`ChildFormModule` and `RootFormModule` which then both includes a `BaseFormModule` which includes all the components and stuff. That ain't worked very well and also wasn't a good solution.

**Comment by aitboudad** [comment]
Here is the right way:
```ts
....
import { formConfig, usedTypes, usedWrappers } from './form.config';
import { FormlyModule, ConfigOption } from '@ngx-formly/core';
import { FormlyBootstrapModule } from '@ngx-formly/bootstrap';

@NgModule({
  imports: [
    ...
    FormlyModule
  ],
  declarations: [
    ...usedTypes,
    ...usedWrappers,
    FormErrorComponent,
    FormComponent
  ],
  exports: [
    FormComponent
  ]
})
export class FormModule {
  public static forRoot(): ModuleWithProviders[] {
    return [
      { ngModule: FormModule, providers: [] },
      FormlyModule.forRoot(),
      FormlyBootstrapModule,
    ];
  }

  public static forChild(config: ConfigOption = {}): ModuleWithProviders[] {
    return [
      { ngModule: FormModule, providers: [] },
      FormlyModule.forChild(config),
    ];
  }
}  
```

**Comment by davideperozzi** [comment]
Thank you! It works like a charm. Didn't know it's possible to nest modules like that. So als learned something new. 

Btw. ngx-formly is great. It's helping us a lot! :)
