### ISSUE TITLE
Get component instance from field onInit event

### ISSUE THREAD

**Issue by Constantinos-Impact** [formly-js/ngx-formly#946]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```
Hello there, first thank you all for the great library.
I have one question. Is there a way to get component instance from on init event? Basically i am trying to create Cascaded Select like the example but without settings the field.to.options. I have implement a custom select wrapper using another select component lib and on the init function subscribing to other select valueChanges and change the url of the select component and reload it to fetch the new data.

Here is the part  of code to get the idea.
```
  lifecycle: {

          onInit: (form, field) => {

            let selectComponent = field.component as SelectComponent;

            form.get('customerId').valueChanges.pipe(

              takeUntil(this.onDestroy$),
              startWith(form.get('customerId').value),
              tap(customerId => {

                if (!customerId) return;

                field.formControl.setValue('');
                field.templateOptions.config = this.selectConfig.getCustomerAccountConfig(customerId);

               selectComponent.loadFromUrl();

              }),
            ).subscribe();
          },
        }
```
Is what trying to do doable?  the field.component as i can see is a function not the action component instance.

**Comment by aitboudad** [comment]
you can do it by assigning the component instance to field during component construction:

```ts
@Component({
  ...
})
export class SelectComponent extends FieldType {
  private _field: FormlyFieldConfig;
  set field(field) {
    this._field = field;
    this._field.templateOptions.componentRef = this;
  }
  get field() { return this._field; }
  ...
}
```

IMO using a separate service would be better ;).

**Comment by Constantinos-Impact** [comment]
Thanks @aitboudad. It worked like a charm :)

**Comment by aitboudad** [comment]
**Update**: added `ngOnDestroy` to clear assigned `componentRef`.

**Comment by smile2014** [comment]
FormlyForm.html:2 ERROR TypeError: this.interceptTable is not a function
    at eval (eval at _loop_1 (apes-form.component.ts:132), <anonymous>:5:6)
    at FormlyField.push../node_modules/@ngx-formly/core/esm5/ngx-formly-core.js.FormlyField.lifeCycleHooks (ngx-formly-core.js:1056)
    at FormlyField.push../node_modules/@ngx-formly/core/esm5/ngx-formly-core.js.FormlyField.ngOnInit (ngx-formly-core.js:1003)
    at checkAndUpdateDirectiveInline (core.js:10097)
    at checkAndUpdateNodeInline (core.js:11363)
    at checkAndUpdateNode (core.js:11325)
    at debugCheckAndUpdateNode (core.js:11962)
    at debugCheckDirectivesFn (core.js:11922)
    at Object.eval [as updateDirectives] (FormlyForm.html:2)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:11914)

**Comment by smile2014** [comment]
} else if (t === 'object') {
      for (let k in metadata) {
        let value = metadata[k];
        if (type(value) === 'string') {
          if (k === 'onInit' || k === 'onChanges' || k === 'doCheck'
            || k === 'afterContentInit' || k === 'afterContentChecked'
            || k === 'afterViewInit' || k === 'afterViewChecked'
            || k === 'onDestroy'
          ) {
            metadata[k] = new Function('form, field', String(value));
          } else if (k === 'onDepends') {
            let functionBody = this.createOnDependsFunctionBody(value || undefined);
            if (exists(functionBody)) {
              metadata.lifecycle.onInit = new Function('form, field', functionBody);
            }
          }

**Comment by smile2014** [comment]
@aitboudad

**Comment by mrigank-taxak** [comment]
How to use lifecycle hooks in JSON-Schema in order to populate the options in the second selection field (backend API data) after the selection of the first field using the IDs.

**Comment by aitboudad** [comment]
@mrigank-taxak see https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527

**Comment by smile2014** [comment]
@aitboudad  In the latest version, this is no longer necessary. Could you please clarify what to replace it with?
