### ISSUE TITLE
Question on Cascade select in case of JSON form

### ISSUE THREAD

**Issue by SudeshAK** [formly-js/ngx-formly#947]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] question
```
Hi,
I had a query regarding cascaded select feature in formly, below is the example 
`https://stackblitz.com/edit/ngx-formly-ui-bootstrap-pcwqtr`

how to make the dropdowns present in tab1 as a cascade select? please help me on this

* **Angular version:** 5.0

**Comment by aitboudad** [comment]
see https://github.com/formly-js/ngx-formly/issues/815#issuecomment-374586474

**Comment by SudeshAK** [comment]
if in case I am using dependent dropdown then in this.getField('firstName') firstName will be on the fly. how to get which dropdown templateOptions has to be changed?

**Comment by aitboudad** [comment]
you can add some extra option in templateOptions to identify which dropdown has to be changed

**Comment by SudeshAK** [comment]
another question is there any example of a custom control which will create a single select dropdown?. I have created multiselect dropdowns but they all are created with plugins. I want a custom control which will create a single select dropdown.

**Comment by aitboudad** [comment]
no sure but it can be done easily based on [doc](https://formly-js.github.io/ngx-formly/guide/custom-formly-field)

**Comment by SudeshAK** [comment]
The problem where I am facing is I need to create a dependent dropdown the structure of the dependent  dropdown will be mentioned in json and each dropdown in the dependent dropdown is a custom control and I am not able to get the right method to do this..
