### ISSUE TITLE
Question how to bind event on custom event

### ISSUE THREAD

**Issue by SudeshAK** [formly-js/ngx-formly#952]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] Question
```
In this example 
https://stackblitz.com/edit/angular-eeo7qk
I have created a custom control here how to bind events like 'click' (event has to be defined in app component)

* **Angular version:** 5.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by thorgod** [comment]
Not the best approach I am sure some one else will come up with a better idea.

https://stackblitz.com/edit/angular-byq7zf?file=app%2Fapp.component.ts

**Comment by aitboudad** [comment]
or using `options`

**Comment by thorgod** [comment]
or even onclick if I not mistaken. 

templateOptions: {
  attributes: {
    onclick: console.log('Hello') ,
  },
},

**Comment by aitboudad** [comment]
@thorgod `attributes` is for [string value only](https://github.com/formly-js/ngx-formly/blob/master/src/core/src/lib/components/formly.attributes.ts#L35-L38)

**Comment by SudeshAK** [comment]
Thanks so much for u r help.
One help , as I am using JSON here the below part has to be on the fly 
`this.fields[0].templateOptions.clickEvent = this.clickEvent;
this.fields[1].templateOptions.clickEvent = this.clickEvent;`
how to solve this?

**Comment by aitboudad** [comment]
there is no way to specify a such thing in json, as I said before once you have loaded the JSON from the back-end you have to apply your custom events manually.

**Comment by dinesh-88** [comment]
Is it possible to bind the event on label click? May be using extensions?
