### ISSUE TITLE
Question How to call a function from a custom event function?

### ISSUE THREAD

**Issue by SudeshAK** [formly-js/ngx-formly#958]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x]question
```
Hi,
In this example: `https://stackblitz.com/edit/angular-pyszeh`
I need to call a function from a custom event function but I am unable to call that
ie. from `clickEvent($event)` function I am unable to call `calledFromClickEvent` function
when console.log(this) it shows `MyInputComponent`(I think this is the problem).When I try to call
it is showing an error. How to solve this..? pls help

* **Angular version:** 5

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-nynatp

```ts
      this.fields[0].templateOptions.clickEvent = ($event) => this.clickEvent($event);
      this.fields[1].templateOptions.clickEvent = ($event) => this.clickEvent($event);
```

**Comment by SudeshAK** [comment]
Thank u.. this worked... another thing I want to change the label of field 1 eg: In this
https://stackblitz.com/edit/angular-nnskbp
inside calledFromClickEvent function I am adding this.fields[1].templateOptions.label =  'New Text';
to change the text of field 1 but its not changing how to do that?

**Comment by aitboudad** [comment]
you have to add label wrapper for `ag-select` type:
https://stackblitz.com/edit/angular-ueukda

**Comment by SudeshAK** [comment]
yes this works.. similarly I have a select component in this case I need eg:
`this.fields[1].templateOptions.options= this.getOptions() ;` but this is not working
