### ISSUE TITLE
Binding templateOptions.options inside custom event functions

### ISSUE THREAD

**Issue by SudeshAK** [formly-js/ngx-formly#959]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x]question
```
Hi,
In this example  https://stackblitz.com/edit/angular-yeh3gf I have two dropdown
when I click on first dropdown the second dropdown options has to be changed
i.e 
`this.fields[1].templateOptions.options = this.getSports();`
But this not working.Previously as per your solution I was able to change the label but in similar way
I need to change the options but I am not able to do that please help

* **Angular version:** 5

**Comment by aitboudad** [comment]
you've passed options to the field which is not the rendered field in `MyInputComponent`,
I don't see what do you want to achieve but changing the type to `select` work for me,
https://stackblitz.com/edit/angular-yeh3gf-mxzbwm
please try to avoid lot of questions github is not stackoverflow!!
