### ISSUE TITLE
Cant Bind to Model in Repeat Section

### ISSUE THREAD

**Issue by kritisoft** [formly-js/ngx-formly#961]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search GitHub for a similar issue or PR before submitting
[ ] feature request
[ X] support request
```

**Current behavior**
The Model is not reflecting on Actual Repeat Section.
```
{
  "p_id": "product::1",
  "p_name": "Name 1",
  "details": [
    {
      "det_id": "detail::2",
      "sub_id": "subdetail::1"
    }
  ]
}
```

**Expected behavior**
While Selecting the Dropdown, the corresponding Label text is added to the model on value changes

ie the det_name & sub_detail_name

```
{
  "p_id": "product::1",
  "p_name": "Name 1",
  "details": [
    {
      "det_id": "detail::2",
      "sub_id": "subdetail::1"
      "det_name":"Detail 1",
      "sub_detail_name":"Sub Detail 1"
    }
  ]
}
```
**Minimal reproduction of the problem with instructions**

[(https://stackblitz.com/edit/angular-ablnrt)](https://stackblitz.com/edit/angular-ablnrt)

**What is the motivation/use case for changing the behavior?**

To Get the Corresponding Selecting List Label Text on the Model.

**Please tell us about your environment:**
Windows 10

* **Angular version:**  6.0.3

Also, on Submit the First Tab is not getting reset, it is showing required Validation even after reset.

**Comment by aitboudad** [comment]
Hi can you replacate your example using stackblitz, here is a starter repeat section demo https://stackblitz.com/angular/ndmbdqvebgr?file=src%2Fapp%2Fapp.component.ts

**Comment by kritisoft** [comment]
https://stackblitz.com/edit/angular-ablnrt

**Comment by aitboudad** [comment]
seems delete is the origin of the issue as it may loose the model ref used inside formly-form use `length = 0` instead:
```ts
this.productModel.details.length = 0;
``` 
> Also, on Submit the First Tab is not getting reset, it is showing required Validation even after reset.

you have to reset the parent form too

**Comment by devesh23** [comment]
@aitboudad : Hey 

We have a similar kind of issue with us. We are trying to get the value of model for repeat section from an api call.

The model is updated but it is not being reflected  in repeat section. Therefore I think that the model reference might not be updating with update in model.

Do you know any way to update the model?

**Comment by aitboudad** [comment]
@devesh23 to update model rely on `formControl` see https://github.com/formly-js/ngx-formly/issues/1309#issuecomment-441225170

**Comment by devesh23** [comment]
@aitboudad The solution which you provided would work in the case the repeat section exists. But in my case I don't have any repeat section and I am aiming to add repeat section dynamically by changing the value of model dynamically

**Comment by aitboudad** [comment]
not sure what you mean can you show me a stackblitz example?

**Comment by devesh23** [comment]
https://stackblitz.com/edit/angular-nr4cob

This is the stackblizt example on what I am trying to acheive. On writing in text field. Two repeat section should get generated

**Comment by aitboudad** [comment]
try with:
```ts
        this.model = {
            ...this.model,
            investments: [{
              'investmentName': 'hello',
            },
            {
              'investmentName' : 'hello'
            }]
          };
```

**Comment by devesh23** [comment]
@aitboudad It's actually working! 

Can you explain what purpose are those 3 dots solving and why was it not working in the previous implementation

**Comment by aitboudad** [comment]
see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals

what we have done is just let angular to take account of the new model change by changing the model reference
