### ISSUE TITLE
Matching Two Fields from examples is not working as expected

### ISSUE THREAD

**Issue by Toktik** [formly-js/ngx-formly#966]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
When you input password in "Password" then in "Confirm Password" it fires the validation. But when "Password" is changed it will not trigger the validation.

For example input matching passwords, then change Password field to not match, it will not yield the error message.

**Expected behavior**
Validation must be triggered when there is input in both cases.

**Comment by aitboudad** [comment]
here is the solution https://stackblitz.com/edit/angular-qbwj4j, can you open a PR to include that fix, thanks!

**Comment by Toktik** [comment]
@aitboudad Thanks! But is there any way we can use expressionProperties inside validator so that it automatically binds to model? I think that would be more ideal solution

**Comment by aitboudad** [comment]
for now there is no way, if there is lot of requests in that part we can find a way to add it in the core.

**Comment by lorenzonet** [comment]
I've found out this bug while I was looking for a solution of the problem I've reported on Gitter
I think that the solution would be to have the chance to specify a form validation not bound to a specific field. @aitboudad what do you think about?

**Comment by aitboudad** [comment]
@lorenzonet yep, any good proposal is welcomed!

**Comment by aitboudad** [comment]
added a better way in #1001 by moving the validation into the parent field.

**Comment by Toktik** [comment]
Actually in my use-case the fields do not share same ancestor. We need a way to bind dependency fields to trigger related field validations.

**Comment by thorgod** [comment]
^Example

**Comment by aitboudad** [comment]
well I have an idea to solve your use-case but I think it may be complicated to implement it :thinking: 
introduction a new property named `errorPath` to specify the target of a validation error:

```ts
validators: {
  fieldMatch: {
    errorPath: 'passwordConfirm',
    expression: ...,
    message: ...,
  },
},
```

WDYT ?

**Comment by Toktik** [comment]
2 points.
- I think we may have multiple fields depending on one validator. So I think we must also support array of paths.
- What is a path exactly? Does it support repeat-section, like `messages.1.text` or `messages.*.text`?

**Comment by aitboudad** [comment]
> I think we may have multiple fields depending on one validator.

in that case the validator should be placed in their parent form and the message error should be displayed only in one field (I don't see the need of array path)

> What is a path exactly?

specify the target of a validation, in the demo example the message error will appear near the `passwordConfirm` field instead of the root element

For you use-case you can stick with my first proposal.

**Comment by aitboudad** [comment]
`errorPath` added in `4.5.0` which fix the issue https://github.com/formly-js/ngx-formly/issues/1007 too
