### ISSUE TITLE
How to create a form group ?

### ISSUE THREAD

**Issue by ssarisen82** [formly-js/ngx-formly#967]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```
I am sending the following data to the form, but I want to intervene in the group of the form.

In this way, all the elements are automatically placed according to the given class.

How can I create form elements in a group for placement as below ? I want to group the form

1. row =  col-md-4 ; col-md-4
2. row = col-md-3  ; col -md-4

**Comment by aitboudad** [comment]
just use `className` see the following example: https://formly-js.github.io/ngx-formly/examples/bootstrap-specific/advanced-layout
