### ISSUE TITLE
Repeat section does not reset properly

### ISSUE THREAD

**Issue by Toktik** [formly-js/ngx-formly#969]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Here is reproducible scenario: https://stackblitz.com/angular/ovmrpppeojm?file=src%2Fapp%2Fapp.component.ts

It's the original repeat section example but with `options.resetModel()` after alerting the values.

Fill something, then submit, then (without removing, adding new item) you fill something else, empty object is alerted.

**Expected behavior**
The FormGroup should have correct values reflected.

**Comment by thorgod** [comment]
I also have this issue. I used a work around for now, something similar to this (https://stackblitz.com/edit/angular-puuh1g?file=src%2Fapp%2Fapp.component.ts)

Where I reset the ng form, you can add logic to copy the model back after if needed
