### ISSUE TITLE
[HELP] custom validation not working for me 

### ISSUE THREAD

**Issue by NuruddinBadawi** [formly-js/ngx-formly#970]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

hello, I have a question about custom validartion if I need to compare inserted input with other resurce object and apply validation to this input if not vlidated, I create this function inside my Component class and importred to the `validators` but not work
 
```
 NameValidator(control: FormControl): ValidationErrors {
        return this._appHelper.lists.find(l => l.name.toLowerCase() == control.value.trim().toLowerCase() && l.id != this.listId);
    }
```
and the field is: 

```
{
        key: 'name',
        type: 'input',
        templateOptions: {
            type: 'text',
            label: this.l("Name"),
            placeholder: '',
            required: true,
        },
        validators: {
            validation: [this.NameValidator],
        },
    }
```

**Comment by thorgod** [comment]
Submit a stackblitz of your attempt, you can use this (https://stackblitz.com/edit/ngx-formly-ui-bootstrap) as a template to fork.

Pretty sure validators are not applied to components, rather general functions where you can access the field inside that function.
```
export function TestValidator(
  control: FormControl,
  field: FormlyFieldConfig
): ValidationErrors {
 ...Access to the field
}
```

```
      validators: [
        { name: 'precision', validation: PrecisionValidator }
      ],
```

**Comment by aitboudad** [comment]
just use arrow function or use `bind`:
```ts
validation: [(control, field) => this.NameValidator(control, field)],
```

**Comment by deexita** [comment]
I've a similar use case but I'm using json to render the forms. Seems like validators aren't working with json driven forms.
