### ISSUE TITLE
Ionic - Unable to get a working multicheckbox

### ISSUE THREAD

**Issue by geraldapeoples** [formly-js/ngx-formly#972]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

I have created a blank ionic project with a single page, I created custom radio and custom multicheckbox types based on the source code available for the bootstrap module. The radio works perfectly but the multicheckbox gives an error -

 - 'Cannot find control with unspecified name attribute'

I removed my custom types and instead used the @ngx-formly/bootstrap module directly. Again the multicheckbox from the bootstrap module gives the same error, all of the other types work just fine.

Has anyone else experienced this behaviour, is it a bug with formly or is it specific to Ionic?

**Expected behavior**

The multicheckbox should not give errors.

**Minimal reproduction of the problem with instructions**

I have attached the HomePage component. The app modules etc. are all configured correctly.

[home.zip](https://github.com/formly-js/ngx-formly/files/2063147/home.zip)
    
**What is the motivation / use case for changing the behavior?**
I have an ionic app that uses formly for it's forms and I need to have a multicheckbox as part of the form.

**Please tell us about your environment:**
├── cordova@7.1.0
├── ionic@3.20.0
└── npm@5.6.0
@ngxformly/core 3.1.0

* **Angular version:**

Angular 5.2.10

* **Browser:** 

Issue appears on Firefox, chrome, iOS XX UIWebView, Android 7 Web Browser

* **Language:** 

Typescript 2.6.2

**Comment by aitboudad** [comment]
in `FormlyFieldMultiCheckbox` you have to change `option.key` to `option.value`.

**Comment by geraldapeoples** [comment]
@aitboudad Thanks for that ... So obvious when you pointed out the answer, I had gone completely code blind looking at this.
