### ISSUE TITLE
The form is not built on ngAfterViewInit

### ISSUE THREAD

**Issue by Toktik** [formly-js/ngx-formly#974]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
The form controls are not created upon `ngAfterViewInit()`. You need to do `setTimeout(..., 0)` to be able to interact with form controls.

**Expected behavior**
The form controls are populated on `ngAfterViewInit()`

**Comment by aitboudad** [comment]
there is no such guarantee that the form should be build before `ngAfterViewInit`, you may use `lifecycle` to interact with form controls see the [Cascaded Select](https://formly-js.github.io/ngx-formly/examples/other/cascaded-select) example.

let me know if it doesn't fits to your need.
