### ISSUE TITLE
Assigning a new model won't update the custom field model

### ISSUE THREAD

**Issue by JorgeSolFerreira** [formly-js/ngx-formly#975]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

**Current behavior**
When changing the form model by assigning it to a new object the custom fields won't update its values while the default fields will. 
If the model is updated by changing a model property it will updated in the custom fields but not in the default fields.

**Expected behavior**
Model in custom field should update when assigning a new model.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-2at8wq?file=app/app.component.ts

**Please tell us about your environment:**
Windows 10, Microsoft Visual Code, yarn

* **Angular version:** 5.2.7

* **Browser:** [all]

* **Language:** [all]

* **Node (for AoT issues):** `node --version` = 9.2.1

**Comment by aitboudad** [comment]
it's an expected behavior since angular doesn't track change of property values in case of object but instead it rely on it's reference.
to change a property, we often use spread operator:
```ts
    this.model = {
      ...this.model,
     email: 'email',
    }
```

**Comment by JorgeSolFerreira** [comment]
Is there a way to change a property twice? After changing the value for the first time  the custom field loses the reference to the model.

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-aj18js?embed=1&file=app/app.component.ts

**Comment by aitboudad** [comment]
that's a bug :smiley:

**Comment by aitboudad** [comment]
fixed in `4.4.3`

**Comment by krish-ram** [comment]
Hi, 

Is it possible to have this fix in Angular 5 too? 3.x versions?

**Comment by aitboudad** [comment]
@krish-ram we currently only support one version (which is the latest one), sorry :pray:

**Comment by adrigardi90** [comment]
@krish-ram I had the same problem using Angular 5. 
Every time I wanted to update the model I had to reset the formGroup too, apart from updating the required field in the model object
