### ISSUE TITLE
File input example does not return any file properties

### ISSUE THREAD

**Issue by RobinPel** [formly-js/ngx-formly#976]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**

When implementing a file input exactly like the file input example, I receive an empty File object in my model.

**Expected behavior**

I should receive a file object with metadata.

**Minimal reproduction of the problem with instructions**

Check the formly example at https://formly-js.github.io/ngx-formly/examples/other/input-file

**Comment by RobinPel** [comment]
After further investigation it seems that the model does contain the file metadata, but it just doesn't get displayed correctly. On the formly example page it states "No properties", instead of displaying the file with all of its metadata.

**Comment by thorgod** [comment]
I am able to get all the metadata, with the example. (Just not displaying with the pipe, but console log works) See example

https://stackblitz.com/edit/angular-aiudy7?file=src/app/app.component.html

**Comment by aitboudad** [comment]
we use [json-formatter-js](https://github.com/mohsen1/json-formatter-js) to render model object, please fill an issue there to add support for a File object.
