### ISSUE TITLE
Model updated of radio fields with same name but different keys.

### ISSUE THREAD

**Issue by Pat-Lovelace** [formly-js/ngx-formly#977]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**
I have a form which has different radio fields that share the same "name" property.  It was made in that way because I need to have other fields between them.  These radio fields only share "name" property but no "key" property due to the fact that sometimes I need to disable or to hide these fields, and if they would have the same "key" all of them would be affected by the disable or hide expression. 

The problem is, as they have different keys, when I pick a radio field,  it adds its value to the model:
```json
{
radio1: "valueRadio1"
}
```
But, when I pick another radio field, it adds its value, but the previous radio field don't update its value to null, although visually it doesn't appear marked.  
```json
{
radio1: "valueRadio1",
radio2: "valueRadio2"
}

```
**Expected behavior**
The expected behavior is updating the model of the previous radio field selected to null.  
```json
{
radio1: null,
radio2: "valueRadio2"
}

```
**Minimal reproduction of the problem with instructions**
[DEMO](https://stackblitz.com/edit/ngx-formly-ui-bootstrap-wgfkpr?file=app/app.component.ts)

**What is the motivation / use case for changing the behavior?**
Having the radio button options separated in different fields and with different keys, but sharing de same name, so we could have other fields between them and be able to disable or have different options, or another field which depends on these options.

* **ngx-formly version:** 
I updated my project to 3.1.0, but I can't have the dependency of angular 6 of the version 4.x.x of ngx-formly.

* **Angular version:** 5.2.11

**Comment by aitboudad** [comment]
sorry but there is no way since it's managed by angular itself.
