### ISSUE TITLE
Defining CSS Class on Formly Material Radio

### ISSUE THREAD

**Issue by Carbammato** [formly-js/ngx-formly#978]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
Hello everyone. As I'm trying to create a formly with some design from Material, I got some problems with the Radio button (`type: button`). Basically, I'd like to have a list of options aligned in vertical (and not inline), but the closest I can get, is a list of four option, 2 of them in the first row, the other 2 on the second row. I've an example in a Stackblitz attached.

Also, is there a chance to get to add some margin, or some spacing, between an option and the next one on the same line? It would improve readibility a lot.

**Expected behavior**
More or less, what I can get from the bootstrap example of a radio button (https://formly-js.github.io/ngx-formly/ui/bootstrap), but with some Material Design (https://material.angular.io/components/radio/examples , like the mat-radio example given)

**Minimal reproduction of the problem with instructions**
Here is a Stackblitz link:
https://stackblitz.com/edit/formly-css-pg
I loaded bootstrap via link on `Index.html` page, and added _d-inline-flex flex-column_ classes, but the result is quite odd.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6.0.X
* **ngx-formly version:** 4.2.X
...and basically what you can see from the stackblitz

* **Browser:** Chrome 67.0.3396.62
_(I admit I only tried on Chrome)_

Thank you for any kind of help you may give me, as well for the effort you're doing.

**Comment by aitboudad** [comment]
you can use custom style like in material example, see https://stackblitz.com/edit/formly-css-pg-zbh3s6?file=src/styles.scss

**Comment by technbuzz** [comment]
According to this stackblitz those style will be applied to all of the radio button inside formely. What I want to style specific radio buttons?

**Comment by aitboudad** [comment]
> According to this stackblitz those style will be applied to all of the radio button inside formely. What I want to style specific radio buttons?

You can use `className`:

```patch
{
  type: 'radio',
+ className: 'custom_radio',
  ...
}
```
