### ISSUE TITLE
Issue with form generation on Angular 5 and forms loaded via JSON

### ISSUE THREAD

**Issue by darlontrofy** [formly-js/ngx-formly#980]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

The form is not generated and errors out with errors printed on the console.
**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

VS CODE
* **Angular version:** 2.0.X

5
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript
* **Node (for AoT issues):** `node --version` =

**Comment by darlontrofy** [comment]
Using angular 5 with wrong version of ngx formly

**Comment by aitboudad** [comment]
hi, can provide a reproduction example please, here is a working example that use Angular5 https://stackblitz.com/edit/ngx-formly-ui-bootstrap

**Comment by darlontrofy** [comment]
Instead of [model]="model", I had (model)="model". It's resolved now. thanks.
