### ISSUE TITLE
Matching multiple fields in json powered forms

### ISSUE THREAD

**Issue by SpindlerS** [formly-js/ngx-formly#985]
Hello,

**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```
* **Angular version:** 6.0.x

**What is the aim?**
We need to implement a set of json powered forms using ngx-formly. Therefore we need the ability to implement validators over multiple fields (like the [Matching Two Fields example](https://formly-js.github.io/ngx-formly/examples/validation/matching-two-fields)). Since the given features do not support that (please correct me, if I'm wrong), we need to find a solution.

**Our approach is ...**
to declare those validators in ngModule (just like other validators) and reference them in json. Therefore I guess we would need a validator function that takes the control and the model as parameters.

What do you think about the problem and our approach?

Please let us know if you need more information.
Thank you in advance and best regards,
Sören

**Comment by thorgod** [comment]
Here is a example on how match multi with multi inputs. (Probably other approaches but this is one.)

https://stackblitz.com/edit/angular-qbygth?file=src%2Fapp%2Fapp.module.ts

**Comment by aitboudad** [comment]
> this is a bug looks like you need to refresh the validation if you change a or b after. 

see my solution https://github.com/formly-js/ngx-formly/issues/966#issuecomment-392764308

**Comment by thorgod** [comment]
@aitboudad  Thanks
@SpindlerS  Let me know if you need any help combining what I did with what Aitboudad did.

**Comment by SpindlerS** [comment]
@thorgod @aitboudad Thanks for your answers!
I will check your solution as soon as possible and give a response.
