### ISSUE TITLE
How to trigger a Model Change on Field Type

### ISSUE THREAD

**Issue by thorgod** [formly-js/ngx-formly#986]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
Button click to append text to model[key] is not refreshing
![image](https://user-images.githubusercontent.com/13910170/41184338-75210e2c-6b34-11e8-9ede-67dbfe2a7203.png)

**Expected behavior**
The model will refresh the input field. (Probably something I missed on angular documentation) 

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/ngx-formly-custom-template-hcsbyt?file=app/formly-field-input.ts

**What is the motivation / use case for changing the behavior?**
I am able to click a button on a field type to add keystroke.

**Comment by thorgod** [comment]
I did some research and tried a few things, but you might have a quick answer.

**Comment by aitboudad** [comment]
use `formControl.setValue`:
```ts
    this.formControl.setValue(
      (this.formControl.value || '') + event.target.value
    );
```

see https://stackblitz.com/edit/ngx-formly-custom-template-s6jvww
