### ISSUE TITLE
validate custome type in parent is failing 

### ISSUE THREAD

**Issue by rmayuri** [formly-js/ngx-formly#989]
@aitboudad 

Hi Sir, we are trying to create a custom type with 2 text fields and want to validate them in parent as below,
my requirement is that, 
1. submit button should be disabled until we enter values in 2 fields of custom type i.e, how it normally happens for formly types 
2. onclick of submit I should be able to get the data of 2 text fields in custom type along with parent field
3. the field should be red outlined if we remove the value from the custom type fields its similar to how it happens to a field we give as required true in fieldconfig

Thanks in advance

**custom-type-component.ts**

`import { Component, OnInit } from '@angular/core';
import { FieldType } from '@ngx-formly/core';
import { FormBuilder, Validators, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-test-parent',
  templateUrl: './custom-type-component.html',
})
export class customTypeComponent extends FieldType implements OnInit {
  form = new FormGroup({});
  formgroup: FormGroup;

  constructor(private fb: FormBuilder) {
    super();
    this.createForm();
  }

  createForm() {
    this.formgroup = this.fb.group({
      prop1: ['', Validators.required],
      prop2: ['', Validators.required],
    });
    this.form = this.formgroup;
  }
}
`

**custom-type-component.html**

`<form [formGroup]="formgroup" [formlyAttributes]="field">
  <input class="form-control" formControlName="prop1" /
  <input class="form-control" formControlName="prop2" /
</form>`

**app-module.ts**

`import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { ReactiveFormsModule } from '@angular/forms';

import {FormlyModule} from '@ngx-formly/core';

import { customTypeComponent } from './formly-field-input';
import { AppComponent } from './app.component';

@NgModule({
  imports: [ 
    BrowserModule,
    ReactiveFormsModule,
    FormlyModule.forRoot({
      validationMessages: [
       { name: 'required', message: 'This field is required' },
      ],
      types: [
        { name: 'custominput', component: customTypeComponent },
      ]
    }),
  ],
  declarations: [ AppComponent, customTypeComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
`

**"app-component.ts"**

`import { Component } from '@angular/core';
import {FormGroup} from '@angular/forms';
import {FormlyFieldConfig} from '@ngx-formly/core';

@Component({
  selector: 'my-app',
  template: `
    <form [formGroup]="form" (ngSubmit)="submit(model)">
      <formly-form [model]="model" [fields]="fields">
        <button type="submit" [disabled]="!form.valid">Submit</button>
      </formly-form>
    </form>

    {{ model|json }}
  `,
})
export class AppComponent {
  form = new FormGroup({});
  model = {};
  fields: FormlyFieldConfig[] = [
    {
      key: 'name',
      type: 'custominput',
      templateOptions: {
        label: 'Field 1',
        placeholder: 'Formly is terrific!',
        required: true,
      },
    },
        {
      key: 'name',
      type: 'input',
      templateOptions: {
        label: 'Field 2',
        required: true,
      },
    },
  ];

  submit(model) {
    console.log(model);
  }
}`

**Comment by aitboudad** [comment]
1. submit button should be disabled until we enter values in 2 fields of custom type i.e, how it normally happens for formly types 

since both fields are required relying on `form.valid` should work

2. onclick of submit I should be able to get the data of 2 text fields in custom type along with parent field
the form model can be retrived from model object

3. the field should be red outlined if we remove the value from the custom type fields its similar to how it happens to a field we give as required true in fieldconfig

that can be done by using wrapper during field declaration see https://github.com/formly-js/ngx-formly/blob/master/src/bootstrap/src/lib/bootstrap.config.ts#L43
