### ISSUE TITLE
integrating it with ng2-image-cropper

### ISSUE THREAD

**Issue by raviada** [formly-js/ngx-formly#991]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` = 9.3.0

I am trying to upload an image, set that image to cropper, once its cropped, get the cropped image data into the model. I was able to input type file working, got the image cropper and copped image data. but how do we set this data into the model?

any help is appreciated. thanks

**Comment by thorgod** [comment]
Here is a sample. This will help whoever tries to help you figure it out.


Just a mater of binding the model to it next.

https://stackblitz.com/edit/ngx-formly-custom-template-4u17ra?file=app/formly-field-input.ts

**Comment by raviada** [comment]
Thank you for sharing this example. I got this far, I even integrated file input to get the original file but  am stuck with gettin the cropped image bound to model. This may be because there are no form fields or  `ngModel` defined in cropper. I am thinking to emit `@Output` all the way to top level component where formly is being used.

**Comment by aitboudad** [comment]
@raviada to set data to your model you have to use `formControl` see https://github.com/formly-js/ngx-formly/issues/986#issuecomment-395963984
