### ISSUE TITLE
ng-select integration for typeahead with server side search

### ISSUE THREAD

**Issue by raviada** [formly-js/ngx-formly#992]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` = 9.3.0

I am trying to integrate `@ng-select/ng-select@2.1.3` component for typeahead and server side search for search term.

As mentioned in the example @ [https://ng-select.github.io/ng-select#/filter](url)

```
<ng-select [items]="people3$ | async"
           bindLabel="name"
           [addTag]="true"
           [multiple]="true"
           [hideSelected]="true"
           [loading]="people3Loading"
           [typeahead]="people3input$"
           [(ngModel)]="selectedPersons">
</ng-select>
```

I am trying to create a field type of `autocomplete` component. What I am struggling with is how do we send `people3Loading` which boolean and how do we access `people3input$` and `selectedPersons` in my component to construct the input parameters to call the backend service where I am defining a field of `autocomplete` and using it in formly form.

As a final result, I would like to see the selected items in the model.

Any help is appreciated. thanks

**Comment by aitboudad** [comment]
see https://github.com/formly-js/ngx-formly/issues/708#issuecomment-364903803
