### ISSUE TITLE
Use floating label on ngx-formly label

### ISSUE THREAD

**Issue by darlontrofy** [formly-js/ngx-formly#994]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

I will like to use the floating label found at https://codepen.io/tonystar/pen/LRdpYZ on the ngx-formly but can't figure out or see how to create a custom label control, similar to what can be done for other field types to be able to use this class on it.

**Expected behavior**

I will like to specify the class and have that applied to the form so that it works with the floating label css.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

5
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
it can be done using a custom wrapper see https://formly-js.github.io/ngx-formly/guide/custom-formly-wrapper
