### ISSUE TITLE
Do you plan to add Observables to the Multicheckbox?

### ISSUE THREAD

**Issue by cpiffat** [formly-js/ngx-formly#995]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request
```

**Current behavior**
Setting the templateOptions.options in a multicheckbox to an Observable gives the following error:
[Formly Error] You cannot pass an Observable to a multicheckbox yet.

**Expected behavior**
Be able to set options using methods that return an Observable in a multicheckbox the same way as is done in a select.

**Minimal reproduction of the problem with instructions**
Not currently set up in code at line 35 in multicheckbox.type.ts.

**What is the motivation / use case for changing the behavior?**
To be able to set up generic components that use multicheckbox. 

**Please tell us about your environment:**
N/A

* **Angular version:** 6.0.X

* **Browser:** all 

* **Language:** all

* **Node (for AoT issues):** `node --version` = 9.4.0

**Comment by aitboudad** [comment]
PR welcomed :)
