### ISSUE TITLE
Repeating section example

### ISSUE THREAD

**Issue by raviada** [formly-js/ngx-formly#998]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ X] support request
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

I am using `repeating section` example to build a form for one-many relation model. 

Couple of questions..

**1st question**

```
@Component({
  selector: 'formly-repeat-section',
  template: `
    <div *ngFor="let field of field.fieldGroup; let i = index;">
      <formly-group
        [model]="model[i]"
        [field]="field"
        [options]="options"
        [form]="formControl">
        <div class="col-sm-2 d-flex align-items-center">
          <button class="btn btn-danger" type="button" (click)="remove(i)">Remove</button>
        </div>
      </formly-group>
    </div>
    <div style="margin:30px 0;">
      <button class="btn btn-primary" type="button" (click)="add()">Add More Investments</button>
    </div>
  `,
})
```
how to get `btnText` from field definition and use it in place of ```Add More Investments``` in the above template?

field definition
```
      fieldArray: {
        fieldGroupClassName: 'row',
        templateOptions: {
          btnText: 'Add another investment',
        },
```

**2nd question**

```<button class="btn btn-primary" type="button" (click)="add()">Add More Investments</button>```

where **add()** is being defined? how do I override to some defaults the model when pressed on that button?

thanks in advance

**Comment by jdpnielsen** [comment]
For the 1. question:
See this https://stackblitz.com/edit/angular-47rdkm?file=src/app/repeat-section.type.ts

**Comment by aitboudad** [comment]
@jdpnielsen thanks!

**Comment by raviada** [comment]
Thanks @jdpnielsen for the answers! 
For question 2, I am looking for a dynamic defaultValue, which is in my case it is parent's id in a one-to-many relationship in the model. Whenever we add a ```repeating section```, that means we are adding a child records, at that time I want to default ```parentId``` column to the id of the model.

Thanks in advance.

**Comment by jdpnielsen** [comment]
If you create a minimal reproduction of your setup, i can try and take a look. You can base it on https://stackblitz.com/edit/angular-47rdkm?file=src/app/repeat-section.type.ts

**Comment by jdpnielsen** [comment]
Take a look at this: https://stackblitz.com/edit/angular-47rdkm-3s4opz?file=src/app/app.component.ts

@aitboudad do you have any input on how this could be improved? Seems kinda strange i had to manually trigger change detection in the lifecycle hook.

**Comment by raviada** [comment]
Great it works!
I will wait for @aitboudad comments regarding detecting changes manually, but I understood how to use lifecycle hooks in the field config. 

Thanks again for quick responses. You guys rock!

**Comment by raviada** [comment]
one more quick question couldn't find the right answer for it.

```javascript object vs loading it from json file.```

If we have to add lifecycle events like this, I can't do it in the json file, what is your recommendation getting away defining the field config in the component itself.

**Comment by raviada** [comment]
@aitboudad, yes when we add a child record, `id` of `customer` model should be read and set `Customer Id` of `investments` model. It is a nested model `customer has many investments`

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-47rdkm-kzzqfd

**Comment by raviada** [comment]
Prefect! you are the man!

**Comment by aitboudad** [comment]
@thetinshusasi here is working example https://stackblitz.com/edit/angular-l2tyre, if your model is loaded async then just ensure to override to hole model in order to take account of the new changes, so
instead of:
```ts
this.model.investments.push(newModel);
```
use:
```ts
this.model = {
   ...this.model,
   investments: [
      ...this.model.investments,
      newModel,
   ]
}
```
